### ISSUE TITLE
Script plugin non-instance configuration fails

### ISSUE THREAD

**Issue by MartinMulder** [rundeck/rundeck#1120]
I have a script plugin (workflow node step) and try to use "Project" or "Framework" scoped config (with RD 2.4.2).
The plugin is listed in the "List plugins", and if selected I get:
```
infraconfigurations path:
Path to infra-configurations SVN checkout
configure project: project.plugin.WorkflowNodeStep.mo-esb-package.icpath=value
```
Plugin provider config:
```
     - name: mo-esb-package
       service: WorkflowNodeStep
       title: ESB Packager
       description: Package an ESB node
       plugin-type: script
       script-interpreter: /bin/bash
       script-file: esb-node-package.sh
       config:
         - type: String
           name: icpath
           title: infraconfigurations path
           required: true
           description: Path to infra-configurations SVN checkout
           scope: ProjectOnly
```
project.properties line:
```
project.plugin.WorkflowNodeStep.mo-esb-package.icpath=/tmp
```
When I add the "ESB Packager" to a workflow, and try to save it, I see an error in the service.log:
```
2015-02-27 13:31:14,085 ERROR WorkflowController - Plugin configuration was not valid
```
