### ISSUE TITLE
rd-acl shows REJECTED_NO_SUBJECT_OR_ENV_FOUND

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1236]
I'd like to use rd-acl to test my aclpolicy files. But when I try to run the command, all items show "REJECTED_NO_SUBJECT_OR_ENV_FOUND"

```
[root@lsc102 rundeck]# rd-acl list -u admin -p GSSC -n lsc629
Using configured Rundeck etc dir: /etc/rundeck
# Application Context access for username admin

- configure: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- admin: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- read: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- delete: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- delete_execution: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- import: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- export: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]

```

**Comment by gschueler** [comment]
is that the full output from the command?

**Comment by rophy** [comment]
That's partial output. The complete outputs are basically the same:


[root@lsc102 ~]# rd-acl list -u admin -p GSSC -n lsc629
Using configured Rundeck etc dir: /etc/rundeck
# Application Context access for username admin

- read: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- admin: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- delete_execution: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- delete: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- configure: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- import: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- export: project named "GSSC" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]

(No storage path (-s) specified, skipping Application context actions for a specific storage path.)

- create: project [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- read: system [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- admin: job [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- admin: user [REJECTED_NO_SUBJECT_OR_ENV_FOUND]

# Project "GSSC" access for username admin

- read: Adhoc executions [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- kill: Adhoc executions [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- killAs: Adhoc executions [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- run: Adhoc executions [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- runAs: Adhoc executions [REJECTED_NO_SUBJECT_OR_ENV_FOUND]

(No job (-j) specified, skipping Project context actions for a specific job.)

- run: Node "lsc629" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- read: Node "lsc629" [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- create: node [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- refresh: node [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- read: node [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- update: node [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- create: event [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- read: event [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- create: job [REJECTED_NO_SUBJECT_OR_ENV_FOUND]
- delete: job [REJECTED_NO_SUBJECT_OR_ENV_FOUND]

**Comment by gschueler** [comment]
can you paste your aclpolicy files as well?

**Comment by rophy** [comment]
admin.aclpolicy
```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin
```

apitoken.aclpolicy
```
description: API project level access control
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [create,delete] # allow create and delete jobs
    - equals:
        kind: node
      allow: [read,create,update,refresh] # allow refresh node sources
    - equals:
        kind: event
      allow: [read,create] # allow read/create events
  adhoc:
    - allow: [read,run,kill] # allow running/killing adhoc jobs and read output
  job: 
    - allow: [create,read,update,delete,run,kill] # allow create/read/write/delete/run/kill of all jobs
  node:
    - allow: [read,run] # allow read/run for all nodes
by:
  group: api_token_group

---

description: API Application level access control
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read] # allow read of system info
  project:
    - match:
        name: '.*'
      allow: [read] # allow view of all projects
  storage:
    - match:
        path: '(keys|keys/.*)'
      allow: '*' # allow all access to manage stored keys
by:
  group: api_token_group
```

user.aclpolicy
```
description: Default access for all users 
context:
  project: 'GSSC'
for:
  job: 
    - allow: [read,run]
  resource:
    - equals:
      kind: event
      allow: [read, create]
by:
  group: user

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: ['read']
  project:
    - allow: read
by:
  group: user
```
