### ISSUE TITLE
"Run Job Again" does not reuse previous value for remote URL options

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1347]
Version: 2.6.0-0-SNAPSHOT

Use this job:
```
- id: 774a7b43-fe8b-4db0-8ac1-48008d9deccc
  project: GSSC
  loglevel: DEBUG
  multipleExecutions: true
  sequence:
    keepgoing: false
    strategy: node-first
    commands:
    - exec: hostname
  description: ''
  name: Test Remote Option
  uuid: 774a7b43-fe8b-4db0-8ac1-48008d9deccc
  group: test
  options:
    MyOption:
      enforced: true
      required: true
      value: c
      valuesUrl: file:/tmp/options.json
```

/tmp/options.json:
```
["a","b","c"]
```

1. Run the job with `MyOption` as `b`
2. After the job succeed, click `Run Again`
3. Check the value of `MyOption` in the Run Job page

**Expected** : Value of `MyOption` should be `b`
**Actual** : Value of `MyOption` is `c`
