### ISSUE TITLE
Properly document Active Directory configuration

### ISSUE THREAD

**Issue by ssbarnea** [rundeck/rundeck#1397]
As someone that discovered RunDeck recently my first try was to configure it to use Active Directory but I soon discovered that this use-case is [not properly documented](http://rundeck.org/docs/administration/authenticating-users.html#ldap) and in fact the support seems to be limited to password authentication only.

Active Directory is a specific type of LDAP with a much more consistent structure and for this reason it should be properly documented. After spending many hours trying different configurations I am starting to believe that is not really supported, more than authentication.

Authentication part worked well but it seems impossible to map the groups by their name.

```
ldap {
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
      debug="true"
      contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
      providerUrl="ldap://example.com:3268"
      bindDn="CN=svcacct_rundeck,OU=Example,OU=Service Accounts,DC=example,DC=com"
      bindPassword="rundeck123"
      authenticationMethod="simple"
      forceBindingLogin="true"
      userBaseDn="dc=example,dc=com"
      userRdnAttribute="sAMAccountName"
      userIdAttribute="sAMAccountName"
      userPasswordAttribute="unicodePwd"
      userObjectClass="user"
      roleBaseDn="dc=example,dc=com"
      roleNameAttribute="sAMAccountName"
      roleUsernameMemberAttribute="cn"
      roleMemberAttribute="member"
      roleObjectClass="group"
      cacheDurationMillis="300000"
      supplementalRoles="user"
      reportStatistics="true"
      timeoutRead="10000"
      timeoutConnect="20000"
      nestedGroups="false";
};
```

I will try to explain few important concept related to AD:
- `sAMAccountName` is the username (or the group name) and while it can change in time but almost never does. You can call it your login, because that's what you type when you have to login.
- `cn` does uniquely identify a resource but you cannot expect users to type it in order to login.
- for security reasons most AD configurations do not allow anonymous bind, which means that you need to login before making any queries. Remember that the LDAP login (bindDn) is supposed to be a cn and you may have to specify the full distinguished name there instead of the `sAMAccountName` or `DOMAIN\sAMAccountName`. The last two can work but depends on your configuration, "DN" approach always work.
- Instead of using ports 389/636 to connect to AD, you should probably want to use 3268/3269 which are pointing to the Global Catalog. If you do not you may be surprised that your queries do not return all users from the forests or that you client is not able to get the referrals (responses from other AD servers in the forest).
- most AD users believe that their access to AD via LDAP is read-only, but they are wrong, AD can easily be modified by any user if they have the right ownership on the resource they are trying to modify. For example any Exchange mailing list is also a group in AD and if you own it or if you are listed as one of its managers, you will be able to add or remove other members.

Groups can be identified using two methods, the easiest and fastest one is to get the `memberOf` attribute of the user accounts. 

If you try to retrieve all the groups in or order to get their members you will probably his serious scalability issues because is is something common for an AD with 15.000 users to have 10.000 groups! Better to sticks to the first method.

When you retried groups, the members are stored in the member attribute as DNs (distinguished names) and not as account names (what you probably use in your app to identify users). You have to convert them, which makes the operation longer.

Example group record:

```
distinguishedName: CN=\#DevOps,OU=Groups,OU=EMEA,DC=example,DC=com
sAMAccountName: #DevOps
name: Development Operation long description
member: CN=John Doe,OU=User Accounts,OU=Bangalore,OU=APAC,DC=example,DC=com
member: CN=John Smith,OU=User Accounts,OU=UK,OU=EMEA,DC=example,DC=com
objectGUID: <binary data>
```

Example user record:

```
distinguishedName: CN=John Doe,OU=User Accounts,OU=EMEA,DC=example,DC=com
name: John Doe
sAMAccountName: johnd
memberOf: CN=...,DC=example,DC=com
memberOf: CN=...,DC=example,DC=com
Email: john.doe@example.com
Manager: CN=...
```

As you can observe while the simple and intuitive way is to use sAMAccountName to identify users and groups, when it comes to identifying membership you will only get the `CN` which has to be translated later.

While in practice sAMAccountName can have duplicates, I would say that this is an extreme case that would be easier not to support as 99% of the applications are not able to deal with this and this can easily be handled by the IT support by renaming the duplicated accounts.

And now the big questions, these being said, how are we supposed to complete the   `roleNameAttribute`, `roleUsernameMemberAttribute` and `roleMemberAttribute` in order to make rundeck to recognize the groups from AD?

**Comment by Jalpal** [comment]
Is this fixed ?

**Comment by dsiluri** [comment]
Any news for this one?

**Comment by spuder** [comment]
+1 I would also like to see better documentation on active directory. Several days in and I still can't get rundeck to authenticate against AD.

**Comment by spuder** [comment]
I'll share my progress and struggle with this same issue. I've successfully been able to give users admin rights to rundeck based on AD group, but I am unable to grant access to a project with AD groups.

## User 1
 Part of AD group "**Enterprise Admins**"

With the following config, this user is given full rundeck administrative rights.


(Note the following 3 lines) 
```json
    roleNameAttribute="sAMAccountName"
    roleMemberAttribute="member"
    roleObjectClass="group"
```
jaas-ldap.conf


```
ldap {
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="<%= node['nd-rundeck']['ldap-url'] %>"
    bindDn="<%= node['nd-rundeck']['bindDn'] %>"
    bindPassword="<%= node['nd-rundeck']['bindPassword'] %>"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn="<%= node['nd-rundeck']['userBaseDn'] %>"
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="unicodePwd"
    userObjectClass="user"
    roleBaseDn="<%= node['nd-rundeck']['roleBaseDn'] %>"
    roleNameAttribute="sAMAccountName"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="300000"
    supplementalRoles="user"
    reportStatistics="true"
    timeoutRead="10000"
    timeoutConnect="20000"
    nestedGroups="false";
    
    org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule required
    debug="true"
    file="/etc/rundeck/realm.properties";
};

```

web.xml

```xml
        <security-role>
                <role-name>Enterprise Admins</role-name>
        </security-role>
        <security-role>
                <role-name>user</role-name>
        </security-role>
        <security-role>
                <role-name>admin</role-name>
        </security-role>
```

admin.aclpolicy
```yaml
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin

---

description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: Enterprise Admins

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: Enterprise Admins

```
![screenshot 2016-02-26 11 33 30](https://cloud.githubusercontent.com/assets/242382/13361648/35d87efa-dc7d-11e5-86a0-d54adbdbc7b8.png)




## User 2

User 2 is only part of the "SWAT" group. They are not able to see the 'swat' project in rundeck. 

web.xml
```xml
      <security-role>
                <role-name>SWAT</role-name>
        </security-role>
        <security-role>
                <role-name>Enterprise Admins</role-name>
        </security-role>
        <security-role>
                <role-name>user</role-name>
        </security-role>
        <security-role>
                <role-name>admin</role-name>
        </security-role>
```

admin.aclpolicy
```yaml
description: SWAT, modify swat
context:
  project: 'swat'
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: SWAT
```

![screenshot 2016-02-26 11 34 12](https://cloud.githubusercontent.com/assets/242382/13361653/3a775abc-dc7d-11e5-8c56-bc4020e1d929.png)

**Comment by gschueler** [comment]
to see a project, would need to grant `application` level access first, as you have done for admin group:

`$ rd-acl create -c application -g SWAT -p swat -a read`

~~~{.yaml}
# create or append this to a .aclpolicy file
---
by:
  group: SWAT
context:
  application: rundeck
for:
  project:
  - allow: read
    equals:
      name: swat
description: generated
~~~

**Comment by ARentz07** [comment]
Hey @spuder 
I have been able to get AD group membership-based access control to work (in 2.6.7) without adding any more security roles. Funny thing is, I meant to add another security role but simply missed that step, and somehow, it still works fine.

Your jaas-ldap.conf already contains this:
```
supplementalRoles="user"
```
You've also got that "user" [security role](http://rundeck.org/docs/administration/authenticating-users.html#security-role) in web.xml. From what I understand, since anyone authenticated via LDAP is already a "user" based on your LDAP config, that means they already have the required "user" role to login. Thus, in your case, the additional security roles should be unnecessary. 

@gschueler does this sound right to you?

**Comment by dwaynekuan** [comment]
supplementalroles is a crutch. it grants EVERYONE the roles specified by this parameter. what's the point of having different roles if you are going to use supplementalroles since everyone inherits the roles specified in supplementalroles?

i havent been able to get rundeck working properly with AD either and i mean proper differentiation of permissions based on ids & roles.

has anyone solved this problem?

**Comment by gschueler** [comment]
@dwaynekuan supplementalroles is meant to be used simply to grant authenticated users the access needed by the security-constraint in web.xml.  It is not really meant to be used to grant authorization levels to users (as all users would be in that role, as you mention).  User membership in different AD groups/roles is the proper way to grant selective access via ACL policies for those roles.

It seems to be a large stumbling block for people to configure JAAS-ldap exactly right for their AD environment...  this seems to depend on access levels granted to the account authenticating to AD, the directory structure, etc.

Are you able to see the AD groups listed as roles under your user profile?  If not, then some of the "role search" attributes for your config need to be tweaked.

Do you see the list of roles in your profile, but everyone has the same access level?  If so then your ACL policy files need to be tweaked.

**Comment by dwaynekuan** [comment]
**@gschueler**  here's what i've done so far:

here's my jaas-ldap.conf file:

```
ldap {
   com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
   debug="true"
   contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
   providerUrl="ldap://xxx"
   port="389"
   bindDn="<ldap email address>"
   bindPassword="<password>"
   authenticationMethod="simple"
   forceBindingLogin="true"
   userBaseDn="ou=Corp,ou=VCI,ou=Domain Users,dc=usvci001,dc=vci,dc=na,dc=vwg"
   userRdnAttribute="sAMAccountName"
   userIdAttribute="sAMAccountName"
   userPasswordAttribute="userPassword"
   userObjectClass="user"
   roleBaseDn="ou=Corp,ou=VCI,ou=Domain Users,dc=usvci001,dc=vci,dc=na,dc=vwg"
   roleNameAttribute="cn"
   roleMemberAttribute="member"
   roleObjectClass="group"
   cacheDurationMillis="300000"
   reportStatistics="true";

  org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule required
    debug="true"
    file="/etc/rundeck/realm.properties";
};

```

here's my admin.aclpolicy file:

```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin

---

description: Admin, rundeck
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin

---

description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  username: kuand

---


description: Admin, rundeck
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: Domain Users

---

description: Admin, rundeck
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: Global IS Unix

```

my web.xml file contains (not the whole file, just a snippet):

```
        <security-role>
                <role-name>user</role-name>
                <role-name>admin</role-name>
                <role-name>Global IS Unix</role-name>
        </security-role>
```

when i attempt to login at the web interface i get :

```
HTTP ERROR 403
Problem accessing /. Reason:
    !role
```

my service.log shows:

```
2016-06-23 15:44:17.998:INFO:cdrjj.JettyCachingLdapLoginModule:Attempting authentication: CN=Kuan\, Dwayne (TMP),OU=Corp,OU=VCI,OU=Domain Users,DC=usvci001,DC=vci,DC=na,DC=vwg
2016-06-23 15:44:18.002:WARN:cdrjj.JettyCachingLdapLoginModule:JettyCachingLdapLoginModule: User 'kuand' has no role membership; role query configuration may be incorrect

```
any ideas?

**Comment by gschueler** [comment]
@dwaynekuan this message `User 'kuand' has no role membership` means the directory search is not able to find any roles for the user.  This message `!role` in the web page means that the web app server is not able to fulfill the role requirement of the web.xml (obviously since you have no roles). (If there is no single common role in the directory for the users you want to have access to rundeck, you can use the `supplementalRoles="user"`, and set the web.xml to only require `user` role.)

You need to figure out why you are not receving any role results from the server query:

1) Is this the correct base DN for roles? `roleBaseDn="ou=Corp,ou=VCI,ou=Domain Users,dc=usvci001,dc=vci,dc=na,dc=vwg"` it is the same as your user base DN.  It should be the base for searching for roles in the directory.  Or in other words, what is the structure of your directory?

2) does your user account have access to search the directory for roles?  You are using binding login, which means it binds to the directory as the authenticating account (instead of an admin account), and uses that context to search.

**Comment by jenulis** [comment]
@dwaynekuan,

I have JAAS working but have some different settings form you.  First make sure you have an explicit context entry for appliciton and project for each user and group.  For me combining username and group has worked in aclpolicy file.  Try something like:

```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin
  username: kuand
---

description: Admin, rundeck
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin
  username: kuand
```
 When accessing active directory all usernames and groups are case sensitive.  (Thanks JAAS project!)

I have jass-activedirectory.conf file in etc
```
activedirectory {
	com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
	debug="true"
	contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
	providerUrl="ldap://fqdn.dns.org:3268"
	bindDn="NAME"
	bindPassword="PASSWORD"
	authenticationMethod="simple"
	forceBindingLogin="true"
	userBaseDn="dc=ofi,dc=com"
	userRdnAttribute="sAMAccountName"
	userIdAttribute="sAMAccountName"
	userPasswordAttribute="unicodePwd"
	userObjectClass="user"
	roleBaseDn="OU=ORG_UNIT,DC=DOMAIN,DC=ROOT,DC=org" 
	roleNameAttribute="cn"
	roleMemberAttribute="member"
	roleObjectClass="group"
	cacheDurationMillis="300000"
	supplementalRoles="user,admin"
	reportStatistics="true";
};
```
I have a separate jass-loginmodule.conf file in the same etc directory as jass-activedirectory.conf file

```
RDpropertyfilelogin {
org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule required
debug="true"
file="<path_to_properties>/realm.properties";
};

```

**Comment by ARentz07** [comment]
>what's the point of having different roles if you are going to use supplementalroles since everyone inherits the roles specified in supplementalroles?

You could say, for instance, allow anyone to log in, but restrict access to certain projects or configuration by AD group membership. For instance, my team has a particular security group for operations engineers on a certain project, and we use that to restrict admin access on Rundeck by using a block like this:

```
by:
  group: AD_GROUP_NAME
```

**Comment by ARentz07** [comment]
In any case, a big 👍 for adding some documentation around this. I think we really just need more examples if nothing else.

**Comment by dwaynekuan** [comment]
@gschueler so my AD directory structure does not have definitions for roles so that's why the rolebasedn was not working. i didnt realize it required special role definition in AD (since the documentation makes no mention of this nor how to define these roles). some mention of this should definitely be inserted in the documentation and preferably with sample role definitions in AD.

so i managed to get it working by using ignore roles in jaas-ldap.conf:

```
ldap {
   com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
   debug="true"
   contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
   providerUrl="ldap://xxx"
   port="389"
   bindDn="<ldap email password>"
   bindPassword="xxx"
   authenticationMethod="simple"
   forceBindingLogin="true"
   userBaseDn="ou=Corp,ou=VCI,ou=Domain Users,dc=usvci001,dc=vci,dc=na,dc=vwg
   userRdnAttribute="sAMAccountName"
   userIdAttribute="sAMAccountName"
   userPasswordAttribute="userPassword"
   userObjectClass="user"
   roleBaseDn="ou=Corp,ou=VCI,ou=Domain Users,dc=usvci001,dc=vci,dc=na,dc=vwg
   roleNameAttribute="sAMAccountName"
   roleMemberAttribute="member"
   roleObjectClass="group"
   cacheDurationMillis="300000"
   reportStatistics="true"

   ignoreRoles="true"
   storePass="true"
   clearPass="true"
   useFirstPass="false"
   tryFirstPass="false"
   supplementalRoles="user";

   org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule required
   debug="true"
   useFirstPass="true"
   file="/etc/rundeck/realm.properties";
};

```

and then using admin.aclpolicy:

```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin
  username: kuand

---

description: Admin, rundeck
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin
  username: kuand
```

where kuand is my lan admin.

since i wanted several users to have admin, i used:

```
by:
  group: admin
  username: 
    - kuand
    - user1
    - user 2

```

i also found out something interesting. using <tab> in admin.aclpolicy invalidates the line so only use spaces.

**Comment by dwaynekuan** [comment]
@gschueler if i wanted to use roles in AD, how would i define them?

**Comment by gschueler** [comment]
@dwaynekuan create groups, add users to the groups. for organization you could create a new "OU" level for the groups, giving you a unique base for the role search

**Comment by dwaynekuan** [comment]
@gschueler so here's what my AD structure looks like. 

User ids are at:
OU=Corp, OU=VCI, OU=Domain Users,dc=usvci001,dc=vci,dc=na,dc=vwg

but groups are at:

OU=Domain Users, dc=usvci001,dc=vci,dc=na,dc=vwg

eg a sample group would be "VCI - IT Ops - Unix"... how does rundeck handle spaces in an AD group?

does that mean my roleBaseDn should be:

roleBaseDn="ou=Domain Users,dc=usvci001,dc=vci,dc=na,dc=vwg"

i tried that and it didnt work.

although i used an admin.aclpolicy as shown below

```
description: Admin, rundeck
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
   group: VCI - IT Ops - Unix
```

i tried using group: with a single quote, a double quote, nothing worked.
