### ISSUE TITLE
aclpolicy not getting applied correctly and nodes don't show up

### ISSUE THREAD

**Issue by linbynd** [rundeck/rundeck#1544]
I am running sundeck 2.6.0 under tomcat. I created a aclpolicy under `$RDECK_BASE/etc/mypolicy.aclpolicy` as described in Greg's vids. Just to give read access on project level. But the nodes never show up unless its a admin account

```
description: Admin, all access.
context:
  application: 'rundeck'
for:
  project:
    - equals:
       name: 'containers'
    - allow: 'read'
by:
  group: 'awsusers'

---
description: project level access
context:
  project: 'containers'
by:
  group: 'awsusers'
for:
  job:
   - allow: 'read'
  node:
   - allow: 'read'
  adhoc:
   - allow: 'read'
  resource:
   - allow: '*'
```

**Comment by gschueler** [comment]
try using the `rd-acl` tool to test and validate the policy.  

Running `rd-acl validate` will test the validation of your installed aclpolicy files. Also you can view the Security tab under Configure button to see validation errors.  (Your policy has a validation error allowing read access to all projects.)

however, I don't see any problesm reading nodes in a test setup using this policy

**Comment by linbynd** [comment]
how do i get the rd-acl tool. Would have to install the deb file of rundeck or I can get it separately. as I am using the .war file right now.

**Comment by linbynd** [comment]
i corrected aclpolicy `- allow` section and the policy is clean now.

**Comment by vinitkhandagle** [comment]
I re wrote the policy. using the admin-policy as a base. and its working as expected

```
description: Admin, all access.
context:
  project: 'CONTAINERS' # all projects
for:
  resource:
    - allow: 'read' # allow read/create all kinds
  adhoc:
    - allow: 'read' # allow read/running/killing adhoc jobs
  job:
    - allow: 'read' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: 'read' # allow read/run for all nodes
by:
  group: awsusers

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  project:
    - equals:
        name: 'CONTAINERS'
      allow: [read] # allow view/admin of all projects
by:
  group: awsusers
```
I shifted the contexts as it is in the default admin policy
