### ISSUE TITLE
NodeExecutor plugins and ssh private key passphrase usage

### ISSUE THREAD

**Issue by daysofwineandroses** [rundeck/rundeck#1563]
Rundeck version: 2.6.1-1
OS: CentOS 7.1

Hello Greg,

Following your reply in https://github.com/rundeck/rundeck/issues/1110#issuecomment-148521262 and documentation [here](http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html) and [here](http://rundeck.org/docs/developer/plugin-development.html#script-plugin-development), I created following plugin which runs a wrapper script around ansible:
```
name: ansible-launcher
version: 1.0
rundeckPluginVersion: 1.0
author: Bert Mertens 
date: 23/11/2015
providers:
    - name: ansible-launcher
      service: NodeExecutor
      title: Ansible Launcher 
      description: "This plugin allows executing ansible runs."
      plugin-type: script
      script-file: "run-via-ansible"
      script-args: "${exec.command}"
      config:
        - name: privateKeyPath 
          title: Private Key Storage Path
          type: String
          required: true 
          description: "Storage path for authentication private key. Can contain property references to node attributes. A node attribute named private-key-storage-path will override this value."
          scope: Instance
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            storage-path-root: "keys"
            storage-file-meta-filter: "Rundeck-key-type=private"
            instance-scope-node-attribute: "private-key-storage-path"
        - name: privateKeyPassPhrasePath 
          title: Private Key PassPhrase Storage Path
          type: String
          required: true 
          description: "Storage path for authentication private key passphrase. Can contain property references to node attributes. A node attribute named private-key-passphrase-storage-path will override this value."
          scope: Instance
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
            storage-file-meta-filter: "Rundeck-data-type=password"
            instance-scope-node-attribute: "private-key-passphrase-storage-path"
```

The script basically accepts some input from a job, juggles it around a bit and runs `ansible-playbook` using the private key via an export shell variable ansible-playbook understands and interprets.

Truncated for relevance:
```
#!/bin/bash
COMMAND="ansible-playbook -vvvv"
KEYFILE="${KEYPATH}/${RD_CONFIG_PRIVATEKEYPATH}"
export ANSIBLE_PRIVATE_KEY_FILE=$KEYFILE

cd $ANSIBLE_LOCATION
echo Running $COMMAND -u root -l $@
eval $COMMAND -u root -l $@
```

This works great when there is no passphrase on the private key.

When there's a passphrase on the private key however, it fails.

I pass it in the NodeExecutor plugin definiton, but I have no idea what happens to it then or how to use it here.

I added the ssh-agent options as described [here](http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html#ssh-agent-support) hoping that it would somehow load the private key, using the passphrase, but to no avail:
```
project.local-ssh-agent=true
project.local-ttl-ssh-agent=500
```
Is there a way to achieve what I'm trying to do?
