### ISSUE TITLE
Running bash script as user with arguments

### ISSUE THREAD

**Issue by SirWilli** [rundeck/rundeck#1623]
hey,

I'm trying to run a script on a node via a job, for that I added a remote command to the job but I can't get the variables as argument in the command.
I either get file not found or a empty argument.

How can I correctly pass the variable as argument?

That's my command atm:
```sudo -u launcher bash -c "'bash /home/launcher/modpacks/upgrade.sh ${option.Modpack} ${option.Download}'"```

**Comment by shyam** [comment]
@SirWilli - All the options exposed are prefixed with `$RD_OPTION_`. The same script should be:

`sudo -u launcher bash -c "'bash /home/launcher/modpacks/upgrade.sh ${RD_OPTION_Modpack} ${RD_OPTION_Download}'"`

**Comment by SirWilli** [comment]
I already tested it with `$RD_OPTION_MODPACK` but this just gives a empty argument.

Just tested `${RD_OPTION_Modpack}` and gives also a empty argument

**Comment by shyam** [comment]
Can you paste your job definition ( prefer YAML ) here ?

**Comment by SirWilli** [comment]
```
- description: ''
  executionEnabled: true
  id: c84ffd6a-0e51-405c-bd13-05f752cb2528
  loglevel: INFO
  name: Modpack Update
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: 'tags: launcher'
  nodesSelectedByDefault: true
  options:
  - name: Download
    required: true
  - name: Modpack
    required: true
  - name: Version
    required: true
  scheduleEnabled: true
  sequence:
    commands:
    - exec: sudo -u launcher bash -c "'bash /home/launcher/modpacks/upgrade.sh ${RD_OPTION_Modpack} ${RD_OPTION_Download}'"
    keepgoing: false
    strategy: node-first
  uuid: c84ffd6a-0e51-405c-bd13-05f752cb2528
```
