### ISSUE TITLE
rd-acl test suggests incorrect policy for key storage

### ISSUE THREAD

**Issue by kmusard** [rundeck/rundeck#1626]
Rundeck 2.6.2 RPM install.  The path to the key is /keys/user/username.  The output of running 'rd-acl test' against a storage key instructed me to add the following to the policy

```
  storage:
  - allow: read
    equals:
      name: username
      path: keys/user
```

When running the job I get step errors that I am not authorized to access the key.  Removing the 'path' line allows me to run the job.  I also tried path: /keys/user as well as placing the values assigned to name and path in quotes.
