### ISSUE TITLE
After 2.6.3 upgrade, ACL that does not allow job create/delete always shows Bulk edit checkboxes

### ISSUE THREAD

**Issue by wufpack00** [rundeck/rundeck#1714]
After upgrading to v2.6.3, any user that does not have create/delete job permissions will see the "Select All" and "Select None" options next to every group name on Job list page.

The following Javascript error can be seen in Firebug console:
```
ReferenceError: filterName is not defined
...th($data||{}){return{'css':function(){return { disabled:!nowRunningEnabled()} }}...
```

Here is the ACL that worked in 2.6.2:
```
description: Limited access for jobs on Sample Sandbox
context:
  project: 'Sample.*'
for:
  resource:
    - equals:
        kind: node
      allow: [read,refresh] # allow refresh node sources
  job:
    - match:
        group: 'sandbox.*'
      allow: [run,read,kill]
    - match:
        group: 'common.*'
      allow: [run] # do not allow to see jobs only run them
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: [restricted-users]

---

description: Limited access for jobs on Sandbox
context:
  application: 'rundeck'
for:
  project:
    - match:
        name: 'Sample.*'
      allow: [read] # allow view of Sample project only
by:
  group: [restricted-users]
```
![acl-error](https://cloud.githubusercontent.com/assets/8304087/13410930/67920104-df08-11e5-9ec4-c1893d184f4c.jpg)
