### ISSUE TITLE
Properties not expanded recursively

### ISSUE THREAD

**Issue by skundrik** [rundeck/rundeck#1738]
With the following resource file

```
node1:
  description: some node
  hostname: testhost
  osArch: x86_64
  osFamily: unix
  username: testuser
  ns:custom: /home/${node.username}/test/${node.hostname}
```

I run command `echo ${node.ns:custom}` against node1.
Expected: `/home/testuser/test/testhost`
Actual result: `/home/${node.username}/test/${node.hostname}`
