### ISSUE TITLE
rd-jobs list export schedule.time.hour wrong

### ISSUE THREAD

**Issue by jippi** [rundeck/rundeck#1773]
When running a command like this: `rd-jobs list -f $project.yaml -F yaml -p $project`

the `schedule.time.hour` key get exported as a float when `hour` contains a `,` (comma) - it works correctly if there are just a number (e.g. `hour: 9`) which gets exported as `'9'`

programatically loading, parsing and writing a yaml file like this will result in `hour` being `915` from PHP and Python 

Can it be forced to always be a string, thanks!

Expected:

````yaml
  schedule:
    dayofmonth:
      day: '*'
    month: '*'
    time:
      hour: '9,15'
      minute: '0'
      seconds: '0'
````

Actual:

````yaml
  schedule:
    dayofmonth:
      day: '*'
    month: '*'
    time:
      hour: 9,15
      minute: '0'
      seconds: '0'
````

Running `rundeck-2.6.4-1-GA.deb`
