### ISSUE TITLE
Different authorization levels for different "tokens" 2.6.1

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1784]
Hi,
I'm trying to implement different authorization levels for different tokens "Each of them associated to different rundeck local users", however all my tests seems to point to the fact that this is not possible yet or this is not working, just api_token_group aclpolicy seems applied to all of them.

As I see this from a functional point of view, the token should in-heritate both authorization rules, the api_token_group aclpolicy plus the associated user aclpolicy stuff, at this point I'm not sure If I'm doing something wrong in my configuration or this is just not possible at this moment, I've tried to figure it out on my own by looking to

https://github.com/rundeck/rundeck/blob/v2.6.1/rundeckapp/grails-app/conf/rundeck/filters/AuthorizationFilters.groovy

but I'm lacking some Java/groovy knowledge, could some one confirm me if this is possible? If yes could you provide me some configuration example? If this is not possible, don't you think this would be a useful feature?

Regards

**Comment by gschueler** [comment]
all token access uses the pseudo group `api_token_group`, and the username for the token's user.  So you can apply overall access for that group, and specific access for the username.

**Comment by snebel29** [comment]
Hi @gschueler,
Thanks for you quick answer, this ishow I though this should work, however I'm unable to make it work, this is my use case:

I have a local "admin" user that belongs to "admin" group, I have aclpolicy files for for api_token_group and admin group.

When I test "admin" user using the GUI this works as expected I can do what I'm supposed to being able to do and I'm unable to do what I'm not supposed to do.

My api_token_group policy just allow "read" actions, I have a token associated to admin user through the tokens.properties file and admin user is created using real.properties file.

However when using the associated admin token I'm unable to get the admin authorization rules, looking to rundeck.audit.log I see the actions are denied and just api_token_group is mention on.

```
2016-04-04 04:23:43,238 - Evaluating Decision for: res<name:TEST, type:project> subject<Username:admin Group:api_token_group> action<admin> env<http://dtolabs.com/rundeck/env/application:rundeck>: authorized: false: REJECTED, reason: REJECTED, evaluations:        ACLRule</etc/rundeck/api_token_group.aclpolicy[2][type:resource][rule: 4]>{'Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.' context={application='rundeck'} type='resource' equals , resource={kind=user} for: { group='api_token_group'} allow=[read]} REJECTED for action admin => REJECTED (0ms)
```
At this moment my work aorund is to use password authentication which is no the best, any clues what could have been happening?

Thanks in advance

**Comment by snebel29** [comment]
BTW: Those are the aclpolicy definitions I'm using for testing

```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin

########################################################

description: API project level access control
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [read] # allow create and delete jobs
    - equals:
        kind: node
      allow: [read] # allow refresh node sources
    - equals:
        kind: event
      allow: [read] # allow read/create events
  adhoc:
    - allow: [read] # allow running/killing adhoc jobs and read output
  job:
    - allow: [read] # allow create/read/write/delete/run/kill of all jobs
  node:
    - allow: [read] # allow read/run for all nodes
by:
  group: api_token_group

---

description: Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [read] # allow create of projects
    - equals:
        kind: system
      allow: [read] # allow read of system info, enable/disable all executions
    - equals:
        kind: system_acl
      allow: [read] # allow modifying system ACL files
    - equals:
        kind: user
      allow: [read] # allow modify user profiles
  project:
    - match:
        name: '.*'
      allow: [read] # allow full access of all projects or use 'admin'
  project_acl:
    - match:
        name: '.*'
      allow: [read] # allow modifying project-specific ACL files
  storage:
    - allow: [read] # allow access for /ssh-key/* storage content

by:
  group: api_token_group

```
