### ISSUE TITLE
aclpolicy - grant access to multiple project in 1 file

### ISSUE THREAD

**Issue by amitdaniel86** [rundeck/rundeck#1997]
Hi , 

I would like to get access to multiple project in 1 aclpolicy file .

Tried to do something like that but it's not worked for me .

```
# create or append this to a .aclpolicy file
---
by:
  group: XXXXXX_XXXX
context:
  application: rundeck
for:
  project:
  - allow: read
    equals:
      name: [project1, project2]
description: generated
# create or append this to a .aclpolicy file
---
by:
  group: XXXXXX_XXXX
context:
  project: [project1, project2]
for:
  job:
  - allow:
    - read
    - run
    - kill
    match:
      group: "(group1|group2)"
description: generated
# create or append this to a .aclpolicy file
```

Thanks for your help

**Comment by gschueler** [comment]
for the `context: project: ...` part, use a regular expression, e.g.

~~~ {.yaml}
context:
  project: '(project1|project2)' # all projects
~~~

for the application context section, use a `match` instead of `equals` and use a regular expression:

~~~ {.yaml}
for:
  project:
  - allow: read
    match:
      name: '(project1|project2)'
~~~

or, you can simply define multiple sections for `equals`:

~~~{.yaml}
for:
  project:
  - allow: read
    equals:
      name: project1
  - allow: read
    equals:
      name: project2
~~~

**Comment by amitdaniel86** [comment]
thanks , 

But what about job section ? 

```
  job:
  - allow:
    - read
    - run
    - kill
    match:
      group: "(group1|group2)"
```

How i can give access to all groups ? i can use `.*` ?
