### ISSUE TITLE
Issues posting acl policies

### ISSUE THREAD

**Issue by lusis** [rundeck/rundeck#2012]
I've been working through trying to post acl policies via the API and I think I've hit a bug with non-json payloads.

the following payload works:

``` json
{
    "contents":"description: Access to system_acl via API.\ncontext:\n  application: 'rundeck'\nfor:\n  project_acl:\n    - allow: '*'\n  system_acl:\n    - allow: '*'\nby:\n  group: api_token_group"
}
```

But posting xml or yaml seems to misbehave:

``` xml
<contents><![CDATA[description: Access to system_acl via API.
context:
  application: rundeck
for:
  project_acl:
    - allow: *
  system_acl:
    - allow: *
by:
  group: api_token_group]]></contents>
```

``` yaml
description: Access to system_acl via API.
context:
  application: 'rundeck'
for:
  project_acl:
    - allow: '*'
  system_acl:
    - allow: '*'
by:
  group: api_token_group
```

The error generated is:

```
{"valid":false,"policies":[{"policy":"api2.aclpolicy","errors":["null; mapping values are not allowed here"]}]}
```

I'm posting via curl like so:
- `curl -b cookies.txt -H "Content-Type: application/xml" -d@docker/api_token.xml -XPOST http://localhost:4440/api/17/system/acl/api2.aclpolicy`
- `curl -b cookies.txt -H "Content-Type: application/json" -d@docker/api_token.json -XPOST http://localhost:4440/api/17/system/acl/api2.aclpolicy`
- `curl -b cookies.txt -H "Content-Type: application/yaml" -d@docker/api_token.aclpolicy -XPOST http://localhost:4440/api/17/system/acl/api3.aclpolicy`

A few things of interesting note. When posting with content-type yaml, the response is in json. When posting as xml cdata the error is xml. When posting as json, the error is json.

Is it possible that the accept needs to match the content type when posting acls?
