### ISSUE TITLE
incorrect aclpolicy yaml structure can cause NPE

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#206]
If the aclpolicy yaml is incorrect it may case a NPE:

example:

```
description: application level access
context:
 application: 'rundeck'
for:
 project:
   - equals:
     name: 're'
     allow: [read] # allow view/admin of all projects
by:
 group: re-deploy
```

the -equals section is empty, due to incorrect indentation for name: 're'.
