### ISSUE TITLE
Rundeck Report and Monitor Job step display broken

### ISSUE THREAD

**Issue by schewara** [rundeck/rundeck#2080]
# Bug report

**My Rundeck detail**
- Rundeck version: 2.6.9-1
- install type: rpm
- OS Name/version: CentOS 6

**Expected Behavior**

Job Steps in Report and Monitor view should provide meaningful information.
In my case the step description.
All Steps in this case are Job References.

**Actual Behavior**

All Steps only show 'File'.
![rundeck-job_report_screenshot](https://cloud.githubusercontent.com/assets/2920223/18688604/6520583a-7f85-11e6-9469-9aba70cabbd2.png)

As far as i can see this issue was introduced with #1370
A temporary workaround is to set
_rundeck.feature.workflowDynamicStepSummaryGUI.enabled=false_
as described in the Pull request #1926 

**How to reproduce Behavior**

Permanent when switching to Report or Monitor Page
Tested Browser: Firefox + Chrome

**Comment by gschueler** [comment]
can you paste your job definitions?

**Comment by schewara** [comment]
sorry took me a bit to get back to you
```yaml
- description: Wrapper script for rollout
  executionEnabled: true
  id: <job-uuid>
  loglevel: INFO
  name: rollout
  options:
  - description: the build number
    name: buildnr
    required: true
  - description: the environment
    enforced: true
    name: environment
    required: true
    values:
    - dev
    - test
  - enforced: true
    name: run_puppet
    required: true
    value: run
    values:
    - run
    - skip
  - description: the release version
    name: version
    required: true
  scheduleEnabled: true
  sequence:
    commands:
    - description: Puppet Stop Service
      jobref:
        args: -task stopservice -environment ${option.environment} -exec ${option.run_puppet}
        group: ''
        name: Puppet tasks
    - description: Checkout config
      jobref:
        args: -environment ${option.environment} -version ${option.version}
        group: ''
        name: config checkout
    - jobref:
        args: -buildnr ${option.buildnr} -environment ${option.environment} -version ${option.version}
        group: ''
        name: code checkout
    - description: Puppet Run Agent
      jobref:
        args: -task runagent -environment ${option.environment} -exec ${option.run_puppet}
        group: ''
        name: Puppet tasks
    - description: Puppet Start Service
      jobref:
        args: -task startservice -environment ${option.environment} -exec ${option.run_puppet}
        group: ''
        name: Puppet tasks
    keepgoing: false
    strategy: step-first
  uuid: <job-uuid>
```
and an example of one of the referenced tasks
```yaml
- description: executes Puppet tasks
  executionEnabled: true
  id: <job-uuid>
  loglevel: INFO
  multipleExecutions: true
  name: Puppet tasks
  options:
  - description: the environment
    name: environment
    required: true
  - description: if puppet should run or not
    enforced: true
    name: exec
    required: true
    value: run
    values:
    - run
    - skip
  - description: task to be executed
    enforced: true
    name: task
    required: true
    values:
    - runagent
    - startservice
    - stopservice
  scheduleEnabled: true
  sequence:
    commands:
    - args: ${option.task}  ${option.environment} ${option.exec}
      scriptfile: /path/to/script.sh
    keepgoing: false
    strategy: step-first
  uuid: <job-uuid>
```
hope this helps
