### ISSUE TITLE
job status "killed" when running a job with the job refrence error handler on multiple nodes

### ISSUE THREAD

**Issue by robinwolny** [rundeck/rundeck#2222]
# Bug report

**My Rundeck detail**

* Rundeck version: Rundeck 2.6.9-1 cafe bonbon indigo tower 2016-08-03
* install type: war
* OS Name/version: Centos 7.2

**Expected Behavior**
For a job with the **Job Reference error handler**, running on multiple nodes and having thread count set to number of nodes or higher, the job report "All Steps OK" is expected, when the job/jobs is/are successfully completed.
___

**Actual Behavior**
For some nodes, although the job is successfully completed, the job status is shown as "killed".
[Image of invalid job status](https://screencloud.net/v/m9EH)

___

**How to reproduce Behavior**
Create a job with job reference error handler. Execute this job on 2 or more nodes (with threading)
1. 00_job - is the main job containing a job reference error handler
2. 01_job - is the error handler job

00_job definition (yaml):
```
- description: ''
  executionEnabled: true
  id: 84a3c955-3a5e-441b-a3bb-8d8226d4a9fd
  loglevel: DEBUG
  name: 00_job
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 10
    filter: rwo-centos.*                   # must match multiple nodes
  nodesSelectedByDefault: false
  options:
  - name: error
    required: true
    values:
    - 'no'
    - 'yes'
  scheduleEnabled: true
  sequence:
    commands:
    - description: Error (yes/no)
      errorhandler:
        jobref:
          group: ''
          name: 01_job
          nodeStep: 'true'
          nodefilters:
            dispatch:
              threadcount: 10
            filter: ${node.name}
        keepgoingOnSuccess: true
      exec: '[[ ${option.error} == ''yes'' ]] && exit 1 || exit 0'
    keepgoing: false
    strategy: step-first
  uuid: 84a3c955-3a5e-441b-a3bb-8d8226d4a9fd
```
01_job definition (yaml):
```
- description: ''
  executionEnabled: true
  id: e0741341-fb47-4408-aa72-f075381d8681
  loglevel: DEBUG
  name: 01_job
  scheduleEnabled: true
  sequence:
    commands:
    - exec: date
    keepgoing: false
    strategy: node-first
  uuid: e0741341-fb47-4408-aa72-f075381d8681
```
...
