### ISSUE TITLE
aclpolicy doesn't work for one-project user (1.4.4 error, but 1.4.3 OK)

### ISSUE THREAD

**Issue by yahoon** [rundeck/rundeck#233]
Hi,
:
I want to limit a user who can only access a specified project.
here I want 'abcadmin' can only see and manage prj 'ABC' in the web portal. 
Steps:
create a project "ABC"
create a user 'abcadmin' with role 'abcadmin'
create the acl policy file "abcadmin.aclpolicy', its content is:

```
description: Admin, all access.
context:
  project: 'ABC' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: abcadmin
```

but the user can login but get a authorization error in the web UI, version is 1.4.4.
I ever did the same thing on 1.4.3 and worked well.

should be a bug I think.

thanks.

BR, 
Yahoon
