### ISSUE TITLE
single valued options with "selected=true" fetched from remote URL don't work

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#2420]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.0
* install type: launcher
* OS Name/version: RHEL 7

**Actual Behavior**
selected=true don't work with single valued options

**How to reproduce Behavior**
this is not working for single valued options.
i have a job with the following options:
```
options:
- delimiter: ','
  enforced: true
  multivalued: true
  name: node
  required: true
  value: node01
  values:
  - node01
  - node02
- enforced: true
  name: product_devops-testapp
  required: true
  valuesUrl: http://localhost/cgi-bin/tmp.pl?node=${option.node.value}
```

the url returns the following json objects:
```
URL: http://localhost/cgi-bin/tmp.pl?node=node01
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "00_00_02" },
    { "value" : "testapp;00_00_03", "name" : "last installed: 00_00_03", "selected" : true }
]

URL: http://localhost/cgi-bin/tmp.pl?node=node02
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "last installed: 00_00_02", "selected" : true },
    { "value" : "testapp;00_00_03", "name" : "00_00_03" }
]
```

when the first node is selected it works.
![screenshot_2017-04-11_12-46-33](https://cloud.githubusercontent.com/assets/3838857/24906181/fb46b248-1eb6-11e7-9158-9264ede7fe62.png)

when the second node is selected, the previous selected entry is displayed. the selected=true value is ignored.
![screenshot_2017-04-11_12-46-22](https://cloud.githubusercontent.com/assets/3838857/24906190/02ae4aa0-1eb7-11e7-844f-9f4c71d6c254.png)

**Expected Behavior**
when the second node is selected, "last installed: 00_00_02" should be displayed.

related to #1189
