### ISSUE TITLE
Rundeck not able to pick roles from web.xml

### ISSUE THREAD

**Issue by utsav2307** [rundeck/rundeck#2491]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2-1
* install type: (rpm,deb,war,launcher?) deb
* OS Name/version: ubuntu 14.04
* DB Type/version: rundeck's default

**Expected Behavior**
I added a new role in rundeck'sweb.xml security groups, so it looks something like:
```
     <security-role>
                <role-name>user</role-name>
                <role-name>dev</role-name>
     </security-role>
```

Then I defined a dev.aclpolicy and and added a user in realm.properties as: 
`tom:tom,dev,user`

I then restarted rundeck and tried to login but the access control policies of user were applied, no changes were picked from my dev.aclpolicy. 

My dev.aclpolicy is like:
```
description: dev, only read execute access for few projects
context:
  project: '*' # all projects
for:
  resource:
    - allow: 'read' # allow read/create all kinds
  adhoc:
    - allow: [read,running] # allow read/running/killing adhoc jobs
  job:
    - allow: [read,run,kill] # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: dev

---

description: dev, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: 'read' # allow create of projects
  project:
    - allow: 'view' # allow view/admin of all projects
  project_acl:
    - allow: 'read' # allow admin of all project-level ACL policies
  storage:
    - allow: 'read' # allow read/create/update/delete for all /keys/* storage content
by:
  group: dev
```
