### ISSUE TITLE
Question: ACL to allow indirectly execute referenced jobs.

### ISSUE THREAD

**Issue by blacked** [rundeck/rundeck#2507]
Issue type: Question

**My Rundeck detail**

* Rundeck version: 2.6.9-1 
* install type: deb
* OS Name/version: Ubuntu 12.04

**Expected Behavior**

I have following project jobs groups:
```
project:
  - common/
     - common_job
  - users/
     - user_job
```

User's jobs can contain job references to `common/*` jobs.

I'm trying grant access to users to allow execute their own jobs (`users/*`), which should indirectly execute `common/*` jobs. But at same time, I don't want allow them execute `common/*` jobs directly. 

I did make acl file for user
```
...
  job:
    - allow: [read]
      match:
        name: '.*'
        group: 'common/.*'
    - allow: [read,run,kill]
      match:
        name: '.*'
        group: 'users/.*'
...
```
I did suspect that `read` permission for job, will allow indirect execution if I have `run` permission for parent job, but the actual behavior is different.

**Actual Behavior**

When I do execute user job, I'm getting error.
```
Unauthorized to execute job [common/common_job}
```

Is there a way to make it work the way I need?

**Comment by blacked** [comment]
I'm closing it. 
I did grant just `run` permission for `common/*` and it does the trick. Now `common/*` jobs are hidden from users.

```
...
  job:
    - allow: [run]
      match:
        name: '.*'
        group: 'common/.*'
    - allow: [read,run,kill]
      match:
        name: '.*'
        group: 'users/.*'
...
```
