### ISSUE TITLE
single valued options with "selected=true" fetched from remote URL should not used on run again

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#2552]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: launcher
* OS Name/version: RHEL 7

**Actual Behavior**
selected=true should not used on run again

**How to reproduce Behavior**
i have a job with the following options:
```
options:
- delimiter: ','
  enforced: true
  multivalued: true
  name: node
  required: true
  value: node01
  values:
  - node01
  - node02
- enforced: true
  name: product_devops-testapp
  required: true
  valuesUrl: http://localhost/cgi-bin/tmp.pl?node=${option.node.value}
```

the url returns the following json objects:
```
URL: http://localhost/cgi-bin/tmp.pl?node=node01
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "00_00_02" },
    { "value" : "testapp;00_00_03", "name" : "last installed: 00_00_03", "selected" : true }
]

URL: http://localhost/cgi-bin/tmp.pl?node=node02
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "last installed: 00_00_02", "selected" : true },
    { "value" : "testapp;00_00_03", "name" : "00_00_03" }
]
```

select the second node with version 00_00_03 and run the job.
![screenshot_2017-04-11_12-46-22](https://cloud.githubusercontent.com/assets/3838857/24906190/02ae4aa0-1eb7-11e7-844f-9f4c71d6c254.png)

after click on "Run Again" the version 00_00_02 is displayed.

**Expected Behavior**
after click on "Run Again" the last selected version (00_00_03) schould be selected.
is there a way to tell the web service that the job is run again (job.wasRunAgain=true)?
```
http://localhost/cgi-bin/tmp.pl?node=${option.node.value}&runAgain=${job.wasRunAgain}
```

related to #2420 #1189
