### ISSUE TITLE
single valued options with "selected=true" fetched from remote URL don't work

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#2585]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: launcher
* OS Name/version: RHEL 7

**Actual Behavior**
selected=true don't work with single valued options

**How to reproduce Behavior**
this is not working for single valued options.
i have a job with the following options:
```
options:
- delimiter: ','
  enforced: true
  multivalued: true
  name: node
  required: true
  values:
  - node01
  - node02
  - node03
- enforced: true
  name: product_devops-testapp
  required: true
  valuesUrl: http://localhost/cgi-bin/tmp.pl?node=${option.node.value}
```

the url returns the following json objects:
```
URL: http://localhost/cgi-bin/tmp.pl?node=node01
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "00_00_02" },
    { "value" : "testapp;00_00_03", "name" : "last installed: 00_00_03", "selected" : true }
]

URL: http://localhost/cgi-bin/tmp.pl?node=node02
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "last installed: 00_00_02", "selected" : true },
    { "value" : "testapp;00_00_03", "name" : "00_00_03" }
]

URL: http://localhost/cgi-bin/tmp.pl?node=node03
[
    { "value" : "testapp;00_00_31", "name" : "00_00_31" },
    { "value" : "testapp;00_00_32", "name" : "last installed: 00_00_32", "selected" : true },
    { "value" : "testapp;00_00_33", "name" : "00_00_33" }
]
```

when the first node is selected it works.
![selection_002](https://user-images.githubusercontent.com/3838857/27468513-8bcd6f02-57ea-11e7-8371-cd89ff721341.png)

when the second node is selected it also works.
![selection_005](https://user-images.githubusercontent.com/3838857/27468623-23a1fed8-57eb-11e7-8099-c98f09bec1cf.png)

when the third node is selected, the first value is displayed. the selected=true value is ignored.
![selection_003](https://user-images.githubusercontent.com/3838857/27468536-a6ab19e6-57ea-11e7-9ef5-19faf4dbc44f.png)

after reloading the value of product_devops-testapp option, it works.
![selection_004](https://user-images.githubusercontent.com/3838857/27468584-e0a2dbac-57ea-11e7-8e16-9c9145cd5237.png)

**Expected Behavior**
when the third node is selected, "last installed: 00_00_32" should be displayed.

related to #2420
