### ISSUE TITLE
project server node not loading in UI and causing Rundeck errors

### ISSUE THREAD

**Issue by jeff-fiser** [rundeck/rundeck#2597]
Issue type: Bug report

**My Rundeck detail**
Including the server node in a project file resource causes Rundeck to error and no nodes are displayed in the UI.  This only happens for a single project which is governed by a single aclpolicy (the other aclpolicy files we use do not reference this project).

* Rundeck version: 2.8.2
* install type: deb
* OS Name/version: Ubuntu 14.04
* DB Type/version: mysql

**Expected Behavior**
All nodes (including the server node) show up in the UI and are available for job usage.

**Actual Behavior**
Clicking on the All Node Filters link/button or searching for the server node by name (Nodes tab) causes all the nodes to disappear in the UI and the Rundeck service and error log shows the following:

`2017-06-29 01:22:51,607 [qtp1329552164-679] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /resources/nodesQueryAjax
Stacktrace follows:
java.lang.NullPointerException`

`ERROR GrailsExceptionResolver: NullPointerException occurred when processing request: [GET] /resources/nodesQueryAjax
Stacktrace follows:
java.lang.NullPointerException`

aclpolicy file:

```
description: All Users can access Self Service project jobs
context:
  project: 'User-Self-Service'
for:
  resource:
    - allow: [read,run,kill] # allow read,execute,kill of jobs
  adhoc:
    - deny: '*'  # deny all ad-hoc actions
  job:
    - equals:
        group: 'Passwords'
      allow: [read,run,kill] # allow read/run/kill of all jobs
    - equals:
        group: 'Library'
      allow: [run,kill] # allow read/run/kill of all jobs
  node:
    - match:
        name: '.*'
      allow: '*'
    - equals:
        rundeck_server: 'true'
      allow: [read, run, refresh] # allow run on rundeck server node
by:
  username: '.*'

---
description: All Users can access Self Service project jobs
context:
  application: 'rundeck'
for:
  resource:
    - allow: [read] # allow read of resources
  project:
    - match:
        name: 'User-Self-Service'
      allow: [read]
  storage:
    - allow: [read] # allow access for /ssh-key/* storage content
by:
  username: '.*'
```

**How to reproduce Behavior**
Create a project with a file resource and include the server node.  Update the aclpolicy above to match your project name.  See if the server node loads in the list.

Thanks,
Jeff F

**Comment by gschueler** [comment]
Hi Jeff, can you include any stacktraces from your server log?

**Comment by gschueler** [comment]
I found the issue, this is fixed in 2.8.3 https://github.com/rundeck/rundeck/issues/2559

**Comment by gschueler** [comment]
btw, the cause is that if you specify an ACL `match` rule but the attribute you match does not exist on one of the items, it causes that error.  

in your acl you have

```
node:
  - match:
      name: '.*'
    allow: '*
```

But nodes have a `nodename` attribute, not `node`.  So if you change that to `nodename` it should work in 2.8.2
