### ISSUE TITLE
multi valued options with "selected=true" fetched from remote URL don't work

### ISSUE THREAD

**Issue by hugospinto** [rundeck/rundeck#2604]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: deb
* OS Name/version: Debian 8.6
* DB Type/version: mysql

**Actual Behavior**
selected=true is not selecting the correct options for the remote values when I change the first option and the new remote option has different values

**How to reproduce Behavior**
i have a job with the following options:

```
  options:
  - delimiter: ','
    enforced: true
    multivalued: true
    name: node
    required: true
    value: node01
    values:
    - node01
    - node02
  - delimiter: ','
    enforced: true
    multivalued: true
    name: product_devops-testapp
    required: true
    valuesUrl: file:/opt/rundeck/scripts/option/esp/apps-${option.node.value}.json
```
the url returns the following json objects:

```
URL: http://localhost/cgi-bin/tmp.pl?node=node01
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "00_00_02" },
    { "value" : "testapp;00_00_03", "name" : "last installed: 00_00_03", "selected" : true }
]

URL: http://localhost/cgi-bin/tmp.pl?node=node02
[
    { "value" : "testapp;00_00_04", "name" : "00_00_04" },
    { "value" : "testapp;00_00_05", "name" : "last installed: 00_00_05", "selected" : true },
    { "value" : "testapp;00_00_06", "name" : "00_00_06", "selected" : true }
]
```

select node02 and no default remote options are selected.
![image](https://user-images.githubusercontent.com/22676737/27832909-69c8ed78-60c8-11e7-8786-25f3b50ed2bf.png)

**Expected behavior**

When I select node02 the option with "selected=true", i.e. "last installed: 00_00_05" and  "last installed: 00_00_06" should be selected by default.
