### ISSUE TITLE
REJECTED messages *after* AUTHORIZED messages in audit log

### ISSUE THREAD

**Issue by dirkniblick** [rundeck/rundeck#2662]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.4-1
* install type: rpm
* OS Name/version: CentOS Linux release 7.2.1511 (Core)
* DB Type/version: h2

**Expected Behavior**
Per [documentation](http://rundeck.org/docs/administration/access-control-policy.html):
> For each entry in the audit log, you'll see all decisions leading up to either a AUTHORIZED or a REJECTED message. It's not uncommon to see REJECTED messages followed by AUTHORIZED. The important thing is to look at the last decision made.

**Actual Behavior**
Access control policy is generating REJECTED_NO_SUBJECT_OR_ENV_FOUND errors with "authorized: false" after "authorized: true" messages.  

**How to reproduce Behavior**
The default configuration produces this.  It's continued after AD integration.

**Comment by dirkniblick** [comment]
**Examples**
With the default config (logging in as admin:admin):
```
2017-07-21 16:01:30,376 - Evaluating Decision for: res<type:adhoc> subject<Username:admin Group:build Group:architect Group:admin Group:user Group:deploy> action<run> env<rundeck:auth:env:project:Test_Project>: authorized: true: GRANTED, reason: GRANTED, evaluations:   ACLRule</etc/rundeck/admin.aclpolicy[1][type:adhoc][rule: 1]>{'Admin, all access.' context={project='.*'} type='adhoc' for: { group='admin'} allow=[*]} GRANTED for action run => GRANTED (0ms)
2017-07-21 16:01:30,376 - Evaluating Decision for: res<type:adhoc> subject<Username:admin Group:build Group:architect Group:admin Group:user Group:deploy> action<run> env<rundeck:auth:env:project:Test_Project>: authorized: false:   No context matches subject or environment => REJECTED_NO_SUBJECT_OR_ENV_FOUND (0ms)
```

After AD integration (using the "Administrators" AD group/role):
```
2017-08-03 10:09:26,222 - Evaluating Decision for: res<type:adhoc> subject<Username:jcl3 Group:readyToFlip Group:programmingandoffice Group:Abuse Group:newFormula Group:remalert Group:root Group:Programming Group:Administrators Group:Folder Redirection Group:ticket_notifications Group:loialert> action<run> env<rundeck:auth:env:project:MWL>: authorized: true: GRANTED, reason: GRANTED, evaluations:         ACLRule</etc/rundeck/admin.aclpolicy[1][type:adhoc][rule: 1]>{'Admin, all access.' context={project='.*'} type='adhoc' for: { group='Administrators'} allow=[*]} GRANTED for action run => GRANTED (0ms)
2017-08-03 10:09:26,222 - Evaluating Decision for: res<type:adhoc> subject<Username:jcl3 Group:readyToFlip Group:programmingandoffice Group:Abuse Group:newFormula Group:remalert Group:root Group:Programming Group:Administrators Group:Folder Redirection Group:ticket_notifications Group:loialert> action<run> env<rundeck:auth:env:project:MWL>: authorized: false:       No context matches subject or environment => REJECTED_NO_SUBJECT_OR_ENV_FOUND (0ms)
```

**Relevant Configs**
/etc/rundeck/jaas-activedirectory.conf:
```
activedirectory {
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldap://xxx.xxx.xxx.xxx:389"
    bindDn="CN=foobar,CN=foobar,DC=foobar,DC=foobar,DC=com"
    bindPassword="foobar"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn="DC=foobar,DC=foobar,DC=com"
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="unicodePwd"
    userObjectClass="user"
    roleBaseDn="DC=foobar,DC=foobar,DC=com"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="30000"
    reportStatistics="true"
    timeoutRead="10000"
    timeoutConnect="20000"
    nestedGroups="true";
};
```

/etc/rundeck/admin.aclpolicy:
```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: Administrators

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: Administrators
```

/var/lib/rundeck/exp/webapp/WEB-INF/web.xml:
```
...
  <security-role>
    <role-name>Administrators</role-name>
  </security-role>
...
```
