### ISSUE TITLE
SSH to solaris server fails on key size

### ISSUE THREAD

**Issue by jeroentbt** [rundeck/rundeck#2705]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.2-1
* install type: rpm
* OS Name/version: amazon linux 2017/03
* DB Type/version: postgres

**Expected Behavior**
A ssh connection to succeed.
````
kex: server->client aes128-ctr hmac-md5 none
kex: client->server aes128-ctr hmac-md5 none
SSH_MSG_KEXDH_INIT sent
expecting SSH_MSG_KEXDH_REPLY
ssh_rsa_verify: signature true
Permanently added 'some.host.name' (RSA) to the list of known hosts.
````

**Actual Behavior**
The connection fails, using this same key I can connect without issue using a regular ssh client.
````
kex: server->client aes128-ctr hmac-md5 none 
kex: client->server aes128-ctr hmac-md5 none
SSH_MSG_KEX_DH_GEX_REQUEST(1024<2048<2048) sent
expecting SSH_MSG_KEX_DH_GEX_GROUP
Disconnecting from some.host.name port 22
Session.connect: java.security.InvalidAlgorithmParameterException: DH key size must be multiple of 64, and can only range from 512 to 2048 (inclusive). The specific key size 2047 is not supported
Failed: SSHProtocolFailure: Session.connect: java.security.InvalidAlgorithmParameterException: DH key size must be multiple of 64, and can only range from 512 to 2048 (inclusive). The specific key size 2047 is not supported
````

**How to reproduce Behavior**
Any connection to a SunOS 5.10 server fails in this way

**Comment by jeroentbt** [comment]
Forgot to add that this happens even when the node config clearly states to use a password for authentication.

eg node config:
````
somehost:
  nodename: some.host.name
  hostname: some.host.name
  description: Some host
  tags: host
  environment: PROD
  username: myuser
  ssh-config-PreferredAuthentications: password
  ssh-authentication: password
  ssh-password-storage-path: keys/muyuser.password
````
