### ISSUE TITLE
How to map LDAP groups to Project groups in Rundeck

### ISSUE THREAD

**Issue by SUJER** [rundeck/rundeck#2810]
I have setup LDAP authentication for rundeck ,  it is working fine for authentication but I have to use realm.properties file for mapping user with ACL group names which provide access to projects

I just want to know is there any workaround instead of using realm.properties file I want to add a user to LDAP group  "operator" so he should get access to projects with operator group names in project ACL files.

**Comment by dirkniblick** [comment]
I'm not sure how you have your Rundeck LDAP authentication setup, but when my users authenticate their other AD groups come across.  I get something like this in my service.log:
```
2017-10-12 10:15:30.000:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp149990333-144447: JettyCachingLdapLoginModule: User 'bobby' has roles: [Group1, Group2, RunDeckUsers, RunDeckAdministrators, Group3]
```
I just created `/etc/rundeck/*.aclpolicy` files using those groups and it works fine:
```
# cat /etc/rundeck/Group1.aclpolicy
description: "Read-only access for generic Rundeck users"
context:
  project: '.*'
for:
  resource:
    - equals:
        kind: 'node'
      allow: [read,refresh]
    - equals:
        kind: 'job'
      allow: [read]
    - equals:
        kind: 'event'
      allow: [read]
  job:
    - match:
        name: '.*'
      allow: [read]
  node:
    - match:
        nodename: '.*'
      allow: [read,refresh]
by:
  group: Group1
. . .
```
