### ISSUE TITLE
ACL Policy - Keys Regex Matching Does Not Recognize Trailing Slash

### ISSUE THREAD

**Issue by swtch1** [rundeck/rundeck#2848]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.3-1 
* install type: rpm
* OS Name/version: CentOS 7.3.1611
* DB Type/version: embedded (test instance)

**Expected Behavior**
I expect the ACL policy in question to allow me to see keys/dir1/mykey.

**Actual Behavior**
I am unable to see any keys.

**How to reproduce Behavior**
Create an ACL policy with the following snippet under application: 'rundeck'
```
storage:
  - allow: [read,create,update,delete]
    match:
      path: '(keys|keys/dir1/.*)'
```

Creating a policy with this snippet works, but will also allow users to see keys/dir12345/mykey.
```
storage:
  - allow: [read,create,update,delete]
    match:
      path: `'(keys|keys/dir1.*)'
```
