### ISSUE TITLE
Data passing (key-value) from one job to another fails with rundeck version 2.9.4

### ISSUE THREAD

**Issue by ashpotdar** [rundeck/rundeck#2948]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.4-1
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: Windows 7
* DB Type/version: -

**Expected Behavior**
Variable value captured with key-value log filter ( ${data.LOGFILEPATH} ) in 1st job should be passed properly in another referenced job 

**Actual Behavior**

Variable value returns empty value in referenced job

**How to reproduce Behavior**
Please check below simple scenario  of data passing :
[Validate_Data_Passing.xml.txt](https://github.com/rundeck/rundeck/files/1482353/Validate_Data_Passing.xml.txt)
[Data_Passing.xml.txt](https://github.com/rundeck/rundeck/files/1482355/Data_Passing.xml.txt)

**Comment by ahonor** [comment]
@ashpotdar You can pass the captured data to the child job via a job option. 
```
- description: ''
  executionEnabled: true
  id: b07194c1-6405-4d0b-9092-13e02c389605
  loglevel: INFO
  name: Data Passing
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: true
      threadcount: 1
    filter: app1.anvils.com
  nodesSelectedByDefault: true
  options:
  - name: SOURCENODE
    value: app1.anvils.com
  scheduleEnabled: true
  sequence:
    commands:
    - args: ${option.SOURCENODE}
      script: |-
        #!/bin/bash

        echo "SourceNode="$1

        echo "LOGFILEPATH=/opt/SMP/Cust"
    - description: validate data passing subjob
      jobref:
        args: -path ${data.LOGFILEPATH}
        group: ''
        name: Validate Data Passing
        nodeStep: 'true'
    keepgoing: false
    pluginConfig:
      LogFilter:
      - config:
          logData: 'true'
          regex: ^(LOGFILEPATH)\s*=\s*(.+)$
        type: key-value-data
    strategy: sequential
  uuid: b07194c1-6405-4d0b-9092-13e02c389605
- description: ''
  executionEnabled: true
  id: 9fe41d4d-8eb4-4049-becd-254748c6585b
  loglevel: INFO
  name: Validate Data Passing
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: true
      threadcount: 1
    filter: app1.anvils.com
  nodesSelectedByDefault: true
  options:
  - name: path
  scheduleEnabled: true
  sequence:
    commands:
    - args: ${option.path}
      script: |-
        #!/bin/bash

        echo "LOGFILEPATH in 2nd job : "$1
    keepgoing: false
    strategy: sequential
  uuid: 9fe41d4d-8eb4-4049-becd-254748c6585b
```
