### ISSUE TITLE
Project automatically added to jobs

### ISSUE THREAD

**Issue by vinillum** [rundeck/rundeck#2976]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.0-1
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux 6.8
* DB Type/version: mysql 14.14

**Behavior**
When we upgraded from Rundeck 2.9.2-1 to 2.10-1, several (but not all) of the jobs got the project name automatically added to the job steps.

I have managed to fix that, albeit temporarily, by extracting the job definition, manually removing the project name from job steps, then importing the updated job definition. However, the issue eventually reappeared on the same jobs.

It would not be an issue if we didn't use Rundeck API to export the job definitions jar file. We use this file to populate several differently-named projects on other Rundeck servers, and thus the import fails as they can't find the referenced project on those servers.

**How to Reproduce**
I have not yet found a way to reproduce this, as the issue only affects a subset of jobs, and after manually fixing them, the issue seems to reappear randomly.

**Comment by JustRiedy** [comment]
My Rundeck detail

    Rundeck version: 2.10.1-1
    Install type: rpm
    OS Name/version: CentOS 7
    DB Type/version: MS SQL

Unable to replicate the issue, checked multiple jobs across my 9 projects and no change to Job Steps naming.

Do you use SCM at all?
The renamed workflow steps, were they Commands or Inline Scripts?
I only have job steps of these types sadly.

**Comment by richiereynolds** [comment]
I see this all the time:

After we import a job, a period of time after that a new tag seems to be added to the job definition specifying the project name in the job ref steps e.g.
```
     - description: Checking site-specific files
       jobref:
         args: -Node ${node.name} -Label ${option.Label} -LabelToDiff ${option.LabelToDiff} -Rollback ${option.Rollback}
         group: INSTALL/CHECKS
         name: CheckSiteSpecificFiles
         nodeStep: 'true'
+        project: SIM
```
This doesn't stop anything working in this project but it makes the jobs non portable. If we export the set of jobs to be imported into a different server, with different project names, then it stops that working. Our current workaround is that we strip that line from the files after we export. Why does this line appear? I imagine it's used to specify jobs in other projects but our jobs are referring to the "current" project and we want to be able to import these jobs into projects with different names. (We use the project names refer to our environments)
