### ISSUE TITLE
Variable Substitution in Local Command does not work anymore

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#2990]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.1
* install type: launcher
* OS Name/version: Red Hat Enterprise Linux Server release 6.6 (Santiago)
* DB Type/version: mysql/5.1.73-5

**Actual Behavior**
since the upgrade from 2.8.4 to 2.10.1 the variable substitution in the local command doesn't work anymore.

**How to Reproduce**

Job Example:
```
- description: ''
  executionEnabled: true
  group: testing
  id: a2456a72-016f-4d81-8ce6-ffb1a0ed7c78
  loglevel: INFO
  name: local_command_test
  nodeFilterEditable: false
  options:
  - enforced: true
    name: myTestOption
    required: true
    value: myproduct;1.2.3.4
    values:
    - myproduct;1.2.3.4
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: /bin/bash -c 'for var in this is a test; do echo "...${var}..."; done'
      description: no longer works 1
      nodeStep: true
      type: localexec
    - configuration:
        command: /bin/bash -c 'for var in this is a test; do echo "...$var..."; done'
      description: work
      nodeStep: true
      type: localexec
    - configuration:
        command: 'echo "my version: $RD_OPTION_MYTESTOPTION"'
      description: no longer works 2
      nodeStep: true
      type: localexec
    - configuration:
        command: 'echo "my version: ${RD_OPTION_MYTESTOPTION##*;}"'
      description: no longer works 3
      nodeStep: true
      type: localexec
    keepgoing: false
    strategy: node-first
  uuid: a2456a72-016f-4d81-8ce6-ffb1a0ed7c78
```

Job Example Output:
```

1. no longer works 1 | ......
                     | ......
                     | ......
                     | ......
2. work              | ...this...
                     | ...is...
                     | ...a...
                     | ...test...
3. no longer works 2 | my version: $RD_OPTION_MYTESTOPTION
4. no longer works 3 | my version:
```

**Expected Behavior**

Job Example Output:
```

1. no longer works 1 | ...this...
                     | ...is...
                     | ...a...
                     | ...test...
2. work              | ...this...
                     | ...is...
                     | ...a...
                     | ...test...
3. no longer works 2 | my version: myproduct;1.2.3.4
4. no longer works 3 | my version: 1.2.3.4

```
