### ISSUE TITLE
Problem in ACL

### ISSUE THREAD

**Issue by luizhpriotto** [rundeck/rundeck#3097]
Hello, I need help please!

I have Rundeck  2.10.5-1 in Centos 7 by RPM.

My policy dont work...

I edit the file: /var/lib/rundeck/exp/webapp/WEB-INF/web.xml
so I added:

`<security-role>`
                ` <role-name> user </ role-name>`
                 `<role-name> helpdesk </ role-name>`
`</ security-role>`

my realm file is this:

`test: MD5:3c4c3b382418af548cbe12eef4e20d39,helpdesk,user`

and my acl:

`description: Basic Access.`
`context:`
`  project: '.*'`
`for:`
`  resource:`
`    - allow: read`
`  job:`
`    - match:`
`        group: '.*'`
`        name: '.*'`
`      allow: [run,read]`
`by:`
`  group: helpdesk`

BUT i still get a message that I have no access to any project!
I want a rule that works only for running jobs of any project.

so much thanks my friends!

**Comment by ahonor** [comment]
You need a rule like the one below to grant read access to your project. Replace the "MY-PROJECT" with the name of your project name.

```
by:
  group: helpdesk
description: Allow [read] for project
for:
  project:
  - allow:
    - read
    equals:
      name: MY-PROJECT
context:
  application: rundeck
```
