### ISSUE TITLE
Document Yamllint Preferred Configuration

### ISSUE THREAD

**Issue by netflash** [rundeck/rundeck#3124]
Issue type: Enhancement Request

Current yaml format which Rundeck uses doesn't pass https://github.com/adrienverge/yamllint/ validation.
Which could be annoying a little bit.
Here is the `.yamllint` configuration, which allows yaml-jobs to pass

```
---
extends: default
rules:
  empty-lines: {max-end: 1}
  document-start: {present: false}
  indentation: {spaces: 2, indent-sequences: false}
  line-length:
    max: 130
    level: warning
```

I think it might be valuable to add it to the documentation.

If you guys agree and point me to the best place to add it, I can start a PR for adding it to the docs.

Thank you!

**My Rundeck detail**

* Rundeck version: 2.10.4
