### ISSUE TITLE
"Kill Job" doesn't terminate processes executed locally

### ISSUE THREAD

**Issue by abicky** [rundeck/rundeck#3160]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.7-SNAPSHOT (commit 4a5d97ffe54bf2c1e3bb9b3f9faaf28e7b615ca9)
* install type: launcher
* OS Name/version: Linux dad97b0e48e4 4.4.115-boot2docker ([openjdk:8u151-jdk-stretch](https://hub.docker.com/_/openjdk/) docker image)
* DB Type/version: h2

**Expected Behavior**

"Kill Job" terminates the process executing the inline/local/remote script.

**How to Reproduce**

1. Launch rundeck by a command like below:
```
docker run --rm -m 1024m -p 4440:4440 -w /work -v $PWD:/work openjdk:8u151-jdk-stretch \
java -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server -jar rundeck-launcher/launcher/build/libs/rundeck-launcher-2.10.7-SNAPSHOT.jar
```
2. Create a job with a "Script" step or a "Script file or URL" step like below
```yaml
- description: ''
  executionEnabled: true
  id: 45a06bb9-f896-4d9b-a763-ad8113d0c308
  loglevel: INFO
  name: sleep
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo sleep
        exec sleep 6000
    keepgoing: false
    strategy: node-first
  uuid: 45a06bb9-f896-4d9b-a763-ad8113d0c308
```
3. Run the job
4. Kill the job

Before killing the job, the process tree is like below:

```
root@49615926d6aa:/tmp# ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        24  0.0  0.9  52724 20360 pts/0    Ss   17:50   0:00 bash
root       380  0.0  0.1  38384  3020 pts/0    R+   17:58   0:00  \_ ps auxf
root         1 19.9 30.9 3141652 634708 ?      Ssl  17:49   1:52 java -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server -jar rundeck-launcher/launcher/build/libs/rundeck-launche
root       346  0.0  0.0   4292   752 ?        S    17:58   0:00 /bin/sh -c /tmp/0-1-6b6aee7301f7-dispatch-script.tmp.sh
root       348  0.0  0.0   5948   668 ?        S    17:58   0:00  \_ sleep 6000
```

and after killing the job:

```
root@49615926d6aa:/tmp# ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        24  0.0  0.9  52724 20360 pts/0    Ss   17:50   0:00 bash
root       485  0.0  0.1  38384  3104 pts/0    R+   17:59   0:00  \_ ps auxf
root         1 19.2 31.7 3144728 650532 ?      Ssl  17:49   1:56 java -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server -jar rundeck-launcher/launcher/build/libs/rundeck-launche
root       348  0.0  0.0   5948   668 ?        S    17:58   0:00 sleep 6000
```

As you can see, the process executing the inline script (PID 348) is not terminated. Rundeck terminates only `/bin/sh` (PID 346).
`/bin/sh -c` is always used to execute inline/local/remote scripts by the following codes and we can't avoid it.

https://github.com/rundeck/rundeck/blob/4a5d97ffe54bf2c1e3bb9b3f9faaf28e7b615ca9/core/src/main/java/com/dtolabs/rundeck/core/execution/script/ExecTaskParameterGeneratorImpl.java#L83-L84

I think generated dispatch-scripts should be executed directly, in other words, the script file should be specified as `scriptfile` in `ExecTaskParameterGenerator#generate`.

https://github.com/rundeck/rundeck/blob/4a5d97ffe54bf2c1e3bb9b3f9faaf28e7b615ca9/core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutor.java#L75-L80
