### ISSUE TITLE
Referenced job error handlers cannot be found when job is referenced from other projects

### ISSUE THREAD

**Issue by komodo472** [rundeck/rundeck#3189]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.6
* install type: rpm
* OS Name/version: RHEL 7.4
* DB Type/version: PostgreSQL 9.2.23

When a job that references another as an error handler is referenced and run in another project, Rundeck searches for the referenced error handler job within the project of the initial referencing job. From what I can tell, this is caused by the project name of the referenced error handling job not being stored by the job that references it. For example, if I have an error handler job and a job (Job X) that references that error handler both in Project A, then reference Job X from within Project B, Rundeck looks within Project B for the error handler and doesn't find it. It should know to look in Project A.

**Log output**
```
Hello World!
Result: 1
Failed: NonZeroResultCode: Result code was 1
Job [Error Handler Job] not found, project: Rundeck
Failed dispatching to node dev-secops.byu.edu: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: Job [Error Handler Job] not found, project: Rundeck
Failed: JobFailed: Job [Test Error Handler] failed
Execution failed: 1751718 in project Rundeck: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [dev-secops.byu.edu: JobFailed: Job [Test Error Handler] failed + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {dev-secops.byu.edu=[JobFailed: Job [Test Error Handler] failed + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]
```

**Project: Rundeck**
**Job: Test Referenced Job With Error Handler In Different Project**
```
- description: ''
  executionEnabled: true
  id: de398629-9997-4da2-b8bc-fa5fbdd54390
  loglevel: INFO
  name: Test Referenced Job With Error Handler In Different Project
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: ''
        name: Test Error Handler Job
        nodeStep: 'true'
        project: General-Operations
    keepgoing: false
    strategy: node-first
  uuid: de398629-9997-4da2-b8bc-fa5fbdd54390
```

**Project: General-Operations**
**Job: Test Error Handler Job**
```
- description: ''
  executionEnabled: true
  id: 8d00b8c8-6d38-4169-84d3-72dfc8f90427
  loglevel: INFO
  name: Test Error Handler Job
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - errorhandler:
        jobref:
          group: ''
          name: Error Handler Job
          nodeStep: 'true'
        keepgoingOnSuccess: true
      script: |-
        echo "Hello World!"
        exit 1
    keepgoing: false
    strategy: node-first
  uuid: 8d00b8c8-6d38-4169-84d3-72dfc8f90427
```

**Project: General-Operations**
**Job: Error Handler Job**
```
- description: ''
  executionEnabled: true
  id: 3d824cad-c31d-40cb-9f36-16309136fa6b
  loglevel: INFO
  name: Error Handler Job
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: echo "All good now!"
    keepgoing: false
    strategy: node-first
  uuid: 3d824cad-c31d-40cb-9f36-16309136fa6b
```

Referencing a job in another project as an error handler looks like this with the project defined which runs successfully:
```
- description: ''
  executionEnabled: true
  id: de398629-9997-4da2-b8bc-fa5fbdd54390
  loglevel: INFO
  name: Test Referenced Job With Error Handler In Different Project
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - errorhandler:
        jobref:
          group: ''
          name: Error Handler Job
          nodeStep: 'true'
          project: General-Operations
      jobref:
        group: ''
        name: Test Error Handler
        nodeStep: 'true'
        project: General-Operations
    keepgoing: false
    strategy: node-first
  uuid: de398629-9997-4da2-b8bc-fa5fbdd54390
```
