### ISSUE TITLE
Plugin Create Global Variable

### ISSUE THREAD

**Issue by ghost** [rundeck/rundeck#3229]
Issue type: Bug report?

Hi, I have a parent job that invokes two child jobs as node steps. The first child job generates a global variable (using the plugins "Global Variable" and "Key Value Data"). This variable is accessible from the job parent correctly. When the second child job is run, this variable is not accessible.

Is it a bug or is it the normal behavior? Is there another way to access the global variable from the second child job?

Thank you very much for your help

**My Rundeck detail**

* Rundeck version: 2.10.6-1
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: RHEL 7
* DB Type/version: mysql? postgres? h2?.. H2

**Expected Behavior**
We need to access the global variable of the first child job from the second child job.

**How to Reproduce**
Create Job Child 1
  1. First Step: Local Command --> "echo RUNDECK:DATA:JTC=SOMEVALUE"
  2. Second Step: Global Variable -->  Value: ${data.JTC*} Group: export Name: JTC 
  3. Add "Key Value Data" into Job for capture output from first step.
Create Job Child 2 
  1. First Step: Local Command --> "echo ${export.JTC}"

Create Job Parent
  1. First Step: WorkFlow Step --> Job Child 1
  2. Second Step: Local Command --> "echo ${export.JTC}"
  2. third Step: WorkFlow Step --> Job Child 2

**Comment by rlueckl** [comment]
I'm having the exact same issue with Rundeck 3.0.23. Shame, that there was no progress in 2 years...

**Comment by puremourning** [comment]
Post your jobs refs? This is totally possible with the `exports` group. It's a pain sometimes, but it is possible (we use it a lot)

**Comment by rlueckl** [comment]
Hi @puremourning,

here is my test. It's similar to what OP wrote, perhaps even simpler:

 * Parent:
```
- defaultTab: summary
  description: this is the parent job calling childjob-1 and afterwards childjob-2
  executionEnabled: true
  id: ca08cd42-d908-4c03-8e71-ae3cd491776e
  loglevel: INFO
  name: parentjob
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: ''
        name: childjob-1
        uuid: 55aa3287-007a-47a1-b6f1-72cedfacf705
    - exec: 'echo "parent should show value of global var: ${export.myglobalvar}"'
    - jobref:
        group: ''
        name: childjob-2
        uuid: b05a337b-b333-4cfe-866f-479a2b58b213
    keepgoing: false
    strategy: node-first
  uuid: ca08cd42-d908-4c03-8e71-ae3cd491776e
```

 * Child 1:
```
- defaultTab: summary
  description: child job which creates a global variable.
  executionEnabled: true
  id: 55aa3287-007a-47a1-b6f1-72cedfacf705
  loglevel: INFO
  name: childjob-1
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo "this is childjob-1 creating \$export.myglobalvar"
    - configuration:
        export: myglobalvar
        group: export
        value: child-${job.execid}
      nodeStep: false
      type: export-var
    keepgoing: false
    strategy: node-first
  uuid: 55aa3287-007a-47a1-b6f1-72cedfacf705
```

 * Child 2:
```
- defaultTab: summary
  description: this is the second job which tries to read the global variable
  executionEnabled: true
  id: b05a337b-b333-4cfe-866f-479a2b58b213
  loglevel: INFO
  name: childjob-2
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - exec: 'echo "export.myglobalvar is: ${export.myglobalvar}"'
    keepgoing: false
    strategy: node-first
  uuid: b05a337b-b333-4cfe-866f-479a2b58b213
```

I've also tried using an *inline script* in **childjob-2** and echoing `@export.myglobalvar@`, but that didn't work either. Bash notation (`$RD_EXPORT_MYGLOBALVAR` - if there is such a thing) was also a miss.
