### ISSUE TITLE
Cannot see Job Output (with minimal aclpolicy) due to new "dialog box" run job interface

### ISSUE THREAD

**Issue by bluikko** [rundeck/rundeck#3241]
Issue type: Bug report (unexpected change in functionality)

**My Rundeck detail**

* Rundeck version: 2.10.8-1
* install type: rpm
* OS Name/version: EL7
* DB Type/version: h2

**Expected Behavior**
* Output of a just-run job can be viewed even if no permissions to "Activity" history, by just clicking on the "Log Output" tab of the page that shows job completion status

**How to Reproduce**
* Run a job
* The completion page of the new "dialog box" style run job does not have a tab "Log Output" to display output of the job
* There are only the job history links that cannot be opened with minimal aclpolicy
* aclpolicy:
```
context:
  project: 'proj'
for:
  job:
    - equals:
        group: 'group'
      allow: [read,run]
  node:
    - equals:
        rundeck_server: 'true'
      allow: [read]
    - contains:
        tags: nodes
      allow: [read,run]
by:
  username: ['user']

---

context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read]
  project:
    - equals:
        name: 'proj'
      allow: [read]
by:
  username: ['user']

```
It is a bit surprising that this change was not listed in 2.10.8 version history/release notes, upgrade guide or in the milestone issues.

As an admin I still get the "full-page" run job page.

Or is it a "fix" and the ability to view the output of a just-run job was considered a bug if no permissions to "Activity" history?

Can this be fixable in configuration without giving permissions to anyone else's "Activity" history in the job? My users should not see the history of other users' actions even on the same job, if possible.

If not possible, I assume I must give permissions to "Activity" history to all users so that they can see output of their own job.

If Rundeck is really going towards "dialog box" style interface, how about giving us a job step to create a dialog to inform users of something?
