### ISSUE TITLE
Inconsistent behaviour when using POST /api/1/project/[PROJECT]/jobs/import

### ISSUE THREAD

**Issue by georgekaz** [rundeck/rundeck#3247]
Issue type: Bug report

Inconsistent behaviour when using POST /api/1/project/[PROJECT]/jobs/import as per http://rundeck.org/docs/api/#importing-jobs

When importing a job, a job will successfully create with a crontab of '0 * * * * *' but if the job is updated using the same definition it will failed with the error:
`<error>Crontab string format was invalid: {0}
Validation errors: Crontab string format was invalid: {0}</error>`

I've discovered the reason is that 'day of week' or 'day of month' must be '?' but this should be consistent between create and update. Also, the return code is 200 <result success='true' in all cases, which makes the error hard to test.

**My Rundeck detail**

* Rundeck version: 2.10.8-1
* install type: (rpm,deb,war,launcher?) deb
* OS Name/version: Ubuntu 16.04
* DB Type/version: mysql? postgres? h2?.. mysql

**Expected Behavior**
Consistent behaviour between create and update
Clearer messages to indicate and error has occured

**How to Reproduce**
Create job.yaml

```
- description: ''
  executionEnabled: true
  id: example-test
  group: test
  loglevel: INFO
  name: test
  nodesSelectedByDefault: true
  orchestrator:
    configuration:
      count: '1'
    type: subset
  schedule:
    crontab: '2 */15 * * * *'
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo test
      keepgoing: false
    pluginConfig:
      WorkflowStrategy:
        node-first: null
    strategy: node-first
  timeout: 1h
  uuid: example-test
```

run import
```
curl -X POST -H "Content-Type:application/yaml" -H "Cookie:JSESSIONID=16vgtinos8gz1025fpo3f4ms2;Path=/;Secure;HttpOnly" --data-binary "@job.yaml" -w "%{http_code}\n" https://rundeck.example.com/api/14/project/example/jobs/import?dupeOption=update
```

Return code is 200 and response is
```
<result success='true' apiversion='22'>
  <succeeded count='1'>
    <job index='1' href='https://rundeck.example.com/api/22/job/example-test'>
      <id>example-test</id>
      <name>test</name>
      <group>test</group>
      <project>example</project>
      <permalink>https://rundeck.example.com/project/example/job/show/example-test</permalink>
    </job>
  </succeeded>
  <failed count='0' />
  <skipped count='0' />
</result>
```

run again (unchanged)
```
curl -X POST -H "Content-Type:application/yaml" -H "Cookie:JSESSIONID=16vgtinos8gz1025fpo3f4ms2;Path=/;Secure;HttpOnly" --data-binary "@job.yaml" -w "%{http_code}\n" https://rundeck.example.com/api/14/project/example/jobs/import?dupeOption=update
```

Return code is 200 and response is
```
<result success='true' apiversion='22'>
  <succeeded count='0' />
  <failed count='1'>
    <job index='1' href='https://rundeck.example.com/api/22/job/example-test'>
      <id>example-test</id>
      <permalink>https://rundeck.example.com/project/example/job/show/example-test</permalink>
      <name>test</name>
      <group>test</group>
      <project>example</project>
      <error></error>
    </job>
  </failed>
  <skipped count='0' />
</result>
```

run a 3rd time (again unchanged)
```
curl -X POST -H "Content-Type:application/yaml" -H "Cookie:JSESSIONID=16vgtinos8gz1025fpo3f4ms2;Path=/;Secure;HttpOnly" --data-binary "@job.yaml" -w "%{http_code}\n" https://rundeck.example.com/api/14/project/example/jobs/import?dupeOption=update
```

Return code is 200 and response is
```
<result success='true' apiversion='22'>
  <succeeded count='0' />
  <failed count='1'>
    <job index='1' href='https://rundeck.example.com/api/22/job/example-test'>
      <id>example-test</id>
      <permalink>https://rundeck.example.com/project/example/job/show/example-test</permalink>
      <name>test</name>
      <group>test</group>
      <project>example</project>
      <error>Crontab string format was invalid: {0}
Validation errors: Crontab string format was invalid: {0}</error>
    </job>
  </failed>
  <skipped count='0' />
</result>
```
