### ISSUE TITLE
Problem with child job update stats

### ISSUE THREAD

**Issue by jtobard** [rundeck/rundeck#3283]
Issue type: Bug report

Fail stacktrace when a job is referenced as node step with multiple target nodes, parallel dispatch and theard count > 1

**My Rundeck detail**

* Rundeck version: 2.11.0
* install type: launcher
* OS Name/version: Mac OS X / 10.13.4
* DB Type/version: mysql

**Expected Behavior**
Parent job ends normally without errors.

**How to Reproduce**
-Create any job. (named `jobRef` in this example)
-Create a parent job:
```
- description: ''
  executionEnabled: true
  loglevel: INFO
  name: runJobRef
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '3'
    filter: .*
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: ''
        name: jobRef
        nodeStep: 'true'
    keepgoing: false
    strategy: node-first
```

Run parent job `runJobRef`.
