### ISSUE TITLE
Bug: Option values are escaped when dispatched to remote Windows Nodes

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#3433]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.11.3
* install type: (rpm,deb,war,launcher?): Any
* OS Name/version: Any
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

Option values are escaped when dispatched to remote Windows Nodes (  from any Rundeck install/OS) , not allowing values to be interpreted correctly.

Behavior works as "expected" in non-Windows nodes. 

eg. value `O'Connell` is expected to be dispatched as `O'Connell` not `'O'"'"'Connell'`

**How to Reproduce**

- Create a job including a Text Option which is then `echoed` as a Node Step.
- Include a ` '  ` ( eg. O'Connell ) in the Option Value.
- Run the job against a Windows Node, the option is "escaped" in an abnormay way ( causing , e.g. syntax errors in Powershell commands) 
![image](https://user-images.githubusercontent.com/31705339/40552301-44ebd228-600d-11e8-8528-d3c4e954b697.png)

- Same Job against a Linux node, works as expected.
![image](https://user-images.githubusercontent.com/31705339/40551888-2546ade0-600c-11e8-8766-b369fc171b12.png)

* Note: The same behavior occurrs with different install types and OS ,Linux or Windows, when dispatching to Windows nodes.
![image](https://user-images.githubusercontent.com/31705339/40551402-cddd4df8-600a-11e8-9a0e-51366e9424e6.png)

**Test Job ( yaml)**

```
- defaultTab: summary
  description: ''
  executionEnabled: true
  group: In Development
  id: b452df1b-a847-45dc-b226-fcde7daf2ff4
  loglevel: INFO
  name: test_option_w_char_INLINE_SCRIPT
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: true
      rankOrder: ascending
      successOnEmptyNodeFilter: true
      threadcount: '1'
    filter: 'name: "WindowsNode" "UbuntuNode"'
  nodesSelectedByDefault: true
  options:
  - name: name
    value: O'Connell
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo ${option.name}
    - args: '- ${option.name}'
      interpreterArgsQuoted: true
      script: |-
        param ([string]$w)
        Write-Output $w
      scriptInterpreter: powershell.exe
    keepgoing: true
    strategy: node-first
  uuid: b452df1b-a847-45dc-b226-fcde7daf2ff4
```
