### ISSUE TITLE
Execution of scheduled job fails with uploaded file

### ISSUE THREAD

**Issue by Tetha** [rundeck/rundeck#3441]
**Describe the bug**

Hey,

we're currently trying to automate some late night, ad-hoc sql script execution. To do so, we've created a rundeck job which has a file option 'sql'. The job itself uses the file copy step to upload the file, and a remote command to run the file through mysql. However, when running this, we encounter the following error:

    Failed to start execution: rundeck.services.FileUploadServiceException: File ref "<uuid>" cannot be used because it was used for execution 202

The "execution 202" always contains the id of the job itself. 

**My Rundeck detail**

* Rundeck version: 2.10.8-1
* install type: rpm
* OS Name/version: CentOS 7.4.1708
* DB Type/version: mysql

**To Reproduce**
1. Create a job 'bobcat'
2. Click on Add option
2.1 Set option type to <File>
2.2 Enter "foo" into the option_name
2.3 Save the option
3. Add a local node step
3.1 set the command to <cat ${file.foo}>
3.2 save the command
4, Click <Create>
5. Create a file with any content. Mine is called "select_1.sql" and contains "SELECT 1;"
6. On the job page:
6.1 Click on "Choose File" next to foo
6.2 Select your created file.
6.3 Click on "Run Later"
6.4 Schedule the job to run within 1 - 2 minutes
7. Be redirected to the execution page. Mine has execution ID 214.
8. Coffee! Or, spend the 2 minutes in any other way.
9. Click on "log output"
10. Observe: <Failed to start execution: rundeck.services.FileUploadServiceException: File ref "9b72af88-2155-4988-b320-c9ad4f84c578" cannot be used because it was used for execution 214>

**Expected behavior**
I would not expect a job to block it's own files.

**Screenshots**
I could make some, but we've reproduced the problem in 100% of our cases with just a minute or three of clicking around.

**Desktop (please complete the following information):**
 - OS: Both Fedora and MacOS
 - Browser: Tested in Google Chrome and Chromium.
 - Version: Chromium 63.x. Chrome unknown, my colleague has left the office already

**Comment by ahonor** [comment]
Hi @Tetha can you attach your job definition?

**Comment by Tetha** [comment]
Sure thing. The job I've described above results in this job definition in yaml:

```
- description: ''
  executionEnabled: true
  id: 746ef5b1-9ffa-42d3-81ff-4fc933490dec
  loglevel: INFO
  name: bobcat
  nodeFilterEditable: false
  options:
  - name: foo
    type: file
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: cat ${file.foo}
      nodeStep: true
      type: localexec
    keepgoing: false
    strategy: node-first
  uuid: 746ef5b1-9ffa-42d3-81ff-4fc933490dec
```
