### ISSUE TITLE
Job step skipped for no apparent reason

### ISSUE THREAD

**Issue by vinillum** [rundeck/rundeck#3443]
**Describe the bug**
We have a job that is executed on the nodes. It's a rather long job, but towards the end we received the following:

`
10:22:42 |   |   | Step [27] did not run. start conditions: [], skip conditions: []
-- | -- | -- | --
10:22:42 |   |   | Step [27] did not run. start conditions: [], skip conditions: []
`

This is the first time I am seeing this. The job itself is not new, it had hundreds of successful runs, and it doesn't have any conditions around it - the step should be executed no matter what.

**My Rundeck detail**

* Rundeck version: 2.10.7
* install type: rpm
* OS Name/version: RedHat EL 6
* DB Type/version: MySQL

**To Reproduce**
Not sure how to reproduce this - this is the first time I am seeing this, and I had quite a few successful runs afterwards.

**Expected behavior**
Step should have executed.

**Comment by vinillum** [comment]
Job steps:
![capture](https://user-images.githubusercontent.com/1389869/40657900-58d30eb4-6341-11e8-9b3e-843a4058b12d.PNG)

Log output:
![capture](https://user-images.githubusercontent.com/1389869/40657935-7d1b95ac-6341-11e8-94ca-d7c1552c9c5f.PNG)

**Comment by hs-hub-world** [comment]
Can this problem be reproduced -? Because it will be hard to troubleshoot. Also I would suggest to look in the server rundeck/sevice logs if anything shows up there -? One other thing that comes to mind make sure your jobs are not accidenlty referencing 'itself'. Because rundeck will not throw a proper error message when a job references 'itself'.

**Comment by puremourning** [comment]
As discussed internally, we have seen similar when running the same Start Server script across many nodes. Sometimes the step  is just skipped on some nodes, with no explanation as to why. It is not consistently reproducible, which suggests a race condition internally to rundeck. I have tried to catch the result with execution debug mode without success (yet).

This kind of thing is devastating for production use however, and it is making me very nervous. Skipping running steps in a workflow could lead to disaster. Fortunately when it happens to the "Start Server" job, the next job is "Check server started successfully" in both our implementations, so we just fail on the validate and a human has to recover production or restart the deployment.

But if it skipped "Perform backup", we could be in serious trouble.

Case in point, our regression tests just hit this with another job altogether:

![rundeck-skip-steps-start-condition-empty](https://user-images.githubusercontent.com/10584846/42081506-81d86616-7b7d-11e8-88a9-9c4bd72fda60.PNG)

The relevant section of the workflow is:

* Pre-upgrade intra-week check

```yaml
# Pre-upgrade intra-week check
- id: 390f1149-ae03-4bad-a0df-20d9e4ebb4c2
  uuid: 390f1149-ae03-4bad-a0df-20d9e4ebb4c2
  name: Pre-upgrade intra-week check
  description: Check the system is in a state to be upgraded while the system is up
  scheduleEnabled: true
  project: XTP
  group: Checks
  loglevel: INFO
  multipleExecutions: true
  options:
    - *oSystem
    - *oRegion
    - *oITPCODELINE
    - *oITPLABEL
    - *oITPMACODELINE
    - *oITPMALABEL
    - *oGPMCODELINE
    - *oGPMLABEL
    - *oXTPCODELINE
    - *oXTPLABEL
    - *oXTPMACODELINE
    - *oXTPMALABEL
    - *oPORTALCODELINE
    - *oPORTALLABEL
  sequence:
    keepgoing: true
    commands:
    - jobref:
        group: Checks
        name: Pre-upgrade sanity check
        args: -System ${option.System} -Region ${option.Region}
... <other steps>
```
 * Pre-upgrade sanity check

```yaml
# Pre-upgrade sanity check
- id: d6ae06e7-4100-464d-81d3-b14d268dd57e
  uuid: d6ae06e7-4100-464d-81d3-b14d268dd57e
  name: Pre-upgrade sanity check
  description: Ensure access and box setup
  scheduleEnabled: true
  project: XTP
  group: Checks
  loglevel: INFO
  multipleExecutions: true
  options:
  - *oSystem
  - *oRegion
  sequence:
    keepgoing: true # Run everything even if _basic_ checks fail
    commands:
    - jobref:
        group: Checks/_PerNode
        name: Check account access
        nodefilters:
          filter: 'Fidessa:System: ${option.System}
                   Fidessa:Node: ${option.Region}'
    - jobref:
        group: Checks/_PerNode
        name: Check account setup
        nodefilters:
          filter: 'Fidessa:System: ${option.System}
                   Fidessa:Node: ${option.Region}
                   tags: fidserver'
```

* Check account setup

```yaml
# The server environments should be configured approporiately
- id: 0a88581d-0b96-481d-909c-600bcfd5be2e
  uuid: 0a88581d-0b96-481d-909c-600bcfd5be2e
  name: Check account setup
  description: Ensure the server accounts have appropriate configuration
  scheduleEnabled: false
  project: XTP
  group: Checks/_PerNode
  loglevel: INFO
  nodeFilterEditable: true
  orchestrator:
    configuration:
      maxThreads: '6'
    type: perhost-maxthreads
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: true # Run on all nodes
      successOnEmptyNodeFilter: false
      threadcount: 24
    filter: tags:fidserver
  nodesSelectedByDefault: false
  multipleExecutions: true
  sequence:
    keepgoing: false
    strategy: node-first
    commands:
    - script: |
        ... some secret scripts :)
```

As you can see, it skipped the `Check account setup` step. entirely. I can confirm that the nodes in quetsion have `tags: fidserver` set on them (as evidenced by the later steps in the workflow).

What sort of steps can i perform to debug this? It's not consistently reproducible.

We do use a custom orchestrator plugin, but i'm 99% sure that it is not the cause and is following the spec to the letter, particularly as the OP doesn't use that orchestrator.
