### ISSUE TITLE
Dynamic job options

### ISSUE THREAD

**Issue by majkinetor** [rundeck/rundeck#3667]
**Describe the solution you'd like**

I would like to be able to define job options more dynamically. This is currently possible with remote APIs but its not end user friendly and requires a lot of on-boarding. 

Lets say I have 2 scripts, A & B, that I want to make single interface for, and have totally different params, A1,A2,A3 and B1,B2.

I would like to create a job with 1 parameter Type = A|B which will, when type is selected render A1-3 and when B is selected B1-2.

**How this could get implemented**

One idea is multiple option sets defined by the key. So we define some options to be triggers and others to be in sets which could be activated by selection of values in some other field. For example this yaml definition contains 2 interfaces defined by the Type, and 2nd interface has 2 different interfaces for total 4 variants of possible option sets.

```yaml
 options:
 - description: Select type
   name: Type
    values:
    - A
    - B
 - set A
    - trigger: Type#A
    - description: A1 param desc
      name: A1
    - description: A2 param desc
      name: A2
      secure: true
      storagePath: keys/password/A2
      valueExposed: true
    - description: A3 param desc
      name: A3
  - set B
    - trigger: Type#B
    - description: B1 Type
      name: BSType
      values:
       - date
       - comment
    - description: B2 param desc
      name: B2
    - set BS1
        - trigger: BSType#date
        - description Date of issue
          name: issueDate
          dateFormat: YYYY-MM-DD HH:mm:ss
          isDate: true
    - set BS2
        - trigger: BSType#comment
        - description Comment
          name: comment
```
