### ISSUE TITLE
Bug - Not able to fetch SCM status via API

### ISSUE THREAD

**Issue by roman-io** [rundeck/rundeck#3889]
I'm trying to fetch SCM status a project using the API and it fails on authorization.
The same user is able to execute any SCM command from the web interface.
Issue is specific to tokens created manually in `tokens.properties`. Tokens that are created via the web ui don't have this issue.

rd projects scm status --project myproject --integration export
Error: Not authorized for action "export" for Project myproject
[code: api.error.item.unauthorized; APIv24]
Authorization failed: 403 Forbidden

**Admin policy**
```
aclpolicy:
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin
```
**Setup** 
* Rundeck version: Rundeck 2.11.5-1 
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: postgres

**Way to reproduce**
1. Create admin policy as described above.
2. Add apiuser in `tokens.properties`
3. Restart Rundeck.
4. Try to `rd projects scm status -p any-existing-project -i export`

**realm.properties**
```
#admin:admin,user,admin,architect,deploy,build
admin: MD5:sumhere,user,admin

#
# This sets the api user accounts for the integrateme-dev and integrateme-prod
#
apiintdev: MD5:sumhere1,IntegrateMe_Dev,user
apiintprod: MD5:sumhere2,IntegrateMe_Prod,user
apiservice: passwordhere1,admin,user
```

**tokens.properties**
```
apiintdev: generatedapitokenhere1
apiintprod: generatedapitokenhere2
apiservice: generatedapitokenhere3
```
