### ISSUE TITLE
ACL policy issue with leading hyphen

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4114]
I suspect the leading hyphens are causing issues with the ACL policy. I am unable to create an ACL policy that recognizes the imported role (from LDAP):

-DG-APP-TRRS Enterprise - TSG Level 1

I have tried many variations of ACL group scoping including:

```
by:
  group: [ *TSG Level 1 ]

by:
  group: '*TSG Level 1'

by:
  group: -DG-APP-TRRS Enterprise - TSG Level 1

by:
  group: '-DG-APP-TRRS Enterprise - TSG Level 1'

by:
  group: (.*TSG Level 1)
```

No variation allows the group member through. I ran rd-acl tests against it and realized I could not get the command to account for the leading hyphen because rd-acl saw it as a new switch:

```
[root@gtrep rundeck]# rd-acl create -c application -g "-DG-APP-TRRS Enterprise - TSG Level 1" -p test
org.apache.commons.cli.MissingArgumentException: no argument for:g
```

I suspect this may be related to the issue. I have only tested this on rundeck 3.0.7.
