### ISSUE TITLE
SCM plugin doesn't see fetched jobs from external repo

### ISSUE THREAD

**Issue by brysk** [rundeck/rundeck#4134]
**SCM plugin doesn't see fetched jobs from external repo**

**My Rundeck detail**

* Rundeck version: 3.0.7
* install type: war
* OS Name/version: docker on ubuntu 16.04
* DB Type/version: mysql

I have setup git SCM import plugin as follows:

```
rundeck@rundeck:~$ java -jar rundeck-cli-1.1.0-all.jar projects scm config -p stage --integration import
# Project: stage
# SCM Plugin type: git-import
# SCM Plugin integration: import
config:
  url: [gitlab_repo]
  fetchAutomatically: false
  pullAutomatically: true
  dir: /home/rundeck/projects/stage/import/scm
  filePattern: .*\.xml
  importUuidBehavior: preserve
  useFilePattern: false
  strictHostKeyChecking: no
  sshPrivateKeyPath: keys/stage/user_key
  format: xml
  branch: master
  gitPasswordPath:
  pathTemplate: ${job.group}${job.name}-${job.id}.${config.format}
```

Remote fetch:

```
rundeck@rundeck:~$ java -jar rundeck-cli-1.1.0-all.jar projects scm perform --action remote-fetch  -p stage --integration import
# Action remote-fetch was successful.
# Result: SCM import Action was Successful: remote-fetch
```

Checking import status:
```
rundeck@rundeck:~$ java -jar rundeck-cli-1.1.0-all.jar projects scm status -p stage --integration import
synchState: CLEAN
message:
actions:
  remote-fetch
```

My job list in Rundeck is empty, but I'm able to see all fetched job definitions inside defined directory:

```
rundeck@rundeck:~$ ls -l /home/rundeck/projects/stage/import/scm/ | wc -l
446
```

Inputs list is empty:

```
rundeck@rundeck:~$ java -jar rundeck-cli-1.1.0-all.jar projects scm inputs --action import-all -p stage --integration import
Import remote Changes: Import the modifications to Rundeck
Fields:

Items:
```

Import all doesn't do anything:

```
rundeck@rundeck:~$ java -jar rundeck-cli-1.1.0-all.jar projects scm perform --action import-all --allitems -p stage--integration import
# Action import-all was successful.
# Result: SCM import Action was Successful: import-all
```

**Expected behavior**
Import status should indicate NEEDED IMPORT
SCM inputs should display all new items
Import-all should import all jobs into rundeck

Is there anything I'm missing here? I've managed to make it working once but after I've deleted all the jobs it's causing issues.

Is there any way to clean/reset SCM import status?
