### ISSUE TITLE
Not executable referenced jobs lead to successful execution

### ISSUE THREAD

**Issue by shoelzle** [rundeck/rundeck#4183]
**Describe the bug**
I recently upgraded from Rundeck 2.10.1 to 3.0.8. I noticed a different behavior:
A job can reference other jobs. In 3.0.8 the referenced job must be executable, in 2.10.1 the referenced job did not have to be executable.
The new behavior is comprehensible, however the execution result and the report result in such a case is not.

**My Rundeck detail**

* Rundeck version: 3.0.8

**To Reproduce**
1. Create a job, e.g. "link depth1", and disable the executable flag:
```
- defaultTab: summary
  description: ''
  executionEnabled: false
  group: rundeck3test
  id: 8096c7c6-0811-48a2-bb72-28c2649828bd
  loglevel: INFO
  name: link depth1
  nodeFilterEditable: false
  options:
  - name: opt1
    required: true
  scheduleEnabled: true
  sequence:
    commands:
    - script: echo "link depth1 (@option.opt1@)"
    keepgoing: true
    strategy: parallel
  uuid: 8096c7c6-0811-48a2-bb72-28c2649828bd
```
2. Create another job, e.g. "rundeck link test" and reference the previously created job:
```
- defaultTab: summary
  description: ''
  executionEnabled: true
  group: rundeck3test
  id: 8ea74658-4c1e-4ae0-aa3a-988d7e392639
  loglevel: INFO
  name: rundeck link test
  nodeFilterEditable: false
  options:
  - name: opt1
  scheduleEnabled: true
  sequence:
    commands:
    - description: t1
      script: echo "rundeck link test (@option.opt1@)"
    - description: t1
      jobref:
        args: -opt1 ${option.opt1}
        group: rundeck3test
        name: link depth1
        uuid: 8096c7c6-0811-48a2-bb72-28c2649828bd
    keepgoing: false
    strategy: sequential
  uuid: 8ea74658-4c1e-4ae0-aa3a-988d7e392639
```
3. Execute the job "rundeck link test"

**Expected behavior**
The job execution fails.

**Screenshots**

The report result shows the referenced job in the state "Next up" after the referencing job has finished successfully:
![screenshot 2018-11-07 at 13 12 04](https://user-images.githubusercontent.com/4390702/48131839-b8997480-e291-11e8-9e0a-93a216f20cbf.png)
