### ISSUE TITLE
Unable to pass job.user.email to worflow step

### ISSUE THREAD

**Issue by kquilliam** [rundeck/rundeck#4212]
**Describe the bug**
${job.user.email} not being passed into job resulting in a null value. Im using Rundeck to execute Ansible playbooks and I am trying to pass ${job.user.email} into the playbook to email configlets to the executing user. ${job.user.name} is currently being used without issue.

**My Rundeck detail**
* Rundeck version: 2.11.5
* install type: rpm
* OS Name/version: CentOS Linux release 7.5.1804 (Core)
* DB Type/version: postgres

**To Reproduce**
Create job referencing a playbook with a var assigned to the content of ${job.user.email}.
```
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: 4a24de3e-f576-46e5-90fb-23e4a446faa0
  loglevel: INFO
  name: TESTING
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        ansible-become: 'false'
        ansible-become-method: sudo
        ansible-extra-param: --limit ""
        ansible-extra-vars: |
          rundeck_email: ${job.user.email}
        ansible-playbook: /etc/ansible/new_test/.git/dev/rundeck.yml
      nodeStep: false
      type: com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep
    keepgoing: false
    strategy: node-first
  uuid: 4a24de3e-f576-46e5-90fb-23e4a446faa0

```
```
---
- name: Test template
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - debug: msg="{{ rundeck_email }}"
```

**Expected behavior**
The email address of the user profile would be passed into the workflow step.

When ran directly from Ansible, passing the email as a var the result is what is expected.
`ansible-playbook rundeck.yml -vvv --extra-vars rundeck_email=email@somemail.com`
```
ok: [localhost] => {
    "msg": "email@somemail.com"
}
```

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
