### ISSUE TITLE
Preauth user and cookie session user get out of sync

### ISSUE THREAD

**Issue by yaegashi** [rundeck/rundeck#4394]
**Describe the bug**

Preauth user and cookie session user get out of sync after sign out / sign in as different users.

They get synced again by manually erasing JSESSIONID cookie on web browser.  Apparently Rundeck fails to invalidate user information in the session storage on sign out when preauth enabled.  

**My Rundeck detail**

* Rundeck version: 3.0.12-20190114
* install type: [Official docker image](https://hub.docker.com/r/rundeck/rundeck) `rundeck/rundeck:3.0.12`
* OS Name/version: Ubuntu 16.04 in the container
* DB Type/version: h2

**To Reproduce**

Create `docker-compose.yml`:
```yaml
version: '3'
services:
  rundeck:
    image: rundeck/rundeck:3.0.12
    environment:
      RUNDECK_SERVER_FORWARDED: "true"
      RUNDECK_PREAUTH_ENABLED: "true"
      RUNDECK_PREAUTH_USERNAME_HEADER: X-Forwarded-User
      RUNDECK_PREAUTH_ROLES_HEADER: X-Forwarded-User  # XXX: pass the same role as username
      RUNDECK_PREAUTH_REDIRECT_LOGOUT: "true"
      RUNDECK_PREAUTH_REDIRECT_URL: /oauth2/sign_in
      RUNDECK_GRAILS_URL: http://localhost:8080
  oauth2_proxy:
    image: bitnami/oauth2-proxy
    command:
      - "-http-address=http://:8080"
      - "-upstream=http://rundeck:4440"
      - "-pass-basic-auth=false"
      - "-pass-user-headers=true"
      - "-htpasswd-file=/htpasswd"
      - "-client-id=fake"
      - "-client-secret=fake"
      - "-cookie-name=_rundeck"
      - "-cookie-secret=secret"
      - "-cookie-secure=false"
    volumes:
      - ./htpasswd:/htpasswd
    ports:
      - 8080:8080
```

Create `htpasswd` file including 2 users: `admin`, `user`
```console
$ touch htpasswd
$ htpasswd -bs htpasswd admin password
$ htpasswd -bs htpasswd user password
```

Launch docker containers
```console
$ docker-compose up
```

Open http://localhost:8080 with web browser.

Repeat sign in / sign out as 2 different users using Username/Password form.
1. Sign in as `admin`
2. Sign out (choose Logout)
3. Sign in as `user`
4. Sign out (choose Logout)
5. Repeat from 1 again

**Expected behavior**

Signed-in user and his role (group) should be always identical.

![image](https://user-images.githubusercontent.com/106724/51346528-3aebb380-1ae1-11e9-80fb-b6c72f0d9c7e.png)

**Actual behavior**

Signed-in user and his role get out of sync (actually the latter is correct).

![image](https://user-images.githubusercontent.com/106724/51346891-12b08480-1ae2-11e9-828d-4886b38bc6c1.png)

**Desktop (please complete the following information):**

 - OS: macOS 10.14
 - Browser: Google Chrome 
 - Version: 71.0.3578.98

**Additional context**

None.
