### ISSUE TITLE
unable to deploy rundeck/rundeck on kubernetes

### ISSUE THREAD

**Issue by admun** [rundeck/rundeck#4403]
**Describe the bug**
When deploy rundeck/rundeck on kubernetes, pod failed to come up with the following error

`
container_linux.go:247: starting container process caused "exec: \"docker-lib/entry.sh\": stat docker-lib/entry.sh: no such file or directory"
`

**My Rundeck detail**
* Rundeck version: 3.0.12
* install type: docker image rundeck/rundeck:3.0.12
* OS Name/version: kubernetes 1.12 with rancher 2.1
* DB Type/version: h2

**To Reproduce**
deploy with rancher 2.1 using following deploymen.yml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rundeck
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      volumes:
           - name: rundeck-home
             emptyDir: {}
      containers:
        - name: rundeck
          image: rundeck/rundeck:3.0.12
          env:
            - name: RUNDECK_GRAILS_URL
              value: http://rundeck.somewhere.net
          ports:
            - name: http-port
              containerPort: 4440
          volumeMounts:
            - name: rundeck-home
              mountPath: /home/rundeck
```

**Expected behavior**
able to deploy rundeck to a pod

**Screenshots**
n/a
**Desktop (please complete the following information):**
n/a

**Additional context**

**Comment by admun** [comment]
found the issue my volume overwrite existing from the images

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rundeck
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      volumes:
           - name: rundeck-projects
             emptyDir: {}
           - name: rundeck-data
             emptyDir: {}
      containers:
        - name: rundeck
          image: rundeck/rundeck:3.0.12
          env:
            - name: RUNDECK_GRAILS_URL
              value: http://rundeck.domewhere.net
          ports:
            - name: http-port
              containerPort: 4440
          volumeMounts:
            - name: rundeck-projects
              mountPath: /home/rundeck/projects
            - name: rundeck-data
              mountPath: /home/rundeck/server/data
```
