### ISSUE TITLE
Rundeck holds connections on job referenced jobs

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4459]
**Describe the bug**
Rundeck is holding the connections to backend DB when there are references to other jobs.
These connections will be held as long as the child job is still running and it can be several hours. If there are many such jobs, we will end up in a situation where Rundeck is holding many idle connections for a lot of time with backend DB

**My Rundeck detail**

* Rundeck version: 3.0.9
* install type: rpm
* OS Name/version: ubuntu 18.04
* DB Type/version: Mysql: version: 5.6.22-72

**To Reproduce**
running job referenced jobs

**Comment by jplassnibatt** [comment]
Little more info:
```
When the job was in this weird state, I got the output of the command "SHOW ENGINE INNODB STATUS" from our MySQL server (output attached). You will see that there are "4 RW transactions active inside InnoDB" corresponding to this job in this hung state.

I also got the output of the command "show full processlist;" You will see four sessions in "sleep" state corresponding to the hung job. Output has been attached.

+-------+---------+--------------------+---------+---------+------+----------+-----------------------+-----------+---------------+
| Id | User | Host | db | Command | Time | State | Info | Rows_sent | Rows_examined |
+-------+---------+--------------------+---------+---------+------+----------+-----------------------+-----------+---------------+
| 56837 | rundeck | 17.238.34.98:33276 | rundeck | Sleep | 3525 | | NULL | 0 | 0 |
| 56841 | rundeck | 17.238.34.98:33284 | rundeck | Sleep | 3506 | | NULL | 0 | 0 |
| 56847 | rundeck | 17.238.34.98:33296 | rundeck | Sleep | 3506 | | NULL | 0 | 0 |
| 56848 | rundeck | 17.238.34.98:33298 | rundeck | Sleep | 3506 | | NULL | 0 | 0 |
```
This is part of the db section from rundeck-config.properties:
```
dataSource.properties.validationQuery=SELECT 1
dataSource.properties.validationQueryTimeout=3
dataSource.properties.validationInterval=15000
dataSource.properties.testOnBorrow=true
dataSource.properties.testWhileIdle=true
dataSource.properties.testOnReturn=false
dataSource.properties.maxActive= 50
dataSource.properties.minIdle=10
dataSource.properties.maxIdle=25
dataSource.properties.maxWait=10000
dataSource.properties.maxAge=600000
dataSource.properties.logValidationErrors=true
```

**Comment by jtobard** [comment]
Reproduced using this job:
```
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: f656325e-99b6-4989-a419-ccaa723391ab
  loglevel: INFO
  multipleExecutions: true
  name: parent
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo start
    - jobref:
        group: ''
        name: callme
        nodeStep: 'true'
    - jobref:
        group: ''
        name: callme
        nodeStep: 'true'
    - jobref:
        group: ''
        name: callme
        nodeStep: 'true'
    - jobref:
        group: ''
        name: 'callme '
        nodeStep: 'true'
    - jobref:
        group: ''
        name: 'callme '
        nodeStep: 'true'
    - jobref:
        group: ''
        name: 'callme '
        nodeStep: 'true'
    - jobref:
        group: ''
        name: 'callme '
        nodeStep: 'true'
    - jobref:
        group: ''
        name: 'callme '
        nodeStep: 'true'
    - jobref:
        group: ''
        name: 'callme '
        nodeStep: 'true'
    keepgoing: false
    strategy: parallel
  uuid: f656325e-99b6-4989-a419-ccaa723391ab

```


Connections before and after execute the job (10):
![Captura realizada el 2019-03-18 12 47 43](https://user-images.githubusercontent.com/2894508/54543560-a2589f00-497c-11e9-9288-71a80bc5d548.png)


Connections while the task is running (19): 
![Captura realizada el 2019-03-18 12 48 25](https://user-images.githubusercontent.com/2894508/54543655-cd42f300-497c-11e9-800a-23dbf7f093ea.png)
