### ISSUE TITLE
ACL group REGEX not matching

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4484]
ACL policy for jobs based on group regex is not working. For example, we have a group called "PL1", which only accepts the exact "PL1" name in an ACL. We want to use the first example below with regex.

Doesn't work
```
  job:
    - equals:
        group: '^PL1($|/.*)'
      allow: [run,view,kill]
```
Works
```
  job:
    - equals:
        group: 'PL1'
      allow: [run,view,kill]
```

This was copied and modified from [example documentation on github](https://gist.github.com/gschueler/6732471cbd15536bc8b1) (noticed the latest 3.0.13 does not include regex job example).

install type: yum
version 3.0.13
centos
mysql
