### ISSUE TITLE
Job reference: Unable to rollback against JDBC...

### ISSUE THREAD

**Issue by jacekkow** [rundeck/rundeck#4489]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.0.13
* install type: deb
* OS Name/version: Debian 9 (stretch)
* DB Type/version: MariaDB

**Current Behavior**
Long running jobs that uses references to other job fail just after completion with an error from Rundeck, causing the execution to fail:
```
Failed dispatching to node localhost: org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection
Execution failed: 5 in project Test: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [localhost: Unknown: org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection]}, Node failures: {localhost=[Unknown: org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection]}, status: failed]
```
Running the referenced job itself succeedes.

**Expected Behavior**
Long-running referenced jobs should work correctly.

**How to Reproduce**
1. Install Rundeck 3.0.13 with MySQL backend as described here: https://docs.rundeck.com/docs/administration/configuration/database/mysql.html
2. Create long running job:
```
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: 4fc0a653-ebff-4a18-a1ac-bd96268cdf0f
  loglevel: INFO
  name: Test job
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |
        #!/bin/bash

        COUNTER=600

        while [ $COUNTER -gt 0 ]; do
            COUNTER=$(( COUNTER - 1 ))
            echo "${COUNTER}s left..."
            sleep 1
        done
    keepgoing: false
    strategy: node-first
  uuid: 4fc0a653-ebff-4a18-a1ac-bd96268cdf0f
```
3. Create another job that references the first one:
```
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: 42d109a3-15ed-4ff7-b013-855d2ce937b9
  loglevel: INFO
  name: Execute referenced
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: ''
        name: Test job
        nodeStep: 'true'
        uuid: 4fc0a653-ebff-4a18-a1ac-bd96268cdf0f
    keepgoing: false
    strategy: node-first
  uuid: 42d109a3-15ed-4ff7-b013-855d2ce937b9
```
4. Run the "Execute referenced" job.
