### ISSUE TITLE
Worker threads stuck if no target is defined for node

### ISSUE THREAD

**Issue by SaltySolomon** [rundeck/rundeck#4698]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version:  3.0.19
* install type: rpm
* OS Name/version: CentOS 6 
* DB Type/version: postgres

**Expected Behavior**

On the rundeck 2 instance it just fails the execution if it encounters a node that has no IP defined, with the new install on rundeck 3 it instead make the thread go stuck.

**How to Reproduce**

Attempt to run job with nodes that have no target defined.

**Comment by SaltySolomon** [comment]
The expected behaviour is that the node execution fails.

**Comment by reinerrdeck** [comment]
Hi @SaltySolomon, I tried leaving blank the hostname section of resources.xml but I receive

`Failed: ConfigurationFailure: Hostname must be set to connect to remote node 'my_remote_host'`

You can provide an example of how was configure your host? (e. g. resources.xml file)

Regards.

**Comment by SaltySolomon** [comment]
Okay, I rechecked th config and the ip was configured as:

"ip" : null,

**Comment by reinerrdeck** [comment]
Hi @SaltySolomon,

Do you use node definition in YAML format like this?

```
mynode:
  nodename: mynode
  hostname: 192.168.33.40
  osVersion: 3.10.0-957.10.1.el7.x86_64
  osFamily: unix
  osArch: amd64
  description: Remote server node
  osName: Linux
  username: myuser
  tags: ''
  ssh-key-storage-path: keys/mynode
```

Greetings.
