### ISSUE TITLE
ACL: Add a property to allow indirectly execute referenced jobs (eg. "Allow: RunAsReference" )

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#4705]
**Is your feature request related to a problem? Please describe.**

Use case: A generic set of jobs is created. These "generic" jobs are referred within a Parent Job ( which provide eg, the required parameters to them) but,  NOT allowing the End User to access them. 

Parent job is calling a Child Job as JobRef.  ACL permissions allow the user ONLY to run Parent Job ( run permissions are not inherited to JobRef ). It is not desired to directly Grant access to the "child jobs" but this is currently the only way to make Referenced Jobs work. 

**Describe the solution you'd like**
 
A way to allow indirectly execute referenced jobs may be adding an ACL entry such as "Allow: RunAsReference" that will allow a Referenced Job to run when referenced from a Parent Job ( regardless of the User permissions) 

**Example ACL: 
- Parent_Job calls Child_Job as JobRef
- "user" is only allowed to _view, read, run_ Parent_Job 
- JobRef is NOT executed

```
by:
  username: user
description: Allow running only parent_job
for:
  job:
  - allow:
    - view
    - read
    - run
    equals:
      name: Parent_Job
  node:
    - allow: [read,run] # allow read/run for nodes
context:
  project: TEST_PROJECT
---
by:
  username: user
description: View Project
for:
  project:
  - allow:
    - read
    equals:
      name: TEST_PROJECT
context:
  application: rundeck
---
by:
  username: user
description: Allow [*] for (All) node
for:
  resource:
  - allow:
    - '*'
    equals:
      kind: node
context:
  project: TEST_PROJECT
```
