### ISSUE TITLE
Lowest access ACL taking precedence over higher access acls

### ISSUE THREAD

**Issue by DerfOh** [rundeck/rundeck#4731]
**Describe the bug**
I'm unable to find the delete option in the triangle dropdown for rundeck. I believe this may be related to ACL preference. 

Currently we have 2 groups set up, one specifically for a project with just basic "user" permissions: 
description: read only access policies
user.aclpolicy
```
context:
  project: 'Operations'
for:
  resource:
    - allow: [read]
  job:
    - match:
        name: '.*'
      allow: [read]
  node:
    - match:
        nodename: '.*'
      allow: [read]
by:
  username: [someuser, someotheruser]
  group: [ 'users' ]
```
and another ACL set up for administrative users
admin.aclpolicy
```
description: Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [create] # allow create of projects
    - equals:
        kind: system
      allow: [read,enable_executions,disable_executions,admin] # allow read of system info, enable/disable all executions
    - equals:
        kind: system_acl
      allow: [read,create,update,delete,admin] # allow modifying system ACL files
    - equals:
        kind: user
      allow: [admin] # allow modify user profiles
  project:
    - match:
        name: '.*'
      allow: [read,import,export,configure,delete,admin] # allow full access of all projects or use 'admin'
  project_acl:
    - match:
        name: '.*'
      allow: [read,create,update,delete,admin] # allow modifying project-specific ACL files
  storage:
    - allow: [read,create,update,delete] # allow access for /ssh-key/* storage content

by:
  username: [someadmin,anotheradmin]
  group: ['admin-group']
```
*Members of admin-group also belong to user-group*

**My Rundeck detail**

* Rundeck version: 3.0.20-20190408
* install type: [choose: war]
* OS Name/version: [e.g. RHEL 7]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
Steps to reproduce the behavior: https://docs.rundeck.com/2.11.3/manual/jobs.html#deleting-jobs
1. Go to 'project > jobs'
2. Click on 'V dropdown'
3. Observe no Delete option

**Expected behavior**
ACL with most permission will be applied according to group membership and the delete option should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/6360456/56430826-a2a6cb80-6295-11e9-8283-2f3a7fb6b111.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version Developer Edition 67.0b11 (64-bit)

**Additional context**
I have a 2.11.3-1 instance running with identical ACLs that allows for jobs to be deleted by users who belong to the admin group.

**Comment by DerfOh** [comment]
https://github.com/rundeck/rundeck/issues/2616
Seems similar however we are not using the "deny" directive.

**Comment by DerfOh** [comment]
Solved, this appears to be a configuration snaffoo on our end 
```
  resource:
    - equals:
        kind: project
      allow: [create] # allow create of projects
```
had to be changed to

```
  resource:
    - equals:
        kind: project
      allow: [create, delete] # allow create of projects
```
