### ISSUE TITLE
Wrong execution of local step if followed from Workflow step

### ISSUE THREAD

**Issue by oOHenry** [rundeck/rundeck#4737]
**Describe the bug**
If a local step is followed by a local workflowstep the first local step is executed for all nodes although node first is set.

**My Rundeck detail**

* Rundeck version: 3.0.20-20190408
* install type: deb
* OS Name/version: debian 9.8
* DB Type/version: postgres

**To Reproduce**
1. Create local echo job:
```yaml
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: 3cc6c039-f4b7-4bed-aa29-298ae0742685
  loglevel: INFO
  name: echo local
  nodeFilterEditable: false
  options:
  - name: Hostname
    required: true
  - name: Message
  scheduleEnabled: true
  sequence:
    commands:
    - args: ${option.Hostname} ${option.Message}
      script: |
        #!/bin/bash


        echo "I'm local on the rundeck server: got hostname var: ${1} message: ${2}"
    keepgoing: false
    strategy: node-first
  timeout: 1h
  uuid: 3cc6c039-f4b7-4bed-aa29-298ae0742685
```
2. Create remote echo job:
```yaml
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: bbb08bea-2601-4b6a-89c7-cb1462c22120
  loglevel: INFO
  name: echo remote
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ${option.Hostname}
  nodesSelectedByDefault: true
  options:
  - name: Hostname
  - name: Message
  scheduleEnabled: true
  sequence:
    commands:
    - args: ${option.Message}
      script: |+
        #!/bin/bash

        hostname=$(hostname -f)
        echo "I'm on ${hostname} message: ${1}"

    keepgoing: false
    strategy: node-first
  uuid: bbb08bea-2601-4b6a-89c7-cb1462c22120
```
3.  Create a job which contain the local job and the remote job in the order:
`Local execution -> local execution (workflow step) -> remote execution`

```yaml
- defaultTab: summary
  description: ''
  executionEnabled: true
  id: ae923ea9-08ab-486f-ad66-0706ee824d93
  loglevel: INFO
  name: Rundeck problem
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ${option.Hostname}
  nodesSelectedByDefault: true
  options:
  - name: Hostname
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        args: -Hostname ${node.name} -Message ""
        group: ''
        name: echo local
        nodeStep: 'true'
        uuid: 3cc6c039-f4b7-4bed-aa29-298ae0742685
    - jobref:
        args: -Hostname ${option.Hostname} -Message "Workflowstep"
        group: ''
        name: echo local
        uuid: 3cc6c039-f4b7-4bed-aa29-298ae0742685
    - jobref:
        args: -Hostname  ${node.name} -Message "remote step"
        group: ''
        name: echo remote
        nodeStep: 'true'
        uuid: bbb08bea-2601-4b6a-89c7-cb1462c22120
    keepgoing: false
    strategy: node-first
  uuid: ae923ea9-08ab-486f-ad66-0706ee824d93
```
**Execution for srv[1-3]:**
```
I'm local on the rundeck server: got hostname var: srv01.server.lan message: 
I'm local on the rundeck server: got hostname var: srv02.server.lan message: 
I'm local on the rundeck server: got hostname var: srv03.server.lan message: 
I'm local on the rundeck server: got hostname var: srv0[1-3].* message: Workflowstep
I'm on srv01.server.lan message: remote step
I'm on srv02.server.lan message: remote step
I'm on srv03.server.lan message: remote step
```

**Expected behavior**
```
I'm local on the rundeck server: got hostname var: srv01.server.lan message: 
I'm local on the rundeck server: got hostname var: srv0[1-3].* message: Workflowstep
I'm on srv01.server.lan message: remote step

I'm local on the rundeck server: got hostname var: srv02.server.lan message: 
I'm on srv02.server.lan message: remote step

I'm local on the rundeck server: got hostname var: srv03.server.lan message: 
I'm on srv03.server.lan message: remote step
```

**Desktop (please complete the following information):**
 - OS: Fedora 28
 - Browser  Vivaldi/Firefox
