### ISSUE TITLE
Import option file type from parent to child job fail 

### ISSUE THREAD

**Issue by o0ste0o** [rundeck/rundeck#4944]
**Describe the bug**
When you want import your option FILE type from parent job to child jobs ,rundeck got error:
Option input was not valid for job ......

**My Rundeck detail**

* Rundeck version: 3.0.22
* install type: rpm
* OS Name/version: Linux Centos 7
* DB Type/version: mysql 8

**To Reproduce**
1. create a child job with option FILE type vminv
2. create a parent job with option FILE type VMLIST 
2.1 create workflow step referencing the child job with argument
-vminv {file.VMLIST} and check import option check box as well
4. execute the parent job 
5.you got the error :Option input was not valid for 
**Expected behavior**
I'm expecting that pass the option to the child job 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: WINDOWS 
 - Browser firefox 
 - Version 

**Additional context**

**Comment by MegaDrive68k** [comment]
Confirmed on 3.0.22 WAR.

**Comment by jtobard** [comment]
The argument must be `-vminv {option.VMLIST}` not `-vminv {file.VMLIST}`.
There's an example for this:

`parent.yaml`
```yaml
- defaultTab: nodes
  description: parent job with file
  executionEnabled: true
  group: '4944'
  id: 88b506fe-8725-4cc3-9fb9-fd24e5a668b9
  loglevel: INFO
  name: parent
  nodeFilterEditable: false
  options:
  - name: foo
    type: file
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        args: -foo ${option.foo}
        group: '4944'
        name: child
        useName: 'true'
        uuid: 746ef5b1-9ffa-42d3-81ff-4fc933490dec
    keepgoing: false
    strategy: node-first
  uuid: 88b506fe-8725-4cc3-9fb9-fd24e5a668b9
```
`child.yaml`
```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: '4944'
  id: 746ef5b1-9ffa-42d3-81ff-4fc933490dec
  loglevel: INFO
  name: child
  nodeFilterEditable: false
  options:
  - name: foo
    required: true
    type: file
  scheduleEnabled: true
  sequence:
    commands:
    - exec: cat ${file.foo}
    keepgoing: false
    strategy: node-first
  uuid: 746ef5b1-9ffa-42d3-81ff-4fc933490dec

```
