### ISSUE TITLE
Global options (from project.properties) not available in option values 

### ISSUE THREAD

**Issue by mmiesiak** [rundeck/rundeck#5016]
**My Rundeck detail**
* Rundeck version: Rundeck 2.6.9-1 cafe bonbon indigo tower 2016-08-22
* install type: rpm
* OS Name/version: Linux RedHat 6.5

**Expected Behavior**
* When creating an option on a job using JOB-YAML, the default value for the options can use global variables, such as:
```
    options:                                                                                                                                                                    
      System:                                                                                                                                                                   
        value: ${globals.server_port}                                                                                                        
        required: true    
```

**Actual Behavior**
* Loading the job fails, with the following error:
```
ERROR RundeckAPICentralDispatcher:      Jobs Document was invalid for format yaml: rundeck.controllers.JobXMLException: Unable to create Job: For input string: "${globals.server_port}"
ERROR RundeckAPICentralDispatcher: Server reported an error: Bad Request
Error: Failed request to load jobs: Jobs Document was invalid for format yaml: rundeck.controllers.JobXMLException: Unable to create Job: For input string: "${globals.server_port}"
```

**To Reproduce**
* Add the following line to the projects project.properties
`project.globals.server_port=4441`
* Create a job with a single option as follows in a file test.yaml:
```
  - id: 8a2c58bb-6db9-434d-a8dc-16151b27247d                                                                                                                                    
    uuid: 8a2c58bb-6db9-434d-a8dc-16151b27247d                                                                                                                                  
    name: Test                                                                                                                                                                  
    description: Test                                                                                                                                                           
    project: Test                                                                                                                                                                
    group: Test
    options:                                                                                                                                                                    
      TestOption:                                                                                                                                                               
        required: true                                                                                                                                                          
        value: ${globals.server_port}                                                                                                                                                     
    sequence:                                                                                                                                                                   
      keepgoing: false                                                                                                                                                          
      strategy: node-first                                                                                                                                                      
      commands:                                                                                                                                                                 
      - exec: echo "Hello"                                                                                                                                                      
```
* load the job with `rd-jobs load -F yaml -d update -p Test -f test.yaml`
* Expect: job is loaded
* Actual:
```
[jobs]$ rd-jobs load -F yaml -d update -p XTP -f test.yaml 
ERROR RundeckAPICentralDispatcher:      Jobs Document was invalid for format yaml: rundeck.controllers.JobXMLException: Unable to create Job: For input string: "${globals.buildspec_port}"
ERROR RundeckAPICentralDispatcher: Server reported an error: Bad Request
Error: Failed request to load jobs: Jobs Document was invalid for format yaml: rundeck.controllers.JobXMLException: Unable to create Job: For input string: "${globals.buildspec_port}"
```
