### ISSUE TITLE
500 Error after Authentication (Reverse Proxy)

### ISSUE THREAD

**Issue by kai-cool-dev** [rundeck/rundeck#5090]
Issue type: Server Error

Hello,

I am using Rundeck (3.0.24) behind a nginx (1.16.0) reverse proxy. Every time I try to log in or visit any other site I get following error:

```
Error 500: Internal Server Error
URI
/project/[REDACTED]/jobs
Class
java.lang.IncompatibleClassChangeError
Message
Handler dispatch failed; nested exception is java.lang.IncompatibleClassChangeError: Method com.dtolabs.rundeck.core.authorization.providers.EnvironmentalContext.forProject(Ljava/lang/String;)Ljava/util/Set; must be InterfaceMethodref constant
Caused by
Method com.dtolabs.rundeck.core.authorization.providers.EnvironmentalContext.forProject(Ljava/lang/String;)Ljava/util/Set; must be InterfaceMethodref constant



    Line | Method
->>  137 | authorizeProjectResources in org.rundeck.app.authorization.RundeckAuthContextEvaluator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    413 | doCall           in rundeck.services.FrameworkService$_authorizeProjectResources_closure9
|     62 | invoke . . . . . in jdk.internal.reflect.NativeMethodAccessorImpl
|     43 | invoke           in jdk.internal.reflect.DelegatingMethodAccessorImpl
|     99 | time . . . . . . in com.codahale.metrics.Timer
|     57 | withTimer        in org.grails.plugins.metricsweb.MetricService
|    412 | authorizeProjectResources in rundeck.services.FrameworkService
|    669 | listWorkflows    in rundeck.controllers.MenuController
|     62 | invoke . . . . . in jdk.internal.reflect.NativeMethodAccessorImpl
|     43 | invoke           in jdk.internal.reflect.DelegatingMethodAccessorImpl
|    468 | jobsFragment . . in rundeck.controllers.MenuController
|    297 | jobs             in     ''
|    223 | invoke . . . . . in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke           in org.grails.core.DefaultGrailsControllerClass
|     90 | handle . . . . . in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch       in org.springframework.web.servlet.DispatcherServlet
|    901 | doService . . .  in     ''
|    970 | processRequest   in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet . . . . .  in     ''
|    846 | service          in     ''
|    865 | handle . . . . . in org.eclipse.jetty.servlet.ServletHolder
|   1655 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    215 | doFilter . . . . in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    423 | doAs             in javax.security.auth.Subject
|    105 | doFilter . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke           in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . in     ''
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter . . . . in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter         in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter         in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter         in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter         in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run              in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    423 | doAs . . . . . . in javax.security.auth.Subject
|    105 | doFilter         in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter         in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter         in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter         in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter         in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . in     ''
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal in org.grails.web.filters.HiddenHttpMethodFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle . . . . in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle           in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle . . . . . in org.eclipse.jetty.security.SecurityHandler
|    132 | handle           in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle         in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle         in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope          in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope . . . .  in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope        in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope . . . .  in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle           in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle           in org.eclipse.jetty.server.Server
|    352 | handle . . . . . in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable       in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded . . .  in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable         in org.eclipse.jetty.io.FillInterest
|    118 | run . . . . . .  in org.eclipse.jetty.io.ChannelEndPoint$2
|    762 | runJob           in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run . . . . . .  in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    834 | run              in java.lang.Thread
```

rundeck-config.properties:
```
# {{ansible_managed}}
loglevel.default=INFO
rdeck.base=/var/lib/rundeck
rss.enabled=false
grails.serverURL=https://{{DOMAIN}}
dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true
rundeck.log4j.config.file = /etc/rundeck/log4j.properties
# Remove CSP for Reverse Proxy Usage
rundeck.security.httpHeaders.provider.csp.enabled=false
rundeck.security.httpHeaders.provider.csp.config.form-action=self https://{{DOMAIN}} http://{{DOMAIN}}
server.useForwardHeaders=true
```

framework.properties:
```
# {{ansible_managed}}
framework.server.name = localhost
framework.server.hostname = localhost
framework.server.port = 4440
framework.server.url = https://{{DOMAIN}
rdeck.base=/var/lib/rundeck
framework.projects.dir=/var/rundeck/projects
framework.etc.dir=/etc/rundeck
framework.var.dir=/var/lib/rundeck/var
framework.tmp.dir=/var/lib/rundeck/var/tmp
framework.logs.dir=/var/lib/rundeck/logs
framework.libext.dir=/var/lib/rundeck/libext
framework.ssh.keypath = /var/lib/rundeck/.ssh/id_rsa
framework.ssh.user = ansible
framework.ssh.timeout = 0
# SERVER UUID REDACTED
```

rundeck.conf:
```
# {{ansible_managed}}
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name {{DOMAIN}};
  ssl_certificate /etc/letsencrypt/live/{{DOMAIN}}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/{{DOMAIN}}/privkey.pem;
  root /var/www/;
  location / {
    proxy_pass_header Server;
    expires off;
    add_header Cache-Control private;
    proxy_pass {{ENDPOINT}};
    proxy_set_header X-Forwarded-Host $host:$server_port;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-REAL-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port 443;
    proxy_set_header Host $host;
    proxy_set_header X-Powered-By "";
    proxy_cache one;
  }
  location ~ /\.ht {
    deny all;
  }
  location ^~ /.well-known/acme-challenge/ {
    default_type "text/plain";
    expires modified +48h;
    add_header Cache-Control private;
    root /etc/letsencrypt/webroot/;
    try_files $uri $uri/ =404;
  }
  access_log /var/log/nginx/{{DOMAIN}}.proxy.access.log;
  error_log /var/log/nginx/{{DOMAIN}}.proxy.error.log error;
}

```

Also I can't directly login at Port 4440.
{{DOMAIN}} is an ansible variable for the outside domain
{{ENDPOINT}} is an ansible variable for the endpoint, e.g. http://localhost:4440

**My Rundeck detail**

* Rundeck version: 3.0.24
* install type: Bintray DEB Repo
* OS Name/version: Ubuntu 18.04.2 LTS
* DB Type/version: h2

**Expected Behavior**
Login & Sites working

**How to Reproduce**
Use above configuration and try to login. It works but no other sites.

**Comment by ahonor** [comment]
Hi @kai-cool-dev, What Java version are you using?

**Comment by kai-cool-dev** [comment]
Hi @ahonor I use openjdk 11.0.3 2019-04-16. Is this not compatible with the Rundeck version I am using?

Other Versions like 3.0.16 are working just fine.

**Comment by gschueler** [comment]
@kai-cool-dev currently rundeck requires java 8

**Comment by kai-cool-dev** [comment]
@gschueler I installed openjdk-8-jdk-headless which as far as I know should translate to Java 8.

Here is my ansible role maybe someone have a clue:

```
---
- name: Add OpenJDK repo
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
- name: Add ansible repo
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
- name: Add rundeck signing key
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
    state: present
- name: Add rundeck repo
  apt_repository:
    repo: deb https://rundeck.bintray.com/rundeck-deb /
    state: present
- name: update the repository cache and install required packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - openjdk-8-jdk-headless
    - ansible
    - apache2-utils
    - rundeck=3.0.16.20190223-1.201902232324
- name: install molecule and dopy
  pip:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - git+https://github.com/ansible/molecule.git
    - dopy
- name: move realm.j2 to /etc/rundeck/realm.properties
  template:
    src: realm.j2
    dest: /etc/rundeck/realm.properties
    owner: rundeck
    group: rundeck
    mode: 0640
  notify:
  - restart rundeck
- name: move rundeck-config.j2 to /etc/rundeck/rundeck-config.properties
  template:
    src: rundeck-config.j2
    dest: /etc/rundeck/rundeck-config.properties
    owner: rundeck
    group: rundeck
    mode: 0640
  notify:
  - restart rundeck
- name: move profile.j2 to /etc/rundeck/profile
  template:
    src: profile.j2
    dest: /etc/rundeck/profile
    owner: rundeck
    group: rundeck
    mode: 0640
  notify:
  - restart rundeck
- name: copy ansible-plugin.jar to /var/lib/rundeck/libext/ansible-plugin.jar
  copy:
    src: ansible-plugin.jar
    dest: /var/lib/rundeck/libext/ansible-plugin.jar
    owner: rundeck
    group: rundeck
    mode: 0664
  notify:
  - restart rundeck
- name: change rundeck framework properties to the reverse proxy
  replace:
    path: /etc/rundeck/framework.properties
    regexp: '^(framework\.server\.url).*'
    replace: 'framework.server.url = https://{{ DOMAIN }}'
- name: change rundeck framework properties to the reverse proxy
  replace:
    path: /etc/rundeck/framework.properties
    regexp: '^(framework\.server\.name).*'
    replace: 'framework.server.name = {{ DOMAIN }}'
- name: change rundeck framework properties to the reverse proxy
  replace:
    path: /etc/rundeck/framework.properties
    regexp: '^(framework\.server\.hostname).*'
    replace: 'framework.server.hostname = {{ DOMAIN }}'
- name: adjust the projects organization
  replace:
    path: /etc/rundeck/project.properties
    regexp: '^(project\.organization).*'
    replace: 'project.organization = [REDACTED]'
  notify:
  - restart rundeck
- name: adjust the framework default ssh user
  replace:
    path: /etc/rundeck/framework.properties
    regexp: '^(framework\.ssh\.user).*'
    replace: 'framework.ssh.user = ansible'
  notify:
  - restart rundeck
- name: copy MicrosoftTeamsNotification.groovy to /var/lib/rundeck/libext/MicrosoftTeamsNotification.groovy
  copy:
    src: MicrosoftTeamsNotification.groovy
    dest: /var/lib/rundeck/libext/MicrosoftTeamsNotification.groovy
    owner: rundeck
    group: rundeck
    mode: 0664
  notify:
  - restart rundeck
- name: add Microsoft Teams Webhook URL to rundeck framework configuration
  lineinfile:
    path: /etc/rundeck/framework.properties
    line: 'framework.plugin.Notification.MicrosoftTeamsNotification.webhook_url={{ WEBHOOKURL }}'
    create: yes
  notify:
  - restart rundeck
- name: add Microsoft Teams Webhook URL to rundeck projects configuration
  lineinfile:
    path: /etc/rundeck/project.properties
    line: 'project.plugin.Notification.MicrosoftTeamsNotification.webhook_url={{ WEBHOOKURL }}'
    create: yes
  notify:
  - restart rundeck
- name: Move collectd.j2 to /etc/collectd/collectd.conf.d/curl-{{ DOMAIN }}.conf
  template:
    src: collectd.j2
    dest: /etc/collectd/collectd.conf.d/curl-{{ DOMAIN }}.conf
    owner: root
    group: root
    mode: 0755
  notify:
  - restart collectd
```
