### ISSUE TITLE
List of previous execution is empty for Jobs with custom uuid

### ISSUE THREAD

**Issue by floriangiroudrefinepro** [rundeck/rundeck#5194]
**Describe the bug**
We have lost the detail of previous executions (hundreds of jobs, thousands of executions), following an upgrade from rundeck 3.0.21 to 3.1
Well, rundeck have a sense of it, it properly finds out that we have X executions for the Job, but is not able to retrieve the details in the "activity" tab. See screenshots attached

Our initial investigation shows that only the Jobs that we imported are impacted. And that's probably because we have set the id and uuid ourselves for a mass import through Git.

We manage to retrieve an execution ID with the API, and we can access the execution details page if we know the execution Id

See the detail of one of our jobs that is impacted

```yaml
- defaultTab: output
  description: Collect for XXXXXXAnonymizedXXXXXX in production
  executionEnabled: true
  group: production/reminder
  id: reminder_production_MTAA
  loglevel: INFO
  maxMultipleExecutions: '1'
  name: MTAA
  nodeFilterEditable: true
  schedule:
    month: JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
    time:
      hour: '7'
      minute: '30'
      seconds: '03'
    weekday:
      day: WED
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: 'XXXXXXAnonymizedXXXXXX'
    keepgoing: false
    pluginConfig:
      LogFilter:
      - config:
          color: red
          replacement: '[SECURE]'
        type: mask-passwords
    strategy: node-first
  timeZone: America/Toronto
  uuid: reminder_production_MTAA

```

**My Rundeck detail**

* Rundeck version: 3.1
* install type: deb, apt
* OS Name/version:  Ubuntu 16.04.5 LTS
* DB Type/version: local mysql database

**To Reproduce**
1. Go to a Job
2. Click on Stats, then click on Activity
4. See that there are no activities listed, though Stats shows X executions

**Screenshots**

<img width="1119" alt="Screen Shot 2019-08-28 at 15 49 13" src="https://user-images.githubusercontent.com/53900620/63861942-1d05fb80-c9ac-11e9-8cd9-09e29b2e83f3.png">

<img width="1137" alt="Screen Shot 2019-08-28 at 15 49 18" src="https://user-images.githubusercontent.com/53900620/63861947-1ecfbf00-c9ac-11e9-800d-803cfdc8e59e.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version Version 76.0.3809.100 (Official Build) (64-bit)

Thank you
