### ISSUE TITLE
Key/value data not captured if highlighted first

### ISSUE THREAD

**Issue by gaddman** [rundeck/rundeck#5289]
**Describe the bug**
When a _Highlight Output_ log filter is added to a step, a subsequent _Key Value Data_ log filter looking at the same line will not pick up any values. If the order of the filters is swapped, it works as expected.

**My Rundeck detail**

* Rundeck version: 3.1.0
* install type: rpm
* OS Name/version: CentOS Linux 7
* DB Type/version: builtin (H2)

**To Reproduce**
Using the output of the command `ip address`, step 1 has two log filters to:

1. capture the index and name of all interfaces, then
1. highlight the loopback interface

This works fine - key/value data is captured. Step 2 will reverse the order (highlight then capture), and the loopback interface (the first key/value) is not captured. Sample output of `ip address`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b9:64:1a brd ff:ff:ff:ff:ff:ff
    inet 172.24.236.87/24 brd 172.24.236.255 scope global ens192
       valid_lft forever preferred_lft forever
    inet6 fe80::61ab:f45:f213:9777/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:11:c1:77:77 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:11ff:fec1:7777/64 scope link
       valid_lft forever preferred_lft forever
```

Example job below.
```yaml
- defaultTab: output
  description: ''
  executionEnabled: true
  id: 5626e6af-55dc-415f-a4be-05b64712e653
  loglevel: INFO
  name: capture test
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: ip address
      nodeStep: true
      plugins:
        LogFilter:
        - config:
            logData: 'true'
            regex: (\d+):\s+([^:]+).*
          type: key-value-data
        - config:
            fgcolor: green
            mode: bold
            regex: '.*lo: <LOOPBACK.*'
          type: highlight-output
      type: localexec
    - configuration:
        command: ip address
      nodeStep: true
      plugins:
        LogFilter:
        - config:
            fgcolor: green
            mode: bold
            regex: '.*lo: <LOOPBACK.*'
          type: highlight-output
        - config:
            logData: 'true'
            regex: (\d+):\s+([^:]+).*
          type: key-value-data
      type: localexec
    keepgoing: false
    strategy: node-first
  uuid: 5626e6af-55dc-415f-a4be-05b64712e653
```

**Expected behavior**
The order the log filters are created shouldn't matter (especially since they can't be reordered), and the key value data should be populated in step 2.

**Screenshots**
![steps](https://user-images.githubusercontent.com/1311209/65473059-5dcd3380-deca-11e9-8e27-ac97d76e48c9.png)

**Desktop:**
 - OS: Windows Server 2012 R2
 - Browser Firefox
 - Version 68.0.2
