### ISSUE TITLE
Port usage plugin official repository

### ISSUE THREAD

**Issue by imatpro** [rundeck/rundeck#5332]
Hi all, 

Which port is used to use the official rundeck plugin repository on api.rundeck.com?

**Comment by sjrd218** [comment]
Standard https. 443.

**Comment by imatpro** [comment]
Strange my 443 port is open, but i don't see Official repository

**Comment by sjrd218** [comment]
screenshot?

**Comment by imatpro** [comment]
Curl test : 
$ curl https://api.rundeck.com
{"message":"Forbidden"}

telnet test : 
$ telnet api.rundeck.com 443
Trying 13.224.241.52...
Connected to api.rundeck.com.
Escape character is '^]'.
cat /etc/rundeck/rundeck-config.properties
...
rundeck.feature.repository.enabled = true
rundeck.feature.repository.localSearchOnly = false

<img width="1266" alt="Capture d’écran 2019-10-02 à 17 04 17" src="https://user-images.githubusercontent.com/7237663/66056166-0157bd00-e537-11e9-963a-83beaf6e6b97.png">

**Comment by sjrd218** [comment]
can you post the contents of your `/etc/rundeck/artifact-repositories.yaml` file?

It should look something like: 
```
repositories:
-   repositoryName: Official
    enabled: true
    type: HTTP
    owner: RUNDECK
-   repositoryName: private
    type: STORAGE_TREE
```

**Comment by imatpro** [comment]
i had this : 
```
root@rundeck-01:/etc/rundeck# cat artifact-repositories.yaml.bck
repositories:
-
    repositoryName: private
    type: STORAGE_TREE
    owner: PRIVATE
    configProperties:
        treeName: private
        manifestPath: manifest.json
```

I replaced it with :

```
repositories:
-   repositoryName: Official
    enabled: true
    type: HTTP
    owner: RUNDECK
-   repositoryName: private
    type: STORAGE_TREE
```


and it's working :)

Thanks You very much @sjrd218
