### ISSUE TITLE
Script type plugin WorkflowNodeStep - allow @option.name@ substitution in displayType: CODE configuration property

### ISSUE THREAD

**Issue by tholok97** [rundeck/rundeck#5398]
**Is your feature request related to a problem? Please describe.**
We have been using the 'Script - Execute an inline script' workflow Node Step to run ad-hoc scripts. Now we'd like to create a plugin that appears to the user just like this Node Step, but that executes the given script in some custom manner behind the scenes. So far our plugin is able to take a script from a configuration property with `renderingOptions` of `displayType: CODE`, and execute it how we want, but we are having issues with variable substitution. The default value of the `script-config-opt` configuration property for the below example plugin demonstrates our issue:

```yaml
---
name: rundeck-issue-5398-example-plugin
description: ""
rundeckPluginVersion: 1.2
author: "Thomas Løkkeborg <thomas.loekkeborg@cern.ch>"
date: "2019-10-21"
version: 1.0.0
url: ""
tags:
  - script
providers:
  - name: rundeck-issue-5398-example-plugin-execute-script
    service: WorkflowNodeStep
    title: 'Issue 5398 example'
    description: 'Issue 5398 example'
    plugin-type: script
    script-interpreter: python -u
    script-file: example-script.py
    script-args:
    config:
      - name: script_config_opt
        type: String
        title: "Script"
        description: ""
        default: |
          # the following will not output the value of the job option, it will
          # just output `@option.testoption@` literally
          echo "@option.testoption@"
          
          # the following will output the value of the job option, but at the
          # cost of the next example breaking...
          echo "${option.testoption}"

          # the following will output an empty string, as Rundeck will
          # substitute `${testvariable}` to an empty string (it thinks that it is
          # an `${option.something}` ?)
          testvariable='testvalue'
          echo "${testvariable}"

          # in most cases it's possible to avoid the `${var}` syntax by doing
          # $var, but sometimes `${...}` is needed. For example trying to print a
          # Bash array will cause Rundeck substitution to get confused
          myarray=(1 2 3)
          echo "${myarray[@]}"
        required: true
        renderingOptions:
          displayType: CODE
```

The full example plugin can be found here: https://github.com/tholok97/rundeck-issue-5398-example-plugin

**Describe the solution you'd like**
We would like the ability for our `script-config-opt` configuration option to treat job options just like the script input box in the Node Step 'Script - Execute an inline script'. The same script copy-pasted to the two input boxes should yield the same option substitions.

**Describe alternatives you've considered**
* Avoid any usage of `${var}` in our scripts and use `$var` instead. `$var` will not be substituted for empty string by Rundeck. This is not sufficient however, as the curly braces are sometimes needed, for example to output the contents of a Bash array: `${var[@]}`
* [Disable substitution altogether](https://github.com/rundeck/rundeck/issues/1762) for this input box (not globally). **This would solve our issue**, but we'd still have to pass in job options somehow. In this case we would either use the `RD_OPTION_*` environment variables, or pass in job options through a separate "script arguments" configuration property that would be passed to the script upon execution. Disabling substitution like this is not possible as far as I know.

**Additional context**
Rundeck version: `3.1.0.20190731-2`
