### ISSUE TITLE
Failure to send notification email with invalid email combined with multi-email option

### ISSUE THREAD

**Issue by dnut** [rundeck/rundeck#5432]
**Describe the bug**
There's a weird situation where Rundeck won't send out any notifications. It only seems to happen in the specific circumstances I describe below. I think it's best described by reading the steps to reproduce.

**My Rundeck detail**
* Rundeck version: 3.1.2-20190927
* install type: rpm
* OS Name/version: centos 7
* DB Type/version: postgres

**To Reproduce**
1. Create a job with an `email` option that sends notifications to: `${job.user.email},${option.email}`. Here's the job I created:
```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c7985d10-1964-41c1-a974-07d74e61784c
  loglevel: INFO
  name: Email Test
  nodeFilterEditable: false
  notification:
    onsuccess:
      email:
        recipients: ${job.user.email},${option.email}
  notifyAvgDurationThreshold: null
  options:
  - name: email
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo
    keepgoing: false
    strategy: node-first
  uuid: c7985d10-1964-41c1-a974-07d74e61784c
```
2. Login as a user with no email address in their profile.
3. Run the job with two email addresses in the email option for the rundeck job like this: `user1@example.com,user2@example.com`

**Expected behavior**
user1@example.com or user2@example.com should have received email notifications.

**Actual behavior**
No one receives a notification.

**Other scenarios**
- If the user has an email address, then all three email addresses receive notifications.
- If the user has no email address, but only puts a single email address in the email option, then that email address will receive a notification
- If I get rid of the email option, and change the notification email recipients to `${job.user.email},user1@example.com,user2@example.com`, then run it with a user that has no email address, both user1 and user2 receive notifications.
