### ISSUE TITLE
Webhook - Choose A Job - Blank

### ISSUE THREAD

**Issue by thirdeye-yusuf** [rundeck/rundeck#5471]
**Describe the bug**
I can not view nor add a job to a webhook, on the 'Choose A Job' window it's always blank.

**My Rundeck detail**

* Rundeck version: 3.1.2
* install type: war (docker)
* OS Name/version: Debian Buster
* DB Type/version: mysql

**To Reproduce**
1. Create a new project
2. Create a test job
3. Try to create a webhook, Webhook Event Plugin = Webhook Run Job
4. Click 'Choose A Job' button
5. Notice no jobs listed

**Expected behavior**
At least 1 job to select

**Screenshots**
[Project with job](https://www.dropbox.com/s/bjkhtngn2lwhec3/Screenshot%202019-11-07%2020.22.31.jpg?dl=0)
[Choose A Job](https://www.dropbox.com/s/7bq38kws4vzpmhz/Screenshot%202019-11-07%2020.22.53.jpg?dl=0)

**Desktop (please complete the following information):**
 - OS: Fedora 20
 - Browser Chrome
 - Version 77

**Additional context**
Running behind oauth2_proxy with preauthentication enabled.

**Comment by MegaDrive68k** [comment]
Hi @thirdeye-yusuf 

Seems very similar to this: https://github.com/rundeck/rundeck/issues/5439

Try to set your `grails.serverURL` with your proxy hostname and port configured for Rundeck.

Hope it helps!

**Comment by thirdeye-yusuf** [comment]
> Hi @thirdeye-yusuf
> 
> Seems very similar to this: #5439
> 
> Try to set your `grails.serverURL` with your proxy hostname and port configured for Rundeck.
> 
> Check this ("Environment variables" section):
> 
> https://hub.docker.com/r/rundeck/rundeck
> 
> Hope it helps!

Hi @MegaDrive68k , `RUNDECK_GRAILS_URL` is definitely set, I have an ssl terminated load balancer in front of it, the settings is a public domain, e.g. `https://rundeck.mycompany.com`.

I admit the setup is a little convoluted, after traffic leaves the load balancer it hits an nginx server which then forwards unauthenticated requests to oauth2_proxy and then finally reaches rundeck.

If it helps, everything is working, people are running jobs etc, just the web hooks are not :(, that would really be icing on the cake :)

**Comment by sjrd218** [comment]
@thirdeye-yusuf If you pull up your Chrome devtools on the webhooks page do you see any errors in the Network tab, or javascript errors in the Console tab?

**Comment by thirdeye-yusuf** [comment]
@sjrd218 no errors in either tab unfortunately, of particular -
https://rundeck.companydomain.com/api/26/project/main/jobs?groupPath=*
returns 200, but response is an empty list ([])

**Comment by sjrd218** [comment]
Do you have an ACL that would prevent you from listing jobs in that project via an API call?

**Comment by thirdeye-yusuf** [comment]
I haven't created an api token for myself but my permissions in general is unrestricted:

```
---

description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: 
    - devops-team

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group:
    - devops-team
```

Is it possible I'm missing a specific resource type?
