### ISSUE TITLE
only one script from a script-plugin is executable

### ISSUE THREAD

**Issue by gtudan** [rundeck/rundeck#5568]
**Describe the bug**
If a Plugin contains more than one script-providers than not all get the executable flag. 
Executing those scripts will fail at runtime.
 
**My Rundeck detail**

* Rundeck version: 3.1.2
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: PostgreSQL

**To Reproduce**
1. Create a plugin with more than one script-provider. This is my plugin meta data:
```yaml
# yaml plugin metadata

name: rundeck-ldap-options-plugin
version: 1.0
rundeckPluginVersion: 1.2
author: Gregor Tudan
date: 2019-10-05
providers:
    - name: LDAP Groups
      service: OptionValues
      plugin-type: script
      script-file: get-groups.sh
    - name: LDAP Users
      service: OptionValues
      plugin-type: script
      script-file: get-users.sh
```
2. Deploy it to the server
3. Take a look at the cache dir in the libext directory

**Expected behavior**
All scripts are executable. 
The actual result is that only one of the scripts will have the executable flag (which one seems to be random).

```
[gtudan@rundeck rundeck-ldap-options-plugin]$ ls -l .
total 8
-rwxrw-r--. 1 rundeck rundeck 260 Nov 27 22:47 get-groups.sh
-rw-rw-r--. 1 rundeck rundeck 258 Nov 27 22:47 get-users.sh
drwxrwxr-x. 2 rundeck rundeck   6 Nov 27 22:47 resources
```

**Comment by MegaDrive68k** [comment]
Hi @gtudan 

Can you share the script content? I leave an example that works.

[helloworld-plugin.zip](https://github.com/rundeck/rundeck/files/3932480/helloworld-plugin.zip)

plugin.yaml:

```
name: helloworld
version: 1.0
rundeckPluginVersion: 1.2
author: Warhawk
date: 01-02-2018 (ISO8601)
providers:
  - name: helloworld
    service: RemoteScriptNodeStep
    title: HELLOWORLD
    description: test of custom plugin
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: hello.config
    script-args:
  - name: bye
    service: RemoteScriptNodeStep
    title: BYE
    description: another test of custom plugin
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: bye.config
    script-args:
```

hello.config:

```
#!/usr/bin/env bash
echo "Hello World"
```

bye.config:

```
#!/usr/bin/env bash
echo "Bye"
```

Job Definition:

```
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>bd899c76-3daa-4d46-aae9-c92945542e80</id>
    <loglevel>INFO</loglevel>
    <name>PluginTest</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <node-step-plugin type='helloworld' />
      </command>
      <command>
        <node-step-plugin type='bye' />
      </command>
    </sequence>
    <uuid>bd899c76-3daa-4d46-aae9-c92945542e80</uuid>
  </job>
</joblist>
```

![Screenshot_1](https://user-images.githubusercontent.com/51376003/70328635-48ed1480-1818-11ea-9e2e-30330e8e290e.png)

Hope it helps!
