### ISSUE TITLE
Support variables in ACL policies for generic rules creation

### ISSUE THREAD

**Issue by rnsc** [rundeck/rundeck#5582]
Hello,

During the process of integrating Rundeck in my infrastructure, I successfully configured LDAP and I can then login to my Rundeck server with a user from that LDAP.

I also want my users to their own personal space in the Key Storage of Rundeck, as well as access to a common set of keys.

I've read this:
https://docs.rundeck.com/3.0.0/administration/security/key-storage.html#acl-policies
And this:
https://docs.rundeck.com/3.0.0/administration/security/access-control-policy.html

I then tested this (as suggested by someone on IRC):
```yaml
description: authorize users to have their own keys
context:
  application: 'rundeck'
for:
  storage:
    - match:
        path: 'keys/.*'
      allow: [read]
    - match:
        path: 'keys/${job.username}/.*'
      allow: [read,create,update,delete]
by:
  group: user
```
But to no avail.
I literally have to define a rule for each user that is supposed to use Rundeck.
This completely defeats the purpose of having a third party doing the authentication if I have to add provisioning for each user.

I would love to be able to do the above, or something similar to achieve this.
This would be super useful for me as each user is supposed to be able to use his own private keys/passwords to execute a job.

Let me know if this unclear, I'd gladly expand/rephrase if need be.

Kind regards,
