### ISSUE TITLE
ACL Policy for Webhook Management

### ISSUE THREAD

**Issue by gabrgomes** [rundeck/rundeck#5640]
**Describe the bug**
I'm trying to create ACL Policies for Webhook Management in my projects. Apparently there is no documentation about this and the audit logs are not helpful. 

**My Rundeck detail**

* Rundeck version: 3.2.0-20191218
* install type: war
* OS Name/version: alpine 8.191.2
* DB Type/version: postgres

**To Reproduce**
This is my policy and I am trying to create a webhook. (the webhook on side menu is not available, but I can access the interface via the url) but I get access denied:

```yaml
description: Project policy
context:
  project: 'scb-.*'
for:
  resource:
    - equals:
        kind: job
      allow: [create,read,update,delete,run,runAs,kill,killAs]
    - equals:
        kind: node
      allow: [read,refresh]
    - equals:
        kind: event
      allow: [read,create,update,delete]
  adhoc:
    - allow: [read,create,update,delete]
  job:
    - allow: [create,read,update,delete,run,runAs,kill,killAs] # allow create/read/write/delete/run/kill of all jobs
  node:
    - allow: [read,run]
by:
  group: almfdscb

---

description: Rundeck policy
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [read] # allow create of projects
    - equals:
        kind: system
      deny: '*' # allow read of system info, enable/disable all executions
    - equals:
        kind: system_acl
      deny: '*'
    - equals:
        kind: user
      allow: [read]
  project:
    - match:
        name: 'scb-.*'
      allow: [read,import,export,configure]
  project_acl:
    - match:
        name: '.*'
      allow: [read,create,update,delete]
  storage:
    - equals:
        path: 'keys'
      allow: [read]
    - equals:
        path: 'keys/common'
      allow: [read]
    - match:
        path: 'keys/common/.*'
      allow: [read]
    - match:
        path: 'keys/scb.*'
      allow: [read,create,update,delete]
    - match:
        path: 'keys/scb.*/.*'
      allow: [read,create,update,delete]
    - match:
        path: 'keys/scb/scn.*'
      deny: [create,update,delete]

by:
  group: almfdscb
```
Audit log: 
``` 
action<create> env<rundeck:auth:env:project:scb-correioweb>: authorized: false: REJECTED, reason: REJECTED, evaluations: ACLRule<[system:config]acls/almfdscb.aclpolicy[1][type:job][rule: 1]>{'Definicao do acesso aos projetos da acl almfdscb' context={project='scb-.*'} type='job' for: { group='almfdscb'} allow=[runAs, killAs, read, create, update, run, kill, delete]} REJECTED for action create => REJECTED (0ms)
```

**Comment by sjrd218** [comment]
@gabrgomes 
Try adding a resource where the kind equals webhook with the actions you want to allow.
To get the webhook menu to show up in the UI the minimum required permission is `read`.
For example:
```
resource:
  - equals:
       kind: webhook
     allow: [read,create,update]
```
To allow a user to create a webhook, you will also need to give the user the ability to generate a user api token.
For example:

```
resource:
      - equals:
          kind: apitoken
        allow: [generate_user_token]
```
This last one must go in the context for the application
