### ISSUE TITLE
Multiline in-line script on YAML export displayed in single line

### ISSUE THREAD

**Issue by sinister3vil** [rundeck/rundeck#5723]
**Describe the bug**
When exporting the job definition to YAML in-line scripts display in a single line, with special characters like \t, \n and line wraps.
Previously (3.0.6) in-line scripts would use YAMLs block style and chomp indcators : |-  and the script would be included in human readable format.

This affects exporting from the web interface but also via rd job list command.

currently
```
commands:
    - script: "#!/bin/bash\n\n#change these based on job----------------------------------------------\n\
       \t\texport PLAYBOOK=test #do not add extension\n\t\texport BASEDIR=/tmp/dryrun\n\
       rest of script redacted"

```

previously
```
commands:
    - script: |-
        #!/bin/bash

        #change these based on job----------------------------------------------
        		export PLAYBOOK=test #do not add extension
                export BASEDIR=/tmp/dryrun
                rest of script redacted
```

Issue seems to affect jobs with larger in-line scripts or possible edited.

**My Rundeck detail**

* Rundeck version: 3.1.3, 3.2.1
* install type: official docker image

**To Reproduce**
Export job definition in YAML format

**Expected behavior**
Expecting in-line scripts to properly use multi-line YAML syntax

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 79.0.3945.130

**Comment by MegaDrive68k** [comment]
Hi @sinister3vil 

I tested your issue since our first contact at IRC channel and I found a way to reproduce the issue exactly.

1. Import this job:

```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        ls -la
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

2. Modify the inline-script leaving all in one line and Save the job.

![Screenshot_1](https://user-images.githubusercontent.com/51376003/72925052-cde0ae80-3d30-11ea-8213-46327d2f7b88.png)


3. Modify the inline-script again like the original job def and Save again:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/72925078-d933da00-3d30-11ea-892e-421493bca471.png)


4. See the result:

```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: "echo \"hi\" \nls -la"
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

Thanks for your feedback!

**Comment by spaced0gg** [comment]
We are seeing this issue as well in rundeck 3.2.1

I have managed to pin the issue down to an empty line in the yaml we were trying to load.  If the inline-script contains a line with 9+ spaces on it and nothing else (i.e. 9 spaces followed by a newline) then we encounter this issue.  8 spaces or less seems fine.  9 spaces and then a character seems fine as well.

**My Rundeck detail**
- Rundeck version: 3.2.1-20200113 
- install type: RPM
- OS Name/version: Red Hat Enterprise Linux Server release 6.10 (Santiago)
- DB Type/version: mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1


**To Reproduce**
Import this job:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        #The following line has 9 spaces followed by a new line character
         
        ls -la
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```
When exported the above job the yaml will look like this:

```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: "echo \"hi\"\n#The following line has 9 spaces followed by a new line\
        \ character\n \nls -la"
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

A job with 9 spaces followed by text is ok:
Import:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        #The following line has 9 spaces followed by a new line character
         #Test adding characters after the 9 spaces
        ls -la
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

Export:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        #The following line has 9 spaces followed by a new line character
         #Test adding characters after the 9 spaces
        ls -la
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

A job with 8 spaces followed by a newline is ok as well:
Import:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        #The following line has 8 spaces followed by a new line character
        
        ls -la
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

Export:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        #The following line has 8 spaces followed by a new line character

        ls -la
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

**Comment by spaced0gg** [comment]
Found another case where the yaml output gets scrambled.  If there is trailing whitespace on any line then the exported yaml exhibits this issue.

**To Reproduce**
Import this job:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        #The following line contains a trailing whitespace character
        ls -la 
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

When the above job is exported the yaml will look like this:

```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 3d4b4195-b98b-4df2-a010-4e5956e590d1
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: "echo \"hi\"\n#The following line has a trailing whitespace character\n\
        ls -la "
    keepgoing: false
    strategy: node-first
  uuid: 3d4b4195-b98b-4df2-a010-4e5956e590d1
```

If there is no trailing whitespace then the job exports correctly:

Import:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        #The following line does not contain a trailing whitespace character
        ls -la
    keepgoing: false
    strategy: node-first
  uuid: c5e431e9-ac55-4c80-8409-f4dbb84fbf44
```

Export:
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 3d4b4195-b98b-4df2-a010-4e5956e590d1
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        echo "hi"
        #The following line does not a contain trailing whitespace character
        ls -la
    keepgoing: false
    strategy: node-first
  uuid: 3d4b4195-b98b-4df2-a010-4e5956e590d1
```
