### ISSUE TITLE
Global Log Filters (Unable to edit)

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#5784]
Hi, Thanks for the latest release!  It's coming together really nice!

small issue with version 3.2.2-20200204

Unable to edit Global Log Filters. When Clicking on the icons nothing happens.  But I am able to create a new Global Log Filter.

![image](https://user-images.githubusercontent.com/20629911/74374679-b75bcf00-4d93-11ea-9e1a-b00b447c9849.png)

Thanks!
HS

**Comment by hs-hub-world** [comment]
Update. Newly created Global Log Filters (after the upgrade) works. but the existing Global Log Filters from earlier versions can't edit.  (are they lost -?)

![image](https://user-images.githubusercontent.com/20629911/74374966-51237c00-4d94-11ea-8380-b34fce3d7476.png)

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

Can you share an example job definition to test?

Thanks!

**Comment by hs-hub-world** [comment]
Hi @MegaDrive68k 
Here you go.....

```
- defaultTab: output
  description: ''
  executionEnabled: true
  group: 
  id: 5446bb4a-34c8-488e-974b-d66eb3f3a3bd
  loglevel: INFO
  name: _Main_Job
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: RDEXEC-SRV01'
  nodesSelectedByDefault: true
  options:
  - description: |-
      (True = Dry Run)
      (False = Execute command)
    enforced: true
    name: WhatIf
    required: true
    value: 'True'
    values:
    - 'False'
    - 'True'
    valuesListDelimiter: ','
  - description: Worksheet name to update from.
    label: WorksheetName
    name: WorksheetName
  - enforced: true
    label: winrm UserName
    name: username
    required: true
    value: Rdecksvc
    values:
    - Rdecksvc
    valuesListDelimiter: ','
  - enforced: true
    label: verbose
    name: RunAsVerbose
    required: true
    value: 'False'
    values:
    - 'False'
    - 'True'
    valuesListDelimiter: ','
  scheduleEnabled: true
  sequence:
    commands:
    - description: Update from File
      exec: V:\Scripts\Update_From_File.ps1
        -Worksheetname ${option.WorksheetName} -WhatIf ${option.WhatIf} -RunAsVerbose
        ${option.RunAsVerbose}
    keepgoing: false
    pluginConfig:
      LogFilter:
      - config:
          loglevel: verbose
          matchLoglevel: all
          quietMatch: 'true'
          regex: ^[#<].*|^[\/usr\/lib\/python2.7].*|^[ NoCertificateRetrievedWarning)]+$
        type: quiet-output
      - config:
          bgcolor: cyan
          regex: '(?i)Build Name:|(?i)Creating new Build Def|(?i)Processing:'
        type: highlight-output
      - config:
          bgcolor: green
          regex: '(?i)Release Name:|(?i)Creating new Release Def|(?i)Processing Release:'
        type: highlight-output
      - config:
          bgcolor: yellow
          mode: bold
          regex: (?i)WhatIf = False
        type: highlight-output
      - config:
          bgcolor: green
          mode: bold
          regex: (?i)WhatIf = True
        type: highlight-output
    strategy: node-first
  uuid: 5446bb4a-34c8-488e-974b-d66eb3f3a3bd

```
