### ISSUE TITLE
NPE on scm api endpoint

### ISSUE THREAD

**Issue by jtobard** [rundeck/rundeck#5794]
**Describe the bug**
If the user try to import jobs but has no permission to create resources, instead of getting a well-formatted unauthorized message the API call returns an HTML error page caused by a null pointer exception.

**My Rundeck detail**

* Rundeck version: 3.2.3-snapshot
* install type: war
* OS Name/version: ubuntu 19.10
* DB Type/version: any (current mysql and h2)

**To Reproduce**
1. Configure a project with SCM git plugin import.
2. Try to perform an import using API with a user wit this ACL:
```
by:
  group: scmimport
for:
  project:
  - allow:
    - scm_import
context:
  application: rundeck
---
by:
  group: scmimport
for:
  job:
  - allow:
    - scm_create
    - scm_delete
    - scm_update
context:
  project: .*
```

missing acl permission:

```
by:
  group: scmimport
for:
  resource:
  - allow:
    - create
    equals:
      kind: job
context:
  project: .*
```
`POST $rd_url'/api/32/project/'$project'/scm/import/action/import-jobs'`

3. See html output instead of xml.

**Expected behavior**
a well-formatted error message.

**Additional context**
