### ISSUE TITLE
SCM Import is constantly asking to update a job

### ISSUE THREAD

**Issue by lukasged** [rundeck/rundeck#5814]
**Describe the bug**
I have configured my Rundeck project to use the SCM Import from a Git repository.

The import works fine, but then after a few minutes, I see a notification icon that there are changes to be imported from Git, while I know that actually there are no changes at all. 

When I click on `Import Remote Changes` and then click on `View Diff...` of the suggested file, it doesn't show any new commit in the configured Git repository, and just shows the following diff:

```
@@ -145,4 +145,3 @@
     strategy: node-first
   timeout: 1m
   uuid: 5e0g31c7-7175-42cd-95ef-0f234554ec00
-

```

It seems that it just tries to remove 1 blank line from the file.

If I choose to import that change, the interface doesn't show the suggested import until the next time that job is executed; and then it goes back to suggesting the same change again, removing the same blank line

**My Rundeck detail**

* Rundeck version: `3.1.2.20190927`
* install type: rpm
* OS Name/version: Linux/CentOS 7
* DB Type/version: MySQL

**To Reproduce**
1. Configure Rundeck to import the jobs from Git (SCM plugin)
2. Import the jobs from Git
3. Execute one of the imported jobs
4. Observe that Rundeck now suggests to import the executed job again, suggesting to remove a single blank line from the file

**Expected behavior**
After the job's import, Rundeck shouldn't offer to import the file again until there's an actual change in the configured Git repository.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80

To add more details of the described issue:
- it seems to only happen for scheduled jobs. All the other jobs that I execute manually are not affected. And for the scheduled jobs, the issue only appears when the job is executed upon by the scheduler. If the job is executed manually, the inferface is not suggesting any blank line changes.
- I attach a basic `Hello World` job that's scheduled every 1 minute, and is affected by the described issue. Also, you can see below the mentioned job's description inline:
```
- defaultTab: output
  description: Just a test job for SCM import
  executionEnabled: true
  id: 012a23e5-4db4-4a1d-9ee2-124671c1ab6c
  loglevel: INFO
  name: Test job
  nodeFilterEditable: false
  schedule:
    month: '*'
    time:
      hour: '*'
      minute: 0/1
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: echo 'Hello World!'
    keepgoing: false
    strategy: node-first
  uuid: 012a23e5-4db4-4a1d-9ee2-124671c1ab6c

```

[Test_job.zip](https://github.com/rundeck/rundeck/files/4236459/Test_job.zip)
