### ISSUE TITLE
Dynamic option list depending on node

### ISSUE THREAD

**Issue by ctolon22** [rundeck/rundeck#5898]
Hi,

I do have an environment where, depending on the target node, different services has to managed. If I choose the node 1, I would like to choose only the services that are running on that node.

- Node 1 Services:
    - Service 1
    - Service 2

- Node 2 Services:
    - Service 3
    - Service 4

So, when I choose Node 1 I would like to generate a dynamic option list with Service 1 and Service 2.

I have been testing with dynamic options with Remote URLs but I cannot send the target node as parameter to the Remote URL server.

I have also tested with a plugin as option source for the Job.

Do you know how could I manage this situation?

Thanks

**Comment by ctolon22** [comment]
I have continued with this problem. At the end, I have created a small HTTP server that:
1. Get the list of nodes from the Rundeck (api call to /resources) with the Job Node Filter (as I cannot send it to the call, my node filters are the same as the Job Group)
2. Depending on the option 1 (node) it shows the services from that node that are generated dynamically

The problem here is that it forces the final user to choose twice the node and if nodes mismatch an error will occur.

It would be great to have this dynamics options with node target functionality.

**Comment by MegaDrive68k** [comment]
Hi @ctolon22 

Very interesting use case! I did an example based on remote cascade options combined with Multi-Valued property. Let's go:

In this example we have two jobs: the first one called "Selector" and the second "Executor", also we need three JSON files to use cascade remote options in "Selector" job, those files are: `servers.json` (with `node01.json` and `node02.json` references), `node01.json` (with node01 services) and `node02.json ` (with node02 services) take a look:

**servers.json file**

```json
[
 {"name":"node01", "value":"node01.json"},
 {"name":"node02", "value":"node02.json"}
]
```

**node01.json file**

```json
[
    {"name":"ServiceONE", "value":"serviceone"},
    {"name":"ServiceTWO", "value":"servicetwo"}
]
```

**node02.json file**

```json
[
 {"name":"ServiceTHREE", "value":"servicethree"},
 {"name":"ServiceFOUR", "value":"servicefour"}
]

```
**Selector Job**

![Screenshot_4](https://user-images.githubusercontent.com/51376003/78951740-2f4b2a80-7aa1-11ea-9625-0bb5ced7ad50.png)

In the Selector job, we need to define a cascade option, the first remote option it's a single call to `servers.json` file and the second one it's a call to `servers.json` value (can be: `node01.json` or `node02.json`) this option it's defined as "Multi-Valued" and "," as the delimiter, this for select any services to each server.

Also, the job has an inline-script that takes the first option JSON value (the file name: `node01.json` or `node02.json`), then get out the ".json" extension and store it on a bash variable, later do an API call to "Executor" job with all data (node and services).

```xml
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option enforcedvalues='true' name='mynode' required='true' valuesUrl='file:/home/user/jsons/servers.json'>
          <label>Available nodes</label>
        </option>
        <option delimiter=',' enforcedvalues='true' multivalued='true' name='services' valuesUrl='file:/home/user/jsons/${option.mynode.value}'>
          <label>Services to run</label>
        </option>
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>c7cdf867-14ac-409b-a042-5ec5edeef693</id>
    <loglevel>INFO</loglevel>
    <name>Selector</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <fileExtension>.sh</fileExtension>
        <script><![CDATA[# only for debug, the filename and the services
echo "mynode: @option.mynode@"
echo "service: @option.services@"

####################################################
# now we call the executor job through Rundeck API
####################################################

# protocol
the_protocol="http"

# basic rundeck info
the_host="yournode"
the_port="4440"
the_api="35"
the_token="5T9BUzD2JJb8NP8Rrz7SHL5n6DaFGW50"

# specific api call info
the_job="0711d334-b611-4bdc-9832-e1cb1ece6734"

# get the node name using basename tool
the_node_filter=$(basename "@option.mynode@" .json)

# api call
curl --location --request POST "$the_protocol://$the_host:$the_port/api/$the_api/job/$the_job/run" \
  --header "Accept: application/json" \
  --header "X-Rundeck-Auth-Token: $the_token" \
  --header "Content-Type: application/json" \
  --data "{ \"argString\":\"-services @option.services@ \", \"filter\":\"$the_node_filter\" }"]]></script>
        <scriptargs />
        <scriptinterpreter>/bin/bash</scriptinterpreter>
      </command>
    </sequence>
    <uuid>c7cdf867-14ac-409b-a042-5ec5edeef693</uuid>
  </job>
</joblist>
```

**Executor job**

Basically is an empty job that only receives the node name to put it in the node filter and runs only in the server defined in the Selector job, also, receives the services in a list to be executed (i added an inline script that prints one by one).

```xml
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option delimiter=',' multivalued='true' name='services' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>0711d334-b611-4bdc-9832-e1cb1ece6734</id>
    <loglevel>INFO</loglevel>
    <name>Executor</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <fileExtension>.sh</fileExtension>
        <script><![CDATA[#!/bin/bash
DataList="@option.services@"
Field_Separator=$IFS
 
# set comma as internal field separator for the string list
IFS=,
for val in $DataList;
do
echo "executing: $val"
done
 
IFS=$Field_Separator]]></script>
        <scriptargs />
        <scriptinterpreter>/bin/bash</scriptinterpreter>
      </command>
    </sequence>
    <uuid>0711d334-b611-4bdc-9832-e1cb1ece6734</uuid>
  </job>
</joblist>
```

**Some some "demo" screenshots:**

Selecting node02 with two services selected:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/78951101-e5f9db80-7a9e-11ea-8571-357dd08dd924.png)

Selecting node01 with one service selected:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/78951102-e6927200-7a9e-11ea-8730-fc71ec75a577.png)

Hope it helps.

**Comment by ctolon22** [comment]
Hi @MegaDrive68k,

Thank you for the example, really complete and accurate to my use case.

At the end, I have changed the node filter to the `${option.node}` that is evaluated before running the script/scriptfile/...

I have organized my nodes with TAGS that are equal to the JOB GROUP where the nodes are possible targets. 
My HTTP server receives the Job.Group with which it can retrieve the node list from the Rundeck Server, then, access via ssh to the selected node and retrieves the service list (running another script).

For example, a Node List:

```yaml
- my-node:
  nodename: my-node
  hostname: my-node
  description: "[ Production Instance ]"
  tags: "MY_GROUP"
```

When I ask my HTTP server with the parameter `filter=MY_GROUP` it will reponses with `my-node`. And the other 

You can see my example job:

```yaml
- name: JOB NAME
  description: 'JOB DESCRIPTION'
  loglevel: INFO
  group: MY_GROUP
  nodeFilterEditable: false
  nodefilters:
    filter: ${option.node}
  nodesSelectedByDefault: true
  options:
  - enforced: true
    name: node
    description: "Node to execute the script"
    required: true
    valuesUrl: http://localhost:4441/getNodes?filter=${job.group}
  - name: cluster
    enforce: true
    required: true
    description: "Cluster where members are checked"
    valuesUrl: http://localhost:4441/serviceList?node=${option.node.value}&action=GET_SERVICES
  - name: action
    required: true
    description: action to run
    value: status
    enforced: true
    multivalueAllSelected: false
    values:
    - start
    - stop
    - restart
    - status
    multivalued: false
  sequence:
    commands:
      - scriptfile: /work/rundeck/scripts/my-script.sh
        args: ${option.action}
```

I think it is not the best option, but it solves my use case and the HTTP server does not consume almost anything and a really simple code. 

With your example, I will think about "setting" the HTTP server as a Rundeck Job that I invoke from the final user JOB. 

Thank you again.
