### ISSUE TITLE
RUNDECK_MAIL_PROPS option don't work as expectation

### ISSUE THREAD

**Issue by bienkma** [rundeck/rundeck#5925]
I'm using docker-compose for launching a rundeck instance. Also, I wanna setup notification by Gmail but when I set environment RUNDECK_MAIL_PROPS don't work as document (It's ready worked in groovy config file - worked same my account Gmail. But I don't want to use Groovy file config for production). My docker-compose.yml is below:
```
---
version: '3.1'
services:
  rundeck:
    restart: always
    image: rundeck/rundeck:3.2.4
    ports:
      - 4440:4440
    depends_on:
      - db
    container_name: rundeck
    environment:
      - TS="Asia/Ho_Chi_Minh"
      - RUNDECK_SERVER_FORWARDED=true
      - RUNDECK_SERVER_ADDRESS=0.0.0.0
      - RUNDECK_DATABASE_URL=jdbc:mysql://db/rundeck?autoReconnect=true&useSSL=false
      - RUNDECK_DATABASE_USERNAME=root
      - RUNDECK_DATABASE_PASSWORD=change_me_now
      - RUNDECK_GRAILS_URL=http://10.110.64.20:4440
      - SERVER_URL=http://10.110.64.20:4440
      - RUNDECK_SECURITY_SYNCLDAPUSER=true
      - SETTING_RUNDECK_FORWARDED=true
      - RUNDECK_DATABASE_DRIVER=org.mariadb.jdbc.Driver
      - RUNDECK_LOGGING_STRATEGY=CONSOLE
      - RUNDECK_MAIL_SMTP_HOST=smtp.gmail.com
      - RUNDECK_MAIL_SMTP_PORT=587
      - RUNDECK_MAIL_SMTP_USERNAME=rundeck@lab.vn
      - RUNDECK_MAIL_SMTP_PASSWORD=change_me_now
      - RUNDECK_MAIL_FROM=rundeck@lab.vn
      - RUNDECK_MAIL_PROPS=["mail.smtp.auth":"true","mail.smtp.port":"587","mail.smtp.starttls.enable":"true","mail.smtp.socketFactory.port":"587","mail.smtp.socketFactory.fallback":"false"]
    volumes:
      - /home/bienkma/config/jaas-ldap.conf:/home/rundeck/servers/config/jaas-ldap.conf:ro
      - ./etc/admin.aclpolicy:/home/rundeck/etc/admin.aclpolicy:ro
      - /home/bienkma/entry.sh:/home/rundeck/docker-lib/entry.sh
      - ./data_rundeck:/home/rundeck/server/data:rw
      - ./data_rundeck_logs:/home/rundeck/var/logs/rundeck:rw
  db:
    restart: always
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=change_me_now
      - MYSQL_DATABASE=rundeck
    volumes:
      - ./data:/var/lib/data
      - /etc/localtime:/etc/localtime:ro
```
entry.init
```
#!/bin/bash
set -eou pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

for inc in $(ls $DIR/includes | sort -n); do
    source $DIR/includes/$inc
done

export HOSTNAME=$(hostname)

export RUNDECK_HOME=/home/rundeck

export REMCO_HOME=/etc/remco
export REMCO_RESOURCE_DIR=${REMCO_HOME}/resources.d
export REMCO_TEMPLATE_DIR=${REMCO_HOME}/templates
export REMCO_TMP_DIR=/tmp/remco-partials

# Create temporary directories for config partials
mkdir -p ${REMCO_TMP_DIR}/framework
mkdir -p ${REMCO_TMP_DIR}/rundeck-config
mkdir -p ${REMCO_TMP_DIR}/artifact-repositories

remco -config ${REMCO_HOME}/config.toml

# Generate a new server UUID
if [[ "${RUNDECK_SERVER_UUID}" = "RANDOM" ]] ; then
    RUNDECK_SERVER_UUID=$(uuidgen)
fi
echo "rundeck.server.uuid = ${RUNDECK_SERVER_UUID}" > ${REMCO_TMP_DIR}/framework/server-uuid.properties

# Combine partial config files
cat ${REMCO_TMP_DIR}/framework/* >> etc/framework.properties
cat ${REMCO_TMP_DIR}/rundeck-config/* >> server/config/rundeck-config.properties
cat ${REMCO_TMP_DIR}/artifact-repositories/* >> server/config/artifact-repositories.yaml


# Store settings that may be unset in script variables
SETTING_RUNDECK_FORWARDED="${RUNDECK_SERVER_FORWARDED:-false}"

# Unset all RUNDECK_* environment variables
if [[ "${RUNDECK_ENVARS_UNSETALL:-true}" = "true" ]] ; then
    unset `env | awk -F '=' '{print $1}' | grep -e '^RUNDECK_'`
fi

# Unset specific environment variables
if [[ ! -z "${RUNDECK_ENVARS_UNSETS:-}" ]] ; then
    unset $RUNDECK_ENVARS_UNSETS
    unset RUNDECK_ENVARS_UNSETS
fi

exec java \
    -XX:+UnlockExperimentalVMOptions \
    -XX:MaxRAMFraction="${JVM_MAX_RAM_FRACTION}" \
    -XX:+UseCGroupMemoryLimitForHeap \
		-Drundeck.jaaslogin=true \
		-Djava.security.auth.login.config=/home/rundeck/servers/config/jaas-ldap.conf \
		-Dloginmodule.name=ldap \
		-Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG \
    -Drundeck.jetty.connector.forwarded="${SETTING_RUNDECK_FORWARDED}" \
    "${@}" \
    -jar rundeck.war
```
The erros log:
```
[2020-03-31 04:55:38.973] ERROR NotificationService --- [eduler_Worker-1] Error sending notification email to bienkma@lab.vn for Execution 1: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. a24sm11451071pfl.115 - gsmtp
```

**Comment by brettjenkins** [comment]
Having the exact same issue - cannot get gmail working using the docker env variables

**Comment by markkuit** [comment]
I experienced the same issue, and ended placing `rundeck-config.groovy` (content follows) in `/home/rundeck/server/config/`, since I got it as a volume for other purposes. The file is processed even though the java-style `rundeck-config.properties` is also there, being autogenerated from the env vars.

```
grails {
  mail {
        props = ["mail.smtp.starttls.enable":"true","mail.smtp.auth":"true","mail.smtp.socketFactory.port":"587","mail.smtp.socketFactory.fallback":"false"]
  }
}
```

Did anyone find a better solution? Has this been brought up to the attention of the Rundeck team already?

**Comment by ProTip** [comment]
Hello,

We have successfully used `RUNDECK_MAIL_PROPS` in a number of deployments including against AWS SMS.

Perhaps try just `["mail.smtp.starttls.enable":"true","mail.smtp.port":"587"]` (skipping the socket factory and auth biz) and not specifying the extraneous `RUNDECK_MAIL_SMTP_PORT`.

**Comment by maartendirickx** [comment]
Hi all,

I'm currently on Rundeck 3.4.2, The proposed solution of removing `RUNDECK_MAIL_STMP_PORT` in favour of a simplified `PROPS` did not fix it for me. My current environment variables are:

```
rundeck@rundeck:~$ env|grep RUNDECK_MAIL                                        
RUNDECK_MAIL_SMTP_PASSWORD=password                                            
RUNDECK_MAIL_SMTP_HOST=smtp.gmail.com                                           
RUNDECK_MAIL_PROPS=["mail.smtp.starttls.enable":"true","mail.smtp.port":"587"]  
RUNDECK_MAIL_SMTP_USERNAME=myuser@gmail.com                             
RUNDECK_MAIL_FROM=myuser@gmail.com
```

I tried a couple of combinations, nothing that did the trick for me. Any advice on how to proceed?

Cheers,

**Comment by S0LERA** [comment]
Hello,

I have a production rundeck environment in container on 3.4.3 version. Some days ago the mail service stopped working without modifying any configuration. The mail service is configured in outlook, this is the configuration in rundeck-config.properties:

```
grails.mail.host=outlook.office365.com
grails.mail.username=MY_EXCHANGE_ACCOUNT
grails.mail.default.from=MY_EXCHANGE_MAILBOX
grails.mail.props=["mail.smtp.starttls.enable":"true", "mail.smtp.port":587, "mail.smtp.auth":"true"]
grails.mail.password=MY_PASSWORD
```

This file is filled with the values of the environment variables:
```
RUNDECK_MAIL_SMTP_PASSWORD=
RUNDECK_MAIL_SMTP_HOST=
RUNDECK_MAIL_PROPS=
RUNDECK_MAIL_SMTP_USERNAME=
RUNDECK_MAIL_FROM=
```

All worked fine until the reception of this exception:
`RUNDECK ERROR services.NotificationService - Error sending notification email to ***** for Execution 2037: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 451 5.7.3 STARTTLS is required to send mail`

However in the props I have the Starttls enabled as you can see. I try with and without the environment variable of the PORT but nothing changes.

Any advance on this?

**Comment by ledufakademy** [comment]
same here working then suddenly stopping ...

**Comment by ledufakademy** [comment]
grails.mail.starttls.enable just not working !

**Comment by jmckeown2** [comment]
My solution was to create two files outside the container then mount them in the container as:

/etc/remco/resources.d/rundeck-config-smtp.properties.toml
```toml
[[template]]
    src         = "${REMCO_TEMPLATE_DIR}/rundeck-config-smtp.properties"
    dst         = "${REMCO_TMP_DIR}/rundeck-config/rundeck-config-smtp.properties"
    mode        = "0644"
```

/etc/remco/templates/rundeck-config-smtp.properties
```properties
{%- if exists("/rundeck/mail/smtp/port") %}
grails.mail.props.mail.smtp.port={{ getv("/rundeck/mail/smtp/port", "587") }}
{% endif %}

grails.mail.props.mail.smtp.starttls.enable=true
```

This causes the rundeck-config.properties to be created with the proper settings.

**Comment by occamssafetyrazor** [comment]
Thanks @jmckeown2! It worked with version 4.6.0.
For anyone else who hasn't use the remco configuration extension feature:
Create a Dockerfile as [shown here](https://github.com/rundeck/docker-zoo/blob/master/config/Dockerfile) and [follow a similar project layout as the documentation](https://docs.rundeck.com/docs/administration/configuration/docker/extending-configuration.html#configuration-layout).

**Comment by vainkop** [comment]
You can find a part of my helm chart config which works for AWS SES & sends emails to anything (like gmail).

The important part here is to properly define the value for RUNDECK_MAIL_PROPS.
1) escape the double quotes for values inside array
2) put the array itself into quotes so it's a string, not an array

```
rundeck:
  env:
    RUNDECK_GRAILS_URL: "https://rundeck.example.com"
    RUNDECK_SERVER_FORWARDED: "true"
    RUNDECK_LOGGING_STRATEGY: "CONSOLE"
    RUNDECK_SERVER_ADDRESS: "0.0.0.0"
    RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
    RUNDECK_DATABASE_USERNAME: RUNDECK_DATABASE_USER
    RUNDECK_DATABASE_PASSWORD: RUNDECK_DATABASE_PASSWORD
    RUNDECK_DATABASE_URL: jdbc:postgresql://RUNDECK_DATABASE_URL:5432/rundeck?autoReconnect=true
    RUNDECK_MAIL_SMTP_HOST: "email-smtp.us-east-1.amazonaws.com"
    RUNDECK_MAIL_SMTP_PORT: "587"
    RUNDECK_MAIL_SMTP_USERNAME: "AKIXXXXXXXXXXXYXXXXX"
    RUNDECK_MAIL_SMTP_PASSWORD: "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
    RUNDECK_MAIL_FROM: "rundeck@example.com"
    RUNDECK_MAIL_PROPS: "[\"mail.smtp.starttls.enable\":\"true\",\"mail.smtp.port\":\"587\"]"
```
