### ISSUE TITLE
Add support for command looping 

### ISSUE THREAD

**Issue by btiernay** [rundeck/rundeck#606]
A powerful feature for workflows is the ability to loop over a set of items and perform a command. Ansible's looping feature is a good example of this feature:

http://www.ansibleworks.com/docs/playbooks_loops.html

Of note is the `with_items` property which supports iteration from a variable.

This could work similarly in Rundeck:

``` yaml
sequence:
  keepgoing: true
  strategy: node-first
  commands: 
  - exec: echo ${item}
    with_items:
    - 1
    - 2
```

This becomes even more powerful with something like Ansible's "registered variables" since this allows a job step to execute a variable number of times based on the output of a previous step.

http://www.ansibleworks.com/docs/playbooks_variables.html#registered-variables
