### ISSUE TITLE
Docker Rundeck - Vault configuration is not read from ENV variable. 

### ISSUE THREAD

**Issue by 1ricardo** [rundeck/rundeck#6218]
**Describe the bug**
I am using Kubernetes and I'm trying to implement **Vault-Storage** as Key Backed storage.
The problem is that the configuration from Environment Variables about storage provider is not copied to the Rundeck configuration files.

The plugin is installed correctly 
`01a78578d6d9 : vault-storage : 1.3.0 (installed) `

My ENV vars

```
# export
....
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_ADDRES="http://vault.vault.svc.cluster.local:8200"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_AUTHBACKEND="token"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_ENGINEVERSION="1"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_MAXRETRIES="3"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_OPENTIMEOUT="3"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_PREFIX="rundeck"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_READTIMEOUT="5"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_REMOVEPATHPREFIX="true"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_RETRYINTERVALMILLISECONDS="100"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_SECRETBACKEND="secret"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_STORAGEBEHAVIOUR="vault"
declare -x RUNDECK_STORAGE_PROVIDER_1_CONFIG_TOKEN="myTokenHere"
declare -x RUNDECK_STORAGE_PROVIDER_1_PATH="keys"
declare -x RUNDECK_STORAGE_PROVIDER_1_TYPE="vault-storage"
...
```

**My Rundeck detail**

* Rundeck version: 3.2.8
* install type: official Rundeck docker image [https://hub.docker.com/r/rundeck/rundeck](https://hub.docker.com/r/rundeck/rundeck)
* OS Name/version: Ubuntu 16.04.6 LTS
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
1. Configure the ENV in Kubernetes POD
2. Deploy POD with the plugin
3. Try to use a Key Storage

**Expected behavior**
Possibility to use vault-storage in a docker instance.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser FireFox
 - Version: 78.0.1 (64-bit)

**Additional context**

**Comment by tkorrapati1** [comment]
I ran into same issue aswell. 

Rundeck version: 3.2.8
install type: official Rundeck docker image https://hub.docker.com/r/rundeck/rundeck

Installed on a Kubernetes(EKS) cluster using rundeck [helm chart](https://github.com/helm/charts/tree/master/incubator/rundeck).

Below is how i'm passing env variables using values.yaml

```
omitted
.
.
deployment:
  replicaCount: 1
  annotations: {}
  rolloutStrategy:
    type: Recreate

rundeck:
  adminUser: "admin:admin,user,admin,architect,deploy,build"
  env:
    RUNDECK_GRAILS_URL: "https://rundeckurl.com"
    RUNDECK_SERVER_FORWARDED: "true"
    RUNDECK_LOGGING_STRATEGY: "FILE"
    RUNDECK_DATABASE_URL: "jdbc:postgresql://dburl.rds.amazonaws.com/rundeck"
    RUNDECK_DATABASE_DRIVER: "org.postgresql.Driver"
    RUNDECK_DATABASE_USERNAME: "user"
    RUNDECK_DATABASE_PASSWORD: "password"
    RUNDECK_STORAGE_PROVIDER_2_TYPE: 'vault-storage'
    RUNDECK_STORAGE_PROVIDER_2_PATH: 'keys/vault'
    RUNDECK_STORAGE_PROVIDER_2_REMOVEPATHPREFIX: 'true'
    RUNDECK_STORAGE_PROVIDER_2_CONFIG_PREFIX: 'dev/'
    RUNDECK_STORAGE_PROVIDER_2_CONFIG_SECRETBACKEND: 'secret/'
    RUNDECK_STORAGE_PROVIDER_2_CONFIG_ADDRESS: 'https://vault-server-address:8200'
    RUNDECK_STORAGE_PROVIDER_2_CONFIG_AUTHBACKEND: 'token'
    RUNDECK_STORAGE_PROVIDER_2_CONFIG_TOKEN: 's.thisisatoen'
    RUNDECK_STORAGE_PROVIDER_2_CONFIG_STORAGEBEHAVIOUR: 'vault'
    RUNDECK_STORAGE_PROVIDER_2_CONFIG_ENGINEVERSION: '2'
    RUNDECK_STORAGE_PROVIDER_2_CONFIG_VALIDATESSL: 'true'

  awsCredentialsSecret: ""
  awsVolumeId: ""

persistence:
  enabled: "false"
.
.
omitted
```
I can confirm that environment variables are being loaded into pod, but they are not getting picked up by remco when creating the server/config/rundeck-config.properties file during entrypoint.

Below are list of environment variables that are loaded into rundeck pod.

```
$ kubectl exec -it  rd2-rundeck-74fc646cff-nwrgm -c rundeck -n rundeck  bash
rundeck@rd2-rundeck-74fc646cff-nwrgm:~$ env
RUNDECK_STORAGE_PROVIDER_2_TYPE=vault-storage
RD2_RUNDECK_PORT_80_TCP_ADDR=172.20.158.79
RD2_RUNDECK_SERVICE_HOST=172.20.158.79
RUNDECK_DATABASE_USERNAME=user
HOSTNAME=rd2-rundeck-74fc646cff-nwrgm
RD2_RUNDECK_PORT_80_TCP=tcp://172.20.158.79:80
RUNDECK_DATABASE_DRIVER=org.postgresql.Driver
RUNDECK_STORAGE_PROVIDER_2_PATH=keys/vault
KUBERNETES_PORT=tcp://172.20.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
TERM=xterm
RD2_RUNDECK_PORT_80_TCP_PROTO=tcp
RUNDECK_DATABASE_PASSWORD=password
RD2_RUNDECK_PORT=tcp://172.20.158.79:80
RUNDECK_STORAGE_PROVIDER_2_REMOVEPATHPREFIX=true
KUBERNETES_SERVICE_PORT=443
RUNDECK_DATABASE_URL=jdbc:postgresql://dburl.rds.amazonaws.com/rundeck
KUBERNETES_SERVICE_HOST=172.20.0.1
RUNDECK_STORAGE_PROVIDER_2_CONFIG_ENGINEVERSION=2
LC_ALL=C.UTF-8
RUNDECK_GRAILS_URL=https://rundeckurl.com
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
RUNDECK_STORAGE_PROVIDER_2_CONFIG_SECRETBACKEND=secret/
RUNDECK_STORAGE_PROVIDER_2_CONFIG_PREFIX=dev/
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/rundeck/tools/bin
RD2_RUNDECK_PORT_80_TCP_PORT=80
RD2_RUNDECK_SERVICE_PORT_HTTP=80
PWD=/home/rundeck
RUNDECK_STORAGE_PROVIDER_2_CONFIG_ADDRESS=https://vault.server.address:8200
LANG=C.UTF-8
RD2_RUNDECK_SERVICE_PORT=80
RUNDECK_STORAGE_PROVIDER_2_CONFIG_TOKEN=s.thisisthetoken
SHLVL=1
HOME=/home/rundeck
TINI_VERSION=v0.18.0
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
RUNDECK_STORAGE_PROVIDER_2_CONFIG_STORAGEBEHAVIOUR=vault
RUNDECK_LOGGING_STRATEGY=CONSOLE
RUNDECK_STORAGE_PROVIDER_2_CONFIG_AUTHBACKEND=token
DEBIAN_FRONTEND=noninteractive
RUNDECK_SERVER_FORWARDED=true
KUBERNETES_PORT_443_TCP_ADDR=172.20.0.1
KUBERNETES_PORT_443_TCP=tcp://172.20.0.1:443
RUNDECK_STORAGE_PROVIDER_2_CONFIG_VALIDATESSL=true
_=/usr/bin/env
rundeck@rd2-rundeck-74fc646cff-nwrgm:~$
```

Below is the generated **_rundeck-config.properties_** file from the pod. Note that other environment variables like RUNDECK_DATABASE_USERNAME, RUNDECK_DATABASE_URL etc...were picked up correctly but the **storage provider ones are totally ignored**.


```
rundeck@rd2-rundeck-85c6d6ddc5-hdv7r:~$ cat server/config/rundeck-config.properties
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/home/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false

# Bind address and server URL
server.address=0.0.0.0
server.contextPath=/
grails.serverURL=https://rundeckurl.com

server.session.timeout=3600

dataSource.dbCreate = update
dataSource.url = jdbc:postgresql://dburl.rds.amazonaws.com/rundeck
dataSource.username = user
dataSource.password = password 
    dataSource.driverClassName = org.postgresql.Driver


#Pre Auth mode settings
rundeck.security.authorization.preauthenticated.enabled=false
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=,
# Header from which to obtain user name
rundeck.security.authorization.preauthenticated.userNameHeader=X-Forwarded-Uuid
# Header from which to obtain list of roles
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Forwarded-Roles
# Redirect to upstream logout url
rundeck.security.authorization.preauthenticated.redirectLogout=false
rundeck.security.authorization.preauthenticated.redirectUrl=/oauth2/sign_in

rundeck.api.tokens.duration.max=30d

rundeck.log4j.config.file=/home/rundeck/server/config/log4j.properties

rundeck.gui.startpage=projectHome

rundeck.clusterMode.enabled=true

rundeck.security.httpHeaders.enabled=true

rundeck.security.httpHeaders.provider.xcto.enabled=true

rundeck.security.httpHeaders.provider.xxssp.enabled=true

rundeck.security.httpHeaders.provider.xfo.enabled=true

rundeck.security.httpHeaders.provider.csp.enabled=true

rundeck.security.httpHeaders.provider.csp.config.include-xcsp-header=false

rundeck.security.httpHeaders.provider.csp.config.include-xwkcsp-header=false

rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=keys

rundeck.projectsStorageType=db

```
