### ISSUE TITLE
Global execution variables not exported in Job Reference from another project

### ISSUE THREAD

**Issue by ehrhart** [rundeck/rundeck#6231]
**Describe the bug**
I have two projects (A and B). In the file `project.properties` of project **A**, I have defined the following global variable:

```properties
project.globals.foobar=This is a test
```

If called within a job in project **A**, the global variable is correctly passed to the job.
If called from a _Job Reference_ step to project **A** from project **B**, the global variable is undefined.

**My Rundeck detail**

* Rundeck version: 3.3.0-20200701
* install type: war
* OS Name/version: Debian 11
* DB Type/version: H2

**To Reproduce**
* `project.properties` in project **A**:
```properties
project.globals.foobar=This is a test
```
* `job_A.yml` in project **A**:
```yml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: ce45d2f0-745b-498f-8db4-ecb91dd816ee
  loglevel: INFO
  name: job A
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/usr/bin/env bash
        echo "result: @globals.foobar@"
    keepgoing: false
    strategy: node-first
  uuid: ce45d2f0-745b-498f-8db4-ecb91dd816ee
```
* `job_B.yml` in project **B**:
```yml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 2754ed98-9071-483c-b114-ed3123907319
  loglevel: INFO
  name: job B
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: ''
        name: job A
        nodeStep: 'true'
        project: A
        uuid: ce45d2f0-745b-498f-8db4-ecb91dd816ee
    keepgoing: false
    strategy: node-first
  uuid: 2754ed98-9071-483c-b114-ed3123907319
```

**Expected behavior**
When running "job B", I expect the _Job Reference_ step to be executed within the context of project **A**, with all defined global variables from project **A**. Thus, the output should be:

```
result: This is a test
```

Instead, I'm currently getting:

```
result: 
```

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Version 83.0.4103.116

**Additional context**
I don't know if this is a bug or an expected behavior, but I assume it's loading the global context of the current project, instead of the global context of the project referenced in the _Job Reference step_.

I'm relying on per-project global variables to define environment variables such as paths, and I need to execute jobs from different projects, while keeping the global variables from the referenced project.

Maybe we could have it as an option (checkbox) in the _Job Reference_ step UI, eg. `[x] Run the job from within the referenced project context`?
