### ISSUE TITLE
Rundeck docker with ssl support

### ISSUE THREAD

**Issue by zerr0s** [rundeck/rundeck#6242]
Hi, sorry for my bad english.

I'm trying to use the docker rundeck image. Without SSL, no problem. But I can't get it working with the SSL support.
My rundeck is running behind a traefik RP.

The RDECK_JVM is never used by the rundeck image. How shoud I implement SSL with the official docker image please ??

My docker compose:

```
rundeck:
    image: rundeck/rundeck:3.3.0
    container_name: rundeck
    labels:
      - traefik.enable=true
      - traefik.http.routers.rundeck.rule=PathPrefix(`/`)
      - traefik.http.routers.rundeck.entrypoints=webs
      - traefik.http.routers.whoami.tls.certresolver=myresolver
      - traefik.http.routers.whoami.rule=Host(`xxxxx`)
    depends_on:
      - postgres
    environment:
      RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
      RUNDECK_DATABASE_USERNAME: xxxxx
      RUNDECK_DATABASE_PASSWORD: xxxxxx
      RUNDECK_DATABASE_URL: jdbc:postgresql://postgres/rundeck
      RUNDECK_SERVER_ADDRESS: 0.0.0.0
      RUNDECK_GRAILS_URL: https://xxxxxxx
      RUNDECK_SERVER_PORT: 4443
      RDECK_JVM: "$RDECK_JVM -Drundeck.ssl.config=/home/rundeck/server/config/ssl.properties -Dserver.https.port=4443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/containers/rundeck/etc:/home/rundeck/etc
      - /data/containers/rundeck/server/config:/home/rundeck/server/config
      - /data/containers/rundeck/server/data:/home/rundeck/server/data
      - /data/containers/rundeck/libext:/home/rundeck/libext
      - /data/containers/rundeck/projects:/home/rundeck/projects
    networks:
      - rundeck
```

Hope that someone could help ...

**Comment by MegaDrive68k** [comment]
Hi @zerr0s 

I leave an example that works, feel free to modify and use it as a base for your deploy.

Dockerfile:

```dockerfile
ARG IMAGE

FROM ${IMAGE}

USER rundeck

COPY --chown=rundeck:root lib docker-lib
RUN chmod +x docker-lib/generate-ssl.sh
RUN ./docker-lib/generate-ssl.sh
```

docker-compose.yml:

```yaml
version: "3"
services:
  rundeck:
    build:
      context: .
      args:
        IMAGE: ${RUNDECK_IMAGE:-rundeck/rundeck:3.3.0}
    container_name: rundeck-ssl
    command: "-Dserver.https.port=4443 -Drundeck.ssl.config=/home/rundeck/server/config/ssl.properties"
    ports:
    - 4443:4443
    environment:
      RUNDECK_GRAILS_URL: https://test:4443
```

generate-ssl.sh (script on `lib` directory that creates the SSL cert on Rundeck image).:

```bash
#!/usr/bin/env bash

# creating the keystore
keytool -keystore etc/keystore \
        -alias rundeckssl \
        -genkey -keyalg RSA \
        -keypass adminadmin \
        -storepass adminadmin \
        -dname "C=test, S=stgo, OU= rundeck, L=stgo, O=cst, CN=rundeck"

# and now, copy as truststore
cp etc/keystore etc/truststore
```

Check the project for your tests:

[ssl_oss.zip](https://github.com/rundeck/rundeck/files/4898439/ssl_oss.zip)

Build with `docker-compose build` and run with `docker-compose up` (then you can go to https://test:4443 on your browser, add that hostname on your `/etc/hosts` to access it).

![Screenshot_1](https://user-images.githubusercontent.com/51376003/87071741-a7cc9f00-c1e8-11ea-9a37-88a9f051a519.png)


Hope it helps!

**Comment by zerr0s** [comment]
hello.

Thanks. it's working with small adjustmtents of my traefik component.

**Comment by rivolity** [comment]
Here is my docker compose, it works with no problem with traefik, and with no need to rebuild an Image, it takes the last Rundeck Snapshot.
```
version: '3.9'
networks:
  proxy:
    external: true
services:
  rundeck:
    image: ${RUNDECK_IMAGE:-rundeck/rundeck:SNAPSHOT}
    restart: unless-stopped
    container_name: rundeck
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rundeck.entrypoints=http"
      - "traefik.http.routers.rundeck.rule=Host(`xxxx`)"
      - "traefik.http.middlewares.rundeck-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.rundeck.middlewares=rundeck-https-redirect"
      - "traefik.http.routers.rundeck-secure.entrypoints=https"
      - "traefik.http.routers.rundeck-secure.rule=Host(`xxxx`)"
      - "traefik.http.routers.rundeck-secure.tls=true"
      - "traefik.http.routers.rundeck-secure.service=rundeck"
      - "traefik.http.services.rundeck.loadbalancer.server.port=4440"
      - "traefik.docker.network=proxy"
    tty: true
    links:
      - postgres
    environment:
        RUNDECK_GRAILS_URL: https://xxxx
        RUNDECK_LOGGING_STRATEGY: FILE
        #if enabled redirection after login will note work "no idea why"
        RUNDECK_SECURITY_HTTPHEADERS_ENABLED: 0
        RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
        RUNDECK_DATABASE_USERNAME: rundeck
        RUNDECK_DATABASE_PASSWORD: rundeck
        RUNDECK_DATABASE_URL: jdbc:postgresql://postgres/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    volumes:
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
      - /home/docker/rundeck/ssh:/home/rundeck/.ssh
      - /home/docker/rundeck/config:/home/rundeck/server/config
      - /home/docker/rundeck/logs:/home/rundeck/var/logs/rundeck
      - /home/docker/rundeck/lib:/home/rundeck/server/lib
      - /home/docker/rundeck/libext:/home/rundeck/libext
    ports:
      - 8012:4440
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: posdtgres-rundeck
    networks:
      - proxy
    tty: true
    expose:
      - 5432
    environment:
      - POSTGRES_DB=rundeck
      - POSTGRES_USER=rundeck
      - POSTGRES_PASSWORD=rundeck
    volumes:
      - /home/docker/rundeck-postgres:/var/lib/postgresql/data
```
