### ISSUE TITLE
Error role membership; role query configuration may be incorrect

### ISSUE THREAD

**Issue by joseterra** [rundeck/rundeck#6321]
Hi,

I am getting this error when using the rundeck with LDAP. Please add supplementalRoles="users" to the configuration file.

``` 
rundeck-app | [2020-07-28 09:24:44.447] DEBUG JettyCachingLdapLoginModule --- [qtp879948715-26] Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: dc=github,dc=com
rundeck-app | [2020-07-28 09:24:44.448] DEBUG JettyCachingLdapLoginModule --- [qtp879948715-26] Found user?: true
rundeck-app | [2020-07-28 09:24:44.449] DEBUG JettyCachingLdapLoginModule --- [qtp879948715-26] user cred is present: true
rundeck-app | [2020-07-28 09:24:44.450]  WARN JettyCachingLdapLoginModule --- [qtp879948715-26] JettyCachingLdapLoginModule: User 'jose.terra' has no role membership; role query configuration may be incorrect
```

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: Docker Image
* DB Type/version: Mysql

**My docker compose file**

``` 
version: '3.8'

services:
    rundeck:
        container_name: rundeck-app
        restart: always
        image: rundeck/rundeck:3.3.0
        links:
          - mysql
        environment:
            RUNDECK_DATABASE_DRIVER: com.mysql.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
            RUNDECK_JAAS_MODULES_0: JettyCombinedLdapLoginModule
            RUNDECK_JAAS_MODULES_1: PropertyFileLoginModule
            RUNDECK_GRAILS_URL: http://192.168.0.12:4440
            RUNDECK_JAAS_LDAP_PROVIDERURL: ldap://192.168.0.12:389
            RUNDECK_JAAS_LDAP_FLAG: sufficient
            RUNDECK_JAAS_LDAP_BINDDN: "cn=admin,dc=github, dc=com"
            RUNDECK_JAAS_LDAP_BINDPASSWORD: "xxxxx"
            RUNDECK_JAAS_LDAP_USERRDNATTRIBUTE: dn
            RUNDECK_JAAS_LDAP_USERBASEDN: "dc=github, dc=com"
            RUNDECK_JAAS_LDAP_ROLEBASEDN: "dc=github, dc=com"
            RUNDECK_JAAS_LDAP_FORCEBINDINGLOGIN: "false"
            RUNDECK_JAAS_LDAP_USEROBJECTCLASS: "inetOrgPerson"
            RUNDECK_JAAS_LDAP_USERIDATTRIBUTE: uid
            RUNDECK_JAAS_LDAP_USERLASTNAMEATTRIBUTE: sn
            RUNDECK_JAAS_LDAP_USERFIRSTNAMEATTRIBUTE: cn
            RUNDECK_JAAS_LDAP_USEREMAILATTRIBUTE: mail
            RUNDECK_JAAS_LDAP_ROLEBASEDN: dc=github, dc=com
            RUNDECK_JAAS_LDAP_USERPASSWORDATTRIBUTE: userPassword
        ports:
          - 4440:4440
        depends_on:
          - mysql
        volumes:
          - rundeck-data:/home/rundeck/server/data
        networks:
          - rundeck-network
    mysql:
        container_name: rundeck-mysql
        restart: always
        image: mysql:5.7
        expose:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=xxxxx
        volumes:
          - rundeck-mysql:/var/lib/mysql
        networks:
          - rundeck-network

volumes:
    rundeck-mysql:
        name: rundeck-mysql
    rundeck-data:
        name: rundeck-data

networks:
    rundeck-network:
        name: rundeck-network
        driver: bridge
```
