### ISSUE TITLE
Pre-Authenticated Mode Login URL always points to /user/logout instead of using RUNDECK_PREAUTH_REDIRECT_URL variable

### ISSUE THREAD

**Issue by karann-jain** [rundeck/rundeck#6346]
**Describe the bug**
I have set the RUNDECK_PREAUTH_REDIRECT_URL variable to /oauth2/logout. However, the UI always redirects to /user/logout and eventually to http://localhost/user/logout and fails.

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.0]
* install type: Docker
* DB Type/version: mysql

**To Reproduce**
1. Login to http://<your-rundeck-domain>.com/ using pre-auth mode. Make sure to set the RUNDECK_PREAUTH_REDIRECT_URL='/oauth2/logout'
2. Go to 'Profile'
3. Click on 'Logout'
4. Wait for direction 
5. See error

**Expected behavior**
Expected to use RUNDECK_PREAUTH_REDIRECT_URL variable instead of default /user/logout.

**Comment by MegaDrive68k** [comment]
Hi @karann-jain,

Are you defined `RUNDECK_PREAUTH_REDIRECT_LOGOUT=true` as an environment variable on your container?

You can check it here: https://hub.docker.com/r/rundeck/rundeck

Regards!

**Comment by karann-jain** [comment]
Hi @MegaDrive68k,

Yes its set, here are the env set on my K8s yaml.

```
          env:
            - name: RUNDECK_PREAUTH_ATTRIBUTE_NAME
              value: REMOTE_USER_GROUPS
            - name: RUNDECK_PREAUTH_DELIMITER
              value: ","
            - name: RUNDECK_PREAUTH_USERNAME_HEADER
              value: X-Forwarded-User
            - name: RUNDECK_PREAUTH_ROLES_HEADER
              value: X-Forwarded-Roles
            - name: RUNDECK_PREAUTH_REDIRECT_LOGOUT
              value: "true"
            - name: RUNDECK_PREAUTH_REDIRECT_URL
              value: /oauth2/logout
            - name: RUNDECK_PREAUTH_ENABLED
              value: "true"
```
Regards
