### ISSUE TITLE
job definition load does not preserve option value ordering

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#6364]
**Describe the bug**

When importing a job using the `rd jobs load` command, defined option values get sorted during the import process.

**My Rundeck detail**

* Rundeck version: 3.1.0
* Rundeck CLI version: 1.3.1
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: mysql

**To Reproduce**

1. Create a new job in RunDeck with a single option containing allowed values "E,D,C,B,A", inspecting the job shows the ordering for the option as defined:
   ![initial job](https://user-images.githubusercontent.com/1756536/88932397-ebf61100-d275-11ea-87d7-87652518d2be.png)
2. Export the job using `rd jobs list --project Sandbox --idlist 83efa98c-faa8-4ffc-b169-ecd9cad4fd05 --format yaml --file test.yaml`.  The resulting yaml for the option is in the defined order:
   ```yaml
     options:
     - enforced: true
       name: Ordering
       required: true
       value: C
       values:
       - E
       - D
       - C
       - B
       - A
       valuesListDelimiter: ','
   ```
3. Import the job using `rd jobs load --project Sandbox --format yaml --duplicate update --file test.yaml`, inspecting the job following import shows the ordering for the option is now alphabetic:
   ![post import](https://user-images.githubusercontent.com/1756536/88932697-560eb600-d276-11ea-8356-0704b6f4afae.png)

**Expected behavior**

After importing the job I expect the Allowed Values to have the order originally defined and correctly captured in the yaml file. I.e. E,D,C,B,A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox / Chrome
 - Version: N/A

**Additional context**

None
