### ISSUE TITLE
Rundeck login doesn't work from Chrome

### ISSUE THREAD

**Issue by manticora17** [rundeck/rundeck#6382]
When attempting to login to Rundeck from Chrome, it just hangs on the /user/login page. The error is:

```
Refused to send form data to '<rundeck_url>' because it violates the following Content Security Policy directive: "form-action 'self'".
```

**My Rundeck detail**

* Rundeck version: 3.3.1
* install type: war
* OS Name/version: ubuntu 18.04
* DB Type/version:  postgres 12

**To Reproduce**
1. Go to https://<rundeck_url>/user/login
2. Enter credentials
3. Watch the circle spin.
4. Open Developer Tools.
4. See error.

**Expected behavior**
Correctly working login like in Firefox or Safari.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 80.0.3987.149

**Comment by MegaDrive68k** [comment]
Confirmed.

On 3.3.1:

Chrome

![Screenshot_1](https://user-images.githubusercontent.com/51376003/90562252-e7839080-e16f-11ea-9897-9b2d78998e8a.png)

Firefox

![Screenshot_2](https://user-images.githubusercontent.com/51376003/90562262-ebafae00-e16f-11ea-9bef-b79b264c867c.png)

On 3.3.2:

Chrome

![Screenshot_3](https://user-images.githubusercontent.com/51376003/90562288-f23e2580-e16f-11ea-993a-c08335551a3e.png)

Firefox

![Screenshot_4](https://user-images.githubusercontent.com/51376003/90562311-f9fdca00-e16f-11ea-8643-a6c3f54f1340.png)

Maybe this cause some problems like https://github.com/rundeck/rundeck/issues/6344

Thanks for your feedback @manticora17!

**Comment by manticora17** [comment]
@MegaDrive68k our Rundeck is running in a k8s pod that has 2 containers: nginx and rundeck (used incubator helm chart to deploy - https://github.com/helm/charts/tree/master/incubator/rundeck)

**Comment by MegaDrive68k** [comment]
Hi @manticora17 

I tested a basic deployment using microk8s and works:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rudeckpro-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #for sticky sessions
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"

spec:
  rules:
  - host: hyperion
    http:
      paths:
      - backend:
          serviceName: rdeck
          servicePort: 8080
        path: /

---

apiVersion: v1
kind: Service
metadata:
  name: rdeck
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4440
  selector:
    app: rdeck
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdeck
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdeck
  template:
    metadata:
      labels:
        app: rdeck
    spec:
      containers:
      - name: rundeck
        image: rundeck/rundeck:3.3.1
        env:
        - name: RUNDECK_GRAILS_URL
          value: "http://hyperion"
        ports:
        - containerPort: 4440
     
```

It seems you're facing this: https://github.com/rundeck/rundeck/issues/5122

Hope it helps!
