### ISSUE TITLE
Node context variable node.tags returns null

### ISSUE THREAD

**Issue by doberg** [rundeck/rundeck#6387]
**Describe the bug**
Node context variable node.tags returns null when using a local command execution against a node. Other node context variables seem to work as expected when calling then in the same way in the script. For example just doing a simple `echo` command returns null for `${node.tags}` but returns the node name if you use `${node.name}`.

**My Rundeck detail**

* Rundeck version: 3.3.2
* install type: yum
* OS Name/version: centos7
* DB Type/version: mysql

**To Reproduce**
1. Go to a rundeck project with a node configured like so:
```yaml
lv-dmz-cattle01:
  hostname: lv-dmz-cattle01
  osArch: amd64
  osFamily: unix
  osName: Linux
  osVersion: 3.10.0-1127.8.2.el7.x86_64
  rancherHostId: 1h191
  rancherProjectId: 1a671
```

2. Create a job with the following definition:
```yaml
- defaultTab: nodes
  description: test
  executionEnabled: true
  loglevel: INFO
  name: Test
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: .*
  nodesSelectedByDefault: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: echo "${node.tags}"
      nodeStep: true
      type: localexec
    keepgoing: false
    strategy: node-first
 ```
3. View logs for job execution & see that NO output is generated for node context variable `${node.tags}`.
4. Create a different job with this context:

 ```yaml
- defaultTab: nodes
  description: test
  executionEnabled: true
  loglevel: INFO
  name: Test
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: .*
  nodesSelectedByDefault: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: echo "${node.name}"
      nodeStep: true
      type: localexec
    keepgoing: false
    strategy: node-first
```
5. View logs for job execution & see that output IS indeed generated for node context variable `${node.name}`.

**Expected behavior**
using ${node.tags} in a local command returns a comma separated list of node tags.

**Screenshots**
Step 2 Job:
<img width="1054" alt="Screen Shot 2020-08-19 at 5 45 34 PM" src="https://user-images.githubusercontent.com/22035735/90700734-d015d780-e243-11ea-9d00-7d69df72c819.png">

Step 3 output:
<img width="1239" alt="Screen Shot 2020-08-19 at 5 38 16 PM" src="https://user-images.githubusercontent.com/22035735/90700476-32220d00-e243-11ea-997a-01b9a2f58ebd.png">

Step 4 job:
<img width="1049" alt="Screen Shot 2020-08-19 at 5 45 15 PM" src="https://user-images.githubusercontent.com/22035735/90700761-e02db700-e243-11ea-90c1-5ba4e2b37fdd.png">

Step 5 output:
<img width="1261" alt="Screen Shot 2020-08-19 at 5 40 02 PM" src="https://user-images.githubusercontent.com/22035735/90700806-fcc9ef00-e243-11ea-8a4e-a3797f4487cb.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 84.0.4147.125

**Additional context**
The same problem also happens for ${node.*} or any other star globs.

***Docs referring to:***
https://docs.rundeck.com/docs/manual/job-workflows.html#context-variables

> Node context variables:
> 
> node.name: Name of the Node being executed on
> node.hostname: Hostname of the Node
> node.username: Username of the remote user
> node.description: Description of the node
> **node.tags: Comma-separated list of tags**
> node.os-\*: OS properties of the Node: name,version,arch,family
> node.\*: All Node attributes defined on the Node.
