### ISSUE TITLE
AD Authentication Error

### ISSUE THREAD

**Issue by rehanpeerzade** [rundeck/rundeck#6447]
AD Authentication Not getting established. ACL policies are created as per documentation. 
Error message says "DEBUG interceptors.SetUserInterceptor - Role source not enabled, bean preauthenticatedAttributeRoleSource"
The error logs also list all the groups the User is part of, which means AD authentication itself is getting established. But the login window keeps running, neither authenticates nor fail the user session. 

**My Rundeck detail**

* Rundeck version: rundeck-3.3
* install type: rpm
* OS Name/version: Oracle Linux 7.7
* DB Type/version: rundeck h2 db

**Expected behavior**
User should be allowed to login

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Browser: Chrome
 - Version: 84.0

**Comment by MegaDrive68k** [comment]
Hi @rehanpeerzade 

Can you share the full `service.log` content at the moment of log in using AD to take a look? (please hide or change any potentially sensitive information).

Regards!

**Comment by rehanpeerzade** [comment]
Hi Team,

Below is the logs which being when I hit the login button on rundeck page. 

[2020-09-17T05:49:32,174] INFO  jaas.JettyCachingLdapLoginModule - Login attempts: 6, Hits: 0, Ratio: 0%.
[2020-09-17T05:49:32,176] INFO  jaas.JettyCachingLdapLoginModule - Attempting authentication: CN=test 1,OU=Service Now Only,OU=Citrix - Domain Users,DC=xyz,DC=abc,DC=local
[2020-09-17T05:49:32,550] DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.authentication.jaas.JaasAuthenticationToken@692d886: Principal: test1; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@ffff6a82: RemoteIpAddress: 10.48.136.30; SessionId: node011ijbh8pbitnv1cm8oxyb4vwr55; Granted Authorities: Jaas Authority [rundeck_global_admins,rundeck_global_admins]
[2020-09-17T05:49:32,652] DEBUG interceptors.SetUserInterceptor - Empty role list from bean containerRoleSource for test1
[2020-09-17T05:49:32,652] DEBUG interceptors.SetUserInterceptor - Accepting user role list from bean containerPrincipalRoleSource for test1: [rundeck_global_admins]
[2020-09-17T05:49:32,652] DEBUG interceptors.SetUserInterceptor - Role source not enabled, bean preauthenticatedAttributeRoleSource

**Comment by fgutierrezz** [comment]
Hello,

Does it happen for all users?
Do u have roles configures and users assigned on the ad side?


Please provide us the ad config used on the rundeck side ( you can hide
Pass or ip address ))

Regards
Felipe

**Comment by rehanpeerzade** [comment]
Hi Felipe,

Yes, it's happening for all the users. 
Yes, Groups are configured in AD, and below is the jaas-activedirectory.conf

activedirectory {
com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
debug="false"
contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
providerUrl="ldap://<IP>:389"
authenticationMethod="simple"
bindDn="id@domain"
bindPassword="*******"
forceBindingLogin="true"
userBaseDn="OU=Service Now Only,OU=Citrix - Domain Users,DC=xyz,DC=abc,DC=local"
userRdnAttribute="sAMAccountName"
userIdAttribute="sAMAccountName"
userPasswordAttribute="unicodePwd"
userObjectClass="user"
roleBaseDn="DC=xyz,DC=abc,DC=local"
roleNameAttribute="cn"
roleMemberAttribute="member"
roleObjectClass="group"
cacheDurationMillis="300000"
reportStatistics="true"
nestedGroups="true";
};

Below is the admin.aclpolicy at /etc/rundeck/

description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: rundeck_global_admins

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: rundeck_global_admins

**Comment by rehanpeerzade** [comment]
Hi Team,

Do you see any mis configuration on the setup based no the config files I shared. Any other configs you suggest I should be checking on.

**Comment by JJinMaine** [comment]
Here's my AD admin group ACL:

```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: g-rundeck-admin

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: g-rundeck-admin
````

Here's my jaas conf:

```
activedirectory {
  com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
    debug="false"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldap://ldap.server:389"
    bindDn="CN=\"Rundeck Bind\",OU=AppIDs,OU=Resources,OU=Accounts,DC=domain,DC=com"
    bindPassword="password"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn="OU=Users,OU=Accounts,DC=domain,DC=com"
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="unicodePwd"
    userLastNameAttribute="sn"
    userFirstNameAttribute="givenName"
    userEmailAttribute="mail"
    userObjectClass="user"
    roleBaseDn="OU=Roles,DC=domain,DC=com"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="300000"
    reportStatistics="true"
    supplementalRoles="user"
    ignoreRoles="false"
    nestedGroups="true";
};
```

Just gotta make sure your AD group is correct in the **by: group** section of the ACL. 

Is your **rundeck_global_admins** group part of your Roles DN base?

Hope this helps!
