### ISSUE TITLE
Events ACL does not grant permissions (403 error)

### ISSUE THREAD

**Issue by juresaht2** [rundeck/rundeck#6459]
**Describe the bug**
Setting up a non-admin user with an ACL like:
```
    - equals:
        kind: event
      allow: [read] # allow reading activity logs
```
...does not give the user permission to access the activity logs. 

**My Rundeck detail**
* Rundeck version: 3.3.2
* install type: rpm
* OS Name/version: CentOS 8

**To Reproduce**
1. Set up project with ACL
```
for:
  resource:
    - equals:
        kind: job
      allow: [read, run, kill]
    - equals:
        kind: node
      allow: [read]
    - equals:
        kind: event
      allow: [read] # allow reading activity logs
  job:
    - allow: [read,run,kill]
  node:
    - allow: [read,run] # allow read/run for nodes 
description: "ad"
by:
  group: rundeck_group
```
2. Set up user with access to the project, without admin permissions (in global ACL), add to group, etc
3. Log in and see 403 error trying to access activity logs. Clicking the activity log explicitly, the user is informed that they do not have permission.

**Expected behavior**
I expected read permissions to the activity logs to be granted with this ACL.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 85

**Additional context**
I am using AD auth, but I do not believe this is relevant

**Comment by fgutierrezz** [comment]
Hello

Could you capture the "audit. Log" output while you reproduce the issue

Thanks
Felipe

**Comment by juresaht2** [comment]
Hello,

Find the rundeck.audit.log here:
https://pisarna.t-2.com/s/zHQZgNd6E2xzB4n

It's the log created from signing in with my user (jsah) visiting the Jobs page for project "Interno" where "An Error Occurred: Request failed with status code 403" is displayed, then visiting the Activity page directly, where "Not authorized to read Events in project Interno" is displayed. The group names correspond to the projects.

**Comment by arturmartins** [comment]
I'm also experiencing the same. Same version.

**Comment by arturmartins** [comment]
I have the following `Stored System ACL policy`:

```
description: Ateam, read-only access.
context:
  application: 'rundeck'
by:
  group: ['Ateam']
for:
  resource:
    - equals:
        kind: system
      allow: [read] 
    - equals:
        kind: system_acl
      allow: [read] 
  project:
    - match:
        name: '.*'
      allow: [read]

  storage:
    - allow: [read]
```

and the following project ACL Policy:

```
description: Project1 Policy 
by:
    group: ['Ateam']
for:
  resource:
    - allow: read
    - equals:
        kind: job
      allow: [read, view, run, kill]
    - equals:
        kind: node
      allow: [read,refresh]
    - equals:
        kind: event
      allow: [read]
  job:
    - allow: [run,view,read,kill]
  node:
    - allow: [read,run]
```

All the users of Ateam are able to see the events, but only if they are logged in rundeck at the time that I save the system policy. 

The problem happens when the user does the logout and login. After that, the user can't see any event again. The way I can restore the access is by opening the Stored System ACL policy, add a new blank line and save it.

**Comment by arturmartins** [comment]
ok, I solved the issue by deleting both policies and move them to a single file in /etc/rundeck/ateam.aclpolicy. All works now.

My setup is very simple: fresh rundeck install with only admin and apitoken policy. Looks like there is a bug in the ACL precedence logic?

**Comment by cesouza-br** [comment]
I'm also experiencing the same.

My Rundeck detail

Rundeck version: 3.3.4
install type: rpm
OS Name/version: CentOS 8

**Comment by MegaDrive68k** [comment]
I reproduced the issue in this way:

Using this System ACL (Gear Icon > Access Control):

```yaml
description: app level.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read] 
    - equals:
        kind: system_acl
      allow: [read] 
  project:
    - match:
        name: '.*'
      allow: [read]

  storage:
    - allow: [read]
by:
  group: user
```

And this inside the project (Project Settings > Access Control):

```yaml
description: project level.
for:
  resource:
    - equals:
        kind: job
      allow: [read, run, kill]
    - equals:
        kind: node
      allow: [read]
    - equals:
        kind: event
      allow: [read]
  job:
    - allow: [read,run,kill]
  node:
    - allow: [read,run] 
by:
  group: user
```

I obtain the 403 error:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/95617319-a017d300-0a41-11eb-8934-6a77e98200f2.png)

![Screenshot_2](https://user-images.githubusercontent.com/51376003/95617341-a443f080-0a41-11eb-9f31-e06e9a603531.png)

But using both ACL definitions in the same policy (Gear Icon > Access Control) works:

```yaml
description: project level.
context:
  project: '.*'
for:
  resource:
    - equals:
        kind: job
      allow: [read, run, kill]
    - equals:
        kind: node
      allow: [read]
    - equals:
        kind: event
      allow: [read]
  job:
    - allow: [read,run,kill]
  node:
    - allow: [read,run] 
by:
  group: user

---

description: app level.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read] 
    - equals:
        kind: system_acl
      allow: [read] 
  project:
    - match:
        name: '.*'
      allow: [read]

  storage:
    - allow: [read]
by:
  group: user
```

![Screenshot_3](https://user-images.githubusercontent.com/51376003/95617741-46fc6f00-0a42-11eb-8975-110c44fe3f39.png)

![Screenshot_4](https://user-images.githubusercontent.com/51376003/95617751-4c59b980-0a42-11eb-88aa-3751567332b6.png)
