### ISSUE TITLE
`dispatch` command node filtering broken

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#647]
Given a set of nodes tagged (shown below) the following command ....

```
  dispatch -p anvils -I tags=web
```

...returns an empty list.

resource list:

```
rundeck@rundeck ~]$ dispatch -v
192.168.50.2:
  tags: ''
  osFamily: unix
  username: rundeck
  osArch: amd64
  osVersion: 2.6.32-279.el6.x86_64
  description: Rundeck server node
  nodename: 192.168.50.2
  hostname: localhost
  osName: Linux
db1.anvils.com:
  osFamily: unix
  tags: anvils, db
  username: db1
  osArch: x86_64
  osVersion: 2.6.32-279.el6.x86_64
  description: A db server node.
  nodename: db1.anvils.com
  hostname: 192.168.50.2
  anvils-location: US-East
  anvils-customer: acme.com
  ssh-keypath: /var/lib/rundeck/.ssh/id_rsa
  osName: Linux
www1.anvils.com:
  osFamily: unix
  tags: anvils, www
  username: www1
  osArch: x86_64
  osVersion: 2.6.32-279.el6.x86_64
  description: A www server node.
  nodename: www1.anvils.com
  hostname: 192.168.50.2
  anvils-location: US-East
  anvils-customer: acme.com
  ssh-keypath: /var/lib/rundeck/.ssh/id_rsa
  osName: Linux
app2.anvils.com:
  osFamily: unix
  tags: anvils, app
  username: app2
  osArch: x86_64
  osVersion: 2.6.32-279.el6.x86_64
  description: A app server node.
  nodename: app2.anvils.com
  hostname: 192.168.50.2
  anvils-location: US-East
  anvils-customer: acme.com
  ssh-keypath: /var/lib/rundeck/.ssh/id_rsa
  osName: Linux
rundeck:
  osFamily: unix
  tags: ''
  username: rundeck
  osArch: amd64
  osVersion: 2.6.32-279.el6.x86_64
  description: Rundeck server node
  nodename: rundeck
  hostname: localhost
  osName: Linux
app1.anvils.com:
  osFamily: unix
  tags: anvils, app
  username: app1
  osArch: x86_64
  osVersion: 2.6.32-279.el6.x86_64
  description: A app server node.
  nodename: app1.anvils.com
  hostname: 192.168.50.2
  anvils-location: US-East
  anvils-customer: acme.com
  ssh-keypath: /var/lib/rundeck/.ssh/id_rsa
  osName: Linux
www2.anvils.com:
  osFamily: unix
  tags: anvils, www
  username: www2
  osArch: x86_64
  osVersion: 2.6.32-279.el6.x86_64
  description: A www server node.
  nodename: www2.anvils.com
  hostname: 192.168.50.2
  anvils-location: US-East
  anvils-customer: acme.com
  ssh-keypath: /var/lib/rundeck/.ssh/id_rsa
  osName: Linux
```
