### ISSUE TITLE
Docker container realm.properties and ssl.properties are missing if /home/rundeck/server/config is mounted as a volume

### ISSUE THREAD

**Issue by daviddever** [rundeck/rundeck#6471]
**Describe the bug**
if `/home/rundeck/server/config` is mounted as a volume, as recommended in the [README.MD](https://github.com/rundeck/rundeck/tree/master/docker/official) `realm.properties` and `ssl.properties` will not exist causing logging in with the default admin login to fail. 

If the config directory is not mounted as a volume the files do exist and logging in will work.

I was able to resolve this by starting the container without mounting the config folder and copying out the two missing config files and then stopping and removing the container and creating it again with the mounted volume for config with the files copied from inside the container.

In the logs when logging in with the `realm.properties` file missing, the logs will have an error about the file missing.

**My Rundeck detail**

* Rundeck version: 3.3.4-SNAPSHOT
* install type: Dockerhub container
* OS Name/version: Ubuntu 20.04 Docker version 19.03.12, build 48a66213fe

**To Reproduce**
1. Add rundeck container to `docker-compose.yaml`

```
  rundeck:
    image: rundeck/rundeck:SNAPSHOT
    container_name: rundeck
    environment:
      - RUNDECK_GRAILS_URL=http://<local ip>:4440
    volumes:
      -  ${USERDIR}/docker_files/rundeck/data:/home/rundeck/server/data
      -  ${USERDIR}/docker_files/rundeck/config:/home/rundeck/server/config
    ports:
      - "4440:4440"
    restart: unless-stopped
```

2. docker-compose up -d rundeck 
3. Try to login to rundeck site with default username and password
4. Site returns a bad login error

**Expected behavior**
The container would start with all of the config files (including `realm.properties` and `ssl.properties`  in the mounted config docker volume allowing you to login with the default admin credentials or at least update the documentation to include steps for getting the missing files.

Thanks!

**Comment by ltamaster** [comment]
I would say that a better approach is to mount the file instead of the full folder (because some of the files in that folder are built by the template system)

For example

```
  rundeck:
    image: rundeck/rundeck:SNAPSHOT
    container_name: rundeck
    environment:
      - RUNDECK_GRAILS_URL=http://<local ip>:4440
    volumes:
      -  ${USERDIR}/docker_files/rundeck/data:/home/rundeck/server/data
      -  ${USERDIR}/docker_files/rundeck/config/ream.properties:/home/rundeck/server/config/ream.properties
    ports:
      - "4440:4440"
    restart: unless-stopped
```
