### ISSUE TITLE
Error: Jobs Document was invalid for format yaml: org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck#6552]
**Describe the bug**

After upgrading to rundeck 3.3.4, jobs load from YAML fails with the following error:

```
Error: Jobs Document was invalid for format yaml: org.yaml.snakeyaml.error.YAMLException: Number of aliases for non-scalar nodes exceeds the specified max=50
```

**My Rundeck detail**

* Rundeck version: 3.3.4
* install type: rpm
* OS Name/version: RedHat 7.6
* DB Type/version:: mysql (mariadb)

**To Reproduce**

1. Create a YAML file with a job definiton containing something like:

```yaml
...
  options:
  - &oSystem
    name: System
    description: System Name
    required: false
    enforced: false
    valuesUrl: http://${globals.buildspec_server}/v1/systems
  - &oPLATFORM
    name: PLATFORM
    # Not required when calling this job e.g. from AutoDeploy
    # but other UI options rely on it
    required: false
    enforced: true
    valuesUrl: http://${globals.buildspec_server}/v2/platform/${option.System.value}
...
```

Use these options in 50+ places, as in:

```yaml
  options:
    - *oSystem
    - *oPLATFORM

... etc.
```

Load the YAML with `rd jobs load`

**Expected behavior**

YAML is parsed successfully.

**Additional context**

Worked fine since 2.10 (at least)
