### ISSUE TITLE
JOB-YAML spec - strategy values are wrong? (low prio)

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck#6561]
**Describe the bug**

The JOB-YAML spec says:

> strategy
"node-first" or "step-first". Determines the strategy for executing the sequence across a set of nodes. See the Rundeck User Manual for more info.

But if you load any job with:

```
strategy: step-first
```

You see errors in the service.log saying that `step-first` is not valid.

It behaves correctly (as if you'd specified `sequential`), but i think the docs need correcting.

**My Rundeck detail**

* Rundeck version: 2.10 -> 3.3.4
* install type: rpm
* OS Name/version: RedHat 7
* DB Type/version: mariadb

**To Reproduce**

```
- id: 192f7f9c-e22b-411d-ab55-4ec98b6042d4
  uuid: 192f7f9c-e22b-411d-ab55-4ec98b6042d4
  name: Test
  description: test
  scheduleEnabled: true
  scheduleEnabled: false
  project: XTP
  group:  Test
  loglevel: INFO
  sequence:
    keepgoing: false
    strategy: step-first
    commands:
      - script: echo Hello
```

Results in:

```
│[2020-10-14T17:17:13,124] ERROR plugins.RundeckPluginRegistry - Plugin step-first for service: WorkflowStrategy was not found
```

If you edit the job and save it, then download the job as YAML, you get:

```
- defaultTab: nodes
  description: test
  executionEnabled: true
  group: Test
  id: 4f590aaf-8154-4a19-b62a-2b6efd4ef092
  loglevel: INFO
  name: Test
  nodeFilterEditable: true
  options:
  - description: A test option
    name: TestOption
    required: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: echo Hello
    keepgoing: false
    strategy: sequential
  uuid: 4f590aaf-8154-4a19-b62a-2b6efd4ef092
```

**Expected behavior**

Either no error, or the doc is updated.

**Comment by GNSunny** [comment]
I agree with @puremourning that there is nowhere mentioned in the document, could someone update the doc's please also many of the links on rundeck site are going to 404 which is very distressing to follow along with the new/old versions.

when I change from 
```
  sequence:
    keepgoing: false
    strategy: step-first.   <<-------------
    commands:
      - ######
      - ######
```
to
```
  sequence:
    keepgoing: false
    strategy: sequential     <<-------------
    commands:
      - ######
      - ######
 ```   
then everything started working fine. nothing is mentioned in the changelog either.
