### ISSUE TITLE
Rundeck remote url query results in IllegalArgumentException after upgrade to 3.3.6

### ISSUE THREAD

**Issue by triqster** [rundeck/rundeck#6648]
**Describe the bug**
When upgrading from rundeck 3.0.22 to 3.3.6 my working job results in java a stacktrace with the following message:
```
java.lang.IllegalArgumentException: Invalid uri 'http://localhost:6000/dummy?filter=123(?:_JC1)|000(?:_JC1)': Invalid query
```
This worked fine before upgrading, when experimenting with the uri it seems to not like the regex part in uri argument. When i remove the part after the `|` it works. However this obviously is not what I'm after.

**My Rundeck detail**

* Rundeck version: 3.3.6
* install type: deb
* OS Name/version: Debian Stretch
* DB Type/version: default

**To Reproduce**
I've also created a test job that works on 3.0.22 and doesn't work on 3.3.6 see the attached files. 
[rundeck_test_job.txt](https://github.com/rundeck/rundeck/files/5622516/rundeck_test_job.txt)

Manual reproduction:
1. Create a new job
2. make sure it has a argument containing a regex statement as shown above
3. Open the job (run)
4. See the error "java.lang.IllegalArgumentException: Invalid uri <url> : Invalid query" on the screen or service logs

**Expected behavior**
No error's when getting json from a remote url with cascaded options in uri args containing regex.

**Screenshots**
![rundeck_test_job](https://user-images.githubusercontent.com/5626877/100739860-0a147f00-33d8-11eb-8f16-f94f6d65b1c9.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome and Vivaldi
 - Version 87.0 & 3.4

**Additional context**

Options to reproduce a job with:

```
  options:
  - enforced: true
    label: dummy_loc
    name: dummy_loc
    required: true
    values:
    - Amsterdam
    - Barcelona
    - Huston
    - London
  - description: dummy_number
    label: dummy_number
    name: dummy_number
    regex: ^[0-9]{3}$
    required: true
  - enforced: true
    label: testapicall
    name: testapicall
    required: true
    valuesUrl: http://jsonplaceholder.typicode.com/todos/1?filter=000(?:_123)|000(?:_LONDON1)
```

I've also tried this on version `Rundeck 3.1.6-20200210` but this also didn't work.
