### ISSUE TITLE
Upon post initial login AD group grant certain elements fail to provide access

### ISSUE THREAD

**Issue by eidmantas** [rundeck/rundeck#6699]
**Describe the bug**
When an user receives an AD Group, if he had previously tried to log in or logged in without that AD group, even if he sees that new AD group in his profile various 'modules' might not allow him relevant access.

**My Rundeck detail**

* Rundeck version: 3.3.4
* install type: dockerhub defaults
* DB Type/version: mssql

**To Reproduce**
1. Login to rundeck
2. can't see anything because you're missing an AD Group.
3. get ad group.
4. login again - can't see project. sometimes can't see jobs. direct URL to job always works. Profile always shows all ad groups properly.

**Expected behavior**
All various modules would have same behavior in handling AD Group caching (if that's the culprit)?
Whenever a new AD group is deleted/assigned all panels/access should be aligned.

**Comment by MegaDrive68k** [comment]
Hi @eidmantas 

I'm trying to reproduce the issue. To discard some ACL issue, the permissions after a third login back to defaults on that user? (if logout and login again after seeing the issue).

Regards.

**Comment by eidmantas** [comment]
Hi @MegaDrive68k  sadly I do not have the capability to remove access rights but only give atm. 

What we basically do in our use case:
1) New user logins to rundeck - can not see anything as he forgot to get the right AD group.
2) Gets the AD group and re-logs.
3) Is able to access the dashboard page and go to his profile, but for example doesn't see projects.
Jobs page also is not opening by direct link from atop of my head (need to re-test)

-If I give that user a direct link to a  job/task in a project its fine and is able to see it.
-if I redeploy rundeck (in k8s) - it's fine.
-If user goes to his profile he can see the required AD group as well.

**Comment by MegaDrive68k** [comment]
Hi @eidmantas 

I reproduced your issue on Rundeck 3.3.4:

Using the following ACL for a specific AD group:

```yaml
description: Rules at Project context.
context:
  project: (ProjectONE)

for:
  resource:
    - equals:
        kind: job
      allow: [run]
    - equals:
        kind: node
      allow: [read,update,refresh]

    - equals:
        kind: event
      allow: [read,create]

  adhoc:
    - allow: [read,run,kill]
  job:
    - allow: [read,run,kill]
  node:
    - allow: [read,run]
by:
  group: ad_role
 
---
description: Rules at Rundeck application Project
context:
  application: 'rundeck'
for:
  project:
    - match:
        name: (ProjectONE)
      allow: [read]
  storage:
     - allow: [read]
by:
  group: ad_role
```

If some user gets out of "ad_role" and log in again, the user still seeing the project:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/103544155-66a70600-4e7e-11eb-8c01-24358e3ab80e.png)

![Screenshot_1](https://user-images.githubusercontent.com/51376003/103544162-69a1f680-4e7e-11eb-8870-a749e66a049f.png)

If you restart the Rundeck instance works as expected:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/103544243-8a6a4c00-4e7e-11eb-9ab7-8eb4a59cb98e.png)

So, I tested on 3.3.7 too this doesn't happen, can you test using 3.3.7 docker image?

Regards!
