### ISSUE TITLE
Notifications payload format are not imported properly by the API and the UI

### ISSUE THREAD

**Issue by aylham** [rundeck/rundeck#6711]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.3.7.20201208
* install type: rpm
* OS Name/version: centos7
* DB Type/version: postgres10

**Expected Behavior**

When importing a job definition in YAML the field `notification/format` isn't  properly read and result in a `null` in the `payload format` field after the import.

```
  notification:
    onfailure:
      format: json
      urls: http://rundeck-server:4440/api/36/webhook/TOKEN#webhook
```

**How to Reproduce**

Import the following job :

```
- defaultTab: nodes
  description: Job
  executionEnabled: true
  id: 1fadb795-b378-4e3d-8b46-4b344eadc111
  loglevel: INFO
  name: MyJob
  nodeFilterEditable: false
  notification:
    onfailure:
      format: json
      urls: http://rundeck-server:4440/api/36/webhook/TOKEN#webhook
    onsuccess:
      format: json
      urls: http://rundeck-server:4440/api/36/webhook/TOKEN#webhook
  notifyAvgDurationThreshold: null
  options:
  - description: Numbers of days alarms are conserved
    name: alarms
    regex: \d+
    value: '30'
  - description: ' Numbers of days pb are conserved'
    name: pb
    regex: \d+
    value: '30'
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - args: --alarms ${option.alarms} --pbehaviors ${option.pbehaviors} -f
      scriptfile: /var/lib/rundeck/libext/myscript
    keepgoing: false
    strategy: node-first
  uuid: 1fadb795-b378-4e3d-8b46-4b344eadc111
```

The field `payload format` will not be set as expected by the definition.

**Comment by samyscoub** [comment]
:+1:

**Comment by MegaDrive68k** [comment]
Confirmed and happening on 3.3.8 too.

And saving the job again,  produces a "null" payload format on the notification.

Thanks for your feedback @samyscoub!

**Comment by aylham** [comment]
Hello,
Does someone has any news on this problem?

**Comment by spaced0gg** [comment]
Seeing this is 3.3.8 as well.

**My Rundeck detail**

    Rundeck version: 3.3.8
    install type: rpm
    OS Name/version: RHEL6
    DB Type/version: mysql

This is quite a significant bug due to the way we deploy multiple jobs to multiple rundeck servers using install scripts.  We now have to manually edit the imported jobs in each project on each server.

Is there any ETA on when this will be fixed?

**Comment by antares667367** [comment]
Same here using the API via python . Rundeck v. Community 3.4.1
The payload remains set to null after import

**Comment by spaced0gg** [comment]
This was fixed for us in rundeck 3.4.8.

However, I am testing rundeck 4.6.0 and this issue is now re-occuring:

Rundeck version: 4.6.0
install type: rpm
OS Name/version: RHEL7
DB Type/version: mariadb

**How to reproduce**

Import the following job:

```
- defaultTab: nodes
  description: Test job import
  executionEnabled: true
  group: ZDEV/MMCF
  id: b5f8eff2-1f79-47bf-b757-dcc31ac5d556
  loglevel: INFO
  name: TestJobImport
  nodeFilterEditable: false
  notification:
    onsuccess:
      format: json
      httpMethod: post
      urls: https://webhook.site/3762b3e9-ce0e-492c-92b6-421b7f345f93
  notifyAvgDurationThreshold: null
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo "HELLO"
    keepgoing: false
    strategy: node-first
  uuid: b5f8eff2-1f79-47bf-b757-dcc31ac5d556
```

On export in 3.4.8, format and httpMethod are correct:

```
  notification:
    onsuccess:
      format: json
      httpMethod: post
      urls: https://webhook.site/3762b3e9-ce0e-492c-92b6-421b7f345f93
```

On export in 4.6.0, format and httpMethod are both set to null:
```
  notification:
    onsuccess:
      format: null
      httpMethod: null
      urls: https://webhook.site/3762b3e9-ce0e-492c-92b6-421b7f345f93
```

The same test with xml job definitions works for both versions.
