### ISSUE TITLE
Rundeck 2.0.1 - Can not hide 'Command' / adhoc section

### ISSUE THREAD

**Issue by mumblez** [rundeck/rundeck#672]
Rundeck 2.0.1
CentOS 6.5
Java 7
Rundeck RPM install

Trying various methods to block the 'commands' section from an LDAP group, the group are successfully blocked from running any commands but ideally would like to have the whole 'commands' area blocked.

Here's the policy I'm testing with:

``` yml
description: Senior Devs Access
description: Developer Project Policy
context:
  project: 'Everything' # The farm
for:
  resource:
    - equals:
        kind: job
      allow: [read,run]
    - equals:
        kind: node
      allow: [read,refresh]
    - equals:
        kind: event
      allow: [read] # allow read events
  adhoc:
    - deny: '*' # deny running/killing adhoc jobs
  job:
    - match:
        group: 'qa' 
      allow: [read,run,kill]
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: [senior dev]

---
description: Senior Devs Access
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      deny: [create]
    - equals:
        kind: system
      deny: [read]
    - equals:
        kind: user
      deny: [admin]
    - equals:
        kind: adhoc
      deny: '*'
  project:
    - match:
        name: 'Everything'
      allow: 'read'
by:
  group: [senior dev]
```
