### ISSUE TITLE
Suppress job failure notification from log output

### ISSUE THREAD

**Issue by gaddman** [rundeck/rundeck#6722]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux 7
* DB Type/version: mariadb 5.5.64

**Summary**
When a job fails a summary message is added to the end of the log output. This is not always desirable, can we suppress it?

**Example**
Some of our jobs run a bunch of health checks and will output some message indicating the health of a system. Each step is configured to exit with a failure if any problems are detected, in order to trigger an email notification. The (custom) email template includes the list of failed nodes and the log. With the current setup this log includes the extra summary error message - redundant information since the email template already has the failed nodes included. It adds visual clutter and detracts from quickly identifying problems.

**Proposed Resolution**
A couple of ideas:
- Keep job level messages out of the log (configurable for those that want it?)
- Allow the quiet output log filter to suppress these messages (a global log filter doesn't affect these messages)

**How to Reproduce**
```yaml
- defaultTab: output
  description: How can I suppress the final line of the log output when a job errors?
  executionEnabled: true
  group: testing
  id: d4b8833a-4545-4cc1-8173-c9169822e9d4
  loglevel: INFO
  name: Hide summary error message in log
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: failedcommand
      description: failed step
      nodeStep: true
      type: localexec
    - configuration:
        command: echo "succesful command"
      description: successful step
      nodeStep: true
      type: localexec
    - configuration:
        command: echo "---------------------------------------------------------"
      description: Hide error message after this
      nodeStep: true
      type: localexec
    keepgoing: true
    strategy: node-first
  uuid: d4b8833a-4545-4cc1-8173-c9169822e9d4
```
