### ISSUE TITLE
Rundeck API Import Day-of-week Day-of-month do not honor provided values

### ISSUE THREAD

**Issue by schillingderek** [rundeck/rundeck#6743]
**Describe the bug**
When importing jobs into Rundeck API, the client does not accept specified values in the Day-of-week or Day-of-month fields. It either fails to import, or imports with incorrect values.

**My Rundeck detail**

* Rundeck version: 3.1.0 SNAPSHOT
* install type: docker
* DB Type/version: mysql

**To Reproduce**
E.g. - provided YAML for job definition:
``` 
schedule:
    month: '*'
    time:
      seconds: 0
      hour: 13-23
      minute: 13/20
    weekday:
      day: MON-FRI
    dayofmonth:
      day: '?'
    year: '*'
```
results in an error:
```Crontab string format was invalid: 0 13/20 13-23 ? * ? *
Invalid Notification definition: onfailure notification: Crontab string format was invalid: 0 13/20 13-23 ? * ? *
Validation errors: Crontab string format was invalid: 0 13/20 13-23 ? * ? *; Invalid Notification definition: onfailure notification: Crontab string format was invalid: 0 13/20 13-23 ? * ? *
```

Modifying the schedule to 
``` 
schedule:
    month: '*'
    time:
      seconds: 0
      hour: 13-23
      minute: 13/20
    weekday:
      day: MON-FRI
    dayofmonth:
      day: '*'
    year: '*'
```
schedules the job, but with the schedule as:
``` 
schedule:
    month: '*'
    time:
      seconds: 0
      hour: 13-23
      minute: 13/20
    weekday:
      day: '?'
    dayofmonth:
      day: '*'
    year: '*'
```

Finally - replacing 
```
    dayofmonth:
      day: '*'
```
with:
```
    dayofmonth: null
```
DOES work - but seems non-intuitive

**Expected behavior**
When using the first provided YAML above, I'd expect a job to be scheduled with:
DayOfWeek = Mon-Fri
DayOfMonth = ?

**Screenshots**

**Desktop (please complete the following information):**
Not applicable

**Additional context**
