### ISSUE TITLE
Resource Node plugin script not reading Key Storage path content

### ISSUE THREAD

**Issue by igalvit** [rundeck/rundeck#6775]
**Describe the bug**
 
I'm trying to use the Key Storage to read a password from a Resource Node Plugin made in Bash. I add the Node Source and select a key from the Key Storage. When I go to Node section and display the nodes, in the description of the node I should see the password, but instead of that, I see the path I selected before.

**Note:** For testing purposes I have written this simplified Bash version of the real plugin. The real one I'm writing connects to a OTRS server API and uses the password to login. I have confirm that the problem is exactly the same logging data to a file.

The plugin.yaml content:

```
name: OTRS CMDB Test Model Source
version: 1.0
rundeckPluginVersion: 1.2
author: me
date: 04/02/2021
providers:
    - name: otrs_cmdb_test
      service: ResourceModelSource
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: nodes.sh
      resource-format: resourceyaml
      config:
        - type: String
          name: cmdb_pass_path
          title: OTRS password path
          description: Password to login to CMDB API.
          scope: Instance
          required: true
          renderingOptions:
            selectionAccessor: STORAGE_PATH
            storage-path-root: "keys"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            groupName: CMDB Login
```

The nodes.sh content:
```
#!/bin/bash
echo "oneServer:
  description: $RD_CONFIG_CMDB_PASS_PATH
  hostname: oneServer.domain.tld
  nodename: oneServer.domain.tld
  username: root
  osArch: x86_64
  osFamily: Linux
  osName: CentOS
  osVersion: 7.4.1708
  tags: [ 'test']"
exit $?
```

**My Rundeck detail**

* Rundeck version: 3.3.9
* install type: war
* OS Name/version: Windows 10 2004
* DB Type/version: none

**To Reproduce**
1. Configure a new Node Source.
2. Inside the Node Source, select a key path
3. Go to nodes.
4. In the description of the node I see the Key Storage Path, no the password.

**Expected behavior**
Read the password from Key Storage and display in the description attribute.

**Screenshots**

![image1](https://user-images.githubusercontent.com/10863948/107485584-dabe8300-6b7b-11eb-85d7-f1554afb03ba.png)

![image2](https://user-images.githubusercontent.com/10863948/107485593-deeaa080-6b7b-11eb-882b-7da7e6edcf48.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser Firefox
 - Version 85.0.1

**Additional context**
