### ISSUE TITLE
Global variables defined in job not expanded in email notification

### ISSUE THREAD

**Issue by gaddman** [rundeck/rundeck#6810]
**Describe the bug**
Global variables created inside a job are not expanded in the email notification.

**My Rundeck detail**

* Rundeck version: 3.3.9
* install type: rpm
* OS Name/version: RHEL 7
* DB Type/version: mariadb (mysql)

**To Reproduce**
1. Create a job with a _Global Variable_ step
2. Include the global variable in the subject of an email notification

Sample job:
```yaml
- defaultTab: output
  description: notification with data variable
  executionEnabled: true
  id: 0e4a150b-71a3-42e3-b501-d5a535a04822
  loglevel: INFO
  name: email noti with data
  nodeFilterEditable: false
  notification:
    onsuccess:
      email:
        attachType: file
        recipients: ${job.user.email}
        subject: job.name ${job.name} execution.id ${execution.id} globals.var1 ${globals.var1}
  notifyAvgDurationThreshold: null
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        export: var1
        group: globals
        value: '1234'
      description: Create global variable
      nodeStep: false
      type: export-var
    - configuration:
        command: echo ${globals.var1}
      description: Check global variable
      nodeStep: true
      type: localexec
    keepgoing: false
    strategy: node-first
  uuid: 0e4a150b-71a3-42e3-b501-d5a535a04822
```

**Expected behavior**
The email subject line should include the expanded global variable.

**Screenshots**
![image](https://user-images.githubusercontent.com/1311209/108907102-8d1b3d80-7686-11eb-8b8b-cdd02c08d173.png)

**Desktop:**
 - OS: Windows 10
 - Browser Firefox
 - Version 85

**Additional context**
A global variable defined in the `framework.properties` file will be expanded OK. Any variable defined in the job won't be expanded, eg through the _Global Variable_ step or the _Key Value Data_ log filter.
