### ISSUE TITLE
RUNDECK - Cannot allocate memory

### ISSUE THREAD

**Issue by matheuscaselani** [rundeck/rundeck#6868]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: **3.2.4**
* install type: (rpm,deb,war,launcher?) **war**
* OS Name/version: **Debian Stretch**
* DB Type/version: mysql? postgres? h2? **MYSQL 5.7**

**Expected Behavior**
Web Service UP

**How to Reproduce**
Start RUNDECK container and wait for it ... No need to login into project page or plugin or anything at all

After quite sometime ( up to 1 hour mostly ) i got the following error : 

```
{"log":"OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000535680000, 2086141952, 0) failed; error='Cannot allocate memory' (errno=12)\n","stream":"stderr","time":"2021-03-12T15:11:09.2658724Z"}
{"log":"#  Out of Memory Error (os_linux.cpp:2756), pid=6, tid=0x00007fe85ebfb700\n","stream":"stdout","time":"2021-03-12T15:11:09.272281Z"}
{"log":"Event: 2403.512 Thread 0x00007fe8e02d1800 36214       3       rundeck.services.logging.ExecutionLogWriter::logError (28 bytes)\n","stream":"stdout","time":"2021-03-12T15:11:09.2983628Z"}
{"log":"Event: 2403.535 Thread 0x00007fe8e02d1800 36215       3       com.dtolabs.rundeck.core.logging.LogUtil::logError (6 bytes)\n","stream":"stdout","time":"2021-03-12T15:11:09.29842Z"}
{"log":"7fe85c00e000-7fe85c010000 r--s 00002000 fc:00 1309312                    /home/rundeck/libext/cache/rundeck-object-store-plugin-3.2.4-20200318/20200421204333000-10/lib/error_prone_annotations-2.1.3.jar\n","stream":"stdout","time":"2021-03-12T15:11:09.3326715Z"}
```

**Comment by MegaDrive68k** [comment]
Hi @matheuscaselani 

Which Java version are you using (you can check it doing `java -version`)? How do you launch the WAR file? Also, take a look at the [minimal requirements](https://docs.rundeck.com/docs/administration/install/system-requirements.html#system-requirements) to launch Rundeck.

Regards!

**Comment by matheuscaselani** [comment]
Hello @MegaDrive68k: 

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

war is lauched when container start using an entry point file ( docker-lib/entry.sh )

**Comment by MegaDrive68k** [comment]
Hi @matheuscaselani 

The issue is happening on the [official docker image](https://hub.docker.com/r/rundeck/rundeck)?  how do you launch the container? 

Regards.

**Comment by matheuscaselani** [comment]
> Hi @matheuscaselani
> 
> The issue is happening on the [official docker image](https://hub.docker.com/r/rundeck/rundeck)? how do you launch the container?
> 
> Regards.

Yeah, official image! Container is launched using docker compose file.

**Comment by MegaDrive68k** [comment]
Could you share a reproducible example docker-compose file?

I tested with the following one and works as expected:

```yaml
version: '3'

services:
    rundeck:
        image: ${RUNDECK_IMAGE:-rundeck/rundeck:3.2.4}
        environment:
            RUNDECK_GRAILS_URL: http://localhost:4440
            RUNDECK_DATABASE_DRIVER: com.mysql.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
            RUNDECK_SERVER_ADDRESS: 0.0.0.0
        ports:
          - 4440:4440
    mysql:
        container_name: mysql
        image: mysql:5.7
        expose:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
```

Thanks!!
