### ISSUE TITLE
Unable to dulicate job after upgrade

### ISSUE THREAD

**Issue by morph027** [rundeck/rundeck#6896]
**Describe the bug**

Unable to dulicate job after upgrade from 3.0.13 to 3.3.9 while ACL still allows creating jobs.

**My Rundeck detail**

* Rundeck version: 3.3.9
* install type: deb
* OS Name/version: Ubuntu 18.04
* DB Type/version: mysql

**To Reproduce**
* have a project with read only jobs
* have another project with the permission to create jobs
* try to use the "Duplicate this Job to other Project" -> not there

**Expected behavior**
* find "Duplicate this Job to other Project" inside the context menu

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chromium, Firefox
 - Version: latest

** Additional information

Exporting the job definition as file from the readonly projects and uploading it to the project with create permissions does work.

**Comment by MegaDrive68k** [comment]
Reproduced.

1. Create two projects, ProjectONE and ProjectTWO.
2. Create a job on ProjectONE.
3. Add the following ACL (it's for "user" user):

```yaml
description: Description
context:
  application: rundeck
description: "desc"
for:
  project:
    - match:
        name: Project.*
      allow: [read, run]
  system:
    - match:
        name: '.*'
      allow: [read, run]
by:
  username: user

---
description: Project ONE ACL
context:
  project: 'ProjectONE'
for:
  resource:
    - equals:
        kind: 'node'
      allow: [read,refresh,run]
    - equals:
        kind: 'job'
      allow: [read,run, view,toggle_schedule]
    - equals:
        kind: 'event'
      allow: [read, run, view]
  job:
    - match:
      allow: [read,run,view,toggle_schedule]
  adhoc:
    - allow: '*'
  node:
    - equals:
      allow: '*'
by:
  username: user
---
description: Project TWO ACL
context:
  project: 'ProjectTWO'
for:
  resource:
    - equals:
        kind: 'node'
      allow: [read,refresh,run]
    - equals:
        kind: 'job'
      allow: [read,run, view,create]
    - equals:
        kind: 'event'
      allow: [read, run, view]
  job:
    - match:
      allow: [read,run,view,toggle_schedule,create]
  adhoc:
    - allow: '*'
  node:
    - equals:
      allow: '*'
by:
  username: user
```

On Rundeck 3.0.12 (it's possible to copy the job to another project):

![1](https://user-images.githubusercontent.com/51376003/111679664-2a8a0d00-8800-11eb-8995-5a0a0c1cc0d4.png)

On Rundeck 3.3.10 (the option dissapears):

![2](https://user-images.githubusercontent.com/51376003/111679739-38d82900-8800-11eb-87ab-756f05d1bfca.png)

On Rundeck 3.4.0-SNAPSHOT (same behavior):

![3](https://user-images.githubusercontent.com/51376003/111679807-4c838f80-8800-11eb-9ae8-18d9d192d44a.png)

Thanks for your feedback @morph027!
