### ISSUE TITLE
When executing job via API options using "Select All Values by Default" don't work

### ISSUE THREAD

**Issue by nublaii** [rundeck/rundeck#6972]
**Describe the bug**
I have a simple 2-option job: I select a value from **Option A (App)** and that triggers the cascading remote options loading on **Option B (Servers)**.

**Option B (Servers)** is a Remote URL list loading a JSON. By default all values are enabled using **"selected": "true"** on the JSON that is loaded for **Option B (Servers)**. I also have **Multi-valued = Yes** and **Select All Values by Default** on **Option B (Servers)** config:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/1773409/114308838-7705f700-9ae5-11eb-8d39-d564295cf721.png">

If I run it via web it works fine and all values for **Option B (Servers)** are selected and used, but if I run it via API call only the first value for **Option B (Servers)** is selected.

**My Rundeck detail**

* Rundeck version: 3.3.10.20210301-1
* install type: deb
* OS Name/version: Ubuntu 18.04.5 LTS
* DB Type/version: mysql

**To Reproduce**
1. First import the job:
```
- defaultTab: output
  description: ''
  executionEnabled: true
  group: ZZ Tests/Windows
  id: dcd01789-45c2-438d-b124-24e3005e4b5a
  loglevel: INFO
  name: Restart Server - bug
  nodeFilterEditable: false
  options:
  - enforced: true
    name: App
    required: true
    values:
    - Alpha
    - Beta
    valuesListDelimiter: ','
  - delimiter: ' '
    enforced: true
    label: Servers
    multivalueAllSelected: true
    multivalued: true
    name: Servers
    required: true
    valuesUrl: file:/tmp/list.json
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/bash

        echo App = "@option.App@"
        echo Servers = "@option.Servers@"
    keepgoing: false
    strategy: parallel
  uuid: dcd01789-45c2-438d-b124-24e3005e4b5a

```
1. Second, create a file /tmp/list.json with this content:
```
[
    {
        "name": "Gamma",
        "selected": "true",
        "value": "Gamma"
    },
    {
        "name": "Delta",
        "selected": "true",
        "value": "Delta"
    }
]
```

If you execute it via web the output will be:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/1773409/114308202-50df5780-9ae3-11eb-897e-7a71dc802553.png">

If you execute it via api the output will be:

`curl http://whatevra.wanabi/api/19/job/dcd01789-45c2-438d-b124-24e3005e4b5a/run -H "X-Rundeck-Auth-Token: YoUrWoNdErFuLtOkEn2021" -F "option.Pool=Alpha"`

```
<executions count='1'>
  <execution id='8622' href='http://whatevra.wanabi/api/38/execution/8622' permalink='http://whatevra.wanabi/project/Testing/execution/show/8622' status='running' project='Testing'>
    <user>admin</user>
    <date-started unixtime='1618151743399'>2021-04-11T14:35:43Z</date-started>
    <job id='dcd01789-45c2-438d-b124-24e3005e4b5a' averageDuration='1190' href='http://whatevra.wanabi/api/38/job/dcd01789-45c2-438d-b124-24e3005e4b5a' permalink='http://whatevra.wanabi/project/Testing/job/show/dcd01789-45c2-438d-b124-24e3005e4b5a'>
      <name>Restart Server - bug</name>
      <group>ZZ Tests/Windows</group>
      <project>Testing</project>
      <description></description>
      <options>
        <option name='Pool' value='Alpha' />
        <option name='Servers' value='Gamma' />
      </options>
    </job>
    <description>#!/bin/bash

echo Pool = "@option.Pool@"
echo Servers = "@option.Servers@"</description>
    <argstring>-Pool Alpha -Servers Gamma</argstring>
    <serverUUID>60e0bdf5-05ad-45cd-b5ea-6bdf986ea300</serverUUID>
  </execution>
</executions>
```

**Expected behavior**
I would expect to have all values from **Option B (Servers)** enabled when I execute the job via API, not only because of the **"selected": "true"** but because the config on the option states **Select All Values by Default**.
