### ISSUE TITLE
Rundeck API not recognize JSON content on Rundeck option

### ISSUE THREAD

**Issue by tiendungitd** [rundeck/rundeck#7013]
**Describe the bug**
I have the simple job definition as below
```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='myjson' />
      </options>
    </context>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>2f96d810-010f-44c4-a7ee-e1f67d9c4r60</id>
    <loglevel>INFO</loglevel>
    <name>json_test</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo ${option.myjson}</exec>
      </command>
    </sequence>
    <uuid>2f96d810-010f-44c4-a7ee-e1f67d9c4r60</uuid>
  </job>
</joblist>
```
I want to input the JSON content as text plain on myjson option. With rundeck UI, the option got a correct value when I run a job
![image](https://user-images.githubusercontent.com/21011388/116392576-ca4ca900-a84a-11eb-9668-d78665c79823.png)
But if I tried with Rundeck API using curl or Postman, the value of myjson option was sent to rundeck is empty, please see the command and output below
```
curl -D - -X "POST" -H "Accept: application/json"     -H "Content-Type: application/json"     -H "X-Rundeck-Auth-Token: mytoken"     -d '{
         "options" :  {"myjson": {"name": "john1","age": "321","city": "ny"}
         }
     }' http://localhost:4440/api/21/job/[Job_ID]/executions
HTTP/1.1 200 OK
Date: Wed, 28 Apr 2021 10:55:48 GMT
X-Frame-Options: deny
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none' ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; style-src 'self' 'unsafe-inline' ; img-src * ; font-src 'self' data: ; connect-src 'self' https://api.rundeck.com ; form-action 'self' ;
X-Application-Context: application:production:4440
Set-Cookie: JSESSIONID=node01nkalkv26y66r1slogqeuv5oi8216.node0;Path=/;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked

{"id":1390,"href":"localhost:4440/api/30/execution/1390","permalink":"localhost:4440/project/cloud/execution/show/1390","status":"running","project":"cloud","executionType":"user","user":"admin","date-started":{"unixtime":1619607348000,"date":"2021-04-28T10:55:48Z"},"job":{"id":"[Job_id]","averageDuration":1205,"name":"json_test","group":"","project":"cloud","description":"","href":"localhost:4440/api/30/job/[Job_id]","permalink":"localhost:4440/project/cloud/job/show/[Job_id]"},"description":"echo ${option.myjson}","argstring":null}
```
![image](https://user-images.githubusercontent.com/21011388/116393599-0f250f80-a84c-11eb-8d2a-19b939139be1.png)

**My Rundeck detail**

* Rundeck version: 3.0.20
* install type: docker

**Expected behavior**
Pass the JSON content as text plain on your option via Rundeck API

**Comment by MegaDrive68k** [comment]
Hi @tiendungitd,

Could you try in the following way?

```bash
curl --location --request POST 'http://localhost:4440/api/38/job/2f96d810-010f-44c4-a7ee-e1f67d9c4r60/run?authtoken=JVJ39jNJwhabDjUORVp3ZPWeykyNJecc' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=node0jfrr0y6aav2s1tejq8w7j5bnm36.node0' \
--data-raw '{
 "options": {
  "myjson": '\''{"name": "john1","age": "321","city": "ny"}'\''
 }
}'
```

This is my job definition, basically the same with extra "jq" call to "beautify" the execution output:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 2f96d810-010f-44c4-a7ee-e1f67d9c4r60
  loglevel: INFO
  name: json_test
  nodeFilterEditable: false
  options:
  - name: myjson
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: ' echo ${option.myjson} | jq'
    keepgoing: false
    strategy: node-first
  uuid: 2f96d810-010f-44c4-a7ee-e1f67d9c4r60

```

Result:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/116464089-87cea080-a839-11eb-96ce-0aa0d48ad946.png)
