### ISSUE TITLE
Users can't see custom commands in the activity of a project

### ISSUE THREAD

**Issue by styleart** [rundeck/rundeck#7035]
**Is your feature request related to a problem? Please describe.**
Currently, users with limited roles are limited to see specific commands in the activity of a project which were run as a custom command (basically, not as a job). Jobs activities are visible. So, the activity page of a project just hides custom commands.

**Describe the solution you'd like**
Users with access to activity of a project should see all the activity, not just the job logs.

**Additional context**
Maybe we did configure something wrong? Below is our user.aclpolicy, the event access is granted.

```
description: Users, limited access
context:
  project: ".*"
for:
  resource:
    - equals:
        kind: node
      allow: '*'
    - equals:
        kind: event
      allow: [read,create]
  job:
    - allow: [read,run,runAs,kill,killAs]
  node:
    - allow: [read,run]
by:
  group: 'devs'

---

description: User are allowed to access projects.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [read]
    - equals:
        kind: system
      allow: [read]
  project:
    - match:
        name: ".*"
      allow: [read]
by:
  group: 'devs'
```

Thanks in advance for any input!
