### ISSUE TITLE
Job step "Not Started" when running node step against multiple nodes

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#7053]
**Describe the bug**

I have a top level parent job that makes use of some common jobs using node steps in the workflow.

The top level job is configured to run on localhost.  The node step referenced in the top level job is configured to override the Node Filter - This has the result that the common job is run against multiple nodes.

I've found that on occasion the common job will result in a step with the status "Not Started" - see the image below for example:

![image](https://user-images.githubusercontent.com/1756536/118150801-dd46a800-b40a-11eb-97c2-c19cc1500c67.png)

This seemingly happens at random.  Looking back over old issues I found https://github.com/rundeck/rundeck/issues/3443 which seems very similar.  I noticed that the conditions under which my problem occurs seems to match - with the job called by the node step configured with a "Node First" workflow strategy and a threadcount > 1 - so I decided to switch to a "Sequential" workflow strategy on the called jobs and the problem has gone away.

Is there a problem with the "Node First" workflow strategy at play here?

**My Rundeck detail**

* Rundeck version: 3.3.11
* install type: rpm
* OS Name/version: CentOS7
* DB Type/version: mysql 5.7.30

**To Reproduce**

See job definition in additional context section.

**Expected behavior**

All job steps to execute on all nodes that are identified by the Node Filter for the job.

**Desktop (please complete the following information):**
 - OS: Ubuntu-Budgie 21.04
 - Browser: Firefox
 - Version: 88.0.1

**Additional context**

Top-level job definition:

```yaml
- defaultTab: nodes
  description: Deploys CMS Content (Assets and Config)
  executionEnabled: true
  group: library
  id: 763cd15f-54ef-4610-a6c2-3e5d22baf9af
  loglevel: INFO
  multipleExecutions: true
  name: Deploy - CMS Content v2
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: true
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '10'
    filter: 'name: localhost'
  nodesSelectedByDefault: true
  options:
  - description: The version of the deployment scripts to be used during deployment
    enforced: true
    name: package.version
    required: true
    valuesUrl: http://localhost/rd-option-provider/N3MavenPackages?repository=releases&group=com.dummy.cms&id=${option.package.name.value}&type=zip&limit=10
  - description: The environment to deploy to
    enforced: true
    name: Environment
    required: true
    value: dev2
    values:
    - beta
    - dev-stable
    - dev2
    - prod
    - promo
    - stg
    valuesListDelimiter: ','
  - enforced: true
    name: SubEnv
    required: true
    value: N/A
    valuesUrl: http://localhost/rd-option-provider/SubEnvs?environment=${option.Environment.value}
  - description: The package name of the deployment scripts
    enforced: true
    name: package.name
    required: true
    value: Content
    values:
    - Content
    valuesListDelimiter: ','
  - delimiter: ','
    description: The domain(s) to update
    multivalued: true
    name: Domains
    value: ALL
    valuesUrl: http://localhost/rd-option-provider/CmsContentDomains?environment=${option.Environment.value}
  - enforced: true
    name: NodeFilter
    required: true
    value: 'environment: dev2'
    valuesUrl: http://localhost/rd-option-provider/NodeFilter?filter=environment:%20${option.Environment.value}&subenv=${option.SubEnv.value}
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: false
  sequence:
    commands:
    - description: Deploy CMS Content Assets
      jobref:
        args: -Domains ${option.Domains} -Environment ${option.Environment} -package.name
          ${option.package.name} -package.version ${option.package.version}
        failOnDisable: true
        group: library
        name: Deploy - CMS Content Assets v2
        nodeStep: 'true'
        nodefilters:
          filter: '${option.NodeFilter} role: cms'
        uuid: 1f5b6812-149d-43c7-9ab3-a5009fe08fb9
    - description: Deploy Config
      jobref:
        args: -Domains ${option.Domains} -Environment ${option.Environment} -package.name
          ${option.package.name} -package.version ${option.package.version}
        failOnDisable: true
        group: library
        name: Deploy - CMS Content Config v2
        nodeStep: 'true'
        nodefilters:
          filter: '${option.NodeFilter} role: eap'
        uuid: 107d3dd7-6f61-4c9b-a8bc-0faa6bbdc0a2
    keepgoing: false
    strategy: node-first
  timeout: 1d
  uuid: 763cd15f-54ef-4610-a6c2-3e5d22baf9af
```

Common job definition:

```yaml
- defaultTab: nodes
  description: Deploys CMS Content Assets
  executionEnabled: true
  group: library
  id: 1f5b6812-149d-43c7-9ab3-a5009fe08fb9
  loglevel: INFO
  multipleExecutions: true
  name: Deploy - CMS Content Assets v2
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: true
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '10'
    filter: 'null'
  nodesSelectedByDefault: true
  options:
  - description: The environment to deploy to
    enforced: true
    name: Environment
    required: true
    value: dev2
    values:
    - beta
    - dev-stable
    - dev2
    - prod
    - promo
    - stg
    valuesListDelimiter: ','
  - description: The package name of the deployment scripts
    enforced: true
    name: package.name
    required: true
    value: Content
    values:
    - Content
    valuesListDelimiter: ','
  - description: The version of the deployment scripts to be used during deployment
    enforced: true
    name: package.version
    required: true
    valuesUrl: http://localhost/rd-option-provider/N3MavenPackages?repository=releases&group=com.dummy.cms&id=${option.package.name.value}&type=zip&limit=10
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - description: Get deployment scripts
      jobref:
        args: -package.repo releases -package.group com.dummy.cms -package.name
          ${option.package.name} -package.version ${option.package.version} -package.type
          zip -package.outputFolder ${node.deployRoot}/cms/${option.package.name}/${option.package.version}
          -package.unpack yes
        failOnDisable: true
        group: library
        name: Fetch Maven Package
        nodeStep: 'true'
        nodefilters:
          filter: '"${node.name}"'
        project: Common-Library
        uuid: d9ff39ac-0663-45c4-907e-9ced00c8c70b
    - description: Set script permissions
      fileExtension: .sh
      script: |-
        #!/bin/bash

        echo 'chmod 775 @node.deployRoot@/cms/@option.package.name@/@option.package.version@/scripts/*.sh'
        chmod 775 @node.deployRoot@/cms/@option.package.name@/@option.package.version@/scripts/*.sh
        if [[ $? -ne 0 ]]; then
          echo 'Failed to execute chmod'
          exit 1
        fi

        exit 0
    - description: Run install-v4.sh
      fileExtension: .sh
      script: |-
        #!/bin/bash

        package_root='@node.deployRoot@/cms/@option.package.name@/@option.package.version@'

        if [[ 'ALL' == '@option.Domains@' ]]; then
          echo 'FULL SYNC'
          sudo su - root -c "${package_root}/scripts/install-v4.sh -e @option.Environment@ -t content"
          if [[ $? -ne 0 ]]; then
            exit 1
          fi
        else
          echo 'DOMAIN SPECIFIC SYNC'
          sudo su - root -c "${package_root}/scripts/install-v4.sh -e @option.Environment@ -t content -d @option.Domains@"
          if [[ $? -ne 0 ]]; then
            exit 1
          fi
        fi
    - description: Run cleanup.sh
      exec: sudo ${node.deployRoot}/cms/${option.package.name}/${option.package.version}/scripts/cleanup.sh
        -f ${node.deployRoot}/cms/${option.package.name}
    keepgoing: false
    strategy: node-first
  timeout: 1d
  uuid: 1f5b6812-149d-43c7-9ab3-a5009fe08fb9
```
See : [Job Execution Logs.zip](https://github.com/rundeck/rundeck/files/6473739/Job.Execution.Logs.zip)
