### ISSUE TITLE
Error loading policy information

### ISSUE THREAD

**Issue by leshik** [rundeck/rundeck#7057]
**Describe the bug**

I'm getting `Error loading policy information` when visiting `/menu/acls` as an admin. Web inspector reveals `405 Method Not Allowed` for `/menu/ajaxSystemAclMeta`, probably because of [this](https://github.com/rundeck/rundeck/blob/v3.3.11/rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy#L105).

**My Rundeck detail**

* Rundeck version: `3.3.11`
* install type: `docker`
* DB Type/version: `mysql`

**To Reproduce**

1. Have at least one stored ACL policy configured
2. Go to `/menu/acls` as an admin
3. See `Error loading policy information`

**Expected behavior**

There shouldn't be an error when viewing ACL policies as an admin.

**Screenshots**

![image](https://user-images.githubusercontent.com/443678/118211662-a918c900-b496-11eb-8296-54ebecca38f6.png)

**Comment by MegaDrive68k** [comment]
Hi @leshik 

Your instance is behind a proxy server? I tested on war/docker without success.

**Comment by leshik** [comment]
Yes, I have nginx in front, but how this might break things? Everything else is working.

**Comment by MegaDrive68k** [comment]
Hi @leshik 

I tested using this basic/test environment, all works as expected, maybe I'm missing something?

```yaml
version: '3'

services:
    rundeck:
        build:
            context: ./
            args:
                RUNDECK_IMAGE: ${RUNDECK_IMAGE:-rundeck/rundeck:3.3.11}
        links:
          - mysql
        tty: true
        environment:
            RUNDECK_GRAILS_URL: http://localhost
            RUNDECK_SERVER_FORWARDED: 'true'
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
    nginx:
        image: nginx
        links:
          - rundeck
        volumes:
          - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
          - 80:80
    mysql:
        image: mysql:5.7
        expose:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
```

nginx.conf config:

```
server {
    listen 80 default_server;
    server_name rundeck-cl;

    location / {
        # Set rundeck user / roles
        proxy_pass http://rundeck:4440;
     }
}
```
