### ISSUE TITLE
Job stuck in "NOT STARTED" state indefinitely

### ISSUE THREAD

**Issue by jonathancouchman** [rundeck/rundeck#7085]
**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
We have scheduled job which runs every 5 minutes. One execution got stuck in the NOT STARTED state for 12 days until it was manually killed. Whilst it was stuck no further executions of this particular job could occur. Once killed, the subsequent scheduled jobs ran.

Is it possible to advise on how this is possible and secondly, how we might set up alerts on such a case. Since the job never completed, we do not see execution times in the log, so cannot alert on this. Is there another way to alert on this particular case? Additionally, is it possible to automatically kill any job that has remained in the NOT STARTED state for longer than a certain period?

There was no output from the job, it simply said "Not Started" in the output of the script step?

The job definitions are in the additional context section 

**My Rundeck detail**

* Rundeck version: 3.2.9-20200708
* install type: deb
* OS Name/version: 9.13
* DB Type/version: mysql

**To Reproduce**
1. Implement a job that is scheduled to run every 5 minutes
2. See that it gets stuck in the NOT STARTED state
3. See that no subsequent invocations of that job run until the stuck one is killed

**Expected behavior**

- The job not to get stuck in the NOT STARTED state
- Alerts if the job does get stuck
- Automatic cancelling of jobs that are stuck for a long time

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version:  90.0.4430.212

**Additional context**

Definition of the scheduled job which got stuck

```
- description: ''
  executionEnabled: true
  group: refresh-stuff
  id: bf48bb44-488d-49be-b2f8-34a8b2a86f51
  loglevel: INFO
  name: Refresh Stuff - Monday to Thursday
  nodeFilterEditable: true
  plugins:
    ExecutionLifecycle: null
  schedule:
    month: '*'
    time:
      hour: 00-23
      minute: 0,5,10,15,20,25,30,35,40,45,50,55
      seconds: '0'
    weekday:
      day: MON-THU
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: refresh-stuff
        name: Refresh Stuff
        useName: 'true'
    keepgoing: false
    strategy: node-first
  timeZone: America/New_York
  uuid: bf48bb44-488d-49be-b2f8-34a8b2a86f51
```

```
- defaultTab: summary
  description: Refresh Stuff
  executionEnabled: true
  group: refresh-stuff
  id: 79ba6a4d-9e5a-462f-b498-be36ef509176
  loglevel: INFO
  name: Refresh Stuff
  nodeFilterEditable: false
  notifyAvgDurationThreshold: null
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - script: curl -vv -X "POST" "http://refresher:8080/jobs/refresh_stuff"
    keepgoing: false
    strategy: node-first
  timeZone: America/New_York
  uuid: 79ba6a4d-9e5a-462f-b498-be36ef509176
```
