### ISSUE TITLE
LDAP user without groups(roles) cannot create API tokens

### ISSUE THREAD

**Issue by 0xbentang** [rundeck/rundeck#7086]
**Describe the bug**
I have 2 users,
A is a member of a bunch of groups, and I can create API token with it, and I can pick the role when I create token.
B is not a member of any group, and there's an error when I create an API token

![image](https://user-images.githubusercontent.com/33242068/119456789-9b542500-bd6d-11eb-9de1-1208cc8873e8.png)

![image](https://user-images.githubusercontent.com/33242068/119456823-a0b16f80-bd6d-11eb-8091-253dbe0ccb65.png)

**My Rundeck detail**

* Rundeck version:  3.3.5
* install type: docker
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**To Reproduce**
1. Have 2 LDAP users, one belong to a group, and one without groups
2. Create an API token using the UI
3. See error

**Expected behavior**
A token should be created, the permission should be the same as the user

**Comment by MegaDrive68k** [comment]
Hi @btck30351 

By default, Rundeck assigns the role "user" if you log in with a user without roles. Are you defined an ACL for "user" roles?

Take a look at [this](https://github.com/rundeck/rundeck/issues/3245#issuecomment-379374896).

Regards.

**Comment by btck30351** [comment]
Thanks for the reference.

```
resource:
    - equals:
        kind: apitoken
      allow: generate_user_token
```

I only have this resource policy in place, and didn't see anything about the "user" role in my acl config.

I even tried 

```
resource:
    - allow: "*"
```

but still got the same error. I guess something else is causing the problem?

Full config

```
---
description: rwx
context:
  project: P
for:
  resource:
    - allow: "*"
  adhoc:
    - allow: "*"
  job:
    - allow: "*"
  node:
    - allow: "*"
by:
  username:
    - svc_user


---
description: rwx
context:
  application: "rundeck"
for:
  project:
    - match:
        name: P
      allow: "*"
  project_acl:
    - match:
        name: P
      allow: "*"
  storage:
    - allow: "*"
  resource:
    - allow: "*"
by:
  username:
    - svc_user
```
