### ISSUE TITLE
fileUpload Plugin renames file

### ISSUE THREAD

**Issue by sergue2** [rundeck/rundeck#7092]
Hey,

i wanted to use the fileUpload plugin in combination with the copy file workflow step to copy a file from my pc to rundeck node.
But every file i want to upload is renamed by fileUpload Plugin in a random combination of letters and numbers.
Does anyone know how i can keep the name of the files?

**Comment by MegaDrive68k** [comment]
Hi @sergue2 

Are you using the `${file.Upload.fileName}` format on the destination path?

I made a local example job definition for testing, feel free to adapt it to your environment:

```yaml
- defaultTab: output
  description: ''
  executionEnabled: true
  id: 6df7eb26-7f0f-46ed-bb60-cec9eb21b28b
  loglevel: INFO
  name: UploadJob
  nodeFilterEditable: false
  options:
  - name: Upload
    type: file
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        destinationPath: /home/user/Desktop/${file.Upload.fileName}
        echo: 'true'
        recursive: 'false'
        sourcePath: ${file.Upload}
      nodeStep: true
      type: copyfile
    keepgoing: false
    strategy: node-first
  uuid: 6df7eb26-7f0f-46ed-bb60-cec9eb21b28b
```
