### ISSUE TITLE
Multivalued options are being treated as a single string in "Exec command"

### ISSUE THREAD

**Issue by agarwalpranab** [rundeck/rundeck#7113]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.3.11
* install type: docker
* OS Name/version: ubuntu
* DB Type/version: mysql? postgres? h2? h2

**Expected Behavior**
When sending out multivalued options, each item should be treated as a separate string. This behaviour is correct in the "inline script" but wrong in "exec command".

Sample yaml is attached with both inline script and exec command doing the same thing. If you will execute this on rundeck, you will see 1 error message in exec command and 2 error messages in inline script (inline script behaviour is correct).

**How to Reproduce**
Use the sample yaml code attached

```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 7a16808b-c757-4680-a702-77803cb8c614
  loglevel: INFO
  name: test
  nodeFilterEditable: false
  options:
  - delimiter: ' '
    label: Name
    multivalueAllSelected: true
    multivalued: true
    name: Name
    required: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - script: ls -l @option.Name@
    - exec: ls -l ${option.Name}
    keepgoing: false
    strategy: node-first
  uuid: 7a16808b-c757-4680-a702-77803cb8c614

```

NOTE: Since both the steps are going to fail, to check out the behaviour of the second one, please promote step2 to step1. 

Sample error message in our execution were:

```
ls: cannot access 'bla test': No such file or directory
```

```
ls: cannot access 'test': No such file or directory
ls: cannot access 'bla': No such file or directory
```

NOTE: 2nd behaviour is correct. We are expecting that `exec command` step also behaves the same way as inline script.
