### ISSUE TITLE
Command - Execute a remote command : not expanding node or project context variables

### ISSUE THREAD

**Issue by Daryes** [rundeck/rundeck#7138]
**Describe the bug**
simply the reopening of this bug #2698 that still surprisingly exists as of today.

When using a option using the node or project context variable, like node.name, the plugin "Command - Execute a remote command" won't expand the command line variables and will show "${node.name}" as is instead 
It's is also the same with $(job....} variables

Be it with nodes set to "Execute locally" or "dispatch to nodes"

**My Rundeck detail**

* Rundeck version: 3.3.11
* install type: deb
* OS Name/version: ubuntu 18.04
* DB Type/version: internal H2

**To Reproduce**
load this job : 
```
- defaultTab: nodes
  description: "Show the behavior difference between these execution plugins :  \n\
    \n* Command - Execute a remote command\n* Local Command - Run a command locally\
    \ on the server\n"
  executionEnabled: true
  group: bug
  id: e71ac287-ccee-4e10-8f8d-741779f191c1
  loglevel: INFO
  name: job variable expansion
  nodeFilterEditable: false
  options:
  - name: TEST1
    value: ${node.name}
  - name: TEST2
    value: ${job.project}
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: echo test result: ${option.TEST1} ${option.TEST2}
      description: local plugin
      nodeStep: true
      type: localexec
    - description: remote cmd plugin
      exec: ' echo test result: ${option.TEST1} ${option.TEST2}'
    keepgoing: false
    strategy: node-first
  uuid: e71ac287-ccee-4e10-8f8d-741779f191c1
```
Run it, compare the output :
```
local:  test result: localhost rundeck
remote: test result: ${node.name} ${job.project}
```

**Expected behavior**

The variable expanded for the remote execution plugin
