### ISSUE TITLE
Users unable to job history/activity

### ISSUE THREAD

**Issue by jodygilbert** [rundeck/rundeck#7218]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
We have created an ACL that allow users to run certain jobs in a couple of projects, running the jobs is fine but the cannot view the history and I'm not sure why, apologies if this is covered in the docs or elsewhere

The ACL we are using is:

```
---
description: System-level read-only access to key storage
context:
  application: rundeck
for:
  storage:
  - allow: read
by:
  group: group1
---
description: System-level read access to specific project
context:
  application: rundeck
for:
  project:
  - match:
      name: "(project1|project2)"
    allow: read
by:
  group: group1
---
description: Allow [read] access for (All) nodes generically
context:
  project: "(project1|project2)"
for:
  resource:
  - equals:
      kind: node
    allow: read
by:
  group: group1
---
description: Allow [read, run] for all project nodes
context:
  project: "(project1|project2)"
for:
  node:
  - allow: [read,run]
by:
  group: group1
---
description: Project-level access to a specific job group
context:
  project: "(project1|project2)"
for:
  job:
  - equals:
      group: test
    allow:
      - run
      - read
      - view
by:
  group: group1
---
description: System-level access to create api tokens
context:
  application: rundeck
for:
  resource:
  - equals:
        kind: apitoken
    allow: [generate_user_token]
by:
  group: group1
```

**My Rundeck detail**

* Rundeck version: 3.4.0
* install type: [choose: war
* OS Name/version: Windows Server 2016
* DB Type/version: mysql

**To Reproduce**
1. Go to homepage
2. Click on project|jobs|job
3. Scroll down to bottom page
4. Activity section is missing

**Expected behavior**
I was expecting to see the list of activities for the job

**Screenshots**
![image](https://user-images.githubusercontent.com/74103313/129324546-29ff855f-99ea-4df4-88d2-21f70bc84e44.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser Chrome and Edge
 - Version 92.0.902.55 

**Additional context**
