### ISSUE TITLE
URN: is not accepting list of entries

### ISSUE THREAD

**Issue by elioe** [rundeck/rundeck#7229]
**Bug**

The usage of URN in ACLs policies should accept a list of entries according to the documentation E.G:

```
by:
  urn:
    - project:Project1
    - project:Project2
context:
  application: rundeck
for:
  storage:
    - match:
        path: 'keys/.*'
      allow: [read]
description: Allow access to key storage
```
but this above it's not working, instead of that you should use a String entry for each resource (a policy for each entry), E.G:

```
by:
  urn: project:Project1
by:
  urn: project:Project2
context:
  application: rundeck
for:
  storage:
    - match:
        path: 'keys/.*'
      allow: [read]
description: Allow access to key storage
```
**Screenshot:**

![Screenshot from 2021-08-18 17-36-19](https://user-images.githubusercontent.com/48806282/129975631-05cc3e09-32d9-4b71-9a9f-34b0d64a8554.png)

**service.log:**

`[editor[1]:[Section 'urn:' should be a list or a String, but it was: java.util.ArrayList]]`

**My Rundeck detail**

* Rundeck version: 3.4.2
* install type: war
* OS Name/version: ubuntu 20.04/Mac O.S Catalina
* DB Type/version: MySQL 5.7

**Expected behavior**
Create a System ACL using urn by project that accepts a list of entries
