### ISSUE TITLE
SCM export doesn't allow to commit modified jobs

### ISSUE THREAD

**Issue by matthias-colt** [rundeck/rundeck#7279]
_Note: Bug Reports not following this template may be closed without feedback._

**Describe the bug**

**My Rundeck detail**

* Rundeck version: v3.4.4-20210920
* install type: docker
* OS Name/version: RHEL 7.4
* DB Type/version: mysql

**To Reproduce**
1. Configure SCM export
2. All existing jobs are uploaded to the Git repository as expected
3. Modify a job, e.g. change the job description
4. In the Jobs view the modified job has got an (!) icon with a mouse-over message "Export status:modified"
5. From the job actions dropdown select "Commit Changes to Git"
6. On the commit page, the  modified job is already selected.
7. Enter some commit message and click on "Commit" button.
8. Commit fails with red error message bar on top stating "No changes to local git repo need to be exported"

**Expected behavior**
The commit should be accepted since the job was even flagged as modified.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: MS Edge
 - Version: 94.0.992.31 

**Additional context**
SCM export config

```yaml
Committer Name: ${user.login}
Committer Email: ${user.email}
Export UUID Behavior: preserve
Synchronize Automatically: false
Base branch on: develop
File Path Template: ${job.project}/${job.group}${job.name}-${job.id}.${config.format}
Base Directory: /home/rundeck/projects/CiscoWAE/ScmExport
Git URL: https://${user.login}@gitoss.lon.osspriv.colt.net/testing/rundeck_jobs.git
Branch: develop
SSH: Strict Host Key Checking: yes
Password Storage Path: keys/users/${user.login}/gitea
Format: yaml
Fetch Automatically: true
```
