### ISSUE TITLE
Cron runs multiple times

### ISSUE THREAD

**Issue by mumblez** [rundeck/rundeck#728]
Rundeck 2.0.2 and 2.0.3

I've got a job that simply pings a specific IP

``` yaml
- id: c8b9da21-7b80-441d-ab53-e2155bd1bb9d
  project: Everything
  schedule:
    time:
      hour: '*'
      minute: 0/20
      seconds: '*'
    month: '*'
    year: '*'
    weekday:
      day: '*'
  loglevel: INFO
  sequence:
    keepgoing: true
    strategy: step-first
    commands:
    - script: |-
        #!/bin/bash
        ping 10.10.100.50 -c 4
        exit 0
      description: Ping .100. subnet
  description: Ping test from servers at Rackspace (Cloud and Dedicated)
  name: RS Ping .100.
  notification:
    onfailure:
      recipients: it-<domain>.com
  uuid: c8b9da21-7b80-441d-ab53-e2155bd1bb9d
  nodefilters:
    dispatch:
      threadcount: 50
      keepgoing: false
      excludePrecedence: false
      rankOrder: ascending
    filter: 'hostname: 172.3.*|10.1[78].*'
  group: troubleshooting/network
```

Cron is set to run every 20 minutes, but it runs 4 times each time, tried turning cron off and turning back on but symptom is the same.
(using crontab instead of 'simple')

![screen shot 2014-04-05 at 14 51 52](https://cloud.githubusercontent.com/assets/4791540/2622801/cba22f74-bcc9-11e3-9937-d304c3258aa6.png)

Any idea whats going on?
