### ISSUE TITLE
[ACL] Job ACL to hide job definition but permit read README

### ISSUE THREAD

**Issue by molinacarlos** [rundeck/rundeck#7361]
**Is your feature request related to a problem? Please describe.**
Currently, I have a job with README information defined in Job - Details - Description field. If I use the followint ACL
```
description: Limited user access for adm restart action
context:
  project: '.*'
for:
  resource:
    - allow: [read]
  job:
    - allow: [view,run,kill]

```
With view permission set, users cannot see neither README nor job .definition. If job is set to read (indeed view) user can see README and job definition

**Describe the solution you'd like**
Role permission tha permit a user to see README file but hide job defintiion

**Describe alternatives you've considered**
N/A
