### ISSUE TITLE
Scheduled Job Ran at the wrong time

### ISSUE THREAD

**Issue by jonathancouchman** [rundeck/rundeck#7367]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
We have a job scheduled to run as follows
`0 0 8-16 ? * MON-FRI *`
it had been running correctly, on the hour every hour for the past week, then on Friday 5th November it ran at 08:00, then the 09:00 execution did not run. There were no errors or information in the logs, it just seemed to miss the execution. Then it subsequently ran every hour from 10:00 onwards. However, it also ran at 17:00! The fact that it executed an hour after the final scheduled run was quite disruptive.

It appears that this job was not sticking to the quartz schedule, rather the missed 09:00 job executed at 10:00 and all subsequent executions were an hour late.

We have multiple jobs scheduled and we so no other issues with these jobs. They all executed at the correct time. Only this jobs executions were impacted

**My Rundeck detail**

* Rundeck version: 3.4.4
* install type: deb
* OS Name/version: debian 9 AWS EC2 
* DB Type/version: MySQL 8

**To Reproduce**
1. Schedule a job to run as follows "0 0 8-16 ? * MON-FRI *"
2. See that it did not run as expected 10:00 execution skipped
3. See that it ran at 17:00

**Expected behavior**
The job should run when scheduled. 
If it does not run there should be an error explaining why it did not run
The job should definitely not run 1 hour after the scheduled time with no explanation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios
 - Browser chrome
 - Version 95

**Additional context**
Job Definition
```
- defaultTab: summary
  name: Example Job
  description: Example Job
  executionEnabled: true
  uuid: 91ff7860-af0d-45f1-9d8c-5d020e2e9c31
  loglevel: INFO
  nodeFilterEditable: false
  notifyAvgDurationThreshold: null
  schedule:
    time:
      hour: '8-16'
      minute: 0
      seconds: 0
    weekday:
      day: MON-FRI
    month: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
      - script: |
          #!/bin/sh
          curl --silent --show-error --fail \            
            -X POST -s -S 'http://example:8080/do_something'
    keepgoing: false
    strategy: node-first
  timeZone: Europe/London
```

**Comment by jonathancouchman** [comment]
It happened again with a different Job. The schedule is
```
 schedule:
    time:
      hour: 1
      minute: 0
      seconds: 0
    weekday:
      day: MON-SUN
    month: '*'
    year: '*'
```
and it has been running at 01:00 every day and then today it ran at 09:00. There is nothing in any logs to suggest a problem or reason.
