### ISSUE TITLE
Getting HTTP error 403 - Authentication Issue / WAR Installation

### ISSUE THREAD

**Issue by danielmakita** [rundeck/rundeck#7395]
Issue type: Bug report/Enhancement Request

Hello all, hope you are fine.

I have installed rundeck via WAR file on Linux/Tomcat and I am having issues to login into the /rundeck.
I am getting a 403 error when logging in localhost:8080/rundeck saying that access has been denied.

When installed via WAR on Tomcat, should I configure tomcat-users.xml or realm.properties?
I could see this issue https://github.com/rundeck/rundeck/issues/620 but it was not clear for me if I need to configure just the tomcat-users.xml or if I am missing any other step.

tomcat-users.xml file

I am not able to login using the credentials defined at tomcat-users.xml file, but I can login with the credentials defined at real.properties file. 
```
<?xml version='1.0' encoding='utf-8'?>
<tomcat-users>
  <role rolename="user"/>
  <role rolename="admin"/>
  <role rolename="manager-gui"/>
  <user username="user" password="user" roles="user"/>
  <user username="admin" password="admin" roles="admin,user,manager-gui"/>
</tomcat-users>
```
real.properties file
```
administrador:administrador,user,admin,manage-gui
usuario:usuario,user
```
admin.aclpolicy
```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin

```
framework.properties file
```
framework.server.name = 10.188.25.96
framework.server.hostname = 10.188.25.96
framework.server.port = 8080
framework.server.url = http://10.188.25.96:8080/rundeck

```

rundeck.properties file
```
grails.serverURL=http://10.188.25.96:8080/rundeck
server.servlet.context-path=/rundeck

```

* Rundeck version: rundeck-3.4.6-20211110 (Tomcat version Apache Tomcat/8.5.73)
* install type: WAR 
* OS Name/version:  SUSE Linux Enterprise Server 15 SP1
* DB Type/version: h2

**Expected Behavior**
Successfully login to localhost:8080/rundeck 

**How to Reproduce**
Install the rundeck via WAR file in Tomcat and try to login to localhost:8080/rundeck.
A HTTP Status 403 is displayed as "Access to the requested resource has been denied".

Thanks in advance!
Please let me know if more information is needed.
