### ISSUE TITLE
can not edit Job

### ISSUE THREAD

**Issue by koraz0815** [rundeck/rundeck#7409]
**Describe the bug**
I can not edit a existing job with ranking attribute

**My Rundeck detail**

* Rundeck version: 3.4.6
* install type: rpm
* OS Name/version: CentOS 7.9.2009
* DB Type/version: postgres

**To Reproduce**
1. go to existing Job
2. Click Action->Edit this Job
3. Change Job-Name
4. Click Save
5. get error `Project Name is not valid`

**Expected behavior**
Job will be not edit.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/49562408/144587139-288e9adc-4103-4c7e-a939-7478dd7d5ff4.png)

Logoutput in rundeck.log
```
[2021-12-03T11:23:44,092] ERROR errors.GrailsExceptionResolver [qtp660103401-22400] - NullPointerException occurred when processing request: [POST] /project/Infrastruktur/job/update
Cannot get property 'rankTiered' on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot get property 'rankTiered' on null object
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 91.3.0esr

**Additional context**
Here the yaml from the Job
```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: OS-Update
  id: 5f59b2c6-d03b-437c-9b4c-2cb2eb14e68e
  loglevel: INFO
  multipleExecutions: true
  name: Update Multiple Systems Copy
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: true
      rankAttribute: patchday-priority
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '128'
    filter: '${option.node_filter} !tags: patchday-excluded'
  nodesSelectedByDefault: true
  options:
  - name: node_filter
  orchestrator:
    type: rankTiered
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: OS-Update
        name: Update System
        nodeStep: 'true'
        nodefilters:
          dispatch:
            nodeIntersect: true
          filter: .*
        uuid: b6b7a763-523e-4aaf-bf1d-0f736be9680f
    keepgoing: false
    strategy: parallel
  timeout: 2h
  uuid: 5f59b2c6-d03b-437c-9b4c-2cb2eb14e68e
```
