### ISSUE TITLE
Allow to forward uploaded files with different option names

### ISSUE THREAD

**Issue by sideshowcecil** [rundeck/rundeck#7441]
**Describe the bug**
When using uploaded files in Rundeck jobs and using those options to trigger a job ref it is not possible to use a different option name in the referenced job.

**My Rundeck detail**

* Rundeck version: 3.4.8
* install type: docker
* OS Name/version: ubuntu 20.04
* DB Type/version: postgres

**To Reproduce**
1. Create the referenced job:
```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 76a81ca2-59f9-40d6-9ab0-7acb9b88f5c4
  loglevel: INFO
  name: Referenced Job
  nodeFilterEditable: false
  options:
  - name: FileB
    required: true
    type: file
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: 'echo "Got file: ${file.FileB.filename}"'
    keepgoing: false
    strategy: node-first
  uuid: 76a81ca2-59f9-40d6-9ab0-7acb9b88f5c4
```
2. Create main job
```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: acd62b06-6631-4c9c-a7a8-9a817a447563
  loglevel: INFO
  name: Main Job
  nodeFilterEditable: false
  options:
  - name: FileA
    required: true
    type: file
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        args: -FileB ${option.FileA}
        group: ''
        name: Referenced Job
        uuid: 76a81ca2-59f9-40d6-9ab0-7acb9b88f5c4
    keepgoing: false
    strategy: node-first
  uuid: acd62b06-6631-4c9c-a7a8-9a817a447563
```
3. Trigger job "Main Job" providing a option FileA

**Expected behavior**
The referenced job should be triggered and the file should be handed over to the option correctly.

**Actual behavior**
The job fails with the following error:
```
Option input was not valid for [76a81ca2-59f9-40d6-9ab0-7acb9b88f5c4]: File ref "ff43ef04-4bfc-460c-a1fd-23bfcd8a4fc9" is not a valid for job 76a81ca2-59f9-40d6-9ab0-7acb9b88f5c4, option FileB
Execution failed: 1061 in project Internal: [Workflow result: , step failures: {1=InvalidOptions: Invalid options: [FileB]}, status: failed]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1133175/146380823-5df199d0-14a7-4e2c-8db2-df78fe34d07c.png)
