### ISSUE TITLE
Can't access Global Variable on notifications

### ISSUE THREAD

**Issue by nublaii** [rundeck/rundeck#7451]
**Describe the bug**
The 'Global Variable'  workflow states '_Creates a global variable to be used on other steps or in notifications._"

**My Rundeck detail**
* Rundeck version: [3.4.9.20211221]
* install type: [deb]
* OS Name/version: [Ubuntu 20.04.3 LTS]
* DB Type/version: [mysql]

**To Reproduce**
1. Create simple **Script** step that echos a _key=value_ (rd_appurl=https://www.google.com)
2. Assign a **Key Value Data** Log Filter to this step with pattern _^(rd_appurl)=(.+)$_
3. Create a **Global Variable** workflow step mapping it: Value: _${data.rd_appurl*}_, Group: _export_, Name: _goodllama_, 
4. Create a simple **Script** step to verify that @export.goodllama@ has the correct value
5. Add webhook notification

**Expected behavior**
As stated on the **Global Variable** step, "Creates a global variable to be used on other steps or in notifications." so I expect to see some form of _goodllama_ somewhere on the POST body, but it's nowhere to be found.

**Screenshots**
1.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/1773409/147273587-faffdb11-ada5-415c-9ef1-94f90c2e17fc.png">
2.
<img width="619" alt="image" src="https://user-images.githubusercontent.com/1773409/147273650-781cb9e4-3eac-49f5-8ad5-d5ddb92ec777.png">
3.
<img width="710" alt="image" src="https://user-images.githubusercontent.com/1773409/147273761-1a60def3-772f-4f88-be9b-7cbf8a25ca67.png">
4.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/1773409/147273777-228b09d3-3dc3-40d1-b305-5c79c6a9838c.png">
5.
<img width="892" alt="image" src="https://user-images.githubusercontent.com/1773409/147273831-3717e084-d779-493c-bdb9-66043a8f854b.png">

6. Json content for the webhook:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/1773409/147274190-e2a72ec0-853d-4496-b9c7-4d2b6fbdfed3.png">

**Comment by niall-munnelly** [comment]
I think this is the same thing I asked for in [this feature request](https://github.com/rundeck/rundeck/issues/5315). Last I check, Rundeck's data capture filter doesn't support this.

You need to do one of these:

Capture only one group and hardcode a name in the "name data" field, or
Capture the two groups, but you need to use expressions/patterns, not hard-coded strings, like so:

![image](https://user-images.githubusercontent.com/17707275/147276723-a95d961e-6da5-4770-afb7-290c0e9f5136.png)


So in my F5 management plugin, I need to identify the active and standy balancers in a device pair. My script prints something like

"F5_Active_Balancer = FOO"
"F5_Standby_Balancer" = "BAR"

And the log filter above captures the expressions for reuse. I've got hundreds of jobs that use this filter and have used it successfully since the data capture steps were introduced to Rundeck.

That said, the notifications are another headache entirely, and we had to submit bugs/feature requests for every individual notification, eg Splunk, webhooks, etc. It wasn't a single, global fix, but AFAIK, Rundeck delivered the goods.

**Comment by MegaDrive68k** [comment]
Confirmed, tested with the following job definition:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 6f3361cb-38e7-48fd-9563-5131cccfdbbb
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  notification:
    onstart:
      plugin:
        configuration:
          authentication: None
          body: ${job.execid}${export.mydata}
          contentType: application/json
          method: POST
          noSSLVerification: 'true'
          remoteUrl: https://webhook.site/xxxx-xxxx-xxxx-xxxx-xxxx
          timeout: '30000'
        type: HttpNotification
  notifyAvgDurationThreshold: null
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - description: generate the data value
      exec: ' echo rd_appurl="https://www.google.com/"'
      plugins:
        LogFilter:
        - config:
            invalidKeyPattern: \s|\$|\{|\}|\\
            logData: 'true'
            regex: ^(rd_appurl)=(.+)$
          type: key-value-data
    - description: using data variable
      exec: echo ${data.rd_appurl}
    - configuration:
        export: mydata
        group: export
        value: ${data.rd_appurl*}
      description: global variable
      nodeStep: false
      type: export-var
    - description: using the global variable workflow step
      exec: echo ${export.mydata}
    keepgoing: false
    strategy: node-first
  uuid: 6f3361cb-38e7-48fd-9563-5131cccfdbbb
```

I can see the context variable `${job.execid}` but the global `${export.mydata}` doesn't.

<img width="1133" alt="Screen Shot 2021-12-23 at 16 22 19" src="https://user-images.githubusercontent.com/51376003/147287586-0d4fe94e-7b4d-46ba-a586-669140711b38.png">

Related: 

https://github.com/rundeck/rundeck/issues/5061#issuecomment-616611931
https://github.com/rundeck/rundeck/issues/6810

Thanks for your feedback @nublaii!
