### ISSUE TITLE
Single enforced option can't be selected

### ISSUE THREAD

**Issue by philippeganz** [rundeck/rundeck#7455]
**Describe the bug**
When creating a new option that has a single enforced value, that option can't be selected when launching the job.

**My Rundeck detail**

* Rundeck version: 3.3.16
* install type: docker
* OS Name/version: SUSE 15.3
* DB Type/version: oracle

**To Reproduce**
Create a new job and add the following option :
```yaml
  - delimiter: ' '
    description: Select this option if you want it
    enforced: true
    multivalued: true
    name: option
    values:
    - --noop
    valuesListDelimiter: ','
```
You end up with an option that appears on the job but you can not select it.

On the other hand, if you remove the restriction, the option becomes selectable but you can also add your own value, which is not acceptable in a context where you don't want users to enter their own value.
This would correspond to the following option : 
```yaml
  - delimiter: ' '
    description: Select this option if you want it
    multivalued: true
    name: option
    values:
    - --noop
    valuesListDelimiter: ','
```

**Expected behavior**
I would expect to be able to select a single enforced option

**Screenshots**
![image](https://user-images.githubusercontent.com/14214388/147574802-2d220b7e-13d7-4579-a8c4-a294b461e836.png)
![image](https://user-images.githubusercontent.com/14214388/147574711-fa8406a1-c1c6-4a44-bf17-ab2c9ccc300b.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chromium
 - Version 85

**Additional context**
