### ISSUE TITLE
${execution.succeededNodeListString} not populating in notifications

### ISSUE THREAD

**Issue by TritonDione** [rundeck/rundeck#7467]
I have the following in the HTML for my notification templates:

Nodes Reporting Success: ${execution.succeededNodeListString}
Nodes Reporting Failure: ${execution.failedNodeListString}

When i run a job the failedNodeListString populates fine but the succeededNodeListString never seems to populate.

This also seems to be true for webhooks.

**Comment by TritonDione** [comment]
Hi There. 

Details are:

APIVERSION : 40
BASE : /var/lib/rundeck
BUILD : 3.4.9-20211221
BUILDGIT : v3.4.9-0-gfe92051
VERSION : 3.4.9-20211221

Thanks
Rich

**Comment by MegaDrive68k** [comment]
Confirmed using the HTTP notification plugin. Tested with the following job definition:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 6d178059-3d96-4b84-9fa5-1226d2dbe938
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: .*
  nodesSelectedByDefault: true
  notification:
    onstart:
      plugin:
        configuration:
          authentication: None
          body: ${execution.id}:${execution.succeededNodeListString}
          contentType: application/json
          method: POST
          noSSLVerification: 'true'
          remoteUrl: https://webhook.site/xxxx-xxxx-xxxx-xxxx-xxxx
          timeout: '30000'
        type: HttpNotification
  notifyAvgDurationThreshold: null
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: whoami
    keepgoing: false
    strategy: node-first
  uuid: 6d178059-3d96-4b84-9fa5-1226d2dbe938
```

The `${execution.succeededNodeListString}` variable doesn't work.
