### ISSUE TITLE
how can i enable debug logging ?

### ISSUE THREAD

**Issue by TheFatal** [rundeck/rundeck#7485]
hey guys, i added 2 variables in my docker-compose file, so my docker-compose configs looks like:

docker-compose config
```
services:
  rundeck:
    environment:
      RUNDECK_LOGGING_LOGLEVEL_DEFAULT: debug
      RUNDECK_LOGGING_LOGLEVEL_ROOT: debug
    image: rundeck/rundeck:3.4.9
    ports:
    - published: 4440
      target: 4440
    tty: true
    volumes:
    - data:/home/rundeck/server/data:rw
version: '3'
volumes:
  data: {}
```
but still no debug messages in docker-compose logs rundeck, only warn and info messages, how can i fix this ?
