### ISSUE TITLE
Importing multiple notifications is not working

### ISSUE THREAD

**Issue by balbusm** [rundeck/rundeck#7496]
**Describe the bug**
I'm trying to import YAML configuration with multiple notifications on the same event.
Only the last one is imported

**My Rundeck detail**

* Rundeck version: 3.3.13 ENTERPRISE
* install type: rpm
* OS Name/version: RHEL 7.3 
* DB Type/version: ?

**To Reproduce**
1. Create a job
2. Go to Notifications
3. Add On Failure notification 
  - Trigger on: Failure
  - Notification Type: Http Notification
  - Populate fields with some data
4. Add another On Failure notification:
  - Trigger on: Failure
  - Notification Type: Http Notification
  - Populate fields with some other data
5. Save job
6. Download job definition in YAML
7. Upload previously downloaded YAML
8. After upload only last notification is present

**Expected behavior**
Expected - Both notifications are present

**Example YML**
In attached example notification1 is not imported
Only notification2 is present
```
- name: notification-test
  defaultTab: nodes
  description: Simple job
  executionEnabled: true
  group: G1
  loglevel: INFO
  nodeFilterEditable: true
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: AAA
  nodesSelectedByDefault: true
  notification:
    onfailure:
      plugin:
      - type: HttpNotification
        configuration:
          authentication: None
          contentType: application/json
          method: POST
          remoteUrl: http://notification1
          timeout: '30000'
          body: |
            {
                "title": "Notification1",
            }
      - type: HttpNotification
        configuration:
          authentication: None
          contentType: application/json
          method: POST
          remoteUrl: http://notification2
          timeout: '30000'
          body: |
            {
              "title": "Notification2",
            }
  notifyAvgDurationThreshold: null
  options:
  - name: returnCode
    required: true
    value: '1'
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - exec: exit ${option.returnCode}
    keepgoing: false
    strategy: node-first

```

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 96

**Additional context**
Uploading XML has same behaviour

**Comment by MegaDrive68k** [comment]
Confirmed, also tested with the following job definition:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: f0b3be9c-4790-43d2-9abf-9ab304e62585
  loglevel: INFO
  name: Test
  nodeFilterEditable: false
  notification:
    onfailure:
      plugin:
      - configuration:
          authentication: None
          contentType: application/json
          method: GET
          remoteUrl: http://url1.es
          timeout: '30000'
        type: HttpNotification
      - configuration:
          authentication: None
          contentType: application/json
          method: GET
          remoteUrl: url2.es
          timeout: '30000'
        type: HttpNotification
  notifyAvgDurationThreshold: null
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: whoami
    keepgoing: false
    strategy: node-first
  uuid: f0b3be9c-4790-43d2-9abf-9ab304e62585
```
Thank you @balbusm!
