### ISSUE TITLE
YAML documentation is wrong about dayofmonth 

### ISSUE THREAD

**Issue by mahmoudimus** [rundeck/rundeck#751]
Right here: http://rundeck.org/docs/man5/job-yaml.html#TOC

![image](https://cloud.githubusercontent.com/assets/40820/2833403/19dd9df4-cfd0-11e3-8cb0-707c1b0c22be.png)

Dayofmonth should really be:

```
dayofmonth:
map containing:
day (mutually exclusive with weekday)
```

Here's an example for first day of every month:

``` yaml
- id: ba82e163-640f-48e6-8003-e4db7afe8d7a
  project: balanced
  schedule:
    time:
      hour: '0'
      minute: '0'
      seconds: '0'
    month: '*'
    year: '*'
    dayofmonth:
      day: '1'
```
