### ISSUE TITLE
Script Plugin - Windows - Merge Environment Not Working

### ISSUE THREAD

**Issue by gregbeck** [rundeck/rundeck#7551]
**Describe the bug**
MergeEnvironment isn't working with a script plugin on Windows 

**My Rundeck detail**

* Rundeck version: 3.4.10 (community)
* install type: war
* OS Name/version: Windows Server 2019
* DB Type/version: H2

**To Reproduce**
Steps based off [Script Plugin Development](https://docs.rundeck.com/docs/developer/01-plugin-development.html#script-plugin-development) documents.  

Create a plugin with the following layout, and import into rundeck. 

```
TEST-SCRIPT-PLUGIN
|   plugin.yaml
|
\---contents
        script.ps1
```

plugin.yaml

```yaml
name: test-script-plugin
version: 1.0
rundeckPluginVersion: 1.2
author: author name
date: 2022-02-20
url: website URL
providers:
  - name: test-script-plugin-powershell
    service: NodeExecutor
    plugin-type: script
    script-interpreter: powershell.exe -NoLogo -NonInteractive -NoProfile -File
    script-file: script.ps1
    #script-args: [script file args]
    mergeEnvironment: true
```

script.ps1
```powershell
Get-ChildItem Env:
```

Edit the local node. Add the property `local-node-executor=test-script-plugin-powershell`

Create an inline or command job and run. 

**Expected behavior**
I expect the log to output a list of environment variables including the system ones such has path.  What I get is just the RD_* variables. 

**Additional context**
I also posted about this issue on the rundeck-discuss list: [Script Plugin - Windows - Merge Environment](https://groups.google.com/g/rundeck-discuss/c/OknDqyep028/m/52zu4DTnAQAJ)
