### ISSUE TITLE
Workflow State and Log Output is not available

### ISSUE THREAD

**Issue by tcdev0** [rundeck/rundeck#7676]
**Rundeck**
* Rundeck version: v4.1.0
* install type: docker
* DB Type/version: mysql 8

**To Reproduce**
1. Execute Job, Workflow State and Log output exists
2. Restart Rundeck Container
3. Check Job Activity -> Workflow State and Log Output is not available
4. See screenshot

**Expected behavior**
Workflow State and Log Output should be available after Container restart. 

**Screenshots**

![rundeck_exec](https://user-images.githubusercontent.com/822498/165552429-06e93f10-4b58-4bfa-8f1d-385c8d1388fb.png)

Did i forget to configure something or is it a bug ? 

thanks.

**Comment by MegaDrive68k** [comment]
Hi @tcdev0 

Using this `docker-compose.yml` definition:

```yaml
version: '3'
services:
    rundeck:
        image: rundeck/rundeck:4.1.0
        environment:
            RUNDECK_GRAILS_URL: http://localhost:4440
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true 
            TERM: xterm-256color
        ports:
          - 4440:4440
        tty: true
    mysql:
        image: mysql:8
        expose:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
```

It works following your steps.

![Screen Shot 2022-04-27 at 13 49 27](https://user-images.githubusercontent.com/51376003/165588451-5a7b03ed-cccb-4e8a-9e54-ad43a753062d.png)

Probably it's something related to your docker-compose file structure, take a look at [this](https://github.com/rundeck/welcome-project-community/blob/main/docker-compose.yml) example.

Regards.

**Comment by tcdev0** [comment]
@MegaDrive68k thanks for your quick response.

using your example with db volume:

```yml
version: '3'
services:
    rundeck:
        image: rundeck/rundeck:4.1.0
        environment:
            RUNDECK_GRAILS_URL: http://localhost:4440
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true 
            TERM: xterm-256color
        ports:
          - 4440:4440
        tty: true
    mysql:
        image: mysql:8
        expose:
          - 3306
        volumes:
         - "./data/db:/var/lib/mysql"  
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
```

1. docker-compose up
2. Create test Project
3. Create Job uptime for local node
4. execute Job
5. logs

![rundeck_uptime_1](https://user-images.githubusercontent.com/822498/165747506-e4db221f-9b3c-411a-88df-a1471436cd09.png)

6. docker-compose down
7. docker-compose up
8. no logs

![rundeck_uptime_2](https://user-images.githubusercontent.com/822498/165747566-bb46608d-b500-43b0-824d-4fd0717830c9.png)

Where is the workflow state and log output stored/saved ? 
mariadb volume is persisted with volume and /home/rundeck/server/data is empty.

I tried using to mount the log files with no success.

```yml
        environment:
            ...
            RUNDECK_LOGGING_STRATEGY: "FILE"
        volumes:
          - "./data/logs:/home/rundeck/server/logs"
```

thanks.

**Comment by MegaDrive68k** [comment]
Hi @tcdev0 

The execution logs are stored at `/home/rundeck/var/logs/rundeck` path.

Try with the following example:

```yaml
version: '3'
services:
    rundeck:
        image: rundeck/rundeck:4.1.0
        environment:
            RUNDECK_GRAILS_URL: http://localhost:4440
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true 
            RUNDECK_LOGGING_STRATEGY: FILE
        volumes:
          - ./data/logs/:/home/rundeck/var/logs/rundeck/
        ports:
          - 4440:4440
        tty: true
    mysql:
        image: mysql:8
        expose:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
    
```

It works in my environment.

Regards!
