### ISSUE TITLE
Issue with option escaping in commands on 4.0.1

### ISSUE THREAD

**Issue by fishikles** [rundeck/rundeck#7698]
Describe the bug

    I have updated my test RunDeck server from 3.2.8 to 4.0.1 and I've see a bug with argument escaping.
    This can be reproduced with the attached job.
    When run with value set to * on 3.2.8 the job succeeded and "command /data/notarealdir/*" was output 
    However on 4.0.1 the job fails with "echo: No match."

My Rundeck detail

    Rundeck version: 3.2.8 and 4.0.1
    install type: rpm
    OS Name/version: RHEL 7.7
    DB Type/version: mysql

To Reproduce

    Load the job attached below and run with value set to * on 3.2.8 and 4.0.1

Expected behaviour

    I would have expected the ${options.value} in the command to be escaped in 4.0.1 as it was in 3.2.8

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  loglevel: INFO
  name: test
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ''
  nodesSelectedByDefault: true
  options:
  - name: value
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo command /data/notarealdir/${option.value}
    keepgoing: false
    strategy: node-first

```
