### ISSUE TITLE
issue with uploading YAML Job

### ISSUE THREAD

**Issue by KieranHolton** [rundeck/rundeck#7773]
**Describe the bug**
I have recently created a new Rundeck host with version 4.2 since using the new host it seems I'm having issues with uploading YAML templates for jobs.

The particular issues appears to be with options with multiple values. 
example the following job fails to upload;

```
- defaultTab: nodes
  description: testing multiple values
  executionEnabled: true
  id: 9525e0b4-065b-4d26-9399-a59c9d21a476
  loglevel: INFO
  name: MultiValue Test
  nodeFilterEditable: false
  options:
  - label: Multi 1
    name: multi1
    value: '1'
    values: '1,2,3,4,5,6,7,8'
    valuesListDelimiter: ','
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - description: echo "blah"
      exec: blah
    keepgoing: false
    strategy: node-first
  uuid: 9525e0b4-065b-4d26-9399-a59c9d21a476

````

this returns error: 

`org.rundeck.app.components.jobs.JobDefinitionException: Unable to create Job: Could not find matching constructor for: java.util.ArrayList(String)`

In my previous instance of rundeck (VERSION : 3.4.0-20210614) this works fine.

I appreciate that if i change the values to be 1 per line this works fine, however we template this automatically as part of a deployment which makes it easier to to have them as a comma separated string

**My Rundeck detail**

* Rundeck version: 4.2.0-20220509
* install type: rpm
* OS Name/version: centos08
* DB Type/version: mysql

**To Reproduce**
1.go to project
2. select Job actions/Upload Definition
3. select YAML File
4.upload

**Expected behavior**
Job should upload with no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/51415463/174052902-34cd6455-5328-4aa2-af05-70b5fd5d592d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser Chrome
 - Version 101.0.4951.64
