### ISSUE TITLE
Create Repository button does not obey context/baseurl

### ISSUE THREAD

**Issue by michaelkrieger** [rundeck/rundeck#7795]
**Describe the bug**

Running rundeck with:
      - RUNDECK_GRAILS_URL=https://myhost.mydomain.com/rundeck
      - RUNDECK_SERVER_CONTEXTPATH=/rundeck
Clicking 'Create New Project' from:
  - the giant button at /rundeck/menu/home = works
  - clicking the projects drop down at the top and clicking create project in the bottom right corner = redirects to /resources/createProject which is a 404 not found.

It seems that that link is not obeying the server contextpath or grails_url in redirecting to the appropriate link.

**My Rundeck detail**

* Rundeck version: 4.4.0
* install type: docker
* OS Name/version: Debian 11
* DB Type/version: H2

**To Reproduce**
Click the link while having those two environment variables set.

**Expected behavior**
Both links should work.  All links should work with a sub path.

**Screenshots**
Not working:
![010E428B-3D42-4C45-A36E-68D7FCD096FF](https://user-images.githubusercontent.com/7321259/176934719-109ae105-65d6-4a97-a16f-5560a1a02f38.jpeg)
Working:
![576670DF-C704-4B9C-9B89-13CD4C3BC876](https://user-images.githubusercontent.com/7321259/176934886-58ec03fb-88ba-41d7-9a81-18f57924156d.jpeg)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Version 15.5

**Additional context**

**Comment by MegaDrive68k** [comment]
Confirmed,

I'm seeing the same behavior using this env:

```yaml
version: "3"
services:
  rundeck:
    image: rundeck/rundeck:SNAPSHOT
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: http://localhost/rdeck
      RUNDECK_SERVER_CONTEXTPATH: /rdeck
      RUNDECK_SERVER_FORWARDED: "true"
  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - 80:80
```

The `nginx.conf` file needed by the Nginx container:

```
server {
    listen 80 default_server;
    server_name rundeck-cl;

    # default rundeck location is the root 
    location /rdeck {
        # took from default rundeck conf
        proxy_pass http://rundeck:4440;
     }
}
```

Thanks for your feedback @michaelkrieger!
