### ISSUE TITLE
UI Plugin doesn't work on all pages

### ISSUE THREAD

**Issue by MiyamaMizuki329** [rundeck/rundeck#7813]
Exactly what the title says. The UI Plugin doesn't work on all pages. The javascript isn't even loaded on the job listing page and all the job pages. It is loaded only on dashboard page.

**My Rundeck detail**

* Rundeck version: 4.4.0
* install type: war
* OS Name/version: ubuntu 22.04

1. Copy plugin .zip file to rundeck\var\lib\rundeck\libext\
2. Open rundeck in browser
3. UI Plugin is loaded in dashboard page, but isn't loaded on other pages

**Expected behavior**
The UI Plugin should be loaded on all the pages.

 - OS: ubuntu 22.04
 - Browser chrome, firefox, edge

There's an object called rundeckPage that can be used in the plugin javascript files. The object can be accessed and used in dashboard page, but it doesn't even exist in job listing page and job page.
I can use rundeckPage.path() to get "menu/home" in the dashboard page, but rundeckPage doesn't exist when I open other pages.

**Comment by fdevans** [comment]
Can you post your UI `plugin.yml`?  We use UI plugins internally for things and they seem to be working fine.

**Comment by MiyamaMizuki329** [comment]
Here's my `plugin.yaml`:
```
name: option-filter
rundeckPluginVersion: 1.2
author: Rundeck Dev
license: Apache 2.0
tags:
    - script
    - UI
date: 2019-06-21T19:49:59.141Z
version: 1.0.0
providers:
    - name: option-filter
      service: UI
      plugin-type: ui
      title: option-filter
      description: Option filter UI plugin
      ui:
        - pages: ['menu/jobs','scheduledExecution/show']
          scripts:
            - js/option-filter-init.js
            - js/main.js
          styles:
            - css/option-filter-styles.css
```
