### ISSUE TITLE
Option model json simple list does not work

### ISSUE THREAD

**Issue by Scifire** [rundeck/rundeck#7858]
**Describe the bug**
Using a JSON "Simple List" as allowed value remote URL does produce the error: "ERROR loading result from Rundeck server: error: Server Error" (Option Model Provider)

Simple Object and Name Value List are still working.

**My Rundeck detail**

* Rundeck version: [4.5.0]
* install type: [deb]
* OS Name/version: [ubuntu 20.04]
* DB Type/version: [ postgres/13 ]

**To Reproduce**
1. Create a new Job
2. Create inside the job a new option with allowed values remote URL and use a local file e.g. `file:/media/rundeck/temp.json`
3. Place a JSON file Simple List (https://docs.rundeck.com/4.4.0/manual/job-options.html#json-format) on that path
4. Check the Job, and see the error

**Expected behavior**
JSON should be interpreted and be available as option.

**Screenshots**
Current behavior:
![image](https://user-images.githubusercontent.com/17220258/185150524-812c28f7-a50d-4de4-94ce-518e4bbc57ad.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/17220258/185150171-e819121f-15d3-45c1-a207-78762d9182a0.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [104]

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @Scifire 

Could you test with the following job definition example?

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: d56c8c43-de29-4b17-8a0c-3cab8728df55
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  options:
  - enforced: true
    name: mylist
    valuesUrl: file:/Users/myuser/myopts.json
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo ${option.mylist}
    keepgoing: false
    strategy: node-first
  uuid: d56c8c43-de29-4b17-8a0c-3cab8728df55
```

The job uses the following JSON file:

```json
["x value for test","y value for test"]
```

It works on my env under Rundeck 4.5.0:

![Screen Shot 2022-08-17 at 12 35 08](https://user-images.githubusercontent.com/51376003/185194860-71dd7bfd-9c31-4379-8ca7-f3258fe572e5.png)

![Screen Shot 2022-08-17 at 12 35 26](https://user-images.githubusercontent.com/51376003/185194865-f7267f46-a31e-4b93-bc57-4f7f8566c6a6.png)

Regards.
