### ISSUE TITLE
Limited node filter ignored if node set provided from API call

### ISSUE THREAD

**Issue by 1kUHuiswkvj7spRO** [rundeck/rundeck#7859]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: Rundeck 4.3.0 2022-06-02
* install type: deb
* OS Name/version: Ubuntu 20.04
* DB Type/version: MySQL

**Expected Behavior**
When sending an API request to execute a job with a supplied node list, if the job is configured with "Editable filter" set to "No" and a pre-configured node list, the job should ignore the provided node filter, and only execute on the configured filter. It does not ignore, but instead executes on any node configured in the node source list rather than honoring the Node Filter.

**How to Reproduce**
Create a simple job that echos a string on "Server A". Configure this job to dispatch to nodes under the "Nodes" tab. Supply a node filter, and ensure only "Server A" matches. Also be sure that "Editable filter" is set to "No", and that more than one node is defined in your node source file. ("Server B").

Make an API request to execute this job, but supply a different node in the headers, i.e.:
```
{
    "filter":"Server B"
}
```

The job will execute on the supplied node ("Server B") even though it is not included in the node filter.  This behavior **cannot** be seen on the frontend with the provided configuration above. If this was expected behavior, the user would be able to change which nodes the job executes on, regardless of node filter.
![image](https://user-images.githubusercontent.com/33703686/185177780-543b0c4c-2354-4acf-8ba0-99aed7953d46.png)

When "Editable filter" is set to "Yes", then the frontend exhibits the correct behavior:
![image](https://user-images.githubusercontent.com/33703686/185177995-ac9841e9-1220-49c5-830a-19428fe02301.png)

Is this to be expected when invoking the API rather than utilizing the frontend?

**Comment by MegaDrive68k** [comment]
Reproduced on 4.5.0 too. With the following job definition:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: d56c8c43-de29-4b17-8a0c-3cab8728df55
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: node01 '
  nodesSelectedByDefault: true
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: whoami
    keepgoing: false
    strategy: node-first
  uuid: d56c8c43-de29-4b17-8a0c-3cab8728df55
```

And running with the following  API call (defining other target nodes):

```bash
curl -X POST \
  'http://localhost:4440/api/41/job/d56c8c43-de29-4b17-8a0c-3cab8728df55/run?filter=node02' \
  --header 'Accept: application/json' \
  --header 'X-Rundeck-Auth-Token: Z0xoVbW1IriGfk92EpGqOGJ7lYmTsRc3' \
```

The job runs on that node:

![Screen Shot 2022-08-17 at 12 25 45](https://user-images.githubusercontent.com/51376003/185192624-98ac7ee4-b3d2-4a35-bc2c-4c7c7055e6e1.png)

Thank you for your feedback @booshlinux!
