### ISSUE TITLE
A way to disable Liquibase

### ISSUE THREAD

**Issue by gaspo53** [rundeck/rundeck#8111]
Hi, all. I've been facing a lot of situations on when Rundeck gets restarted (in Kubernetes) for some reason, the DB locks. I want to disable LIquibase like it's possible in Spring (spring.liquibase.enabled=false).
How can that property be passed to Spring?

Thanks

**Comment by pauljeffrey-BMW** [comment]
I am also having these issues in newer releases in our Kubernetes environment, some potential solutions that could be implemented here:
https://stackoverflow.com/questions/61387510/how-to-solve-liquibase-waiting-for-changelog-lock-problem-in-several-pods-in-ope
https://github.com/blagerweij/liquibase-sessionlock

**Comment by zsolt-p** [comment]
Hello, I had this problem too. GKE upgrades would leave our Rundeck deployments unable to restart due to the lock getting left there. We deploy RD using [this](https://artifacthub.io/packages/helm/eugen/rundeck) Helm chart.

My heavy-handed solution was to add an `initContainer` that makes sure the lock is gone just before RD starts:

```yaml
[ ... ]
initContainers:
  - name: clear-db-lock
    image: postgres:13-alpine
    command:
      - /bin/sh
      - -c
      - |
        PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "DROP TABLE IF EXISTS DATABASECHANGELOGLOCK;"
    env:
      - name: DB_HOST
        value: "${db_host}"
      - name: DB_USER
        value: "${db_user}"
      - name: DB_PASSWORD
        value: "${db_password}"
      - name: DB_NAME
        value: "${db_name}"
```
