### ISSUE TITLE
Notifications not received for Job Reference Workflow Step

### ISSUE THREAD

**Issue by wakeling-duncan** [rundeck/rundeck#8114]
Issue type: Bug report

Jobs with workflow step type 'Job Reference' do not send notifications when the notification is configured on the referenced job. The following error is received:
[2023-01-26T08:54:40,160] ERROR services.NotificationService [pool-209-thread-1] - Error sending notification email to d.wakeling@gordian.com for Execution 57: [views/execution/mailNotification/status.gsp:10] Error executing tag <g:render>: [views/execution/mailNotification/_oldStatus.gsp:318] Error executing tag <g:render>: could not initialize proxy [rundeck.Workflow#101] - no Session

* Rundeck version: 4.8.0
* install type: rpm
* OS Name/version: OEL 8
* DB Type/version: MS SQL

Expected Behaviour:
Notification set on referenced job will be received.

Steps to Reproduce:
Create job with Job Reference workflow step (referenced job has email notification set on start). Ensure 'Skip Notifications' is NOT checked.
Trigger parent job, no notification is received. (Notification is received if child job is triggered directly)

**Comment by MegaDrive68k** [comment]
Confirmed,

Happening on "on start" email notifications.

Child job:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 9ef09bfb-a938-4d07-99d4-21f265b5b31f
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  notification:
    onstart:
      email:
        attachLog: true
        attachLogInFile: true
        recipients: devopsteam@example.net
        subject: info
  notifyAvgDurationThreshold: null
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - plugins:
        LogFilter: []
      script: |-
        echo "Lore Ipsum"
    keepgoing: false
    strategy: node-first
  uuid: 9ef09bfb-a938-4d07-99d4-21f265b5b31f
```

Parent job:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c216010f-0687-47d6-90e8-e4943391e520
  loglevel: INFO
  name: ParentJob
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: ''
        name: HelloWorld
        uuid: 9ef09bfb-a938-4d07-99d4-21f265b5b31f
    keepgoing: false
    strategy: node-first
  uuid: c216010f-0687-47d6-90e8-e4943391e520

```

Thank you for your feedback @wakeling-duncan!
