### ISSUE TITLE
RUN-3011: Docker does not support using JettyRolePropertyFileLoginModule 

### ISSUE THREAD

**Issue by craph** [rundeck/rundeck#8255]
## Summary

Using `RUNDECK_JAAS_MODULES_1: JettyRolePropertyFileLoginModule` in Docker Env does not work, the remco template does ignores the JettyRolePropertyFileLoginModule value.

Original bug report below:

---

**Describe the bug**
Can't use role proprety file module with LDAP.

**My Rundeck detail**
With rundeck docker I'm unable to configure LDAP/AD authentication with ignoreRoles and Role mapping with the JettyRolePropertyFileLoginModule.

In the logs I always see LDAP roles listed so I think RUNDECK_JAAS_LDAP_IGNOREROLES: 'true' is not working correctly
```
INFO  audit.AuditLoggerPlugin - Audit Event: AuditEvent {Timestamp=Fri Apr 14 13:10:33 GMT 2023, ActionType='login_success', UserInfo={username='ldapuser1', userRoles=[....ROLE_FROM_LDAP...]
```

* Rundeck version: latest snapshot
* install type: docker
* OS Name/version: CentOS 7.9
* DB Type/version: h2 for testing

Here is my `docker-compose.yml` file configuration : 
```yaml
version: '3'

services:
  rundeck:
    image: ${RUNDECK_IMAGE:-rundeck/rundeck:SNAPSHOT}
    restart: always
    tty: true
    environment:
      RUNDECK_GRAILS_URL: http://myservername:4440
      RUNDECK_JAAS_MODULES_0: JettyCombinedLdapLoginModule
      RUNDECK_JAAS_LDAP_FLAG: sufficient
      RUNDECK_JAAS_LDAP_PROVIDERURL: ldap://ldap:389
      RUNDECK_JAAS_LDAP_BINDDN: "CN=myusers,OU=EU,OU=COMPANY,DC=com"
      RUNDECK_JAAS_LDAP_BINDPASSWORD: "mypassword"
      RUNDECK_JAAS_LDAP_AUTHENTICATIONMETHOD: simple
      RUNDECK_JAAS_LDAP_FORCEBINDINGLOGIN: 'true'
      RUNDECK_JAAS_LDAP_USERRDNATTRIBUTE: sAMAccountName
      RUNDECK_JAAS_LDAP_USERIDATTRIBUTE: sAMAccountName
      RUNDECK_JAAS_LDAP_USERPASSWORDATTRIBUTE: unicodePwd
      RUNDECK_JAAS_LDAP_USEROBJECTCLASS: user
      RUNDECK_JAAS_LDAP_ROLEBASEDN: "CN=myusers,OU=EU,OU=COMPANY,DC=com"
      RUNDECK_JAAS_LDAP_ROLENAMEATTRIBUTE: cn
      RUNDECK_JAAS_LDAP_ROLEMEMBERATTRIBUTE: member
      RUNDECK_JAAS_LDAP_ROLEOBJECTCLASS: group
      RUNDECK_JAAS_LDAP_CACHEDURATIONMILLIS: 300000
      RUNDECK_JAAS_LDAP_USERBASEDN: DC=COMPANY,DC=com
      RUNDECK_JAAS_LDAP_REPORTSTATISTICS: 'false'
      RUNDECK_JAAS_LDAP_IGNOREROLES: 'true'
      RUNDECK_JAAS_LDAP_STOREPASS: 'true'
      RUNDECK_JAAS_LDAP_USEFIRSTPASS: 'false'
      RUNDECK_JAAS_LDAP_TRYFIRSTPASS: 'false'


      RUNDECK_JAAS_MODULES_1: JettyRolePropertyFileLoginModule
      RUNDECK_JAAS_FILE_FLAG: required
      RUNDECK_JAAS_USEFIRSTPASS: 'true'
      RUNDECK_JAAS_DEBUG: 'true'

      RUNDECK_JAAS_MODULES_2: PropertyFileLoginModule
      RUNDECK_JAAS_FILE_FLAG: required
    volumes:
      - data:/home/rundeck/server/data
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
      - "/root/dockercomposefiles/rundeck/realm.properties:/home/rundeck/server/config/realm.properties"
    ports:
      - 4440:4440

volumes:
  data:
```
and here is my `realm.properties` file : 
```
#
# This file defines users passwords and roles for a HashUserRealm
#
# The format is
#  <username>: <password>[,<rolename> ...]
#
# Passwords may be clear text, obfuscated or checksummed.  The class
# org.mortbay.util.Password should be used to generate obfuscated
# passwords or password checksums
#
# This sets the temporary user accounts for the Rundeck app
#
admin:admin,user,admin
user:user,user
ldapuser1:-,user,admin
ldapuser2:-,user

#
# example users matching the example aclpolicy template roles
#
#project-admin:admin,user,project_admin
#job-runner:admin,user,job_runner
#job-writer:admin,user,job_writer
#job-reader:admin,user,job_reader
#job-viewer:admin,user,job_viewer
```

**To Reproduce**

1. Connect any LDAP account
2. I only see "You have no authorized access to projects"

**Expected behavior**
My LDAP account that I configured in Role Property File should have groups on Rundeck.
