### ISSUE TITLE
Error when authentication with default admin user if ldap login module is configured

### ISSUE THREAD

**Issue by craph** [rundeck/rundeck#8276]
**Describe the bug**
Why there is a stack trace from the ldap login module if I tried to login with the default admin user from realm.properties file and the authentication succeed ?

**My Rundeck detail**

* Rundeck version: latest snapshot
* install type: docker
* OS Name/version: CentOS 7.9
* DB Type/version: h2 for testing

Here is my `docker-compose.yml` file configuration : 
```yaml
version: '3'

services:
  rundeck:
    image: ${RUNDECK_IMAGE:-rundeck/rundeck:SNAPSHOT}
    restart: always
    tty: true
    environment:
      RUNDECK_GRAILS_URL: http://myservername:4440
      RUNDECK_JAAS_MODULES_0: JettyCombinedLdapLoginModule
      RUNDECK_JAAS_LDAP_FLAG: sufficient
      RUNDECK_JAAS_LDAP_PROVIDERURL: ldap://ldap:389
      RUNDECK_JAAS_LDAP_BINDDN: "CN=myusers,OU=EU,OU=COMPANY,DC=com"
      RUNDECK_JAAS_LDAP_BINDPASSWORD: "mypassword"
      RUNDECK_JAAS_LDAP_AUTHENTICATIONMETHOD: simple
      RUNDECK_JAAS_LDAP_FORCEBINDINGLOGIN: 'true'
      RUNDECK_JAAS_LDAP_USERRDNATTRIBUTE: sAMAccountName
      RUNDECK_JAAS_LDAP_USERIDATTRIBUTE: sAMAccountName
      RUNDECK_JAAS_LDAP_USERPASSWORDATTRIBUTE: unicodePwd
      RUNDECK_JAAS_LDAP_USEROBJECTCLASS: user
      RUNDECK_JAAS_LDAP_ROLEBASEDN: "CN=myusers,OU=EU,OU=COMPANY,DC=com"
      RUNDECK_JAAS_LDAP_ROLENAMEATTRIBUTE: cn
      RUNDECK_JAAS_LDAP_ROLEMEMBERATTRIBUTE: member
      RUNDECK_JAAS_LDAP_ROLEOBJECTCLASS: group
      RUNDECK_JAAS_LDAP_CACHEDURATIONMILLIS: 300000
      RUNDECK_JAAS_LDAP_USERBASEDN: DC=COMPANY,DC=com
      RUNDECK_JAAS_LDAP_REPORTSTATISTICS: 'false'
      RUNDECK_JAAS_LDAP_IGNOREROLES: 'true'
      RUNDECK_JAAS_LDAP_STOREPASS: 'true'

      RUNDECK_JAAS_MODULES_1: PropertyFileLoginModule
      RUNDECK_JAAS_FILE_FLAG: required
    volumes:
      - data:/home/rundeck/server/data
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
      - "/root/dockercomposefiles/rundeck/realm.properties:/home/rundeck/server/config/realm.properties"
    ports:
      - 4440:4440

volumes:
  data:
```
and here is my `realm.properties` file : 
```
#
# This file defines users passwords and roles for a HashUserRealm
#
# The format is
#  <username>: <password>[,<rolename> ...]
#
# Passwords may be clear text, obfuscated or checksummed.  The class
# org.mortbay.util.Password should be used to generate obfuscated
# passwords or password checksums
#
# This sets the temporary user accounts for the Rundeck app
#
admin:admin,user,admin
user:user,user
ldapuser1:-,user,admin
ldapuser2:-,user

#
# example users matching the example aclpolicy template roles
#
#project-admin:admin,user,project_admin
#job-runner:admin,user,job_runner
#job-writer:admin,user,job_writer
#job-reader:admin,user,job_reader
#job-viewer:admin,user,job_viewer
```

**To Reproduce**

1. Connect with the default admin/admin user
2. Check the logs and you will see 
```
rundeck_1  | javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 775, v4563]
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3259)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3205)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2991)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2905)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:266)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:226)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:284)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:185)
rundeck_1  |    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:115)
rundeck_1  |    at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730)
rundeck_1  |    at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
rundeck_1  |    at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
rundeck_1  |    at java.naming/javax.naming.InitialContext.<init>(InitialContext.java:208)
rundeck_1  |    at java.naming/javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
rundeck_1  |    at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.createBindUserDirContext(JettyCachingLdapLoginModule.java:970)
rundeck_1  |    at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.bindingLogin(JettyCachingLdapLoginModule.java:922)
rundeck_1  |    at com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.authenticate(JettyCachingLdapLoginModule.java:822)
rundeck_1  |    at com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule.login(JettyCombinedLdapLoginModule.java:161)
rundeck_1  |    at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:747)
rundeck_1  |    at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:672)
rundeck_1  |    at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:670)
rundeck_1  |    at java.base/java.security.AccessController.doPrivileged(Native Method)
rundeck_1  |    at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:670)
rundeck_1  |    at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:581)
rundeck_1  |    at org.springframework.security.authentication.jaas.AbstractJaasAuthenticationProvider.authenticate(AbstractJaasAuthenticationProvider.java:173)
rundeck_1  |    at org.rundeck.security.RundeckJaasAuthenticationProvider.super$2$authenticate(RundeckJaasAuthenticationProvider.groovy)
rundeck_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
rundeck_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
rundeck_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
rundeck_1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
rundeck_1  |    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
rundeck_1  |    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
rundeck_1  |    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
rundeck_1  |    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
rundeck_1  |    at org.rundeck.security.RundeckJaasAuthenticationProvider.authenticate(RundeckJaasAuthenticationProvider.groovy:39)
rundeck_1  |    at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
rundeck_1  |    at org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter.attemptAuthentication(UsernamePasswordAuthenticationFilter.java:85)
rundeck_1  |    at grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter.attemptAuthentication(GrailsUsernamePasswordAuthenticationFilter.groovy:53)
rundeck_1  |    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:231)
rundeck_1  |    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
rundeck_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
rundeck_1  |    at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
rundeck_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
rundeck_1  |    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
rundeck_1  |    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
rundeck_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
rundeck_1  |    at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
rundeck_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
rundeck_1  |    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225)
rundeck_1  |    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)
rundeck_1  |    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
rundeck_1  |    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
rundeck_1  |    at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
rundeck_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
rundeck_1  |    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
rundeck_1  |    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
rundeck_1  |    at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
rundeck_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
rundeck_1  |    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
rundeck_1  |    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
rundeck_1  |    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
rundeck_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
rundeck_1  |    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
rundeck_1  |    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
rundeck_1  |    at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
rundeck_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
rundeck_1  |    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
rundeck_1  |    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
rundeck_1  |    at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
rundeck_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
rundeck_1  |    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
rundeck_1  |    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
rundeck_1  |    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
rundeck_1  |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
rundeck_1  |    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
rundeck_1  |    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
rundeck_1  |    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
rundeck_1  |    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
rundeck_1  |    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
rundeck_1  |    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
rundeck_1  |    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
rundeck_1  |    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
rundeck_1  |    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
rundeck_1  |    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
rundeck_1  |    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
rundeck_1  |    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
rundeck_1  |    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
rundeck_1  |    at org.eclipse.jetty.server.Server.handle(Server.java:516)
rundeck_1  |    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
rundeck_1  |    at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
rundeck_1  |    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
rundeck_1  |    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
rundeck_1  |    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
rundeck_1  |    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
rundeck_1  |    at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
rundeck_1  |    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
rundeck_1  |    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
rundeck_1  |    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
rundeck_1  |    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
rundeck_1  |    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
rundeck_1  |    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
rundeck_1  |    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
rundeck_1  |    at java.base/java.lang.Thread.run(Thread.java:829)
```

**Expected behavior**
If the authentication succeed from the PropertyFileLoginModule why there is a stacktrace from le LDAP login module?
