### ISSUE TITLE
Multi-valued job with "default" values will always use default values if nothing is selected.

### ISSUE THREAD

**Issue by sinister3vil** [rundeck/rundeck#8314]
**Describe the bug**
When setting up a job option that allows multiple values and has a default value set, Rundeck will use that default value if no values are selected.

Google Groups discussion : https://groups.google.com/g/rundeck-discuss/c/fUvRheE8Z3Y

**My Rundeck detail**

* Rundeck version: 4.10.0 2023-02-13
* install type: docker
* DB Type/version: H2

**To Reproduce**

Import this job

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: TESTING
  id: 768ec45f-d9c5-45f5-a366-c98a6a2f6949
  loglevel: INFO
  name: test-multi-option
  nodeFilterEditable: false
  options:
  - delimiter: ','
    enforced: true
    multivalued: true
    name: groups
    value: '!group1,!group2'
    values:
    - '!group1'
    - '!group2'
    - '!group3'
    valuesListDelimiter: ','
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/bash

        echo "$RD_OPTION_GROUPS"
    keepgoing: false
    strategy: node-first
  uuid: 768ec45f-d9c5-45f5-a366-c98a6a2f6949
```

Make a selection, for option groups. Get the selected group list echo'd back.
Deselect everything, including default selected values. Get the default group list echo'd back.

**Expected behavior**
I'd expect that when nothing is selected RD_OPTION_GROUPS is empty, regardless if the job has default values set.

**Comment by MegaDrive68k** [comment]
Confirmed. I created the following job:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: eac8952d-347d-4400-bc2f-945c7884267a
  loglevel: INFO
  name: Hiya
  nodeFilterEditable: false
  options:
  - delimiter: ','
    multivalued: true
    name: user
    value: 'bob,charlie'
    values:
    - alice
    - bob
    - charlie
    valuesListDelimiter: ','
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo ${option.user}
    keepgoing: false
    strategy: node-first
  uuid: eac8952d-347d-4400-bc2f-945c7884267a
```

Deselecting all option values and running the job, the output prints the default values defined.

Thanks for your feedback @sinister3vil!
