### ISSUE TITLE
Rundeck 4.14.0 : display of yaml files with UI broken

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#8415]
**Describe the bug**

Display of yaml files with UI seems to be broken beginning with 4.14 update. This is what I get when I try to edit some yaml nodes file :

![image](https://github.com/rundeck/rundeck/assets/38751896/5ff36e59-9609-4131-88ca-21df529d1b93)

It has nothing to do with the file which is present on the server :

```
#****************
# RUNDECK
#****************
RUNDECK:
    tags: 'RDK'
    username: user
    description: Rundeck Server
    nodename: local.test
    hostname: local.test
    node-executor: ssh-exec
    ssh-password-storage-path: keys/test

#****************
# XXXXX  XXXXXX
#****************
SERV1:
    username: test
    nodename: local2.test
    hostname: local2.test
    tags: 'test'
    description: 'xx xxx'
    osName: Linux
    env: Test
    ssh-authentication: privateKey

#****************
# XXXX XXXX
#****************
SERV2:
    tags: 'data'
    username: test2
    description: 'test server'
    nodename: local3.test
    hostname: local3.test
    node-executor: ssh-exec
    ssh-password-storage-path: keys/test

```

If I rollback to 4.13 then the display is exactly the same as on the server and the file can be edited accordingly :

![image](https://github.com/rundeck/rundeck/assets/38751896/ba89a3db-2cbc-4140-a730-3c5be2ce2a42)

**My Rundeck detail**

* Rundeck version: 4.14.1
* install type: war
* OS Name/version: RHEL 7.9
* DB Type/version: Postgre

**Expected behavior**
Be able to edit yaml files with UI

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome/Firefox
 - Version: 114
