### ISSUE TITLE
Odd page when not allowing node info access

### ISSUE THREAD

**Issue by adolfocorreia** [rundeck/rundeck#844]
Rundeck 2.1.3 (RPM install)
RHEL 5.10
Java 7

I've created an ACL which, among other things, does not allow node info access to its users. I noticed that the 'Nodes' entry on the menu is not hidden (which I think should be the case) and that when the user clicks on it an odd page appears with a duplicated header bar.

Here is the aclpolicy file:

```
# Application scope
description: User, restricted access.
context:
  application: 'rundeck'
for:
  project:
    - match:
        name: 'WS_TST'
      allow: [read]
by:
  group: MyGroup

---

# Project scope
description: User, restricted access.
context:
  project: 'WS_TST'
for:
  resource:
    - equals:
        kind: event
      allow: [read] # allow read of all activity (jobs run by all users)
  job:
    - allow: [read, run] # allow read/run of all jobs
    - match:
        group: 'base.*'
      deny: [read] # hide jobs in group 'base' (they can still be run)
  node:
    - contains:
        tags: tst
      allow: [read, run] # allow nodes with the tag 'tst'
    - equals:
        rundeck_server: 'true'
      allow: [read, run] # allow rundeck server node
by:
  group: MyGroup
```

Here is the screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/4016175/3476657/243edba2-0304-11e4-9c17-14f950916e13.png)
