### ISSUE TITLE
Node source list empty in UI

### ISSUE THREAD

**Issue by AishahFatihahh** [rundeck/rundeck#8495]
**Describe the bug**
Node source list empty in UI

**My Rundeck detail**
  - Rundeck version: 4.15.0
  - Install type: Docker
  - OS Name/version: Red Hat release 8.8

**To Reproduce**
1. Create a project
2. Click on "Project settings -> Edit Nodes...", choose "Sources"
3. See the empty list (on screenshot)

**Expected behavior**
We should see a list of node sources

**Screenshots**
![image](https://github.com/rundeck/rundeck/assets/138760516/a7ee9e00-1275-4791-91cd-1f8fbfec13e6)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 115

**Additional context**
I already follow the guide from previous issues solved which to replace grails.serverURL from localhost to my server hostname and add server.useForwardHeaders=true in rundeck-config.properties, but still not solved yet.

**Comment by MegaDrive68k** [comment]
Hi @AishahFatihahh 

Does this issue happen accessing even your rundeck instance directly? (without proxy/lb). Is your grails.serverURL parameter configured by using the rundeck proxy exit url? Could you double check your proxy/lb config?

I tried sucessfully by using this test docker environment:

docker-compose file:

```yaml
version: "3"
services:
  rundeck:
    image: rundeck/rundeck:4.15.0
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: http://rundeckcl
      RUNDECK_SERVER_FORWARDED: "true"
  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - 80:80
```

nginx/nginx.conf file:

```config
server {
    listen 80 default_server;
    server_name rundeckcl;

    # default rundeck location is the root 
    location / {
        # took from default rundeck conf
        proxy_pass http://rundeck:4440;
     }
}
```

![Screenshot_2023-08-18_09-24-38](https://github.com/rundeck/rundeck/assets/51376003/3b3d8f1c-be33-4489-bdeb-81236dda3537)
