### ISSUE TITLE
 minimal job definition example is incorrect: sequence/exec

### ISSUE THREAD

**Issue by philoserf** [rundeck/rundeck#854]
http://rundeck.org/2.1.3/man5/job-yaml.html presents a minimal job definition example that is not correct.

``` yaml
name: job name
description: ''
loglevel: INFO
sequence:
  - exec: a command
```

http://rundeck.org/2.1.3/man5/job-yaml.html#sequence shows `commands:` is required between `sequence:` and `-exec: a command`.

``` yaml
- # test job
  name: job name
  description: ''
  loglevel: INFO
  sequence:
    commands:
      - exec: a command
```
