### ISSUE TITLE
`uuud:` is not required despite text of job-yaml man5

### ISSUE THREAD

**Issue by philoserf** [rundeck/rundeck#855]
http://rundeck.org/2.1.3/man5/job-yaml.html#job-map-contents indicates `uuid:` is required. Yet the example in the docs and the corrected example below have no defined: `uuid:`.

While UUID is important and required internally it appears not to be required in the `job.yml`.

incorrect example from man5

``` yaml
name: job name
description: ''
loglevel: INFO
sequence:
  - exec: a command
```

working example 

``` yaml
- # test job
  name: job name
  description: ''
  loglevel: INFO
  sequence:
    commands:
      - exec: a command
```
