### ISSUE TITLE
[Bug report] "Allowed Values | List" / "Allowed Values | Remote URL" bug with "Restrictions | Enforced from Allowed Values"

### ISSUE THREAD

**Issue by pgmgb** [rundeck/rundeck#8569]
**Describe the bug**
We started to use `Allowed Values | List` to specify some preconfigured values. Over time, we moved to `Allowed Values | Remote URL`. This will allow us to reuse the `allowed values` for different jobs and also to manged the result centralized.

Unfortunately, we encountered the problem, that after selecting `Allowed Values | Remote URL`, the old values of `Allowed Values | List` were still used during validation.

![list_bug](https://github.com/rundeck/rundeck/assets/94605888/1cd31bad-9fdc-49a3-b4ba-d6c2fd34a55f)

It's also visible inside the exported job:

```yml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: Testing
  id: 7627a665-c67c-4850-8768-afad4bb252ff
  loglevel: INFO
  name: list-remote-url-bug
  nodeFilterEditable: false
  options:
  - enforced: true
    label: value
    name: value
    required: true
    sortValues: true
    values:
    - '1'
    - '2'
    - '3'
    valuesListDelimiter: ','
    valuesUrl: https://mocki.io/v1/0f58bdc3-82ca-454f-bfb7-08d60d9dd3a9
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo "$RD_OPTION_VALUE"
    keepgoing: false
    strategy: node-first
  uuid: 7627a665-c67c-4850-8768-afad4bb252ff
```

**My Rundeck detail**

* Rundeck version: 4.15.0
* install type: Kubernetes container
* OS Name/version: Ubuntu 20.04.6 LTS
* DB Type/version: mysql

**To Reproduce**
1. Create a new job with an option which uses the `Allowed Values | List`.
2. Save the newly created job.
3. Updated the job and use `Allowed Values | Remote URL` which will provide new values which are not inside `Allowed Values | List`.
4. Execute the job with one of the new values.
5. See error

**Expected behavior**
When using `Allowed Values | Remote URL`, the `Restrictions | Enforced from Allowed Values` should use the values from `Allowed Values | Remote URL`.

**Screenshots**
See in `Describe the bug`.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version 116.0.5845.188
