### ISSUE TITLE
[Bug report] Protocol & port as ${globals.*} in "Allowed Values | Remote URL" is not possible

### ISSUE THREAD

**Issue by pgmgb** [rundeck/rundeck#8570]
**Describe the bug**
We use two Rundeck environments (dev & prod) and need to stage jobs between these two environments. For that, we enabled the `SCM` integration, which works perfectly. Inside the jobs, we use the `Allowed Values | Remote URL` possibility to load common values.  The `Remote URL` is not the same for the two environments. Therefore, we needed a way to set each `Remote URL` depending on where the job is executed. We came up with the solution to use [Global execution variables](https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html#global-execution-variables), which looks like the following:

```bash
framework.globals.url_protocol=https
framework.globals.url_hostname=mocki.io
framework.globals.url_port=443
```

In the end, the  `Allowed Values | Remote URL` would look like `${globals.url_protocol}://${globals.hostname}:${globals.port}/v1/0f58bdc3-82ca-454f-bfb7-08d60d9dd3a9`

The job definition would look like:
```yml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  group: Testing
  id: 7627a665-c67c-4850-8768-afad4bb252ff
  loglevel: INFO
  name: remote-url-import-bug
  nodeFilterEditable: false
  options:
  - enforced: true
    label: value
    name: value
    required: true
    sortValues: true
    valuesListDelimiter: ','
    valuesUrl: ${globals.url_protocol}://${globals.url_hostname}:${globals.url_port}/v1/0f58bdc3-82ca-454f-bfb7-08d60d9dd3a9
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo "$RD_OPTION_VALUE"
    keepgoing: false
    strategy: node-first
  uuid: 7627a665-c67c-4850-8768-afad4bb252ff
```

Unfortunately, importing the above definition will result in the following error:
`org.rundeck.app.components.jobs.JobDefinitionException: Unable to create Job: no protocol: ${globals.url_protocol}://${globals.url_hostname}:${globals.url_port}/v1/0f58bdc3-82ca-454f-bfb7-08d60d9dd3a9`

**My Rundeck detail**

* Rundeck version: 4.15.0
* install type: Kubernetes container
* OS Name/version: Ubuntu 20.04.6 LTS
* DB Type/version: mysql

**To Reproduce**
1. Upload the provided job definition.

**Expected behavior**
Importing jobs with `Allowed Values | Remote URL` looking like `${globals.url_protocol}://${globals.url_hostname}:${globals.url_port}/v1/0f58bdc3-82ca-454f-bfb7-08d60d9dd3a9` should work.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 116.0.5845.188

**Comment by MegaDrive68k** [comment]
Reproduced, it seems the options can't get the globals as steps do.

Even on labels and direct values like the following example:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 6594dcb5-0efd-4588-9bd4-f0c9723679a9
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  options:
  - label: ${globals.protocol}
    name: opt1
    value: ${globals.protocol}
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo ${option.opt1}
    keepgoing: false
    strategy: node-first
  uuid: 6594dcb5-0efd-4588-9bd4-f0c9723679a9
``` 

This example tries to call a project level global:

`project.globals.protocol=https`

Thanks for your feedback @pgmgb!
