### ISSUE TITLE
[Bug report] Allowed Values | Remote URL | Json Path Filter unexpected behavior

### ISSUE THREAD

**Issue by pgmgb** [rundeck/rundeck#8573]
**Describe the bug**
We try to use the `Allowed Values | Remote URL | Json Path Filter` integration to get specific keys from a result. For example, the following mock API:
https://mocki.io/v1/a34fe7a4-4599-4490-bd61-9deda5f5b2aa
```json
{
  "output": [ "A", "B"]
}
```

For my understanding, the JSON path `$.output[*]` would result in (https://jsonpath.com/):
```json
[
  "A",
  "B"
]
```

This should be a valid [JSON format](https://docs.rundeck.com/4.15.0/manual/job-options.html#json-format) for Rundeck options. But somehow, this will result in the error `Exception: java.lang.Exception: the filter $.output[*] return a list, please use another filter
URL: https://mocki.io/v1/a34fe7a4-4599-4490-bd61-9deda5f5b2aa`:

![image](https://github.com/rundeck/rundeck/assets/94605888/3ec23bbc-87e4-4a78-93a6-504e61882f46)

The second mock API returns directly the result without the use of JSON path - and works as expected:
https://mocki.io/v1/15c52045-eba7-4330-8f4b-c3b30c6abe2c
```json
[ "A", "B"]
```
My job definition:
```yml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 6ea0623d-9016-43db-907e-aaaa1c88d7ce
  loglevel: INFO
  name: remote-url-json-path
  nodeFilterEditable: false
  options:
  - configRemoteUrl:
      jsonFilter: $.output[*]
    enforced: true
    name: json_path
    required: true
    valuesUrl: https://mocki.io/v1/a34fe7a4-4599-4490-bd61-9deda5f5b2aa
  - enforced: true
    name: remote_url
    required: true
    sortValues: true
    valuesUrl: https://mocki.io/v1/15c52045-eba7-4330-8f4b-c3b30c6abe2c
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - script: '#'
    keepgoing: false
    strategy: node-first
  uuid: 6ea0623d-9016-43db-907e-aaaa1c88d7ce
```

**My Rundeck detail**

* Rundeck version: 4.15.0
* install type: Kubernetes container
* OS Name/version: Ubuntu 20.04.6 LTS
* DB Type/version: mysql

**To Reproduce**
1. Import the job definition
2. Open the job, so the remote values will be loaded

**Expected behavior**
Using the following mock API with the JSON path `$.output[*]` should render the retrieved values successfully as option:
https://mocki.io/v1/a34fe7a4-4599-4490-bd61-9deda5f5b2aa
```json
{
  "output": [ "A", "B"]
}
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 116.0.5845.188
