### ISSUE TITLE
[Bug report] Job log output, follow setting is not functional

### ISSUE THREAD

**Issue by hal9000jw** [rundeck/rundeck#8574]
**Describe the bug**
Job log output, follow setting is not functional.

**My Rundeck detail**
* Rundeck version: 4.17.0
* install type: deb
* OS Name/version: ubuntu 22.04
* DB Type/version: postgres 14.9

**To Reproduce**
1. Execute job
2. Verify that 'Follow' is enabled.
3. See that automatic scrolling is not functional.

**Expected behavior**
That job log output would scroll automatically.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Browser: Chrome, Firefox
 - Version: Chrome 117.0.5938.92, Firefox 117.0.1

**Additional context**
The previous rundeck version 4.15.0 did not have this issue.

**Comment by MegaDrive68k** [comment]
Confirmed, thanks for your feedback @hal9000jw!

I used this job to test it:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: c40b501b-60e9-4c6b-b71a-0732aa29a04e
  loglevel: INFO
  name: ScrollTest
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - fileExtension: .sh
      interpreterArgsQuoted: false
      script: |-
        while true;
        do
         date=$(date +%N)
         echo $date ;
         sleep  1 ;
        done
      scriptInterpreter: /bin/bash
    keepgoing: false
    strategy: node-first
  uuid: c40b501b-60e9-4c6b-b71a-0732aa29a04e
```
