### ISSUE TITLE
[Bug report] Remote URL Job Options | Cascading Remote Options does not clear previous loaded values

### ISSUE THREAD

**Issue by pgmgb** [rundeck/rundeck#8587]
**Describe the bug**
We use [Cascading Remote Options](https://docs.rundeck.com/4.15.0/manual/job-options.html#cascading-remote-options) to load values from [remote url](https://docs.rundeck.com/4.15.0/manual/job-options.html#remote-url-job-options) depending on the previous selected values. When `Restrictions | None Any values can be used`, `Multi-valued | Yes` and `Multi-valued | Select All Values by Default` are set for the option, the previous loaded values will not be cleared when loading new values because of cascading.

We have a Rundeck job, which should be able to update users of an application. For that, we created the following job:

**Application API**
https://mocki.io/v1/1b95d58b-f2fc-49af-921a-f40cfad492ea
```json
[
	{
		"name": "Application 1",
		"value": "725d33c6-fd28-4af7-a4fa-c2764bed526b"
	},
	{
		"name": "Application 2",
		"value": "9bad66b1-80d8-428c-9a9b-2497bad80ba9"
	}
]
```

**User Application 1**
https://mocki.io/v1/725d33c6-fd28-4af7-a4fa-c2764bed526b
`["user1", "user2", "user3"]`

**Users Application 2**
https://mocki.io/v1/9bad66b1-80d8-428c-9a9b-2497bad80ba9
`["user1", "user4", "user5"]`

**Rundeck job definition**
```yml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: f05ce6f9-9fba-4b08-a6ca-002415a54be6
  loglevel: INFO
  name: Cascading Remote Options
  nodeFilterEditable: false
  options:
  - enforced: true
    name: Application
    required: true
    sortValues: true
    valuesUrl: https://mocki.io/v1/1b95d58b-f2fc-49af-921a-f40cfad492ea
  - delimiter: ','
    multivalueAllSelected: true
    multivalued: true
    name: User
    required: true
    sortValues: true
    valuesUrl: https://mocki.io/v1/${option.Application.value}
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - script: '#'
    keepgoing: false
    strategy: node-first
  uuid: f05ce6f9-9fba-4b08-a6ca-002415a54be6
```

When loading the job, application `Application 1` will be selected as default and the corresponding users were loaded.
![image](https://github.com/rundeck/rundeck/assets/94605888/9410d303-9066-4f6e-adbe-00d375886f7d)

When changing the application to `Application 2`, the users of the application will be loaded and selected, but the previous users of `Application 1` are still present as unselected users.
![image](https://github.com/rundeck/rundeck/assets/94605888/fb796ccd-4bff-4f8e-9089-228bc12bf6bb)

When changing back to `Application 1`, duplicated values will appear.
![image](https://github.com/rundeck/rundeck/assets/94605888/6ece6abd-3c6d-4769-8567-a29188b47f67)

My expectation would be, that the previous loaded (or added) values were cleared before loading the new values from the remote url.

**My Rundeck detail**

* Rundeck version: 4.15.0
* install type: Kubernetes container
* OS Name/version: Ubuntu 20.04.6 LTS
* DB Type/version: mysql

**To Reproduce**
1. Import the provided job definition
2. Open the job and load the select `Application 1`
3. Select `Application 2`
4. Select `Application 1`
5. See duplicated entries

**Expected behavior**
I would expect, that the loaded (or added) values were cleared before loading new values from the remote url.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: 116.0.5845.188
