### ISSUE TITLE
Bug with roles parsing

### ISSUE THREAD

**Issue by fbacchella** [rundeck/rundeck#8711]
I’m running rundeck 4.17.3.

The authentication I’m using inject roles directly as DN entry from our AD, and look like `CN=XXX,OU=Groups,OU=XX,OU=EU,OU=XX, DC=XX,DC=XX,DC=com`.

But when creating a token, it really doesn’t like the comma and split it as multiple groups:
— CN=XXX
— OU=Groups
....

The split seems to be done internally, as even if no group are provided, that means all groups, it’s still splited.

* Rundeck version:  4.17.3-20231113 
* install type: rpm, the war is embedded in custom tomcat, and using an Apache as a front end for SSO.
* OS Name/version: rockylinux 8.8
* DB Type/version: mysql

**To Reproduce**
1. Go to `Profile`
2. Click on '+' for a User API Token
3. Create a token with empty roles 
4. Using the API, list the tokens at `/api/45/tokens`. The new token roles are:
    ```
    "roles": [
      "cn=XXX",
      "ou=XXX",
   ]
```
 where it should be:
    ```
    "roles": [
      "cn=XXX,ou=XXX,....",
   ]
```

**Additional context**

This problem arise because I’m using an SSO solution in Apache front end that return users' groups as DN entry from our AD. And rundeck split them around the comma.

The authentication in `rundeck-config.properties` is configured as:

```
rundeck.jaaslogin=false
rundeck.security.authorization.preauthenticated.enabled=true
rundeck.security.authorization.preauthenticated.userSyncEnabled=true
rundeck.security.authorization.preauthenticated.attributeName=CAS-memberOf
rundeck.security.authorization.preauthenticated.userNameHeader=CAS-uid
rundeck.security.authorization.preauthenticated.userRolesHeader=CAS-memberOf
rundeck.security.authorization.preauthenticated.delimiter=;
rundeck.security.authorization.preauthenticated.userFirstNameHeader=CAS-firstName
rundeck.security.authorization.preauthenticated.userLastNameHeader=CAS-lastName
rundeck.security.authorization.preauthenticated.userEmailHeader=CAS-mail
```

This fails only for tokens, the ACL policies, configured using full DN works as expected:
```
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group:
    - 'cn=XXX,ou=XXX,...'
---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group:
    - 'cn=XXX,ou=XXX,...'
```
