### ISSUE TITLE
Rundeck targets the Rundeck server in Ansible playbooks instead of honoring the inventory file

### ISSUE THREAD

**Issue by lbp-code** [rundeck/rundeck#8712]
**Describe the bug**
I have a job that executes an Ansible playbook as a "Workflow step". The job uses an inventory file for the execution: "-i staging.ini". In that inventory file, the Rundeck server is NOT listed.
The Ansible playbook has the targets: "- hosts: all"
When running the playbook via Rundeck, it tries to target the Rundeck server, which shouldn't.
I set the "Disable limit" both to "Yes" and "No" (or check/unchecked) and the results are the same.

**My Rundeck detail**

* Rundeck version: 4.17.3
* install type: deb
* OS Name/version: ubuntu 20.04
* DB Type/version: mysql

**To Reproduce**
1. Create a playbook with this code:
```
- hosts: all
  user: ansible
  become: yes

  tasks:
  - name: Ping
    ping:
```
2. Create an inventory file 'staging.ini' like this:
```
[staging_servers]
staging-server1 
staging-server2
```
3. Create a Rundeck job with:

Workflow Steps --> Ansible Playbook
Ansible base directory path: /etc/ansible/playbooks/temp-lbp/
Playbook: test-hosts-limit.yml
Extra Ansible arguments: -i staging.ini
Disable Limit: Yes

Nodes --> Execute locally

4. Execute and see error

> com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[lbp-rundeck-server]}
> 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.validateNodeSet(BaseWorkflowExecutor.java:880)
> 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:92)
> 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:220)
> 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:95)
> 	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:146)
> 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:77)
> Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[lbp-rundeck-server]}
> No matched nodes: MultiNodeSelector{nodenames=[lbp-rundeck-server]}
> 

**Expected behavior**
Ansible playbook should connect exclusively to the servers in the inventory file staging.ini.

**Screenshots**
Here is how the execution works from the command line:

```
root@lbp-rundeck-server:/etc/ansible/playbooks/temp-lbp# sudo -u rundeck ansible-playbook test-hosts-limit.yml -i staging.ini 

PLAY [all] ******************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************
ok: [staging-server1]
ok: [staging-server2]

TASK [Ping] *****************************************************************************************************************************************************
ok: [staging-server1]
ok: [staging-server2]

PLAY RECAP ******************************************************************************************************************************************************
staging-server1            : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
staging-server2            : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

root@lbp-rundeck-server:/etc/ansible/playbooks/temp-lbp# 
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 119

**Comment by lbp-code** [comment]
I was able to work around it: instead of Nodes "Execute locally" I selected "Dispatch to nodes" and forced the node selection to the Rundeck server.
That configuration worked OK

I think the option "Execute locally" should behave like that.

But I can't help wonder if this is by design. Can someone clarify?


Btw, the other jobs I have are configured as "Execute locally". They use an inventory file too, but the Ansible playbooks they execute don't have "- hosts: all" but something like "- hosts: someservergroup"

Thank you

**Comment by MegaDrive68k** [comment]
Hi, I tried successfully on 4.17.3 

![Screenshot_2023-12-04_09-19-00](https://github.com/rundeck/rundeck/assets/51376003/463c819c-8699-4df9-8272-41123e531164)

The  inventory file:

```ini
[the_farm]
192.168.56.20
192.168.56.21
192.168.56.22

[the_farm:vars]
ansible_user=vagrant
```

Job definition example:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: d21a67dc-aa24-4e1f-bb05-79591287342f
  loglevel: INFO
  name: HelloWorld
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        ansible-base-dir-path: /path/to/ansible/project/
        ansible-become: 'false'
        ansible-disable-limit: 'true'
        ansible-extra-param: -i hosts
        ansible-playbook: ping.yml
        ansible-ssh-passphrase-option: option.password
        ansible-ssh-use-agent: 'false'
      nodeStep: false
      type: com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep
    keepgoing: false
    strategy: node-first
  uuid: d21a67dc-aa24-4e1f-bb05-79591287342f
```

I'm using your playbook:

```yaml
- hosts: all
  user: ansible
  become: yes

  tasks:
  - name: Ping
    ping:
```

Could you share your job definition example? Probably I'm missing something.

Thanks!
