### ISSUE TITLE
Assets Behind Proxy with Url Path not Mapped Correctly

### ISSUE THREAD

**Issue by adjinugroho** [rundeck/rundeck#8819]
**Describe the bug**
I deployed rundeck app to Ubuntu with deb install and put it behind Nginx with url path. The url path is correct (the page was loaded), but the assets (css, js, svg) for the page is not loaded.

Checking the dev console and it seems the path is not added to the url when the page call the assets. When I try to add the path manually, I can get the asset correctly.

**My Rundeck detail**

* Rundeck version: 5.0.1
* install type: deb
* OS Name/version: Ubuntu 22.04
* DB Type/version: postgres

**To Reproduce**
1. Install rundeck
2. Change framework.server.url value to http://[someurl]/rundeck in framework.properties file
3. Change grails.serverURL value to http://[someurl]/rundeck in rundeck-config.properties file
4. Add server.address with value 0.0.0.0 in rundeck-config.properties file
5. Add server.contextPath with value /rundeck in rundeck-config.properties file
6. Open the page in browser
7. Open the browser console
8. See error

**Expected behavior**
Page loaded with asset correctly

**Screenshots**
![image](https://github.com/rundeck/rundeck/assets/10370492/b04d8ec0-4371-464b-9b09-cf3e3cc59f77)
framework.properties

![image](https://github.com/rundeck/rundeck/assets/10370492/cc762eb4-3764-4ae1-9bec-ff4ea49f3d30)
rundeck-config.properties

![image](https://github.com/rundeck/rundeck/assets/10370492/4d0adc31-066b-4298-bcf7-dca7e41ca57b)
Nginx configuration

![image](https://github.com/rundeck/rundeck/assets/10370492/5bfaeac4-81d2-43d7-9bb4-a0670a62d63a)
Login page

![image](https://github.com/rundeck/rundeck/assets/10370492/cd008d68-61ce-430c-b75c-c6881e9b814d)
Dev console

![image](https://github.com/rundeck/rundeck/assets/10370492/11f81477-a03f-4365-926a-829898b0f070)
Manually add the rundeck path and get the correct asset

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge

**Comment by MegaDrive68k** [comment]
Hi @adjinugroho 

I'm trying to reproduce your issue unsuccessfully.

![Screenshot_2024-01-17_10-25-32](https://github.com/rundeck/rundeck/assets/51376003/026ae44f-6f3a-4e16-a9d9-77fda16a3553)

Here are my config:

`docker-compose.yaml`:

```yaml
version: "3"
services:
  rundeck:
    image: rundeck/rundeck:5.0.1
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: http://rundeckcl/rundeck/
      RUNDECK_SERVER_FORWARDED: "true"
      RUNDECK_SERVER_CONTEXTPATH: /rundeck
  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - 80:80
 ```

Here you can see that I'm using the RUNDECK_GRAILS_URL, RUNDECK_SERVER_FORWARDED, RUNDECK_SERVER_CONTEXTPATH.

So, regarding your config, add the `server.servlet.context-path=/rundeck` on your `rundeck-config.properties` file (is defined as `RUNDECK_SERVER_CONTEXTPATH` on my Docker YAML file).

Also, test using the `X-Forwarded-*` headers like [this](https://docs.rundeck.com/docs/administration/cluster/loadbalancer/NGINX.html#nginx-open-source-config-example) example.

nginx.conf:

```
server {
    listen 80 default_server;
    server_name rundeckcl;

    # default rundeck location is the root 
    location /rundeck/ {
        # took from default rundeck conf
        proxy_pass http://rundeck:4440;
     }
}
````

Greetings.
