### ISSUE TITLE
GroovyRuntimeException in job after upgrading from 4.17.4 to 5.0.1

### ISSUE THREAD

**Issue by xavier8854** [rundeck/rundeck#8896]
**Describe the bug**
After upgrading from 4.17.4 to 5.0.1, some jobs fail to run with error 
```
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.rundeck.plugin.scriptnodestep.ScriptFileNodeStepExecutor(null, Boolean, null, null, String, null, null)
```

**My Rundeck detail**

* Rundeck version: 5.0.1
* install type: RPM
* OS Name/version: RHEL7/8
* DB Type/version: mysql

**To Reproduce**

1.  Upgrade from 4.17.4 to 5.0.1
2. Launch a job (definition attached)
3. See the above error (stacktrace attached)

**Expected behavior**
Job running without error

**Screenshots**
[rundeck-bug-log.txt](https://github.com/rundeck/rundeck/files/14207344/rundeck-bug-log.txt)
[Supervision_Instances_Rundeck.yaml.txt](https://github.com/rundeck/rundeck/files/14207345/Supervision_Instances_Rundeck.yaml.txt)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Additional context**
Downgrading to 4.17.4 (with database restore) restores operation

**Comment by MegaDrive68k** [comment]
Hi @xavier8854 

Tried to reproduce (unsuccessfully) your issue by replacing the Perl script with a basic  hello world as follows:

```perl
#!/usr/bin/perl 
  
# Modules used 
use strict; 
use warnings; 
  
# Print function  
print("Hello World\n"); 
```

So, this is my job:

```yaml
- defaultTab: output
  description: Supervision des 6 serveurs Rundeck
  executionEnabled: true
  id: e3fcb8d7-04fa-4d97-99c9-7e53f3006668
  loglevel: INFO
  name: Supervision Instances Rundeck
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: null
  schedule:
    dayofmonth:
      day: '*'
    month: '*'
    time:
      hour: '*'
      minute: 0/5
      seconds: '0'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - scriptfile: /home/user/Downloads/hello.pl
    keepgoing: false
    strategy: node-first
  timeout: 10s
  uuid: e3fcb8d7-04fa-4d97-99c9-7e53f3006668
```

I tested updating 4.17.4 to 5.0.1 on MySQL 8.0.33.

1. What do see in the execution if you enable the job debug mode?
2. Did you test altering the work before saving it again?
3. Could you please run my script/job?

Regards.
