### ISSUE TITLE
Node filter input field missing in "Execute Job" popup

### ISSUE THREAD

**Issue by rlueckl** [rundeck/rundeck#9053]
**Describe the bug**
Since 5.1.2 the input field for "Change the Target Nodes" is missing in the small popup when clicking on the green "play" button in the job list which opens up the "Execute Job" popup. Opening the job's page first the field is there and can be used.

**My Rundeck detail**

* Rundeck version: 5.1.2
* install type: deb
* OS Name/version: Debian 11 Bullseye
* DB Type/version: postgres

**To Reproduce**
1. Create a job with an editable filter (or use the provided example below)
2. Click on Jobs
3. Click on the little green "play" button in front of the job name
4. Popup "Execute Job" opens up
5. Click on "Change the Target Nodes"
6. The node filter is missing!

**Expected behavior**
The node filter should be visible just as it is on the job's page.

**Screenshots**
Broken:
![testjob_missing_filter](https://github.com/rundeck/rundeck/assets/10848041/3ed42f8a-8123-4169-8049-ae0a2526ab0f)
Working:
![testjob_with_filter](https://github.com/rundeck/rundeck/assets/10848041/56d9f820-580b-463b-9c24-aca6839eac17)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 Virginia
 - Browser firefox
 - Version 124.0.2

**Additional context**
Testjob to import: 
```
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 20ad65fc-e38f-4097-9219-5618b6e1a6d2
  loglevel: WARN
  name: testjob
  nodeFilterEditable: true
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ''
  nodesSelectedByDefault: true
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo "hello"
    keepgoing: false
    strategy: node-first
  uuid: 20ad65fc-e38f-4097-9219-5618b6e1a6d2
```
