### ISSUE TITLE
Help Needed: Passing Node Enhancer Tags to Ansible Dynamic Inventory

### ISSUE THREAD

**Issue by kedar9696** [rundeck/rundeck#9185]
I am currently using Rundeck to manage and orchestrate my Azure VMs. 
  My setup involves using an **azure_rm.yml** inventory file to discover nodes.
  After nodes discovered i am applying tags using the Node Enhancer feature in Rundeck. 
  My goal is to pass these enhanced tags to Ansible when Rundeck generates a dynamic inventory.

below is the content of **azure_rm.yml** inventory which i passed to rundeck to fetch azure vms and rundeck uses this inventory as input to generates its own inventory.

```
plugin: azure.azcollection.azure_rm  # Specifies the Azure dynamic inventory plugin
cloud_environment : "AzureCloud"
auth_source: auto  # Automatically determines the authentication source
include_vm_resource_groups:  # List of Azure resource groups to include
  - "decops-aero"

regions:  # List of Azure regions to include
  - centralindia

plain_host_names: yes  # Use plain host names instead of the FQDN
strict_permissions: false  # Do not enforce strict permissions
allow_duplicated_hosts: false  # Do not allow duplicated hosts

conditional_groups:
  logstash_hosts: '"logstash_hosts" in tags.values()'
    
use_extra_vars: true  # Allow use of extra variables in the inventory

# Compose variables to set for each host
compose:
  ansible_host: public_ip_address[0].ipv4_address
  ansible_user: "'azureuser'"
  zookeeper_id: tags.zookeeper_id  # Set the zookeeper_id from the tags
  kafka_broker_id: tags.kafka_broker_id  # Set the kafka_broker_id from the tags
  crate_node_master: tags.crate_node_master  # Set the crate_node_master from the tags
  cluster_name: "'cracluster'"
  opt_dir: "'/opt'"
  data_dir: "'/data'"
  spark_dir: "'/opt/spark'"
  cra_dir: "'/opt/cra'"
  cra_nexus_repo_url: "'https://jfrog.independent.com/repository'"

```

**Requiremet** : don't want to give any tags to vm in azure portal ,instead of that want to give tags through node enhancer and pass that tags to ansible to include it in dynamic inventory and filter out nodes and run playbook on the nodes which matches this tags given by node enhancer.
