### ISSUE TITLE
Global Log Filters Not Applied in Referenced Jobs

### ISSUE THREAD

**Issue by adriamarcovalm** [rundeck/rundeck#9196]
**Describe the bug**

When creating a job in Rundeck with a "Global Log Filter" of type "Highlight Output," it works correctly when the job is executed. However, when this job is executed within the workflow of another job as a "Job Reference," the "Global Log Filters" of the referenced job is not applied in the logs.

This issue only occurs when a "Key Value Data" is defined as "Global Log Filter"  **in the main job** with **"Log Data" enabled** and the pattern is modified in a **script before referenced job**. Please look "To Reproduce" section for details.

**My Rundeck detail**

* Rundeck version: 5.1.2
* install type: deb
* OS Name/version: Red Hat 9.3
* DB Type/version: Postgresql 13.13

**To Reproduce**
1. Create a new job and configure a global log filter of type "Highlight Output."
2. Set a "Global log Filter" highlight with the pattern "Active.*".
3. Create a script step with a ```echo "Active:"```
4. Save and execute the job directly to verify that the global log filter works as expected.
5. Create another job and add "Global log Filter" " Key Value Data" with pattern "^RUNDECK:DATA:\s*([^\s]+?)\s*=\s*(.+)$"
6. Create a script step with ```echo 'RUNDECK:DATA:S=HOLA';```
7. In the next job step, creates a job step with the job previously created as a "Job Reference" in its workflow.
8. Execute the main job and observe the logs of the referenced job.
9. Notice that the global log filters are not applied in the logs of the referenced job.

**Expected behavior**
The global log filters configured in the referenced job should be applied and visible in the logs when the main job is executed,

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 119.0.6045.160

**Comment by MegaDrive68k** [comment]
Hi, I tried the following basic way (Rundeck 5.1.2/5.3.0):

Parent Job:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 134d0c9b-b182-4602-ae2b-8323eae13cc8
  loglevel: INFO
  name: Parent
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: ''
        name: Child
        uuid: dbb4e70e-3d95-4f3c-86b2-94d6acb75ec0
    keepgoing: false
    strategy: node-first
  uuid: 134d0c9b-b182-4602-ae2b-8323eae13cc8
```

Child Job:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: dbb4e70e-3d95-4f3c-86b2-94d6acb75ec0
  loglevel: INFO
  name: Child
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - script: echo 'mykey=myvalue';
    keepgoing: false
    pluginConfig:
      LogFilter:
      - config:
          invalidKeyPattern: \s|\$|\{|\}|\\
          logData: 'true'
          regex: (.*)=(.*)
          replaceFilteredResult: 'false'
        type: key-value-data
    strategy: node-first
  uuid: dbb4e70e-3d95-4f3c-86b2-94d6acb75ec0
```

However, I wasn't able to reproduce the issue. Could you provide a reproducible example to take a look at? Probably I'm missing something.

Thank you!

**Comment by adriamarcovalm** [comment]
Parent Job:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 13fdf3e4-4f08-448a-bef2-c605263f504a
  loglevel: INFO
  name: parent job
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - script: echo 'RUNDECK:DATA:Servidors=HOLA'
    - jobref:
        group: ''
        name: child job
        nodeStep: 'true'
        uuid: 35fb04c4-d7ba-4155-b2ed-fd715ba88603
    keepgoing: false
    pluginConfig:
      LogFilter:
      - config:
          invalidKeyPattern: \s|\$|\{|\}|\\
          logData: 'true'
          regex: ^RUNDECK:DATA:\s*([^\s]+?)\s*=\s*(.+)$
          replaceFilteredResult: 'false'
        type: key-value-data
    strategy: node-first
  uuid: 13fdf3e4-4f08-448a-bef2-c605263f504a

```

Child Job:
```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 35fb04c4-d7ba-4155-b2ed-fd715ba88603
  loglevel: INFO
  name: child job
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - script: 'echo "JOB: a"'
    keepgoing: false
    pluginConfig:
      LogFilter:
      - config:
          bgcolor: red
          fgcolor: red
          mode: underline
          regex: 'JOB: *'
        type: highlight-output
    strategy: node-first
  uuid: 35fb04c4-d7ba-4155-b2ed-fd715ba88603
```

**Comment by MegaDrive68k** [comment]
Hi,

If you want to use child job data on your parent job, you need to "elevate" that variable from child job to parent job. Similar to [this](https://docs.rundeck.com/docs/learning/howto/env-in-notifications.html#using-the-variable-in-notifications).

That's how rundeck works by design.

Parent Job:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 13fdf3e4-4f08-448a-bef2-c605263f504a
  loglevel: INFO
  name: parent job
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        group: ''
        name: child job
        uuid: 35fb04c4-d7ba-4155-b2ed-fd715ba88603
    - exec: echo ${export.myvar}
    keepgoing: false
    strategy: node-first
  uuid: 13fdf3e4-4f08-448a-bef2-c605263f504a
```

Child Job:

```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 35fb04c4-d7ba-4155-b2ed-fd715ba88603
  loglevel: INFO
  name: child job
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - plugins:
        LogFilter:
        - config:
            invalidKeyPattern: \s|\$|\{|\}|\\
            logData: 'true'
            regex: (.*)=(.*)
            replaceFilteredResult: 'false'
          type: key-value-data
      script: echo "anotherkey=anothervalue"
    - configuration:
        export: myvar
        group: export
        value: ${data.anotherkey*}
      nodeStep: false
      type: export-var
    - exec: echo ${export.myvar}
    keepgoing: false
    strategy: node-first
  uuid: 35fb04c4-d7ba-4155-b2ed-fd715ba88603
```

Regards.
