### ISSUE TITLE
RUNDECK_MULTIURL_ENABLED causes redirect error since 5.3.0

### ISSUE THREAD

**Issue by palto42** [rundeck/rundeck#9205]
Since Rundeck release 5.3.0 the [Multi-URL Setting](https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html#multi-url-setting) doesn't seem to work anymore.

**My Rundeck detail**

* Rundeck version: 5.4.0
* install type: docker
* OS Name/version: ubuntu 22.04
* DB Type/version: build-in or mysql

**To Reproduce**
1. Setup a fresh Rundeck in Docker with Nginx reverse proxy for https
   - `rd-test` is the external name of the Rundeck test server, for my debugging I added it to `/etc/hosts` to resolve to localhost at 127.0.0.1
   - `rd-docker` is the name of the Rundeck docker container

Folder structure

```
├── config
│   ├── nginx.conf
│   └── ssl
│       ├── nginx.crt
│       └── nginx.key
├── docker-compose.yaml
```

docker-compose.yaml
   
```yaml
services:
  rundeck:
    # image: rundeck/rundeck:5.2.0-20240410
    image: rundeck/rundeck:5.4.0-20240618
    container_name: rd-docker
    ports:
      - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: https://rd-test
      RUNDECK_SERVER_FORWARDED: "true"
      RUNDECK_MULTIURL_ENABLED: "true"
  nginx:
    image: nginx:alpine
    container_name: nginx-docker
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/ssl:/etc/nginx/ssl:ro
    ports:
    - 443:443
```

nginx.conf

```nginx
server {
    listen 443 ssl;
    server_name rd-test;
    access_log  /var/log/nginx/rundeck.access.log;
    ssl_certificate           /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key       /etc/nginx/ssl/nginx.key;

    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1.1 TLSv1.2;
    
  location / {
    proxy_pass http://rd-docker:4440/;
    proxy_set_header    Host $host;
    proxy_set_header    X-Real-IP $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto $scheme;
  }
}
```

Create certs for Nginx with

```sh
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout config/ssl/nginx.key -out config/ssl/nginx.crt
```

2. Start the docker environment with `docker compose up -d` and wait until Rundeck is ready.
3. Open the Rundeck web interface in a browser.
   - Tested with Edge and Firefox
4. Login with default `admin` account
5. See error message
   - Edge:  
     This page isn’t working right now  
     rd-test sent an invalid response.  
     `ERR_INVALID_REDIRECT`
   - Firefox:  
     An error occurred during a connection to rd-test.  
     The page you are trying to view cannot be shown because an error in the data transmission was detected.  
     - Please contact the website owners to inform them of this problem.
6. Manually navigate to `https://rd-test/menu/home`
   - The expected page is shown.
   - Similar redirect errors are observed on other actions like creating a new project (after clicking "Create")
7. Comment-out `# RUNDECK_MULTIURL_ENABLED: "true"` and recreate Rundeck container with `docker compose up -d`
   - Retest with above steps and check that there is no redirect error anymore.

**Expected behavior**
After login, the user should be redirected to `/menu/home` page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11, WSL2
 - Browser Edge, Firefox

**Additional context**

This issue was first observed with RUndeck version 5.3.0. When downgrading to 5.2.0 it works again with `RUNDECK_MULTIURL_ENABLED: "true"` setting.
