### ISSUE TITLE
Consecutive spaces in a job name are mangled in the web UI by html behavior

### ISSUE THREAD

**Issue by Daryes** [rundeck/rundeck#9307]
**Describe the bug**
Related web UI pages : 
* `https://<rundeck url>/project/<my project>/jobs`
* `https://<rundeck url>/project/<my project>/job/show/<job id>`
* `https://<rundeck url>/project/<my project>/job/edit/<job id>`

When a job name has 2 or more consecutive spaces in its name, the standard html behavior from a browser will be to merge them into one
Example with this real name : `issues x - multiples     spaces    merged   in  one`

From the project job list : 
![spaces1](https://github.com/user-attachments/assets/db6ddfd1-a3fb-44ff-afdf-439e98288542)

From the job informations
![spaces2](https://github.com/user-attachments/assets/af81b649-f7fb-4c76-83d6-466da55d93a2)

The problem is, while this wasn't intentional, the correct name was only visible when editing the job in the "name" label, or when exporting it to a file.  
And with a single extra space, it was too subtle to be immediately visible.

**My Rundeck detail**

* Rundeck version: 5.4.0
* install type: war
* OS Name/version: ubuntu 22.04
* DB Type/version: H2

**To Reproduce**
Create this job :
```
- defaultTab: nodes
  description: 'This jobs has multiples spaces in the name : multiples<5s>spaces<4s>merged<3s>in<2s>one'
  executionEnabled: true
  group: bug
  id: fb4e5a1b-ebff-4579-bd09-d63e5f7f231a
  loglevel: INFO
  name: issues x - multiples     spaces    merged   in  one
  nodeFilterEditable: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        command: bash -c "echo need one step"
      description: step
      nodeStep: true
      type: localexec
    keepgoing: false
    strategy: node-first
  uuid: fb4e5a1b-ebff-4579-bd09-d63e5f7f231a
```

Then go to the project's job listing, or select the job to show its informations and observe its visible name

**Expected behavior**
Having the real name of the job, not the one with the extra spaces mangled
At least in the job information panel (/job/show/id and /job/edit/id) should give the correct information.

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 115 ESR
