### ISSUE TITLE
ACLs not updating in a timely manner

### ISSUE THREAD

**Issue by MrDaGree** [rundeck/rundeck#9379]
**Describe the bug**
[Documentation](https://docs.rundeck.com/docs/learning/howto/acl_basic_examples.html#storage-locations) states that file based ACLs will need to wait a period of time before updating with it normally being around a minute. Unfortunately lately for me this hasn't been the case. When updating file based ACLs, mainly adding new job UUIDs to groups, it hasn't updated until the `rundeckd` service has been restarted.

**My Rundeck detail**

* Rundeck version: 5.6.0.20240912-1
* install type: deb
* OS Name/version: ubuntu 22.04
* DB Type/version: mysql

**To Reproduce**
1. `vim /etc/rundeck/test.aclpolicy`
2. Modify the policy
3. Attempt to run a job, etc, that was added to be allowed.

<details>
  <summary>Example ACL</summary>

  ```yaml
  description: testing policy
  context:
    project: 'staging'
  for:
    resource:
    - equals:
        kind: 'node'
      allow: [read,refresh]
    - equals:
        kind: event
      allow: [read]
    adhoc:
    - allow: [read,run,kill]
    job:
    - allow: [read,run,kill,update]
      match:
        uuid: 'ecb40f92-c8a1-4701-914f-ee243df3bb94'
  by:
    group: my-test-group
  ```
</details>

**Expected behavior**
The ACLs should update in a timely manner, according to the documentation
