### ISSUE TITLE
ACL: delete action for project at application level not working, export action activates both export and delete acess

### ISSUE THREAD

**Issue by clueware** [rundeck/rundeck#9414]
**My Rundeck detail**

* Rundeck version: 5.7.0
* install type: docker
* OS Name/version: Debian 12
* DB Type/version: postgres

**To Reproduce**

With the following ACL policy:
```yaml
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read]
    - equals:
        kind: project
      allow: [create]
  project:
    - match:
        name: '.*'
      allow: [read,configure,delete]
by:
  group:
  - prj_admin
```
1. Create a project
2. Go to the project the project dashboard
3. Click on the "Project settings"
4. The "Delete project" is missing
5. Change `[read,configure,delete]` with `[read,configure,export]` in the policy above
6. Both "Export archive" and "Delete project" become available in the "Project settings" menu

**Expected behavior**

The "delete" action should activate the "Delete project" right, and the "export" action should only activate the "Export archive" right

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser: Firefox, Chromium
 - Version: 128.3.1ESR and 130.0.6723.69 respectively
