### ISSUE TITLE
RUN-2938: ACL: admin action on a project at application level does not open all actions

### ISSUE THREAD

**Issue by clueware** [rundeck/rundeck#9416]
**Describe the bug**
While trying to articulate a clearer separation of duty, we met an issue with the "admin" action when set on projects at application level.
While we were expecting this action to open every other actions as described [the application scope generic type actions table](https://docs.rundeck.com/docs/administration/security/authorization.html#application-scope-resources-and-actions), the project settings icon is available but the menu is empty

**My Rundeck detail**

* Rundeck version: 5.7.0
* install type: docker
* OS Name/version: Debian 12
* DB Type/version: postgres

**To Reproduce**
With this policy:
```yaml
description: Project admin
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: system
      allow: [read]
    - equals:
        kind: project
      allow: [create]
  project:
    - match:
        name: 'project_1'
      allow: [admin]
    - match:
        name: 'project_2'
      allow: [read,configure]
by:
  group:
    - prj_admin
```
1. When going to the "project_1" dashboard: a "Project settings" icon is available, but the menu is empty, despite the user bieng allowed the "admin" action
2. When going to the "project_2" dashboard: a "Project settings" icon is available and shows the configuration entries as epected

**Expected behavior**
A user having the "admin" action should have all other actions - read, configure, delete, import, export, scm_import, scm_export, delete_execution - available in the "Project settings" menu.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox, Chromium
 - Version: 128.3.1ESR and 130.0.6723.69 respectively
