### ISSUE TITLE
Job Imports are set to "Execute locally" when Node filter is empty

### ISSUE THREAD

**Issue by claudekenni** [rundeck/rundeck#9526]
**Describe the bug**
Jobs that are exported and then imported are being set to "Execute Locally" when the Nodes field does not have any content

This looks to be applicable to all the different ways Jobs can be imported into the system.
- Project archive import 
- Job Actions > Upload definition
- SCM Import Plugin
- Rundeck Terraform providers "rundeck_job" resource 
- I have not tried using the rest api for a job import

**My Rundeck detail**

* Rundeck version: 5.6.1 although this has been an issue since at least v2.x
* install type: deb
* OS Name/version: Ubuntu 22.04
* DB Type/version: mysql

**To Reproduce**
- Create a Job with Dispatch set to "Dispatch to nodes" and leave the "Node Filter" empty
- Export the Job as YAML 
- Reimport the Job
Now the Job is is set to "execute locally"

**Expected behavior**
Job should still have the Dispatch set to "Dispatch to nodes" when importing it.

Here is an example job yaml that when imported should have the dispatch set to "execute locally"
```yaml
- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 6140bb05-3bd3-4ee9-ad19-7be3d928af80
  loglevel: INFO
  name: 'Test Job '
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: ''
  nodesSelectedByDefault: false
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  schedules: []
  sequence:
    commands:
    - exec: date
    keepgoing: false
    strategy: node-first
  uuid: 6140bb05-3bd3-4ee9-ad19-7be3d928af80
```
