### ISSUE TITLE
Execute nodes from Ansible Inventory file is error

### ISSUE THREAD

**Issue by svjatoslav-torn** [rundeck/rundeck#9601]
Good afternoon, I'm facing a problem where I can't extract nodes from ansible playbooks.  
I will try to describe the situation as broadly as possible, however, do not hesitate to clarify the details.
I will be glad of any ideas.   
  
I'm conducting experiments, testing the convenience of managing ansible playbooks.  
I have a large fleet of Windows servers.   
   
1. **RunDeck**
I use RunDeck version 5.10.0, installed in docker container:  
```
docker run --name rundeck5   -p 4440:4440   -e RUNDECK_GRAILS_URL=http://ip_address:4440   -v ~/rundeck/data:/home/rundeck/server/data   -v ~/rundeck/projects:/home/rundeck/projects -d rundeck/rundeck:5.10.0
```

2. **Ansible**:
Next, I go into the container and install the necessary packages right there. I tried not to do this, but RunDeck doesn't know what Ansible is if it's not in the container.  

2.1 **Go to container**:
```
docker exec -it rundeck5 sudo bash
```

2.2 **Install python and pip**
```
apt install python3 python3-pip
```

2.3 **Install Ansible by pip**
```
pip install ansible
```

2.4 **Install sshpass**
```
apt install sshpass
apt install nano
```

Ok, let's go next)

3. **Create ansible inventory in container**
```
nano /home/rundeck/my-hosts.yml
```
with contains...
```
---
all:
  vars:
    ansible_connection: ssh
    ansible_host_key_checking: false
    ansible_shell_type: cmd
    ansible_ssh_port: 33
  hosts:
    65.217.25.146:
      ansible_ssh_user: AnsibleAdmin
      ansible_ssh_password: password
```
Yes, I connect to Windows servers via SSH as it is easier to configure. And I use the cmd shell

4. **Ok, Run ansible in container by inventory**
```
ansible all -i /home/rundeck/my-hosts.yml -m win_ping
```

result:

![Image](https://github.com/user-attachments/assets/60e291b1-08ab-498d-95c6-1753cb2c7d56)  
  
5. **Ok go RunDeck**   
5.1 **All Ansible plugins are already installed**    

5.2 **Create project, input name**  

5.3 **Default Node Executor**
I select `Ansible Ad-Hoc Node Executor`   
And they set the values of the following fields (I leave the rest by default):  
- Ansible binaries directory path: /usr/local/bin
- Executable: /bin/bash
- Windows Executable: cmd.exe
- Authentication.Authentication Type: password

5.4 **Go to add nodes**
 
Settings Projects -> Edit Nodes -> Add a new Node Source  
And they set the values of the following fields (I leave the rest by default):    
- ansible inventory File path: /home/rundeck/my-hosts.yml
- Gather Facts: Yes
- Ignore Host Discovery Errors: No
- Extra Ansible arguments: -vvvv
- Authentication.Authentication Type: password

5.5 **And I get an error**  

![Image](https://github.com/user-attachments/assets/e56f823c-747b-46c2-812f-a42f2c501941)  

6. **Well, let's see the container logs**
```
docker logs --tail 500 rundeck5
```

And that's what I saw there (A little extra stuff was removed):
```
[2025-03-18T02:40:30,742] INFO  web.requests "GET /resources/nodesQueryAjax" MY.IP.ADDRESS.OMG http admin form 5 Test [application/json;charset=utf-8] (my_user_agent)
ansible-playbook [core 2.17.9]
  config file = None
  configured module search path = ['/home/rundeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/rundeck/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
No config file found; using defaults
setting up inventory plugins
Loading collection ansible.builtin from
host_list declined parsing /home/rundeck/my-hosts.yml as it did not pass its verify_file() method
script declined parsing /home/rundeck/my-hosts.yml as it did not pass its verify_file() method
Parsed /home/rundeck/my-hosts.yml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.10/dist-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: gather-hosts.yml *****************************************************
Positional arguments: gather-hosts.yml
verbosity: 4
connection: ssh
become_method: sudo
tags: ('all',)
inventory: ('/home/rundeck/my-hosts.yml',)
extra_vars: ('@/home/rundeck/var/tmp/ansible-runner17220275728718396773extra-vars',)
forks: 5
1 plays in gather-hosts.yml

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
task path: /home/rundeck/var/tmp/ansible-hosts7423844747373816720/gather-hosts.yml:2
[2025-03-18T02:40:33,251] INFO  web.requests "GET /resources/nodesQueryAjax" MY.IP.ADDRESS.OMG http admin form 6 Test [application/json;charset=utf-8] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36)
[2025-03-18T02:40:33,255] INFO  web.requests "GET /resources/nodesQueryAjax" MY.IP.ADDRESS.OMG http admin form 4 Test [application/json;charset=utf-8] (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 YaBrowser/25.2.0.0 Safari/537.36)
redirecting (type: modules) ansible.builtin.setup to ansible.windows.setup
Loading collection ansible.windows from /usr/local/lib/python3.10/dist-packages/ansible_collections/ansible/windows
Using module file /usr/local/lib/python3.10/dist-packages/ansible_collections/ansible/windows/plugins/modules/setup.ps1
Pipelining is enabled.
<65.217.25.146> ESTABLISH SSH CONNECTION FOR USER: AnsibleAdmin
<65.217.25.146> SSH: EXEC sshpass -d12 ssh -vvvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=33 -o 'User="AnsibleAdmin"' -o ConnectTimeout=10 -o 'ControlPath="/home/rundeck/.ansible/cp/0370d81052"' 65.217.25.146 'chcp.com 65001 >nul 2>&1 && PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand ...'
<65.217.25.146> (0, b'{"changed":false,"invocation":{"module_args":{"_measure_subset":false,"gather_timeout":10,"gather_subset":["all"],"fact_path":null}},"ansible_facts":{"ansible_ip_addresses":["i_clear_it","65.217.25.146"],...,"ansible_os_name":"Microsoft Windows Server 2022 Standard"...
ok: [65.217.25.146]

TASK [Ensure tmpdir data directory] ********************************************
task path: /home/rundeck/var/tmp/ansible-hosts7423844747373816720/gather-hosts.yml:10
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: rundeck
<localhost> EXEC /bin/sh -c 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand ... && sleep 0'
fatal: [65.217.25.146 -> localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand ..., exited with result 127, stderr output: /bin/sh: line 1: PowerShell: command not found\n",
    "unreachable": true
}

PLAY RECAP *********************************************************************
65.217.25.146                : ok=1    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

[2025-03-18T02:40:34,515] ERROR resources.ExceptionCatchingResourceModelSource - [ResourceModelSource: 1.source (com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory), project: Test]
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Failed Ansible Runner execution: ERROR: Ansible execution returned with non zero code.
...

```

7. **And then the question arises.**
I see that the necessary inventory has been taken, and the facts have been successfully received from the Windows server. But the next step involves connecting to a local computer, why is this necessary? To preserve the facts?  
Do I need to configure SSH in the docker container? 
Why is the powershell command running on the local Ubuntu host?

I will be glad of any help.

UPD: 

**This is exactly the script that runs Node Executor.**
```
---
- hosts: all

  vars:
    facts: True

  gather_facts: "{{ facts }}"

  tasks:
    - name: "Ensure tmpdir data directory"
      file:
        path: "{{ tmpdir }}/data"
        state: directory
      become: no
      run_once: yes
      delegate_to: localhost

    - name: "Template the gathered facts"
      template:
        src: host-tpl.j2
        dest: "{{ tmpdir }}/data/{{ inventory_hostname }}"
      delegate_to: localhost
      become: no
```

**UPD 2:**
I haven't changed any settings. But I decided to conduct an experiment, and deleted all Windows hosts from the inventory file, and added 1 Ubuntu host. Node extraction was successful
![Image](https://github.com/user-attachments/assets/f83d3560-f623-4cec-b183-2d0856676cb8)

**Comment by svjatoslav-torn** [comment]
I think I've figured it out. The fact is that my inventory is only for working with Windows servers, and I globally install the CMD runtime environment, apparently this prevented the execution of the task to save the fact on the RunDeck server.

Before:
```
---
all:
  vars:
    ansible_connection: ssh
    ansible_host_key_checking: false
    ansible_shell_type: cmd
    ansible_ssh_port: 33
  hosts:
    65.217.25.146:
      ansible_ssh_user: AnsibleAdmin
      ansible_ssh_password: password
```

After:
```
---
all:
  vars:
    ansible_connection: ssh
    ansible_host_key_checking: false
    ansible_ssh_port: 33
  hosts:
    65.217.25.146:
      ansible_shell_type: cmd # transfer ansible_shell_type here form all:vars
      ansible_ssh_user: AnsibleAdmin
      ansible_ssh_password: password
```

The nodes were successfully extracted
