### ISSUE TITLE
Duplicated Jobs with the same name

### ISSUE THREAD

**Issue by cmanzur** [rundeck/rundeck#9618]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
After latest rundeck docker image update (v5.10.0-20250312), when I upload a Job YAML Definition (via CLI or via GUI) the job get duplicated.

**My Rundeck detail**

* Rundeck version: v5.10.0-20250312
* install type: docker
* OS Name/version: ubuntu 20.04
* DB Type/version:  postgres 15.8

**To Reproduce**

```
curl -XPOST -H "X-Rundeck-Auth-Token: $RUNDECK_PERSONAL_TOKEN" "http://localhost:4440/api/45/project/developers_self_service_portal/jobs/import?format=yaml&dupeOption=update" -H 'Content-Type: application/yaml' --data-binary @job.yaml
```

Repeat the same curl command 3 times --> create 3 jobs.

Note: **job.yaml** is a Job **without** the **uuid** and **id** in the YAML template.

**Expected behavior**
The current job with the same name should be updated, instead of creating a new job.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser: chrome
 - Version: 134

**Comment by MegaDrive68k** [comment]
Hi,

I tried using your curl call, but I see the job updated successfully (without id/uuid as you posted). Can you share the job definition example to take a look? 

Regards.

**Comment by cmanzur** [comment]
No matter what job.yaml I use, it always gets duplicated, triplicated, etc..

![Image](https://github.com/user-attachments/assets/f3b0b4f6-1614-4e6f-8913-a8afeee2f6e3)

This is one example:

```yaml
- defaultTab: nodes
  description: Creates items for the generated Quick Lessons
  executionEnabled: true
  group: assessment/steps/
  loglevel: INFO
  name: generate_items_for_quick_lessons
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: aws
  nodesSelectedByDefault: true
  options:
  - description: Write a list of Identifiers
    label: Identifiers
    required: true    
    name: ids
  plugins:
    ExecutionLifecycle: null
  scheduleEnabled: true
  sequence:
    commands:
    - args: ${option.ids}
      description: Command
      scriptfile: scripts/test/command.sh
    keepgoing: false
    strategy: node-first
```

**Comment by cmanzur** [comment]
I'm running this docker-compose:

```yaml
version: '3'

services:
  rundeck:
    container_name: rundeck
    restart: on-failure
    build:
      context: rundeck
      args:
        RUNDECK_IMAGE: rundeck/rundeck:5.10.0
    environment:
      RUNDECK_GRAILS_URL: https://rundeck.test.dev
      RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: xxxxxxxxxxxxxxxx
      RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      RUNDECK_SERVER_ADDRESS: 0.0.0.0
      RUNDECK_FEATURE_UINEXT_NAME: uiNext
      RUNDECK_FEATURE_UINEXT_ENABLED: 'true'
      # for google oauth
      RUNDECK_SERVER_FORWARDED: 'true'
      RUNDECK_PREAUTH_ENABLED: 'true'
      RUNDECK_PREAUTH_ATTRIBUTE_NAME: REMOTE_USER_GROUPS
      RUNDECK_PREAUTH_DELIMITER: ","
      RUNDECK_PREAUTH_USERNAME_HEADER: X-Forwarded-Email
      RUNDECK_PREAUTH_ROLES_HEADER: X-Forwarded-Roles
      RUNDECK_PREAUTH_REDIRECT_LOGOUT: 'true'
      RUNDECK_PREAUTH_USERSYNC_ENABLED: 'true'
      RUNDECK_PREAUTH_USERSYNC_EMAIL: X-Forwarded-User-Email
      RUNDECK_PREAUTH_REDIRECT_URL: '/oauth2/auth'
    ports:
      - 4440:4440
    volumes:
      - /root/volume:/volume

  oauth-proxy:
    build:
      context: ./oauth
    container_name: oauth-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./oauth/nginx.conf:/etc/nginx/nginx.conf
      - ./oauth/default.conf:/etc/nginx/sites-enabled/default
      - ./oauth/oauth.conf:/etc/supervisor/conf.d/oauth.conf

  nginx:
    image: nginx:alpine
    container_name: usermap
    restart: always
    volumes:
      - ./usermap/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./usermap/nginx.conf:/etc/nginx/nginx.conf:rw
```

Just in case, the Dockerfile is:
```
ARG RUNDECK_IMAGE
FROM ${RUNDECK_IMAGE}

RUN  sudo apt-get update && \
     sudo apt-get install -y -qq --no-install-recommends \
     wget  \
     git \
     curl \
     jq \
     iputils-ping \
     sysstat \
     python3 \
     python3-pip \
     awscli

# Install kubernetes python client (Required for rundeck k8s plugin)
RUN  pip3 install kubernetes

# AWS CLI
RUN curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip ./aws && \
    echo 'complete -C "$(which aws_completer)" aws' >> ~/.bashrc

# Kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256" && \
    echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl kubectl.sha256 && \
    echo 'source <(kubectl completion bash)' >> ~/.bashrc

# Rundeck k8s plugin uses python (not python3)
RUN sudo ln -s $(which python3) /usr/bin/python
RUN curl -sSL https://github.com/rundeck-plugins/kubernetes/releases/download/2.0.14/kubernetes-2.0.14.zip -o ~/libext/kubernetes-2.0.14.zip
```
