### ISSUE TITLE
Policy for resource of kind "user" doesn't work

### ISSUE THREAD

**Issue by falon** [rundeck/rundeck#9683]
I have written this policy:
```
description: Do not allow to modify own user profile
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: 'user'
      deny:
        - 'admin'
by:
  username:
    - 'myuser'
```

After that if I open the web page of my Rundeck service, I login with 'myuser', I go to profile page I'm still able to modify the profile (Email, First Name, Last Name).

**My Rundeck detail**

* Rundeck version: Rundeck5.11.1 2025-04-15
* install type: docker
* OS Name/version: 5.15.0-205.149.5.4.el9uek.x86_64 
* DB Type/version: mysql

**To Reproduce**
1. Go to User Profile through web page
2. Click on Profile
3. Click in Edit
4. Modify a field and save
5. No errors happen. The profile has been modified.

**Expected behavior**
Really, the Edit button should not show if the policy denies the user profile change.
Even if the Edit button appears, the profile change should be denied.

**Desktop:**
 - OS: Windows
 - Browser: Firefox  
 - Version 128.11.0esr (64 bit)

**Additional context**
[Discussion on Google Group](https://groups.google.com/d/msgid/rundeck-discuss/fd166fed-2899-4350-a86b-56da1dc98137n%40googlegroups.com?utm_medium=email&utm_source=footer)
